### ISSUE TITLE
Move khmer wrappers here

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/tools-iuc#1]
See https://github.com/ged-lab/khmer/tree/master/scripts/galaxy

(This is the appropriate place, yes?)

**Comment by mr-c** [comment]
This is in progress in #80

**Comment by erasche** [comment]
@mr-c thanks for doing this, I'll be very excited to see #1 closed!

**Comment by mr-c** [comment]
#80 was merged; thanks all!

**Comment by mr-c** [comment]
@bgruening What should be done with my khmer repo on the toolshed? https://toolshed.g2.bx.psu.edu/view/crusoe/khmer/2c4635f5be47

Wait for you all to push the IUC version and delete, or ..?

**Comment by bgruening** [comment]
@mr-c Once we move everything into the TTS and the MTS please deprecate the repository. There is no delete in the TS ... sustainability :)
Are you fine merging my other k-mer PR, after changing the leading space? (Thanks for catching.)

The last thing I would like to see is that we change the IDs somehow and use them to generate automatically the repository name. With this in place we could automatically create different repositories for every tool.
Can we change the IDs?

**Comment by mr-c** [comment]
@bgruening great, can do.

Yes, the new PR LGTM!

I'm not following your suggestion about IDs. Does tool in this context mean each khmer script would have its own individual repository or do you mean the suite as a whole?

Either way I don't have an opinion as we haven't published any workflows that use the IDs. Have at it!

**Comment by bgruening** [comment]
> Yes, the new PR LGTM!

Thanks!

> I'm not following your suggestion about IDs. Does tool in this context mean each khmer script would have its own individual repository or do you mean the suite as a whole?

The former.
We will than create a meta-package which will install all tools.

> Either way I don't have an opinion as we haven't published any workflows that use the IDs. Have at it!

Great thanks!

**Comment by mr-c** [comment]
On Thu, Oct 15, 2015 at 11:25 AM Björn Grüning <notifications@github.com>
wrote:

> I'm not following your suggestion about IDs. Does tool in this context
> mean each khmer script would have its own individual repository or do you
> mean the suite as a whole?
>
> The former.
> We will than create a meta-package which will install all tools.
>
Interesting; is the `macros.xml` file copied to each sub-repository?

**Comment by bgruening** [comment]
`macro.xml`, test-data, dependency definitions ... at least this is the plan :)
xref: https://github.com/galaxyproject/planemo/issues/313

**Comment by mr-c** [comment]
Wacky; have fun with that! :-)

**Comment by erasche** [comment]
I'll try and find time for https://github.com/galaxyproject/planemo/issues/313 this weekend. Is that an okay release delay for everyone?
