### ISSUE TITLE
Prebuilt R packages link to X11

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#101]
Reported by @Unode on the IRC channel.

**Comment by Unode** [comment]
The alternative of forcing compilation on linux (using the recipe from darwin included in the XML) has problems linking with libreadline.

The following symbols are reported not found:

    ld: warning: cannot find entry symbol _start; not setting start address
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `tputs'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `tgoto'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `tgetflag'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `UP'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `tgetent'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `tgetnum'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `PC'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `tgetstr'
    /GALAXY/galaxy_dist/tool_dependencies/readline/6.2/rjalves/package_readline_6_2/052e8df231ac/lib/libreadline.so.6: undefined reference to `BC'

**Comment by bgruening** [comment]
ping @davebx

**Comment by bgruening** [comment]
I think this can be closed. @unode with conda life is hopefully easier nowadays.
