### ISSUE TITLE
GenomeSpace import (genomespace_file_browser_prod) failing at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1010]
Run-time error? Params not being passed before the job is executed? See the end of the quote (this is from the "i" info page. Tool error is not very informative, but is also included below this.

ping @galaxyproject/guac 

Info page report

> Tool: GenomeSpace import
> Number:   1
> Name: GenomeSpace import on MZha-BNO_0h1_S10_R1_001.fastq.gz
> Created:  Tue 25 Oct 2016 02:01:13 PM (UTC)
> Filesize: 6.9 GB
> Dbkey:    ?
> Format:   fastq
> Galaxy Tool ID:   genomespace_file_browser_prod
> Galaxy Tool Version:  0.0.1
> Tool Version: 
> Tool Standard Output: stdout
> Tool Standard Error:  stderr
> Tool Exit Code:   0
> History Content API ID:   XX
> Job API ID:   XX
> History API ID:   XX
> UUID: XX
> Full Path:    /galaxy-repl/main/files/XX
> Operating System  Linux roundup58.tacc.utexas.edu 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> Processor Count   32
> Total System Memory   123.0 GB
> Total System Swap 976.6 MB
> Job Runtime (Wall Clock)  1 hours and 48 minutes
> Cores Allocated   1
> Job Start Time    2016-10-25 09:01:20
> Job End Time  2016-10-25 10:49:34
> 
> **Input Parameter Value   Note for rerun
> appCallbackUrl    not used (parameter was added after this job was run)  
> appName   not used (parameter was added after this job was run)  
> GALAXY_URL    not used (parameter was added after this job was run)  
> Inheritance**

Tool error

Detailed Job Information

> Job environment and execution information is available at the job Info Page.
> Job ID    XX
> Tool ID   genomespace_file_browser_prod
> Tool Version  0.0.1
> Job PID or DRM id 8382211.roundup
> Job Tool Version  None
> Job Execution and Failure Information
> 
> Command Line
> None
> stderr
> Job output not returned from cluster
> stdout
> Job Information
> None
> Job Traceback
> None

**Comment by natefoo** [comment]
I think this was a one-time cluster error. The tool has been running successfully immediately before this particular failure and many times since.

**Comment by jennaj** [comment]
Great, closing out
