### ISSUE TITLE
hisat2 output fastq files of unaligned reads?

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/tools-iuc#1041]
This request is inspired by [this post](https://biostar.usegalaxy.org/p/20551/) on the biostars site (and the fact that it's only a matter of time before one of our post-docs asks for this). It'd be nice if the hisat2 wrapper supported the `--un-conc` and `--un` options. In experiments like ribosomal profiling, you end up with a LOT of rRNA and small non-coding RNAs that are basically just nuisance species. At the command line, we get rid of these by making a fasta file with rRNA and the other things in it, align everything against that, and then just continue with the reads that don't align. I presume that the "remove rRNA using bowtie" on RiboGalaxy is working in a similar way, but of course it'd be nice to not need a separate tool that's not in the main toolshed for this.

As always, since I'm making the request, I'm happy to implement it if the IUC supports the idea.

**Comment by nsoranzo** [comment]
You can probably copy/paste from the devteam's bowtie2 Galaxy wrapper.

**Comment by yhoogstrate** [comment]
@dpryan79 This looks like a great addition to me and I would be happy to review it.

**Comment by dpryan79** [comment]
@yhoogstrate: I totally forgot about this :P I'll see if I can put this together tomorrow and then tag you in the PR :)

**Comment by yhoogstrate** [comment]
🍻

**Comment by yhoogstrate** [comment]
Thanks @dpryan79
