### ISSUE TITLE
Error on package package_perl_pdf_api2_2_023

### ISSUE THREAD

**Issue by adefelicibus** [galaxyproject/tools-iuc#1052]
`Error downloading from URL
http://search.cpan.org/CPAN/authors/id/S/SS/SSIMMS/PDF-API2-2.023.tar.gz:
HTTP Error 404: Not Found`

Revision: b9b7fadfdb69
I'm using Galaxy 16.07.

**Comment by bgruening** [comment]
@adefelicibus can you try this link: http://pkgs.fedoraproject.org/repo/pkgs/perl-PDF-API2/PDF-API2-2.023.tar.gz/md5/1087a69c71078ee12154fa32b089d2d9/PDF-API2-2.023.tar.gz and patch maybe the recipe?
