### ISSUE TITLE
SRA tools - fastqdump: recently occurring errors

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/tools-iuc#1059]
SRA tools - fastqdump (version 2.7.0.1) is returning the error below when trying to retrieve data:
Fatal error: Exit code 3 ()
2016-12-02T18:46:20 prefetch.2.7 err: path not found while resolving tree within virtual file system module - 'SRR549355' cannot be found.

This is happening on a local instance (16.07) and Cloudman (16.11). The same version of the tool worked on Cloudman (16.11) for us on November 7th. @afgane noted that [NCBI moved to 'HTTPS only'](https://www.ncbi.nlm.nih.gov/home/develop/https-guidance.shtml) on November 9th and these errors could be related. The NCBI move to 'HTTPS only' was mentioned in #1050 and #911.

**Comment by mvdbeek** [comment]
Yeah, we need to get to 2.8.0, which is not in conda yet (https://github.com/bioconda/bioconda-recipes/pull/2577).
