### ISSUE TITLE
Add more of the picrust suite

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1064]
@shiltemann kickstarted these tools already in https://github.com/galaxyproject/tools-iuc/pull/1044

A few tools are missing and I think this is a very good task for a beginner that wants to learn Galaxy Tool Dev.

- [ ] predict_traits
- [x] metagenome_contributions
- [ ] ancestral_state_reconstruction
- [x] compare_biom
- [x] format_tree_and_trait_table
- [ ] run_genome_evaluations
- [ ] scale_metagenome

**Comment by bernt-matthias** [comment]
Will this still be needed once we have picrust2? https://github.com/galaxyproject/tools-iuc/pull/3904

**Comment by shiltemann** [comment]
I don't think it will be, no
