### ISSUE TITLE
Tool request: Gffcompare

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/tools-iuc#1065]
Hi IUC!
The output of Stringtie Merge requires running Gffcompare in order for the merged transcripts to be annotated (with class codes). Not having Gffcompare available limits the functionality of Stringtie Merge. 
It would be excellent and very much appreciated if Gffcompare could be wrapped and added to the TS. 

Gffcompare can be found at: https://github.com/gpertea/gffcompare

Thanks, IUC!!

Cheers, 
Mo Heydarian

**Comment by davebx** [comment]
#1228

**Comment by davebx** [comment]
GffCompare can now be installed from https://toolshed.g2.bx.psu.edu/view/iuc/gffcompare
