### ISSUE TITLE
deprecate redundant htseq wrapper?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1072]
Should this tool be deprecated in favor of https://github.com/galaxyproject/tools-iuc/blob/master/tools/htseq_count/htseq-count.xml

https://github.com/galaxyproject/tools-iuc/tree/master/tools/htseq

ping @yhoogstrate

**Comment by yhoogstrate** [comment]
Yes please, these packages areredundant. Good catch, thanks @bgruening. The `htseq-count` fits the IUC standards a bit bitter than `htseq`, so I would go for `htseq-count` too.

**Comment by bgruening** [comment]
@yhoogstrate do you have time to do this?

**Comment by yhoogstrate** [comment]
I will take care of this. Do I just need to move it to `/deprecated` and disable it via the webinterface or does this need to be done via the `.shed.yml` these days?

**Comment by bgruening** [comment]
Via the webinterface is enough I think.

**Comment by bgruening** [comment]
Thanks @yhoogstrate! Sorry in a meeting right now :(

**Comment by yhoogstrate** [comment]
@bgruening I don't think IUC is able to deprecate it, only fubar seems to be able to do this.
