### ISSUE TITLE
QIIME Contribution Fest - 9th & 10th January 2017

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/tools-iuc#1078]
Hi, 

Some work has already be done to integrate QIIME into Galaxy: see #431. 

But there is still work to be done:
- Add some love on some wrappers
   - use argument="--myparam"
   - make flake8 passing
   - add params in command section in quotes
   - add help text and version command
   - check the indentation
   - and many other make up 
- Add tests data for all wrappers
- Add new wrappers for new commands

And we need your help on this! 

We planned a Contribution Fest on the 9th & 10th of January 2017.
It could be great if you can join for this hackathon

Thanks everyone! This will be awesome!

Bérénice, Björn, and Saskia

**Comment by bgruening** [comment]
Only 8 days to go and we will start 2017 with our first online Contribution Fest dedicated t the QIIME wrapper.

ping @galaxyproject/iuc

**Comment by bebatut** [comment]
Hi all,

Ready for the hackathon?

For live chat, we can use the IUC Gitter channel: https://gitter.im/galaxy-iuc/iuc
We can there coordinate our efforts on QIIME. 

Happy hacking :)

**Comment by bgruening** [comment]
What do you think, do we want to have every tool as separate TS entry, as encouraged by the IUC? it will be a lot of different repos.

**Comment by lparsons** [comment]
I think that would be too many tools. In theory, one repo per tool is a good idea, but in reality, it's a big admin headache (IMHO).

**Comment by bgruening** [comment]
@lparsons for admins there will be a suite repository, which aggregates all the single tools. Not enough?

**Comment by lparsons** [comment]
The suites haven't worked for me in the past. OK for an initial install, but updates to new versions have always failed in various ways.

**Comment by gregvonkuster** [comment]
I know there are pros and cons to 1 tool per repo, but I've always leaned towards it.  I really don't like the fact that you have to install an entire suite of tools (suites sometimes are very large) to get the 1 or 2 that you really want.  For example, my ChIP-exo environment needs only a single picard too, but I have to install all of these https://github.com/galaxyproject/tools-devteam/tree/master/tools/picard to get it.  I've not experienced the headaches involved in installing and maintaining a tool per repo, but that doesn't mean there aren't any - I'm just not seeing what they are.  ;)

**Comment by lparsons** [comment]
I fully agree that having to install an entire suite of tools is problematic, but I've never been able to install a new version of suite. Always fails and leaves me in a nasty state. Then I end up installing each new version manually (which takes forever). Deeptools was my latest example. Have you actually installed deeptools_suite, then installed a new version of deeptools_suite (in the same Galaxy instance)?

**Comment by bgruening** [comment]
I did that and it worked, Oo.

**Comment by lparsons** [comment]
:sigh: Well, if it does indeed work in some cases, then I suppose creating separate tools is OK. Personally, I think separate repos is a big PITA and Galaxy should allow more customization when installing (and putting tools in various places in the tools menu). Also, I'd consider this a bit of a special case since I'm certain the suite install won't work for me with so many tools (proxy will time out). But I guess I can start writing some API scripts to install tools....
