### ISSUE TITLE
sra-tools fails when forward has no output from fastq-dump

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/tools-iuc#1081]
So tool will finish to completion but the collection will be in finished or running state with no data. Issue is that discover output will fail because we see a SRA_2.fastq file but no corresponding _1 fastq file. 

Reason being is that the SRA_1.fastq does not exist because fastq-dump did not create one becuase the forward read was empty.

Example of SRA would be https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1993644

No idea how to solve this.

**Comment by yhoogstrate** [comment]
Hi @Takeadonet,

I don't really see this as a issue but more as a (valid) error message.

I am aware of FASTQ tools that depend on the order in the _R1 and _R2 of the files to link mate pairs.
Given that this is not the case in your example, i.e. the number of lines does not correspond, we're dealing with FASTQ files that are likely to cause unexpected behaviour and I would prefer to see an error.

I think this problem has to be solved upstream and such dataset should be set to single-end.

I am happy to hear your thoughts on this.


Youri

**Comment by Takadonet** [comment]
I agree that it has to be solved upstream and I am thinking more on the lines that SRA should be reject outright or have a 'discarded' collection. Perhaps allow the user to select which one to use.

**Comment by blankenberg** [comment]
I'd lean towards the side that there is a bug with the way that these tools handle the collection discovery when some pairs might be empty. Upstream fixes are always great, but we definitely don't want to have the case where we end up with a 'forever running' collection. 

Also, there an issue where, when we have empty collections that had job errors there is no way for the user to see the error.

 xref https://github.com/galaxyproject/tools-iuc/issues/970

**Comment by Takadonet** [comment]
Fixed in #1212
