### ISSUE TITLE
Flip on Travis for repository

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#110]
Okay, I screwed up here, and meant to open this as a PR, but then I committed to master and pushed before I checked my work. My bad, won't happen again. (Github *really* needs protected branches) That said, I push the `.travis.yml` file copied straight from tools-devteam, so...very little harm done.

Anyway, back on topic, since we're the IUC and love our standards SO much, we now have a `.travis.yml` config for linting all of the tools. https://github.com/galaxyproject/tools-iuc/commit/6e6439fd38b7baed47cfb3e80e6554b5a49ed8d8 Would it be possible for one of the galaxyproject admins (or someone with proper permissions) to turn on Travis for this repository?

**Comment by jmchilton** [comment]
Just enabled this for both ``tools-iuc`` and ``tools-devteam``.

**Comment by erasche** [comment]
Thanks!
