### ISSUE TITLE
GEMINI - Later version

### ISSUE THREAD

**Issue by xirasasa** [galaxyproject/tools-iuc#1130]
Do you plan to integrate the latest version of GEMINI (0.19.1)?

**Comment by bgruening** [comment]
@xirasasa this is all a time issue, we would love to get help from the community to update the tools.
A first step would be to add tests to all tools and then update them.

**Comment by gregvonkuster** [comment]
This work is started with this PR: https://github.com/galaxyproject/tools-iuc/pull/1202

**Comment by xirasasa** [comment]
Thank you, we appreciate it!
Sandhya
