### ISSUE TITLE
JBrowse: missing JSON.pm 

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/tools-iuc#1162]
Tried running JBrowse. I get an error referring to a missing JSON.pm file. 

```
Fatal error: Exit code 1 ()
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/../src/perl5 /remote/RMS/users/galaxy/repos/perl5/sharedperlmodules /usr/local/share/perl5 /opt/shed_tools/_conda/pkgs/perl-5.22.0.1-0/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /opt/shed_tools/_conda/pkgs/perl-5.22.0.1-0/lib/perl5/site_perl/5.22.0 /opt/shed_tools/_conda/pkgs/perl-5.22.0.1-0/lib/perl5/5.22.0/x86_64-linux-thread-multi /opt/shed_tools/_conda/pkgs/perl-5.22.0.1-0/lib/perl5/5.22.0 .) at /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/JSON.pm line 10.
BEGIN failed--compilation aborted at /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/JSON.pm line 10.
Compilation failed in require at /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FormatSequences.pm line 23.
BEGIN failed--compilation aborted at /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FormatSequences.pm line 23.
Compilation failed in require at /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/prepare-refseqs.pl line 7.
BEGIN failed--compilation aborted at /opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/prepare-refseqs.pl line 7.
Traceback (most recent call last):
  File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/4cbceec1d6b4/jbrowse/jbrowse.py", line 665, in <module>
    gencode=root.find('metadata/gencode').text
  File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/4cbceec1d6b4/jbrowse/jbrowse.py", line 315, in __init__
    self.process_genomes()
  File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/4cbceec1d6b4/jbrowse/jbrowse.py", line 344, in process_genomes
    '--fasta', genome_path])
  File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/4cbceec1d6b4/jbrowse/jbrowse.py", line 335, in subprocess_check_call
    subprocess.check_call(command, cwd=self.outdir)
  File "/remote/RMS/users/galaxyd/job_working_directory/013/13563/conda-env/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['perl', '/opt/shed_tools/_conda/pkgs/jbrowse-1.12.1-3/opt/jbrowse/bin/prepare-refseqs.pl', '--fasta', '/remote/RMS/users/galaxyd/files/094/dataset_94714.dat']' returned non-zero exit status 2
```

**Comment by dwightkuo** [comment]
Tried setting "conda_copy_dependencies = True". Now get this error:

Fatal error: Exit code 1 ()
INFO:jbrowse:Processing Default / GFF3 file from data 48
Attempt to reload Scalar/Util.pm aborted.

On Mon, Feb 6, 2017 at 1:23 AM, Anthony Bretaudeau <notifications@github.com

**Comment by abretaud** [comment]
Do you have more details for this error? I have never seen it

**Comment by dwightkuo** [comment]
Here are the full details:
>
> Fatal error: Exit code 1 ()
> INFO:jbrowse:Processing Default / GFF3 file from data 48
> Attempt to reload Scalar/Util.pm aborted.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/lib/perl5/5.22.0/File/Temp.pm line 18.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/lib/perl5/5.22.0/File/Temp.pm line 18.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/ExternalSorter.pm line 42.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/ExternalSorter.pm line 42.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/NCFormatter.pm line 8.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/NCFormatter.pm line 8.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/lib/perl5/5.22.0/base.pm line 99.
> 	...propagated at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/lib/perl5/5.22.0/base.pm line 108.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FlatFileToJson.pm line 18.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/flatfile-to-json.pl line 7.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/flatfile-to-json.pl line 7.
> Traceback (most recent call last):
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 709, in <module>
>     for key in keys:
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 578, in process_annotations
>     track['conf']['options']['gff'])
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 538, in add_features
>     self.subprocess_check_call(cmd)
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 335, in subprocess_check_call
>     subprocess.check_call(command, cwd=self.outdir)
>   File "/remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['perl', '/remote/RMS/users/galaxyd/job_working_directory/013/13750/conda-env/opt/jbrowse/bin/flatfile-to-json.pl', '--gff', '/remote/RMS/users/galaxyd/files/094/dataset_94717.dat', '--trackLabel', '955cdeb547221b777c786d630d2d8f51_0', '--key', 'GFF3 file from data 48', '--clientConfig', '{"className": "feature", "color": "#a6cee3", "description": "note,description", "label": "name,id"}', '--trackType', 'JBrowse/View/Track/CanvasFeatures', '--config', '{"category": "Default", "menuTemplate": [{}, {}, {}, {}], "key": "GFF3 file from data 48", "label": "955cdeb547221b777c786d630d2d8f51_0"}']' returned non-zero exit status 255
>
>

**Comment by abretaud** [comment]
Sorry, I have no clue why you have this error :/
Could there be some conflict with another perl version installed on your server?

**Comment by dwightkuo** [comment]
I am using perlbrew when starting up the galaxy server. I just tried
changing all of the references "#!/usr/bin/perl" to "#!/usr/bin/env perl".
I now get a different message:

> Fatal error: Exit code 1 ()
> Perl API version v5.23.6 of Encode does not match v5.22.0 at /remote/RMS/users/galaxy/perl5/perlbrew/perls/perl-5.23.6/lib/site_perl/5.23.6//x86_64-linux-thread-multi/XSLoader.pm line 114.
> Compilation failed in require at /remote/RMS/users/galaxy/perl5/perlbrew/perls/perl-5.23.6/lib/site_perl/5.23.6/Pod/Text.pm line 33.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxy/perl5/perlbrew/perls/perl-5.23.6/lib/site_perl/5.23.6/Pod/Text.pm line 33.
> Compilation failed in require at (eval 3) line 2.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxy/perl5/perlbrew/perls/perl-5.23.6/lib/site_perl/5.23.6/Pod/Usage.pm line 30.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd.pm line 6.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd.pm line 6.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/lib/perl5/5.22.0/base.pm line 99.
> 	...propagated at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/lib/perl5/5.22.0/base.pm line 108.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/opt/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FormatSequences.pm line 13.
> Compilation failed in require at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/opt/jbrowse/bin/prepare-refseqs.pl line 7.
> BEGIN failed--compilation aborted at /remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/opt/jbrowse/bin/prepare-refseqs.pl line 7.
> Traceback (most recent call last):
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 669, in <module>
>     gencode=root.find('metadata/gencode').text
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 315, in __init__
>     self.process_genomes()
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 344, in process_genomes
>     '--fasta', genome_path])
>   File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/db5fe5a3176a/jbrowse/jbrowse.py", line 335, in subprocess_check_call
>     subprocess.check_call(command, cwd=self.outdir)
>   File "/remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['perl', '/remote/RMS/users/galaxyd/job_working_directory/013/13848/conda-env/opt/jbrowse/bin/prepare-refseqs.pl', '--fasta', '/remote/RMS/users/galaxyd/files/094/dataset_94714.dat']' returned non-zero exit status 2
>
>

**Comment by dwightkuo** [comment]
In case anyone is running into this issue, I managed to get around this by manually specifying the LD_LIBRARY_PATH and PERL5LIB paths within the jbrowse.xml

```
export LD_LIBRARY_PATH=/opt/shed_tools/_conda/pkgs/libdb-6.1.26-0/lib:\$LD_LIBRARY_PATH;  
export PERL5LIB=/opt/shed_tools/_conda/pkgs/perl-db-file-1.835-5/lib/perl5/site_perl/5.22.0:/opt/shed_tools/_conda/pkgs/perl-file-next-1.16-0/lib/perl5/site_perl/5.22.0:/opt/shed_tools/_conda/pkgs/perl-file-next-1.16-0/lib/perl5/site_perl/5.22.0:/opt/shed_tools/_conda/pkgs/perl-hash-merge-0.200-0/lib/perl5/site_perl/5.22.0:/opt/shed_tools/_conda/pkgs/perl-digest-crc32-0.01-0/lib/perl5/site_perl/5.22.0:/opt/shed_tools/_conda/pkgs/perl-json-2.90-1/lib/perl5/site_perl/5.22.0:/usr/local/share/perl5;
```
