### ISSUE TITLE
Cannot find the tool from admin panel 

### ISSUE THREAD

**Issue by CicoZhang** [galaxyproject/tools-iuc#1166]
I would like to install the circos plot tool. I Googled it and found it in toolshed. 

https://toolshed.g2.bx.psu.edu/view/saskia-hiltemann/cg_circos_plots

![image](https://cloud.githubusercontent.com/assets/11710225/22662927/0d6a295c-ecab-11e6-8db2-235f3797639b.png)

However, I cannot find it within the admin panel. (I have tried two Galaxy instances in different servers). 

![image](https://cloud.githubusercontent.com/assets/11710225/22662912/004ef108-ecab-11e6-88e3-4c88b5e69501.png)

![image](https://cloud.githubusercontent.com/assets/11710225/22662939/1d35fb0e-ecab-11e6-8bf3-1f671df36e5d.png)

Thank you for the help in advance.

**Comment by martenson** [comment]
@CicoZhang That repository has no contents so it is not installable. Ping @shiltemann - can you give some details please?

However there are some circos repositories on the Test Tool Shed which might be worth trying.

https://testtoolshed.g2.bx.psu.edu/view/iuc/circos_tools/04ec82208544

**Comment by CicoZhang** [comment]
@martenson  Thank you for the information, I will try this one on the test toolshed.

**Comment by martenson** [comment]
@CicoZhang please keep us posted whether it works for you. Thanks.

**Comment by shiltemann** [comment]
Hi Cico, how are you?  :) ..this is a tool I made a long time ago, it was in our DTL/NBIC toolshed, which, s you know, they shut down a couple years ago. I was going to move it over to main tool shed, but it is a tool for very a specific version of Complete Genomics file formats, which they've now stopped producing, so I never did..

If you are looking to visualize old CG data I can dig up the code for you and put it in the toolshed, but if you are looking for a more generic circos plotter, this tool will not help you I am afraid, and you're better off trying the tool suggested by @martenson

**Comment by martenson** [comment]
@shiltemann would you mind deprecating your [repository](https://toolshed.g2.bx.psu.edu/view/saskia-hiltemann/cg_circos_plots) so it does not show up in search?

**Comment by shiltemann** [comment]
will do!

**Comment by CicoZhang** [comment]
@shiltemann Hi, Saskia, I am doing well, how about you?  Actually, I am looking for a general version of Circos plot. Here is another one: https://f1000research.com/slides/5-1875, I am not sure whether it is the same with the one recommended by @martenson .

Thank you again for the responsive help.

**Comment by martenson** [comment]
ping @erasche ^^

**Comment by martenson** [comment]
@CicoZhang those slides seem to refer to this dev repository: https://github.com/TAMU-CPT/galaxy-circos-tool which in turn seems to not be published in Tool Shed yet.

**Comment by CicoZhang** [comment]
@martenson Got it. It is a different Galaxy tool. :+1:

**Comment by erasche** [comment]
Yep, different one. Just waiting on the chord implementation from @shiltemann before we move it to the MTS (No pressure @shiltemann ;)) for the first release. No estimate for when that will be available I'm afraid. (Though if you wish to install it manually and test it, we'd be happy to have feedback on it!)

**Comment by CicoZhang** [comment]
@erasche Thank you for letting me know. I am gonna install it manually and give some feedback if possible. :+1:
