### ISSUE TITLE
Freebayes wrapper does not respect the "Limit to region" option

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#1169]
When I enter a region to limit the analysis to, freebayes still outputs variants outside of that region. I suspect this is due to the parallel implementation, but I haven't had looked through the code yet.

Also, the latest version, `1.0.2.29-2`, is not available on the toolshed. I believe that automatic pushes to the toolshed for tools not owned by iuc may still be broken.

**Comment by nsoranzo** [comment]
> Also, the latest version, 1.0.2.29-2, is not available on the toolshed. I believe that automatic pushes to the toolshed for tools not owned by iuc may still be broken.

@lparsons `freebayes` repo should now be updated and the automatic push fixed for the 4 repositories recently migrated from devteam (emboss_5, fastqc, freebayes, picard).

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/tools-iuc/pull/1289.
