### ISSUE TITLE
IUC member proposal - Bérénice Batut

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#1171]
I am proposing Bérénice Batut to become an IUC member.

Bérénice (@bebatut) did recently substantial work on EBI tools and Qiime. Moreover she keeps her work maintained (https://github.com/galaxyproject/tools-iuc/pull/1164). She also contributes to Galaxy training materials (leading committer there - by far!) and other Galaxy-related projects.

IUC repo contributions: https://github.com/galaxyproject/tools-iuc/commits?author=bebatut
Galaxy repo contributions: https://github.com/galaxyproject/galaxy/commits?author=bebatut 
training material: https://github.com/galaxyproject/training-material/graphs/contributors

Please comment and vote.

Martin

**Comment by bgruening** [comment]
Yeah!!!

**Comment by erasche** [comment]
:+1:. amazing work on the training materials @bebatut!

**Comment by nsoranzo** [comment]
:+1:

**Comment by abretaud** [comment]
Youpi ! :+1:

**Comment by mvdbeek** [comment]
👍

**Comment by shiltemann** [comment]
big :+1:!

**Comment by blankenberg** [comment]
+1

**Comment by bebatut** [comment]
Thanks a lot !!!

**Comment by martenson** [comment]
@bebatut Welcome! I have invited you to the IUC team on GitHub. Please make sure you have a strong password here.

**Comment by bebatut** [comment]
Thanks a lot :)

**Comment by martenson** [comment]
Somebody else needs to invite you to the mailing list, I do not have the rights. :)
