### ISSUE TITLE
Enforce required inputs for Sailfish

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1179]
This parameter is required but can be left empty when the form is submitted. This results in a spurious error. 

`File containing a mapping of transcripts to genes`

If this is done, while updating the tool please also consider:

 1.  Adding in "(required)" to help text for the three key inputs (transcriptome, fastq, ref annotation).
 2. Clarify that the tool accepts fasta input having title lines without description content (identifier only, same as "split at first whitespace"). The tool NormalizeFasta can be used.

**Comment by bernt-matthias** [comment]
Please report over here: https://github.com/bgruening/galaxytools
