### ISSUE TITLE
Update Stringtie version

### ISSUE THREAD

**Issue by ACastanza** [galaxyproject/tools-iuc#1185]
The latest version of Stringtie (v1.3.3) fixes a critical issue with transcriptome assembly using guide sequences. Galaxy is currently on version 1.2.3 which is substantially behind the current release and in addition to the issue above, has known problems parsing several types of GTF files, and a calculation bug with several aspects of transcript abundance estimation and coverage values. Would it be possible to get the new release integrated into the main server?

https://ccb.jhu.edu/software/stringtie/

**Comment by bgruening** [comment]
@ACastanza as soon as we update this wrapper here I guess the main Galaxy instance can be updated real quick. Are you interested in helping to update them? PR welcome!

**Comment by ACastanza** [comment]
I know literally nothing about Github or the inner workings of galaxy but I made some guesses? https://github.com/ACastanza/tools-iuc/tree/master/packages/package_stringtie_1_3_3

**Comment by bgruening** [comment]
I guess all what we need to update is the tool, not the package: https://github.com/galaxyproject/tools-iuc/blob/master/tools/stringtie/stringtie.xml

Do you know if any new parameters were added or removed since this old version?

**Comment by bgruening** [comment]
Here is a very primitive start: https://github.com/galaxyproject/tools-iuc/pull/1186

I haven't looked at any parameter that needs to be updated or new functions we need to add.

**Comment by ACastanza** [comment]
They added a script (prepDE.py) that allows conversion of stringtie outputs to produce DESeq2 and edgeR compatible read counts, but it appears to be a separate script and not a direct component of stringtie. Everything else appears to be bugfixes.

**Comment by bgruening** [comment]
Ok, we need to get this in as an additional output. But this means a little bit more work.

**Comment by bgruening** [comment]
here is the conda package with prepDE: https://github.com/bioconda/bioconda-recipes/pull/3916 and I have worked a little bit on: https://github.com/galaxyproject/tools-iuc/pull/1186

But there is still work do be done. Especially in hiding outputs that are not needed ... maybe asking the user if he want to have ballgown *or* DESeq/EdgeR output.

**Comment by bgruening** [comment]
@MoHeydarian this might be interesting for you as well. From stringtie to DESeq2 ....

**Comment by davebx** [comment]
StringTie 1.3.3 is now running on main
