### ISSUE TITLE
Make picard_SamToFastq output collections of fastq

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#1190]
When converting a collection of BAM files, picard_SamToFastq does not output a collection of FASTQ files as expected. Instead, the fastq files are simply separate history items and lose association with the element identifiers.

**Comment by bernt-matthias** [comment]
This seems to be because datasets are discovered:

```
    <data format="txt" name="report" label="SamToFastq run" hidden="true">
      <discover_datasets pattern="(?P&lt;designation&gt;.+)\.fastq" ext="fastqsanger" visible="true"/>
    </data>
```

Don't know if this can be circumvented...

**Comment by bernt-matthias** [comment]
Maybe we just make this a collection. Not sure if the output will then be a nested collection...

**Comment by bernt-matthias** [comment]
This should be fixed in https://github.com/galaxyproject/tools-iuc/pull/2855.. Please reopen if needed.
