### ISSUE TITLE
GCC17 abstract for IUC work

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#1256]
Deadline in 5 hours from now (midnight in Montpelier).

Please edit here: https://docs.google.com/document/d/1u2ls9GD7B8xHwyeB3yEQjYVemz7oFX8O3dTYCRfmjZo/edit?usp=sharing

ping @galaxyproject/iuc

**Comment by bgruening** [comment]
On it.

**Comment by martenson** [comment]
This has been submitted, thanks all.
