### ISSUE TITLE
Declaring packages legacy and marking them as unmaintained

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#1262]
Dear @galaxyproject/iuc 

I would like to move all packages on the IUC's github repo into the deprecated folder, so that it is clear that the way forward is to abandon these packages. The infrastructure for using Conda is in place in galaxy since 16.01, and I would consider this mature since 17.01.

This may be a problem for administrators running older galaxy versions, but the likelihood of successfully installing things like R or deeptools with the complete dependency chain from scratch today is low (outdated download links, newer/older gcc versions, etc. pp.).
I personally consider time spent on toolshed packages in 2017 a waste of time (on top of it being a frustrating experience).

Consequently, I think we should also lobby for toolshed package dependency installations to not be the default, starting as soon as possible.

**Comment by nsoranzo** [comment]
:100:

**Comment by yhoogstrate** [comment]
I like this idea too. Do you think this requires to deprecate the tools listed in https://github.com/galaxyproject/tools-iuc/blob/master/.tt_blacklist ?

**Comment by mvdbeek** [comment]
That's a good point. So right now these are:
- [ ] tools/differential_count_models
- [ ] tools/gatk2
- [ ] tools/gff3_rebase
- [ ] tools/progressivemauve
- [ ] tools/rglasso
- [ ] tools/rgrnastar
- [ ] tools/taxonomy
- [ ] tools/gemini
- [ ] tools/taxonomy_krona_chart
- [ ] tools/tool_factory_2
- [ ] tools/transtermhp

tool_factory_2 just needs ghostscript or graphicsmagick, that should be doable.
differential_count_models is kind of nice because of the comparison between deseq2/edgeR/limma and the nice plots it produces by default. But all these packages are outdated, and I think it is effectively already unmaintained.

The other tools I haven't used, so I'm not sure about their status.

**Comment by peterjc** [comment]
I also agree in principle, but think we need to continue to support the legacy packaging for a little longer - while as you say pushing people towards the bioconda infrastructure.

Separately I've emailed the IUC list about strategies for ensuring things are available on both during this transition period. Is it acceptable/sensible to add old versions of packages already on bioconda?

**Comment by mvdbeek** [comment]
> Is it acceptable/sensible to add old versions of packages already on bioconda?

I think so. IIRC this was the reason we didn't invest more energy in homebrew.

**Comment by peterjc** [comment]
Can we systematically check all the legacy packages to ensure everything is present in bioconda (and add older versions to bioconda as needed)?

**Comment by mvdbeek** [comment]
> Can we systematically check all the legacy packages to ensure everything is present in bioconda (and add older versions to bioconda as needed)?

I think @bgruening had been working towards this, and initially I was also thinking that would be important. We do have an IUC conda channel that we can use for "dirty" packages. But currently I think it may be wiser to work towards "future-facing reproducibility", and assume that few people are going to re-install old tools with old packages (which will still be possible! We're just discouraging people from investing time in these packages, be it an admin that installs a legacy toolshed package when conda would be available, or a developer that updates outdated packages).

**Comment by bgruening** [comment]
For the list of blacklisted packages it would be nice if we can fix a few more of them.

`RNAstar` will be fixed here: https://github.com/galaxyproject/tools-iuc/pull/1207
`Gemini`, needs some love. ping @gregvonkuster 
`taxonomy_*` @blankenberg or @davebx 
`progressivemauve` and `gff3_rebase` @bgruening or @erasche 

GATK should be depreacted.
It would be great if we can tackle this before the IUC - GCC talk, if we get a spot :)

---- 

Regarding the auto-convertion of all package to conda packages I started this many moth ago. I actually took your work of xml to bash and created out of this conda packages:

https://github.com/galaxyproject/planemo/compare/master...bgruening:conda?expand=1

I never finished this and it was my first conda related work. At the moment I'm not sure it is worth the effort. It for sure a good idea to do so, but it means some more work.

I would put these packages in conda-iuc.

**Comment by abretaud** [comment]
I just made it for the gff3_rebase: #1266

**Comment by yhoogstrate** [comment]
@mvdbeek How do you think about starting with deprecating the packages that are not involved with tools from the blacklist?

**Comment by nsoranzo** [comment]
@yhoogstrate I'm not against, but there may be third-party tools which depend on them.

**Comment by peterjc** [comment]
There are indeed third party tools depending on IUC packages, I have some and at least one dependency has been reported broken (#1001). Closing such issues just ignores these problems - although as Galaxy instances move to conda, the problems do "go away".

**Comment by mvdbeek** [comment]
I don't think we'd have the capacity to fix these packages in any case. My guess is that half of them are either directly broken or broken through something in their dependency chain. Let's do it now :)

**Comment by peterjc** [comment]
You're right about capacity issues, practically speaking it would avoid false hope if these were all deprecated.

Are we talking about flagging them as deprecated on the Tool Shed (which hides them by default and blocks updates)? That isn't yet easy to do with planemo - see https://github.com/galaxyproject/planemo/issues/670

**Comment by davebx** [comment]
@bgruening 
> GATK should be depreacted.

Or maybe not? 

https://www.broadinstitute.org/news/broad-institute-release-genome-analysis-toolkit-4-gatk4-open-source-resource-accelerate

**Comment by nsoranzo** [comment]
gatk2 should.

**Comment by erasche** [comment]
This motion passes. @mvdbeek would you please submit a PR that fixes this + closes this issue?
