### ISSUE TITLE
Move some download_store packages to BioArchive

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#128]
Now that @nitesh1989 has built http://bioarchive.github.io/, perhaps it's time to move `package_r_ggplot2`'s R packages to using bioarchive.

For those not familiar with bioaRchive, it's a dump of EVERY version of every package from Bioconductor

**Comment by bgruening** [comment]
Sure! @nitesh1989 let me know what to do.

**Comment by erasche** [comment]
Well... blocking on https://github.com/bioarchive/aRchive_source_code/issues/9 (unless @nitesh1989 has suggestions on how to download without .tar.gz files).

**Comment by nitesh1989** [comment]
@erasche @bgruening Adding code to tar.gz the files. I'll let you guys know as soon its done.

**Comment by bgruening** [comment]
@nitesh1989 feel free to pull everything what you need from `download_store`

**Comment by erasche** [comment]
@bgruening this is a de-novo archive generated from walking back through svn revisions, no `download_store` files needed :)

**Comment by bgruening** [comment]
Can we close this? I guess bioarchive will get a major redesign before we start the migration, isn't it?

**Comment by erasche** [comment]
Most things have started moving that direction, happy to close this now.
