### ISSUE TITLE
Problem with DEXseq tools in Galaxy

### ISSUE THREAD

**Issue by afalaki** [galaxyproject/tools-iuc#1281]
Dear,

I tried to use Dexseq and Dexseq_Count tools to prepare an annotation and count reads, but unfortunately I encountered a Fatal error (in red color). I was wondering if there is something wrong with the GTF file that I used or it can be an error in the tool. I highly appreciate it if you please check it. Please find the errors as follows:
```
Fatal error: Exit code 127 ()
/galaxy-repl/main/jobdir/015/654/15654942/tool_script.sh: line 9: dexseq_prepare_annotation.py: command not found

Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
Error in library("DEXSeq") : there is no package called 'DEXSeq'
```
If any further information is needed, please let me know.
Thanks.

Best,
Ali

**Comment by jennaj** [comment]
Dexseq at Galaxy Main has had the dependencies updated. Please run the job again.

Future questions about tool usage/errors can be directed at Galaxy Biostars: https://galaxyproject.org/support/biostar/ or a bug report can be sent in (when working at https://usegalaxy.org)

IUC team - this can be closed out
