### ISSUE TITLE
HISAT's long conda shebang causes extract_splice_sites.py to fail

### ISSUE THREAD

**Issue by chambm** [galaxyproject/tools-iuc#1318]
When I run the tool_script, I get:
```
/vol_b/jobs/000/95/tool_script.sh: /opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2bb67013a57cac1e35f407d06d1f347baae35159f498496f1e36f84784069212/bin/hisat2_extract_splice_sites.py: /opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2bb67013a57cac1e35f407d06: bad interpreter: No such file or directory
```

This is due to bash cutting off the shebang at ~80 characters. The full shebang of `hisat2_extract_splice_sites.py` is:
```
#!/opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2bb67013a57cac1e35f407d06d1f347baae35159f498496f1e36f84784069212/bin/python
```
Is something wrong with my conda or Galaxy config that the shebang is this long?

**Comment by bgruening** [comment]
@chambm can you try if this is fixing your problem? https://github.com/bioconda/bioconda-recipes/pull/4744

**Comment by caleb-easterly** [comment]
I'm getting the same problem with a different tool. @bgruening, I'm not following your fix. Any tips?

```
Fatal error: Exit code 126 ()
/opt/galaxy/galaxy-app/database/jobs/001/1233/tool_script.sh: /opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2c23d9457252de1265d8ebc008be117ea2c1ac830cc74f44aa02abdc91991306/bin/metaquant: /opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2c23d9457252de1265d8ebc00: bad interpreter: No such file or directory
```
The full shebang is 
```
#!/opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2c23d9457252de1265d8ebc008be117ea2c1ac830cc74f44aa02abdc91991306/bin/python
```

**Comment by bgruening** [comment]
@caleb-easterly and this #!/opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2c23d9457252de1265d8ebc008be117ea2c1ac830cc74f44aa02abdc91991306/bin/python does not exists?

**Comment by caleb-easterly** [comment]
As far as I can tell, it does exist, but when it gets called by bash it's truncated to `/opt/galaxy/tool_dependencies/_conda/envs/mulled-v1-2c23d9457252de1265d8ebc00`, which doesn't exist

**Comment by bgruening** [comment]
I'm not sure why it should do this. Which exact version is not working? Can you try on usegalaxy.eu, than I have a handle on that.

**Comment by nsoranzo** [comment]
Are you using conda <4.3.15 to create the environment? This should have been fixed in https://github.com/conda/conda/pull/4828 .
If that's the case, update conda and recreate the environment.

**Comment by caleb-easterly** [comment]
Ah, it was an old conda installation. Thanks!
