### ISSUE TITLE
Rename Stringtie tools to make it easier to tell different tools apart

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1320]
Example:

**StringTie** merge transcripts
**StringTie** transcript assembly and quantification

The bold part of the name should be unique across tools. thanks!

**Comment by malloryfreeberg** [comment]
This could be edited to:
**StringTie merge** transcripts
**StringTie** transcript assembly and quantification

"StringTie merge" is how users typically refer to the first tool.

**Comment by jennaj** [comment]
Thanks @malloryfreeberg @nsoranzo @bgruening 

@davebx Could we update this at http://usegalaxy.org? The tool shed has the updated version. Same version 1.3.3 with modified tool name from 6/1/2017 repo.
