### ISSUE TITLE
Stringtie 1.3.3 errors when the option to output Deseq2/EdgeR is used

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1322]
Switching to no additional output or to Ballgown works fine. All inputs appear to meet specification and this is reproducible across different input datasets/target genomes.

**Error produced:** 

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/galaxy/main/deps/_conda/envs/__stringtie@1.3.3/bin/prepDE.py", line 186, in <module>
    t_dict.setdefault(t_id, {})
NameError: name 't_id' is not defined
```

**Example job info**

```
StringTie
Dataset Information
Number:	XX
Name:	StringTie on data X and data X: Assembled transcripts
Created:	Fri 19 May 2017 08:06:59 PM (UTC)
Filesize:	40.5 MB
Dbkey:	mm10
Format:	gtf
Job Information
Galaxy Tool ID:	toolshed.g2.bx.psu.edu/repos/iuc/stringtie/stringtie/1.3.3
Galaxy Tool Version:	1.3.3
Tool Version:	1.3.3
Tool Standard Output:	stdout
Tool Standard Error:	stderr
Tool Exit Code:	1
History Content API ID:	X
Job API ID:	X
History API ID:	X
UUID:	X
Full Path:	/galaxy-repl/main/files/X/X/dataset_X.dat

Tool Parameters
Input Parameter	Value	Note for rerun
Mapped reads to assemble transcripts from	X: SortSam on data X: BAM sorted in coordinate order	
Use GFF file to guide assembly	yes	
Reference annotation to use for guiding the assembly process	X: UCSC Main on Mouse: knownGene (genome)	
Perform abundance estimation only of input transcripts	False	
Output additional files for use in...	deseq2	
Average read length	75	
Whether to cluster genes that overlap with different gene IDs	False	
Options	default	
Job Resource Parameters	no	

Inheritance Chain
StringTie on data X and data X: Assembled transcripts

Command Line
mkdir -p ./special_de_output/sample1/ && ln -s '/galaxy-repl/main/files/X/X/dataset_X.dat' ./special_de_output/sample1/guide.gtf &&  stringtie '/galaxy-repl/main/files/X/X/dataset_X.dat'  -o "/galaxy-repl/main/files/X/X/dataset_X.dat" -p "${GALAXY_SLOTS:-1}" -C '/galaxy-repl/main/files/X/X/dataset_X.dat.dat' -G '/galaxy-repl/main/files/X/X/dataset_X.dat'  -b ./special_de_output/sample1/  && prepDE.py -i ./special_de_output/ -g gene_cout_matrix.tsv -t transcripts_count_matrix.tsv -l 75 && sed -i.bak 's/,/\t/g' transcripts_count_matrix.tsv && sed -i.bak 's/,/\t/g' gene_cout_matrix.tsv

Job Metrics

core

Cores Allocated	4
Job End Time	2017-05-19 15:13:40
Job Runtime (Wall Clock)	6 minutes
Job Start Time	2017-05-19 15:07:24

cpuinfo

Processor Count	32

meminfo

Total System Memory	123.0 GB
Total System Swap	976.6 MB

uname

Operating System	Linux roundup52.XXXX XXX #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Job Dependencies
Dependency	Dependency Type	Version
stringtie	conda	1.3.3
```

cc @davebx

**Comment by jennaj** [comment]
When used at http://usegalaxy.org, there is another small warning that comes up. Not sure if related to current server issues. If "Ballgown" output is selected (same run as above), this is printed in the info comments for the green results datasets:

`rm: cannot remove `working/special_de_output/sample1': Directory not empty`

**Comment by jennaj** [comment]
This error occurred on jobs run yesterday. I can't reproduce it today. Maybe was a cluster issue. Closing for now, but will reopen if can figure out what triggers it.

**Comment by jennaj** [comment]
A few more reports of this error have been reported. I can reproduce the error again now in a current Galaxy RNA-seq tutorial history, using the latest version of the tool. The last four stringtie jobs were run with the four different related options - three pass, one fails ("additional output files = DEseq/EdgeR"). More details in the history annotation. https://usegalaxy.org/u/jen/h/test-history-stringtie-133

This seems important to fix with priority. @MoHeydarian @davebx @martenson @natefoo

**Comment by jennaj** [comment]
**Specific problem:**

Stringtie-merge performs summary calculations and produces new "transcript" lines in the result (and resets the "Source" and removes other content lines). Running just iGenomes/external GTF through the Stringtie-merge tool will groom it and allow a successful job. 

**Work-around for now:**

If using an external GTF source with this tool, and not using Stringtie merge transcripts, running just the external GTF dataset through the **Stringtie merge transcripts** tool (as an "input_gtf") will produce a version of the reference annotation that can be used by **Stringtie**.

**How to resolve?** 

One or more of these? Some are @MoHeydarian ideas and other solutions are likely possible.

1. Explain this usage on both of the tool forms and in web help/tutorials
2. Allow Stringtie to detect when a GTF does not have the "transcript" annotation lines and error with a message explaining that the input needs to be groomed/prepared with the merge tool first
3. Have the primary Stringtie tool create the "transcript" lines if they are not present
4. Have the primary Stringtie tool not require "transcript" lines if they are not actually used by the tool

ping @bgruening

**Comment by davebx** [comment]
One of the issues is that the `prepDE.py` expects `t_id` to be set regardless of whether or not the provided gtf file even contains transcripts. I also noticed that it only increments the transcript length by `stop` - `start` if the line currently being examined is an exon, not a transcript. All in all, I'm confused by this script.

**Comment by davebx** [comment]
The `prepDE.py` script is written in a way that I'm confused as to what it's supposed to accomplish. It also references variables before they could possibly have been created.

**Comment by jennaj** [comment]
Still errors.

@bgruening Do you know if a correction for this is in progress or planned for? ETA? Or is cycling/prepping through strigtie-merge the solution? If so, I can add that to the help. Thanks!

**Comment by bgruening** [comment]
Upps, sorry missed this completely, will look into it tomorrow.

**Comment by jennaj** [comment]
Hi - any updates?

**Comment by bgruening** [comment]
@jennaj with `primary Stringtie tool` you mean the upstream tool, not the Galaxy tool? If so 3. and 4. are out of scope here, right?

Could you provide some text for 1) and 2) and I can get this into the tool.

**Comment by NCEichner** [comment]
Hi everyone!

We had the same issue with 't_id' not defined in prepDE.py. I think I can present some solution here but I don't know how to send commits. So maybe someone else can add the changes to the 'stringtie.xml'-file and test if that resolves the problem.
In general the problem is caused because the input of the python script 'prepDE.py' actually is not the stringtie-OUTPUT-file (in the history shown as 'Assembled transcripts') but the .gtf-file which was set in the '-G' option of stringtie (see 'Reference annotation to use for guiding the assembly process' in the GUI). So in the command-line the 'ln' command is at the wrong position and is referencing the wrong file.

We patched the command-section and the output-section of the stringtie.xml as follows:`
 
        mkdir -p ./special_de_output/sample1/ &&

        #if $input_bam.metadata.ftype == 'sam':
            samtools sort -@ \${GALAXY_SLOTS:-1} '$input_bam' | stringtie
        #else
            stringtie '$input_bam'
        #end if
`
Above we deleted the 3 lines below the mkdir-command.

`

        #if str($guide.use_guide) == 'yes':
            #if $guide.special_outputs.special_outputs_select == 'deseq2':
                &&
                ln -s '$output_gtf' ./special_de_output/sample1/output.gtf
                &&
                prepDE.py
                    -i ./special_de_output/
                    -g gene_counts.tsv
                    -t transcript_counts.tsv
                    -l $guide.special_outputs.read_length
                    #if str($option_set.options) == 'advanced':
                        -s '$option_set.name_prefix'
                    #end if
                    #if $guide.special_outputs.clustering:
                        -c
                        --legend legend.tsv
                        &&
                        sed -i.bak 's/,/\t/g' legend.tsv
                        &&
                        sed -i.bak 's/\r//g' legend.tsv
                        &&
                        mv -T legend.tsv "$legend"
                    #end if
                &&
                sed -i.bak 's/,/\t/g' transcript_counts.tsv
                &&
                sed -i.bak 's/\r//g' transcript_counts.tsv
                &&
                mv -T transcript_counts.tsv "$transcript_counts"
                &&
                sed -i.bak 's/,/\t/g' gene_counts.tsv
                &&
                sed -i.bak 's/\r//g' gene_counts.tsv
                &&
                mv -T gene_counts.tsv "$gene_counts"
            #end if
        #end if

`
The 'ln' command then was added just before the 'prepDE.py'. It's using the output.gtf from stringtie.
The additional commands are cleaning up the 'prepDE.py' output (.csv to .tsv; carriage return-deletion before LF).
The resultfiles are moved to the database after editing.   

`

        <data name="gene_counts" format="tabular" label="${tool.name} on ${on_string}: Gene counts">
            <filter>guide['use_guide'] == 'yes' and guide['special_outputs']['special_outputs_select'] == 'deseq2'</filter>
        </data>
        <data name="transcript_counts" format="tabular" label="${tool.name} on ${on_string}: Transcript counts">
            <filter>guide['use_guide'] == 'yes' and guide['special_outputs']['special_outputs_select'] == 'deseq2'</filter>
        </data>
        <data name="legend" format="tabular" label="${tool.name} on ${on_string}: legend">
            <filter>guide['use_guide'] == 'yes' and guide['special_outputs']['special_outputs_select'] == 'deseq2' and guide['special_outputs']['clustering'] is True</filter>
        </data>

`
In the Output-section we cleaned up the references to the working-directory because the are no longer needed.

**Comment by mblue9** [comment]
Hi @NCEichner I only learnt how to make commits here pretty recently and I have some notes I started making for our in-house documentation (on how to test Galaxy tools and submit to Github). I've attached them here in case they're any use to you, if you wanted to try making commits yourself sometime (it sounds like you've got good suggestions!).

[GAD-TestingatoolusingPlanemo-121017-1229-18.pdf](https://github.com/galaxyproject/tools-iuc/files/1377716/GAD-TestingatoolusingPlanemo-121017-1229-18.pdf)
[GAD-SubmittingtoolstoIUC-121017-1242-20.pdf](https://github.com/galaxyproject/tools-iuc/files/1377717/GAD-SubmittingtoolstoIUC-121017-1242-20.pdf)

**Comment by mblue9** [comment]
Oops, I just noticed something I had added to the wrong place in that planemo doc, corrected version is attached here: 
[GAD-TestingatoolusingPlanemo-121017-1256-22.pdf](https://github.com/galaxyproject/tools-iuc/files/1377743/GAD-TestingatoolusingPlanemo-121017-1256-22.pdf)

**Comment by jennaj** [comment]
Tests pass: https://usegalaxy.org/u/jen/h/test-history-stringtie-and-stringtie-merge-133 data 187-188. Many thanks!
