### ISSUE TITLE
Best practices for FASTQ output formats

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#1323]
While this is a general problem, it is based on a problem with my stacks clone_filter tool so I am pinging @bgruening and @abretaud .

My question is: what is the best practice for FASTQ output formats? Namely compressed versus uncompressed.

I naively made the tool to always output compressed data. In my mind it makes sense: much less disk space occupied. But I had an immediate complain from a user that told me that some tools could not receive the output from clone_filter. I see several alternatives:

1. My preferred is the one I implemented, as it saves disk space on potentially enormous files
2. Another alternative is to use the same format for input as for output (so a compressed file gets compressed output and an uncompressed file gets uncompressed output). But this might be problematic if a tool further down the pipeline does not take whatever is the original format of the data
3. Yet another is to allow the user to choose. But is it really needed to burden the user with this?
4. Finally a hybrid between 2 and 3: Use the default from the input file, but allow the user to override.

Generally I think everything compressed would be the most sensical thing to do. But that is not possible.

I will implement whatever you folks tell me its the best practice.

Thanks

**Comment by nsoranzo** [comment]
If I remember correctly, for some other tool we used option 2.

**Comment by mvdbeek** [comment]
> But I had an immediate complain from a user that told me that some tools could not receive the output from clone_filter.

All tools that accept fastqs will also accept fastq.gz/bz2 etc, though an intermediate conversion step will be automatically invoked. The only time it may appear to not work is when a tools demands e.g fastqsanger and you have a plain fastq.gz and not fastqsanger.gz. I'd always opt for compressed out.

**Comment by peterjc** [comment]
So is the problem ``fastq.gz`` rather than ``fastqsanger.gz`` as the output format?

**Comment by mvdbeek** [comment]
That would be my guess, otherwise I'd consider this a galaxy bug.

**Comment by tiagoantao** [comment]
Argh... I might be missing a dot here:

```
<data format="fastqsangergz" name="clean_fwd" from_work_dir="clone_outputs/R1.1.fq.gz">
```

So, @mvdbeek if I understand well: Other than my idiotic bugs on the XML file, I can choose and not worry? That would be ideal.

I just wonder because in other places I have:

```
<param name="fname" type="data" format="fastqsanger,fastqsanger.gz" label="FASTQ" />
```

i.e. explicitly referring both formats. It would be amazing if this could be handled transparently...

**Comment by peterjc** [comment]
I believe for input using this is best as Galaxy will feed you the FASTQ file as is, compressed or not:

```
<param name="fname" type="data" format="fastqsanger,fastqsanger.gz" label="FASTQ" />
```

However, if you put just one of those formats (say ``fastqsanger``) then Galaxy will let the user supply ``fastqsanger.gz`` and decompress it behind the scenes (meaning more disk IO overhead).

**Comment by peterjc** [comment]
Note if you were missing a dot, I would have expected ``planemo lint ...`` or ``planemo shed_lint --tools ...`` to spot the unrecognised format. Does it?

**Comment by tiagoantao** [comment]
@peterjc Nope, it says all OK.

**Comment by mvdbeek** [comment]
I'll go ahead and close this. Feel free to reopen if there is still any confusion.
