### ISSUE TITLE
vsearch clustering memory limitation

### ISSUE THREAD

**Issue by ccedmendoza** [galaxyproject/tools-iuc#1325]
Hi,
I would like to cluster a database of sequences with sizes from 300bp to 1million + bp. And so I was wondering if it was possible to lift vsearch's memory limitation when clustering?

Thank you for your time.

**Comment by bgruening** [comment]
@ccedmendoza do you have any information how this can be done? Are you sure this is not a limitation of your scheduler configuration?

**Comment by ccedmendoza** [comment]
Thank you for your answer, but I asked the same question on the repository of vsearch and aparently vsearch is not designed to handle very long sequences.

Thank you for your time.
