### ISSUE TITLE
Typo in HISAT2 parameter

### ISSUE THREAD

**Issue by malloryfreeberg** [galaxyproject/tools-iuc#1334]
Under **Alignment options**, the **Skip *reference* strand of reference** parameter should be **Skip *reverse* strand of reference** (screenshot below). This is from tool version 2.0.3 on Main.

![screen shot 2017-05-31 at 1 56 49 pm](https://cloud.githubusercontent.com/assets/10993501/26646484/cbe62a68-4609-11e7-8c85-154711f82080.png)

**Comment by nsoranzo** [comment]
That's already been fixed with commit 709c0094b5ddef2317a214043b58786e86777a03, the tool needs to be updated on Main, ping @martenson @davebx.

**Comment by malloryfreeberg** [comment]
Cool! Thanks for the clarification!

**Comment by bgruening** [comment]
@natefoo @martenson @davebx with the recent advantages of IUC tools and testing, I'm thinking about running a cron job of updating IUC tools weekly. Do you think this is a good idea? Maybe even for main?

**Comment by martenson** [comment]
@bgruening probably not for Main, deploying and updating tools on Main has bunch of cvmfs & Conda mumbo-jumbo. We would love to automate this but have only one @natefoo.

**Comment by martenson** [comment]
This is what updating Main looks like: https://github.com/galaxyproject/usegalaxy-playbook/wiki/Installation-on-Main

**Comment by bgruening** [comment]
There is only one @natefoo ever!
