### ISSUE TITLE
Bowtie2 UI bug: 

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-iuc#1343]
https://github.com/galaxyproject/tools-iuc/blob/master/tools/bowtie2/bowtie2_wrapper.xml#L536

When you want to save mapping_stats in the context of a workflow that includes bowtie2, clicking the star in the workflow editor doesn't successfully save the file and render it in the history. Instead, you need to also check a checkbox in the bowtie parameters (link above). This is confusing UI.

**Comment by nsoranzo** [comment]
This doesn't seem to be a bug of the bowtie2 wrapper, many tools have outputs that are produced only under certain conditions.

**Comment by zfrenchee** [comment]
This is a *UI bug* in the bowtie 2 wrapper, I believe. To reproduce: create a workflow with bowtie2 and "star" **mapping stats** in the workflow editor. That should save the output, but does not, unless you have also checked the checkbox. Though I haven't tested, running bowtie without starring that output but checking that checkbox probably also doesn't work for getting that output.

**Comment by nsoranzo** [comment]
The Galaxy workflow interface does not know *a priori* which of the outputs will be created by the tool, if you want this particular output to be produced you **have to** set this parameter to "Yes", there is no connection with the workflow star. Sorry, that is how it works.
