### ISSUE TITLE
blacklist / test skip list - nearly empty - help needed

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1345]
Hi @galaxyproject/iuc,

our blacklist is nearly empty! https://github.com/galaxyproject/tools-iuc/blob/master/.tt_blacklist

*Peter: now here https://github.com/galaxyproject/tools-iuc/blob/master/.tt_skip (renamed)*

A few things needs to be decided and worked on but I think we can do this until GCC :)

https://github.com/galaxyproject/tools-iuc/pull/1347 deprecates the following 3 tools:
 * [x] tools/gatk2
 * [x] tools/rglasso
 * [x] tools/tool_factory_2

What about:
 * [x] tools/differential_count_models deprecated in https://github.com/galaxyproject/tools-iuc/pull/1398
 * [ ] tools/gemini https://github.com/galaxyproject/tools-iuc/pull/1203
 * [x] tools/progressivemauve #2068
 * [ ] ~~tools/taxonomy~~
 * [x] tools/transtermhp: https://github.com/bioconda/bioconda-recipes/pull/4905 https://github.com/galaxyproject/tools-iuc/pull/1346

**Comment by nekrut** [comment]
We do need GEMINI

**Comment by nsoranzo** [comment]
Also, list of `tool_dependencies.xml` files we may want to remove:
- [ ] data_managers/data_manager_bwameth_index_builder/tool_dependencies.xml
- [ ] data_managers/data_manager_gatk_picard_index_builder/tool_dependencies.xml
- [ ] data_managers/data_manager_snpsift_dbnsfp/tool_dependencies.xml
- [ ] tools/art/tool_dependencies.xml
- [ ] tools/bioperl/tool_dependencies.xml
- [ ] tools/bwameth/tool_dependencies.xml
- [ ] tools/datamash/tool_dependencies.xml
- [ ] tools/data_source_iris_tcga/tool_dependencies.xml
- [ ] tools/differential_count_models/tool_dependencies.xml
- [ ] tools/gemini/tool_dependencies.xml
- [ ] tools/hmmer3/tool_dependencies.xml
- [ ] tools/khmer/tool_dependencies.xml
- [ ] tools/meme/tool_dependencies.xml
- [ ] tools/mlst/tool_dependencies.xml
- [ ] tools/ncbi_entrez_eutils/tool_dependencies.xml
- [ ] tools/pear/tool_dependencies.xml
- [ ] tools/progressivemauve/tool_dependencies.xml
- [ ] tools/raxml/tool_dependencies.xml
- [ ] tools/sickle/tool_dependencies.xml
- [ ] tools/star_fusion/tool_dependencies.xml
- [ ] tools/vegan/vegan_diversity/tool_dependencies.xml
- [ ] tools/vegan/vegan_fisher_alpha/tool_dependencies.xml
- [ ] tools/vegan/vegan_rarefaction/tool_dependencies.xml
- [ ] tools/vsearch/tool_dependencies.xml
- [ ] tools/xpath/tool_dependencies.xml

**Comment by gregvonkuster** [comment]
Work on gemini is started here https://github.com/galaxyproject/tools-iuc/pull/1203 but a bit of work remains.  The next step likely requires more of a gemini expert.

**Comment by nsoranzo** [comment]
Why is there `tools/taxonomy` in `.tt_blacklist`? I can't find a directory with that path.

**Comment by peterjc** [comment]
See also #2123 for renaming the file to avoid the loaded term 'blacklist', assuming that gets merged we can retitle this issue to help with searchability.

**Comment by abretaud** [comment]
I think this was at the time of the conda migration, reopen if still needed
