### ISSUE TITLE
SnpEff Download issues, originally v4.1.0 and still in v4.3k.0

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1354]
The tool only makes the first genome from a nested .zip available in UI 

**Tool:** SnpEff Download Download a new database (Galaxy Version 4.1.0)

**Repo:** https://toolshed.g2.bx.psu.edu/repository?repository_id=93a5efea7e957b53&changeset_revision=7adfd0589f49

**Repo tool version:** 4.3k.0

_Is an update at http://usegalaxy.org the solution or is the problem still in the newer version of the tool as well or is there some configuration problem?_ 

ping @bgruening @davebx @natefoo 

---
**Version 4.1.0 issue**

The requested genome is in the list of the available genomes and the stderr for the database download tool _indicates that all of the data is downloaded_. However, only the first genome in the .zip bundle is available through the UI. 

Zip archives are not parsed through upload in a default Galaxy (nor at Galaxy Main). Only the first file is loaded. Not sure if related but seemed worth mentioning.

https://usegalaxy.org/u/jen/h/snpeff-database-download-test-history

<img width="970" alt="screen shot 2017-06-08 at 4 40 58 pm" src="https://user-images.githubusercontent.com/8999735/26955562-5aca7866-4c6c-11e7-92e2-c7e7cf682bf1.png">

**Genome requested by the tool:**

https://www.ncbi.nlm.nih.gov/genome/?term=txid264462[Organism:noexp]
**Bdellovibrio_bacteriovorus_HD100_uid61595**
refseq: NC_005363.1
INSDC: BX842601.2

**Genome accessible by SnpEff tool:**

https://www.ncbi.nlm.nih.gov/genome/486?genome_assembly_id=167053
**Bacillus_thuringiensis_BMB171_uid49135**
chr refseq: NC_014171.1	
chr INSDC: CP001903.1
plsm refseq: NC_014172.1
plsm INSDC: CP001904.1

Examining the target .zip when obtained directly (using the same path that the tool uses) shows that the zip does have the target genome in the set. The genome available through the UI is the first in the archive.

> $ curl https://managedway.dl.sourceforge.net/project/snpeff/databases/v4_1/snpEff_v4_1_NCBI_bacterial_4.zip > snpEff_v4_1_NCBI_bacterial_4.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  102M  100  102M    0     0  5530k      0  0:00:18  0:00:18 --:--:-- 5725k
> $ unzip snpEff_v4_1_NCBI_bacterial_4.zip
> Archive:  snpEff_v4_1_NCBI_bacterial_4.zip
>   inflating: wsu/home/eq/eq83/eq8302/snpEff/data/Bacillus_thuringiensis_BMB171_uid49135/snpEffectPredictor.bin  
>   inflating: wsu/home/eq/eq83/eq8302/snpEff/data/Bacillus_thuringiensis_Bt407_uid177931/snpEffectPredictor.bin
>   inflating: wsu/home/eq/eq83/eq8302/snpEff/data/Bacillus_thuringiensis_HD_771_uid173374/snpEffectPredictor.bin
> etc.. for all 

> $ ls
> Bacillus_thuringiensis_BMB171_uid49135
> Bacillus_thuringiensis_Bt407_uid177931
> Bacillus_thuringiensis_HD_771_uid173374
> Bacillus_thuringiensis_HD_789_uid173860
> Bacillus_thuringiensis_MC28_uid176369
> Bacillus_thuringiensis_YBT_1518_uid229419
> Bacillus_thuringiensis_serovar_IS5056_uid190186
> Bacillus_thuringiensis_serovar_chinensis_CT_43_uid158151
> Bacillus_thuringiensis_serovar_finitimus_YBT_020_uid158875
> Bacillus_thuringiensis_serovar_konkukian_97_27_uid58089
> Bacillus_thuringiensis_serovar_kurstaki_HD73_uid189188
> Bacillus_toyonensis_BCT_7112_uid227218
> Bacillus_weihenstephanensis_KBAB4_uid58315
> Bacteriovorax_marinus_SJ_uid82341
> Bacteroides_CF50_uid222805
> Bacteroides_fragilis_638R_uid84217
> Bacteroides_fragilis_NCTC_9343_uid57639
> Bacteroides_fragilis_YCH46_uid58195
> Bacteroides_helcogenes_P_36_108_uid62135
> Bacteroides_salanitronis_DSM_18170_uid63269
> Bacteroides_thetaiotaomicron_VPI_5482_uid62913
> Bacteroides_uniformis_uid13130
> Bacteroides_vulgatus_ATCC_8482_uid58253
> Bacteroides_xylanisolvens_XB1A_uid197168
> Bartonella_australis_Aust_NH1_uid189950
> Bartonella_bacilliformis_KC583_uid58533
> Bartonella_clarridgeiae_73_uid62131
> Bartonella_grahamii_as4aup_uid59405
> Bartonella_henselae_Houston_1_uid57745
> Bartonella_quintana_RM_11_uid174512
> Bartonella_quintana_Toulouse_uid57635
> Bartonella_tribocorum_CIP_105476_uid59129
> Bartonella_vinsonii_berkhoffii_Winnie_uid189951
> Baumannia_cicadellinicola_Hc__Homalodisca_coagulata__uid58111
> Bdellovibrio_bacteriovorus_HD100_uid61595
> Bdellovibrio_bacteriovorus_Tiberius_uid182482
> Bdellovibrio_exovorus_JSS_uid194119
> Beijerinckia_indica_ATCC_9039_uid59057
> Belliella_baltica_DSM_15883_uid168182
> Beutenbergia_cavernae_DSM_12333_uid59047
> Bibersteinia_trehalosi_192_uid193709
> Bifidobacterium_adolescentis_ATCC_15703_uid58559
> Bifidobacterium_animalis_ATCC_25527_uid162513
> Bifidobacterium_animalis_lactis_AD011_uid58911
> Bifidobacterium_animalis_lactis_ATCC_27673_uid222803
> Bifidobacterium_animalis_lactis_B420_uid163691
> Bifidobacterium_animalis_lactis_BB_12_uid158871
> Bifidobacterium_animalis_lactis_BLC1_uid158867
> Bifidobacterium_animalis_lactis_Bi_07_uid163693
> Bifidobacterium_animalis_lactis_Bl12_uid210081
> Bifidobacterium_animalis_lactis_Bl_04_uid59359
> Bifidobacterium_animalis_lactis_CNCM_I_2494_uid158869
> Bifidobacterium_animalis_lactis_DSM_10140_uid59357
> Bifidobacterium_animalis_lactis_V9_uid158865
> Bifidobacterium_asteroides_PRL2011_uid176921
> Bifidobacterium_bifidum_BGN4_uid167988
> Bifidobacterium_bifidum_PRL2010_uid59883
> Bifidobacterium_bifidum_S17_uid59545
> Bifidobacterium_breve_ACS_071_V_Sch8b_uid158863
> Bifidobacterium_breve_UCC2003_uid193702
> Bifidobacterium_dentium_Bd1_uid43091
> Bifidobacterium_longum_BBMN68_uid60163
> Bifidobacterium_longum_DJO10A_uid58833
> Bifidobacterium_longum_F8_uid197184
> Bifidobacterium_longum_JCM_1217_uid62695
> Bifidobacterium_longum_JDM301_uid49131
> Bifidobacterium_longum_KACC_91563_uid158861
> Bifidobacterium_longum_NCC2705_uid57939
> Bifidobacterium_longum_infantis_157F_uid62693
> Bifidobacterium_longum_infantis_ATCC_15697_uid159865
> Bifidobacterium_longum_infantis_ATCC_15697_uid58677
> Bifidobacterium_thermophilum_RBL67_uid193770
> Blastococcus_saxobsidens_DD2_uid89391
> Blattabacterium__Blaberus_giganteus__uid165873
> Blattabacterium__Blatta_orientalis__Tarazona_uid188115
> Blattabacterium__Blattella_germanica__Bge_uid41533
> Blattabacterium__Cryptocercus_punctulatus__Cpu_uid81083
> Blattabacterium__Mastotermes_darwiniensis__MADAR_uid77127
> Blattabacterium__Nauphoeta_cinerea__uid222815
> Blattabacterium__Panesthia_angustipennis_spadica__BPAA_uid193717
> Blattabacterium__Periplaneta_americana__BPLAN_uid41287
> Bordetella_avium_197N_uid61563
> Bordetella_bronchiseptica_253_uid178913
> Bordetella_bronchiseptica_MO149_uid177517
> Bordetella_bronchiseptica_RB50_uid57613
> Bordetella_parapertussis_12822_uid57615
> Bordetella_parapertussis_18323_uid175569
> Bordetella_parapertussis_Bpp5_uid177516
> Bordetella_pertussis_CS_uid158859
> Bordetella_pertussis_Tohama_I_uid57617
> Bordetella_petrii_uid61631
> Borrelia_afzelii_HLJ01_uid177930
> Borrelia_afzelii_PKo_uid159867
> Borrelia_afzelii_PKo_uid58653
> Borrelia_bissettii_DN127_uid71231
> Borrelia_burgdorferi_B31_uid57581
> Borrelia_burgdorferi_CA382_uid214794
> Borrelia_burgdorferi_JD1_uid161197
> Borrelia_burgdorferi_N40_uid161241
> Borrelia_burgdorferi_ZS7_uid59429
> Borrelia_crocidurae_Achema_uid162335
> Borrelia_duttonii_Ly_uid58791
> Borrelia_garinii_BgVir_uid162165
> Borrelia_garinii_NMJW1_uid177081
> Borrelia_garinii_PBi_uid58125
> Borrelia_hermsii_DAH_uid59225
> Borrelia_miyamotoi_LB_2001_uid215233
> Borrelia_recurrentis_A1_uid58793
> bacterium_BT_1_uid184079
> beta_proteobacterium_CB_uid191340

**Comment by jennaj** [comment]
Update: Open - tool update request for http://usegalaxy.org

**Comment by jennaj** [comment]
Version 4.3k.0 has been installed on Main.

The new tool version is still extracting the wrong database. See the last job in this test history for an example: https://usegalaxy.org/u/jen/h/snpeff-database-download-test-history

Some genomes that are listed as available fail to download. See the "history annotation" field for details about those jobs/dataset #'s.

**Comment by jennaj** [comment]
There was some discussion in Gitter recently about this but could someone give an update about status for the fix? The tools are live on public servers (including https://usegalaxy.org) and users continue to report the problem and are confused about what to do as a workaround. I don't know of one except to natively install the tool and target index in a local/docker/cloud Galaxy - and without a DM - which greatly limits who will be able to do it (is complex). Thanks! Jen

**Comment by jennaj** [comment]
Is this related? https://github.com/galaxyproject/tools-iuc/pull/1529

**Comment by colindaven** [comment]
Hi, sorry to hijack your issue but I have snpeff download issues related to the https proxy. We can hack the config manually and it works, but we don't know where to set the JAVA_OPTIONS (or _ JAVA_OPTIONS?) environment variable (doing it in .bashrc does not get read/kept on the local system).

In other words, we never get this "Picked up _JAVA_OPTIONS ..."

Any ideas ?

**Comment by natefoo** [comment]
You can set `$_JAVA_OPTIONS` in `job_conf.xml`, using an `<env>` tag on a `<destination>`:

https://github.com/galaxyproject/galaxy/blob/b2cc634e8a2eea74adf96ee7a4ee6c29d37b00f3/config/job_conf.xml.sample_advanced#L511

**Comment by jennaj** [comment]
@natefoo @davebx @martenson 

The tool for extracting dbs is still broken on Main.

There is a new version of all three snpeff tools: `4.3r.1`. Could we put those on Test to see if the database extraction function works on our servers? Then can promote to Main. Or could just update Main. Test is currently at `4.1.0`, Main is at `4.3k.0`. 

https://galaxy.uni-freiburg.de already has the `4.3r.1` update. I'll test the functionality there too.

https://toolshed.g2.bx.psu.edu/view/iuc/snpeff/68693743661e

**Comment by CareyLambert** [comment]
I've tried the https://galaxy.uni-freiburg.de  server, but this still has the same problem (requesting Bdellovibrio_bacteriovorus_hd100 pulls up Basilea_psittacipulmonis_dsm_24701).

**Comment by jennaj** [comment]
Hi - to clarify, Carey tested 4.3r.1 at https://galaxy.uni-freiburg.de (where it is installed on a public server, main doesn't have that version yet).

This seems important. The tool is mostly non-functional unless uses can get more builds. Thinking it should be fixed or not on the public sites. Thoughts?

**Comment by bgruening** [comment]
@jennaj sorry don't get the last comments. Is there anything uni-freiburg needs to do?

**Comment by natefoo** [comment]
@jennaj snpEff has been updated on Test by @davebx.

**Comment by jennaj** [comment]
@bgruening @natefoo The user reported the same issue still being present in the latest version (4.3r.1) installed at freiburg. I didn't test it there myself. I'll test there and at https://test.galaxyproject.org/. More soon.

**Comment by jennaj** [comment]
Doesn't work at test: https://test.galaxyproject.org/u/jenjackson/h/snpeff-database-download-test-history-for-43r1-updated-tools

**Comment by jennaj** [comment]
This might help, my original notes in the history annotation (using the prior version) at usegalaxy.org. The same issue seems persistant with 4.3r.1. In short, the nested databases are not being retrieved correctly. I also see multiple versions - my guess is that the tool should know how to retrieve the most current.

https://usegalaxy.org/u/jen/h/snpeff-database-download-test-history

> https://github.com/galaxyproject/tools-iuc/issues/1354
> 
> new runs are with v 4.3k.0 to see if working and if fix prior issue
> 
> d156: failed to download a database listed in the "available databases" from d153. The select in d160 is a double check that the database name was correct.
> 
> Some databases do download - nesting may be the issue (these are nested at the source)
> 
> d158 & d159 are nested databases, jobs didn't fail, but tool extracted the wrong database (top level extracted instead)

**Comment by jennaj** [comment]
v 4.0.0 reportedly works correctly. I'll be testing and will update this ticket with that as a workaround if can reproduce. Tracked here: https://github.com/galaxyproject/usegalaxy-playbook/issues/94

**Comment by CareyLambert** [comment]
Thanks again for your efforts with this. I’m afraid I can’t quite follow the github thread as it’s a bit technical for me, but I saw it was closed so tested again. The name of the genome in snpeff available databases seems to have changed to Bdellovibrio_bacteriovorus_HD100_uid61595, so I tried to fetch this and got this error:
Fatal error: Exit code 255 (Error) Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/018/581/18581553/_job_tmp -Xmx7g -Xms256m 00:00:00 SnpEff version SnpEff 4.1l (build 2015-10-03), by Pablo Cingolani 00:00:00 Command: 'download' 00:00

Apologies if this is something you’re still working on, just thought I’d highlight it in case it helps.

Best Wishes,
Carey

**Comment by jennaj** [comment]
@CareyLambert 

Older versions of the tool might have problems - could you send this error in as a bug report so we can check usage versus the tool functionality? Please include a link to this Github post for reference in the comments. How-to: https://galaxyproject.org/issues/

Also, have you run this with version 4.0.0 yet? That is the reported version that should work correctly. I still need to test that myself. Please leave your test in the reported bug history if you decide to send one in.

Thanks!

**Comment by jennaj** [comment]
@CareyLambert It is okay, no need to send in a bug report, I could reproduce this immediately with both of the older versions of the tool. This needs to be corrected on the server. A ticket with details is here: https://github.com/galaxyproject/usegalaxy-playbook/issues/98

One 4.0.0 is not erroring again, we can test the functionality to see if it pulls the correct database or not

**Comment by jennaj** [comment]
A new version of SnpEff tools is in progress. Looks like it will address this problem. Test once on Main: https://github.com/galaxyproject/tools-iuc/pull/1787

**Comment by CareyLambert** [comment]
Hi,
I've tried with the new version of snpEff download and the original problem persists. I'm trying to get the Bdellovibrio bacteriovorus database, but it STILL chooses the first in the package. In this case it's: Berkelbacteria_bacterium_gw2011_gwa2_35_9
SnpEff4.3
This problem has persisted for well over a year now.
Best,
Carey

**Comment by jennaj** [comment]
Confirmed, **the updated tool still does not choose the correct database**.

**Workaround:** Use the tool SnpEff build: database from Genbank record instead. 

----

**Test history:** https://usegalaxy.org/u/jen/h/snpeff-database-download-test-history

**Dataset 169**

**Requested:** Bdellovibrio_bacteriovorus_str_tiberius

**Retrieved:** Berkelbacteria_bacterium_gw2011_gwa2_35_9

<img width="250" alt="screen shot 2018-06-18 at 12 49 14 pm" src="https://user-images.githubusercontent.com/8999735/41559419-d916a09c-72f8-11e8-80ec-9daa9d1fc8cf.png">


The issue is related to how nested genomes differ in the file structure in source data. The "first" genome in any "nested data" (that contains the target genome) is retrieved, not the actual target genome. This is a tool problem, it is not usable for these genomes. If nested genomes are not retrievable, then we should note that in the "Available databases" tool output and this tool should fail with "genome not available".

**SnpEff eff: annotate variants (Galaxy Version 4.3+T.galaxy1)** is also impacted when the option _Genome source > Download on Demand_ is used. Errors like this when it cannot find the database (even when it is in the source and listed as "available"). Maybe provides more clues about what is wrong.

**_stderr_**

```
Fatal error: Exit code 255 (Error)
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/019/838/19838472/_job_tmp -Xmx7g -Xms256m
java.lang.RuntimeException: Property: 'Bdellovibrio_bacteriovorus_HD100_uid61595.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:106)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:681)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:649)
	at org.snpeff.snpEffect.Config.init(Config.java:480)
	at org.snpeff.snpEffect.Config.<init>(Config.java:117)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:451)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1000)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)
```

ping @nekrut

**Comment by jennaj** [comment]
Workaround may be the solution. Close this out?

Related: https://github.com/galaxyproject/tools-iuc/pull/1787

**Comment by CareyLambert** [comment]
Hi,
I'm afraid the workaround of using snpEff build did not work for me either. I tried with several different strains of Bdellovibrio and different genbank files for each. Have sent the bug reports.
Carey

**Comment by hepcat72** [comment]
If the correction of the assignment of the genome version metadata for the requested genome is the only this this issue is about, then the PR referenced above fixes this.  If the OP wanted all the included genomes accessible by snpeff eff, then the PR doesn't do that.  It eliminates everything except the requested genome.

**Comment by jennaj** [comment]
Pulls the correct database now on Main. Closing this out.

Test history: https://usegalaxy.org/u/jen/h/snpeff-database-download-test-history

Dataset: 170

Tool/version: SnpEff download: download a pre-built database (Galaxy Version 4.3+T.galaxy2)

Requested: Bdellovibrio_bacteriovorus_str_tiberius

Retrieved: Bdellovibrio_bacteriovorus_str_tiberius

<img width="243" alt="screen shot 2018-12-17 at 3 15 58 pm" src="https://user-images.githubusercontent.com/8999735/50121800-cdf9ab00-020e-11e9-91ab-d3ab241e2198.png">
