### ISSUE TITLE
TravisCI: cache the conda package downloads?

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#1357]
As part of #1316 in https://github.com/galaxyproject/tools-iuc/commit/7cebe80cad8a9ac93cb4d8027d16dbb33e5a5fa7 @nsoranzo added this to our ``.travis.yml`` file:

```
cache: pip
```

Reading https://docs.travis-ci.com/user/caching/#Arbitrary-directories makes me wonder if we should also explicitly ask TravisCI to cache the directory used for downloading conda packages? Something like:

```
cache:
  - pip
  - $HOME/anaconda/pkgs
```

I assume we can get the actual path from ``conda info -a | grep cache`` but have not tried that yet.

**Comment by yhoogstrate** [comment]
Would it make sense to also do this for planemo (and Galaxy dependency)?

**Comment by bgruening** [comment]
@peterjc @yhoogstrate I would say, let's try it! :)

**Comment by peterjc** [comment]
Does anyone know the relevant paths to add?

**Comment by yhoogstrate** [comment]
This has been solved by @nsoranzo :+1: , hasn't it?

**Comment by nsoranzo** [comment]
@peterjc was suggesting to add more directories to cache, so I don't think that's been any change since this issue was open.

**Comment by abretaud** [comment]
As we moved to github actions I *think* as been improved, feel free to reopen
