### ISSUE TITLE
Bug with fastqsanger (gzipped)

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#1386]
Hi,

I do not know precisely where is this bug, so I will describe the problem and then speculate on the cause.

I have a tool (from tools-iuc/stacks - clonefilter) that outputs gzip fastsangers.
The history says the type is fastqsanger (not gz).
If I download the file, it will be compressed (gunzip uncompresses it fine).

So far, so good.

If I pass it to trimmomatic the tool chokes. It seems to be getting the input compressed.

So I suspect the Galaxy magic to transparently deal with compressed fastqs is not working: downstream analysis get the compressed file and nothing is made to uncompress it.

**Comment by nsoranzo** [comment]
What Galaxy version are you using? Compressed FASTQ formats and tools using them only work on 17.01 and later.

**Comment by tiagoantao** [comment]
That explains it. I am closing this.

**Comment by tiagoantao** [comment]
@nsoranzo I am reopening this as the problem still exists on 17.05: trimmomatic is reading a fastq.sanger.gz as binary

**Comment by mvdbeek** [comment]
Please tell us more. How are you uploading the file, what is the symptom etc. I have been using this for quite some time now without hickups. Make sure you're using trimmomatic 0.36.2 or newer.

**Comment by tiagoantao** [comment]
The file comes from a previous process based on stacks (clone_filter). On the figure below you can see both part of the failure and the original process.

The stacks based process outputs a gz fastqsanger that seems in great shape (you can see a bit there)
Trimmomatic is the latest version.

Thanks

![image](https://user-images.githubusercontent.com/34787/28842630-a318734c-76bb-11e7-8504-a55df565b53e.png)

**Comment by tiagoantao** [comment]
Sorry, one more thing, trimmomatic shows a bit of garbled input that seems like a still-compressed file

**Comment by mvdbeek** [comment]
It says `fastqsanger` on your dataset ... that can't be correct. It should be `fastqsanger.gz`

**Comment by tiagoantao** [comment]
I have the latest version of the tool, and it says `fastqsanger.gz` as the output::

https://github.com/galaxyproject/tools-iuc/blob/master/tools/stacks/stacks_clonefilter.xml#L90

Any possibility that this is being changed elsewhere?

**Comment by mvdbeek** [comment]
In the screenshot you posted above the green dataset was of format fastqsanger, without the .gz.
If you force a fastqsanger.gz file to be fastqsanger this will fail.
The datatype can be changed many different ways. I'd suggest uploading the [sample data that comes with trimmomatic](https://github.com/fls-bioinformatics-core/galaxy-tools/tree/master/tools/trimmomatic/test-data) to verify that if you have a proper fastqsanger.gz file everything works fine.

**Comment by tiagoantao** [comment]
So, I am using 17.05, which is an update from a 16.0X version database (not a clean install - production machine). There is no fastqsanger.gz in the available datatypes... I wonder if the database should be updated?

The tool generates fastqsanger.gz (see link above), There was no manual forcing on top of it: it simply appeared as fastqsanger

I then tried to force in the direction fastqsanger->fastqsanger.gz and the option was not even there.

My suspicion is something missing in the datatypes database...

**Comment by bgruening** [comment]
@tiagoantao have you followed these instructions: https://github.com/bgruening/docker-galaxy-stable#upgrading-images--toc - especially point 7? You have a file called datatypes_conf.xml which you need to update. In your case add the new datatypes that were added during the last 2 releases.

**Comment by tiagoantao** [comment]
@bgruening That was it. But a suggestion: change the wording on point 7:

_Use diff to find changes in the config files (only if you changed any config file)._

I think you should remove the parenthesis text, my interpretation was that I only needed to do it if I had changed a config file myself.

I am closing this one. Thanks both!
