### ISSUE TITLE
bedtools map  should support BEDGraph input type

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/tools-iuc#1399]
Hi,
According to `bedtools map` manual the bedgraph is natively supported by the tool. At least this is the case for the second file B. However the galaxy wrapper does not allow passing the `bedgraph` file without the implicit or explicit conversion to `bed` format.

http://bedtools.readthedocs.io/en/latest/content/tools/map.html

**Comment by bernt-matthias** [comment]
bedgraph is now accepted by bedtools: https://github.com/galaxyproject/tools-iuc/blob/fa19d3b6a9d0160a13f8d1e4a99f20c4dbe937b2/tools/bedtools/macros.xml#L10
