### ISSUE TITLE
package_bedtools_2_19 missing on GitHub

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#14]
File ``tools/bedtools/tool_dependencies.xml`` currently reads:

```
<?xml version="1.0"?>
<tool_dependency>
    <package name="bedtools" version="2.19.1">
        <repository name="package_bedtools_2_19" owner="iuc" />
    </package>
</tool_dependency>
```

However, this package in not currently in this repository.

**Comment by bgruening** [comment]
And here we go: https://github.com/galaxyproject/tools-iuc/pull/24
Hope this is ok for you all.
