### ISSUE TITLE
HISAT2 wrapper default min score doesn't match HISAT2 default

### ISSUE THREAD

**Issue by chambm** [galaxyproject/tools-iuc#1406]
I was getting lower alignment rates than expected for some not-so-great data, so after some investigation I found that the min score in the wrapper is set to `C,0,0` (constant function, i.e. score must be at least 0), whereas the command-line default is `C,-18,0` (score must be at least -18). It made a huge difference for this data. I'm not an expert HISAT2 user by any means, but this difference in defaults seems fishy. 

> -score-min <func>
Sets a function governing the minimum alignment score needed for an alignment to be considered "valid" (i.e. good enough to report). This is a function of read length. For instance, specifying L,0,-0.6 sets the minimum-score function f to f(x) = 0 + -0.6 * x, where x is the read length. See also: [setting function options]. The default is C,-18,0.

**Comment by nsoranzo** [comment]
@chambm Not sure where are you copying the help from, but both https://ccb.jhu.edu/software/hisat2/manual.shtml#performance-tuning and `hisat2 --help` (for v2.0.5) say: `The default is L,0,-0.2.`

**Comment by chambm** [comment]
Ah, I was reading the HISAT 1 manual: https://ccb.jhu.edu/software/hisat/manual.shtml
