### ISSUE TITLE
Enhancement: use a .loc file for genome files.

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/tools-iuc#1443]
I'm trying to modify the slopBed in order to be able to work with a genome file found in a .loc file.

It seems to work.

Do you think it could be possible to add this feature for all others tools which use a genome file ?

I can submit a PR with the slopBed example (macros.xml with a token and a conditional parameter and slopBed.xml modified accordingly)

**Comment by mvdbeek** [comment]
That would be great, yes!
