### ISSUE TITLE
Enhancement: add a tool to reorder columns based on values: start < end 

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/tools-iuc#1444]
I'm working from a tabular blast result file.
It's pretty easy to create a bed like file, using Galaxy (with the cut tool)
But (of course) I can't go futher (within Galaxy) because this bed like file is not well formed :
`Error: malformed BED entry at line 2. Start was greater than end. Exiting.`

On command line it's easy to deal with that and sort start < end line by line using awk.
But I would like to stay within Galaxy in order to create a workflow for a user.

Or is there an existing way to do that ?

thank you

**Comment by nsoranzo** [comment]
You can use the `awk` tool from https://toolshed.g2.bx.psu.edu/repository?repository_id=2593fd36ae8011aa (which also contains a `cut` tool which is different from the one included with Galaxy, not sure which one you are using).

**Comment by jj-umn** [comment]
You could use the query_tabular tool, which would load blast tabular file into a sqlite database.  
Then you could use the sqlite min() and max() functions in your sql query to get the start and end columns correct.

**Comment by FredericBGA** [comment]
@nsoranzo: thank you, I was using the one included with Galaxy and I missed the text_processing suite from  @bgruening. I will install and use it.
@jj-umn: thank you too. I will try also the query_tabular tool.

**Comment by FredericBGA** [comment]
@nsoranzo @jj-umn: works perfectly, thank you again.
