### ISSUE TITLE
Usage: Modify sam_dump.xml to avoid conflicting params that result in failures

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1445]
Tool: Download and Extract Reads in BAM format from NCBI SRA (Galaxy Version 2.8.1.2)

It is possible to choose BAM output and in the same job to also to choose _to not_ output a header. This always results in a failed job with an ambiguous failure message (invalid data format is the root cause).

The suggestion is to do one of these or another alternative that meets the same goal (prevent this use-case from being submitted as a valid job).

 1 - modify the way the tool form is modeled (only have header option available when SAM is chosen? on main form or in advanced section) 

 2 - or to have the job abort with a pop-up stating the parameter conflict ("Sam output must with used with the option to not include a header" or similar). 

The first seems better but either would be enough and someone else may have a preferred solution?

While this is changed, it would also be nice if rerun for the tool left the advanced parameter section expanded when the original job had the advanced parameters changed from default - or - had the advanced section expanded at the time of the original job's submission (the usual method). For this tool/version, the advanced parameter section does not remain expanded at rerun. This is different than most other tool's usage during a rerun and in effect "hides" advanced setting changes that may have been made.

Graphic of parameters: 

<img width="763" alt="screen shot 2017-08-22 at 7 58 58 pm" src="https://user-images.githubusercontent.com/8999735/29597128-79f48f62-8775-11e7-8e9c-be3502dbdda1.png">

**Comment by mvdbeek** [comment]
Yeah, galaxy doesn't do well without headers, so we should always ask for the headers if choosing bam (and probably also when using sam).

Keeping the parameters expanded will happen with the galaxy 17.09 release.

**Comment by jennaj** [comment]
Agree @mvdbeek  - BAM/SAM both could have headers as a default. Can always be removed later as needed. I definitely agree that leaving these headers intact is better for the vast majority of use cases/tools.

So .. to keep it simple we propose to strip out the header toggle from advanced options. This means that SAM and BAM data would always have headers. **Is everyone OK with that? Any downsides?**

**Comment by bgruening** [comment]
@jennaj please have a look at https://github.com/galaxyproject/tools-iuc/pull/1565
