### ISSUE TITLE
Broken tool: bedtools_map

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/tools-iuc#1447]
tested on usegalaxy.org.

when you want to give a genome file (option -g : Treat split/spliced BAM or BED12 entries as distinct BED intervals when computing coverage.) it fails:

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 864, in prepare
>     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 454, in build
>     raise e
> NotFound: cannot find 'genome_choose' while searching for 'genome.genome_choose'

**Comment by FredericBGA** [comment]
I think that the good label for this option should be:

> Specify a genome file the defines the expected chromosome order in the input files.
[http://bedtools.readthedocs.io/en/latest/content/tools/map.html](url)

**Comment by bgruening** [comment]
This https://github.com/galaxyproject/tools-iuc/pull/1448 might solve the issue. However, I do not get why this passed our tests.

**Comment by nsoranzo** [comment]
Because the error appears only when the `genome_choose` is `Yes` (`-g`) and the expand conditional has a param named `genome` which conflicts with the parent conditional element of the same name. And we don't have a test for that.

**Comment by bernt-matthias** [comment]
Did https://github.com/galaxyproject/tools-iuc/pull/1448 solve the issue?

**Comment by FredericBGA** [comment]
#1448 was superseded by #1446.
so it seems that this issue can be close.

**Comment by bernt-matthias** [comment]
Thanks for the info
