### ISSUE TITLE
Incoming tool wrappers for pRESTO

### ISSUE THREAD

**Issue by tfenne** [galaxyproject/tools-iuc#1454]
Hi iuc team!  I'm creating this issue pursuant to the IUC Best Practices for Tool Creation to inform you that I'm working on a set of `tool.xml`s for the tools contained within the [pRESTO](https://presto.readthedocs.io/) toolkit for analyzing immune repertoire sequencing experiments.

I'm working in collaboration with @bwlang, and have an in progress branch - diff vs. tools-iuc master [here](https://github.com/galaxyproject/tools-iuc/compare/master...tfenne:tf_presto_tools).

I still have a little more work to do, mostly wrapping one or two more tools and then manually inspecting the tool interfaces to make sure the params and help look good.  Once that's done I'll open a PR here and request a review.  If there's anything else I can do to help make this process easier/smoother please just let me know.  Cheers!

**Comment by shiltemann** [comment]
Sounds great @tfenne! looking forward to the PR :) ..if you have any questions feel free to ask, and you are also welcome to open a WIP PR here if you would like some input from us as you go, great work!

**Comment by tfenne** [comment]
Thanks @shiltemann!  I do have on question.  I read that, after merge, tools are automatically published to the test and main toolsheds.  Will it screw anything up if I independently use planemo to publish to the test toolshed?  I'd like to make the tools easily available to a couple of collaborators to help test them before generating a PR.

**Comment by bgruening** [comment]
I just looked briefly over the diff and this already looks great. A few tips which might already help.

* try to use `argument="--maxerror"` https://docs.galaxyproject.org/en/master/dev/schema.html#common-attributes
* you can use `from_work_dir` instead of your `mv` commands: https://docs.galaxyproject.org/en/master/dev/schema.html#id53
* better help sections can be easily written with http://rst.ninjs.org/
* you can macrofy the version for example
* all the `Copy/pasted values from align` could be macrofied I think

**Comment by bgruening** [comment]
@tfenne you can use the TTS as you like you will not screw something up :)

**Comment by tfenne** [comment]
Thanks @bgruening!  I'm new to a lot of this (galaxy, tool.xml wrappers, cheetah, rst).  I appreciate the feedback and should be able to fix most of those things pretty quickly.  One question I can't find an answer to online, does `from_work_dir` support any kind of dynamic eval/globbing?  In most cases I know the output filename ahead of time but in at least one case the name includes a dynamic component - it actually embeds an input parameter.

**Comment by bgruening** [comment]
No globing I'm aware of, in this case the `mv` is good enough.

**Comment by bgruening** [comment]
migmap was merged and should be in the TS soon.

**Comment by bernt-matthias** [comment]
this seems to be finished
