### ISSUE TITLE
bcftools_mpileup vs. bcftools_call

### ISSUE THREAD

**Issue by chambm** [galaxyproject/tools-iuc#1456]
What is the difference between these two? Both were updated fairly recently.

Also, should I expect these to reproduce the results from samtools' mpileup?

**Comment by jj-umn** [comment]
@chambm Sorry I didn't see this before.   mpileup was moved from samtools to bcftools for bcftools 1.4   The general workflow is bcftools_mpileup (compressed bcf) -> bcftools call (Best to only output the variants from here)
