### ISSUE TITLE
SPADES FASTG

### ISSUE THREAD

**Issue by mglgnn** [galaxyproject/tools-iuc#1458]
do you think it will be feasible to add the possibility for downloading FASTG file which is produced by SPADES (already included within Galaxy Tool shed) in addition to FASTA for both contigs and scaffolds? 

FASTG would be very useful for further analysis with application such as BANDAGE in order to evaluate the final De Bruijn graph of the assembly.

**Comment by bgruening** [comment]
@mglgnn do you mean that Spades puts the FASTG file into the Galaxy history?

**Comment by mglgnn** [comment]
Exactly, I'd like to have chance to download FASTG to get information to build the graph underlying SPADES assembly both for contigs and scaffolds.
I think it can be useful for anyone eager to investigate the assembly in greater depth.
Thanks

**Comment by bgruening** [comment]
@mglgnn do you want to work on this. We can help you! Or should we try to get this done?

**Comment by mglgnn** [comment]
Indeed, I'll find it useful to have it done. I thought the inclusion of the fastg routinely created by SPADES would be an easy task to accomplish for you (this is the reason I asked). If either it is not the case or you prefer to encourage users in taking active part into GALAXY, of course I'd be glad to give some contribute and work on this topic but currently I'm more concerned with building a good assembly in Spades as a simple user...anyway we can exchange some information if you like and try to collaborate...

**Comment by Slugger70** [comment]
Added to new spades 3.11.1 wrapper.

**Comment by Slugger70** [comment]
@mglgnn can you close this issue please?
