### ISSUE TITLE
package_samtools_1_2 should include tabix and bgzip

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-iuc#146]
According to http://www.htslib.org/download/ , the bgzip, htsfile, and tabix utilities are now provided by HTSlib, but they can also be installed from a samtools or bcftools source package.

These are the command needed:

```sh
cd htslib-*
make bgzip tabix
cp -f bgzip tabix $INSTALL_DIR/bin
```

Then `package_tabix_0_2_6` can be deprecated and substituted by `package_samtools_1_2` where needed.

**Comment by lparsons** [comment]
Any chance of getting this pushed out to the toolshed soon? I'd very much like to address galaxyproject/tools-devteam#111 but that is waiting on this.

**Comment by erasche** [comment]
@lparsons the blocking issue there was that we don't have a docker-build version of samtools 1.2 and no one has invested the time in that. 

https://github.com/galaxyproject/tools-iuc/pull/155
