### ISSUE TITLE
mothur: output

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1472]
The mothur tools output the actual output and the log. 

1. The preview of the actual data set shows the content of the log. 
2. Is it possible to include the log file only if it contains any useful information? Or make it optional? 

The output currently looks like this. 

```
[H[J





mothur v.1.36.1
Last updated: 7/27/2015

by
Patrick D. Schloss

Department of Microbiology & Immunology
University of Michigan
pschloss@umich.edu
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

Type 'quit()' to exit program



mothur > make.group(fasta=fasta_0.dat-fasta_1.dat,groups=pampa-anguil)

Output File Names: fasta_0.fasta_1.groups


mothur > quit
```

**Comment by bernt-matthias** [comment]
I just discovered that mothur has a -q or --quiet command line switch. As long as important messages are still printed this seems to be a good idea.

**Comment by shiltemann** [comment]
I included the log file as output because some of my users who were used to using mothur in interactive mode still really wanted to see this output for a lot of the commands, but if you feel it clutters the history too much I could add a checkbox to indicate whether you want this output or not, sure :)

**Comment by bernt-matthias** [comment]
Indeed log output can be important. Its a good idea to keep it if it contains useful information. Maybe for the next version of the wrappers one can incorporate the --quite parameter and add the log files only if it contains anything..?

**Comment by bernt-matthias** [comment]
Another idea for the next version that might help galaxy users to get informations on the tools.  For the documentation calls like `cluster.split(citation)` could extract the original citations automatically.

**Comment by shiltemann** [comment]
ah, thanks for the tip :+1:

**Comment by bernt-matthias** [comment]
Another tip: cluster.split(help) outputs help.

**Comment by bgruening** [comment]
Hopefully fixed with: https://github.com/galaxyproject/tools-iuc/pull/1722
