### ISSUE TITLE
bedtools mapBed.xml tool is invalid

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-iuc#148]
After latest push to the MTS, https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/457b09031d57 reports that mapBed.xml is invalid:

`This file requires an entry for "'input'" in the tool_data_table_conf.xml file. Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error.`

which does not make much sense for me.

**Comment by nsoranzo** [comment]
Unfortunately PR #150 fixed mapBed.xml , but broke mergeBed.xml . From https://testtoolshed.g2.bx.psu.edu/repository?repository_id=7f940896abcf000c&changeset_revision=bdb4509d9482 :

`This file requires an entry for "'inputA'" in the tool_data_table_conf.xml file. Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error.`

**Comment by bgruening** [comment]
True, thanks for reporting. It seems that neither `planemo l` and `planemo t` catches these kind of errors.

**Comment by bgruening** [comment]
@nsoranzo next try #148
I have removed the macro and using yield now to manually adopt for the correct input value.

**Comment by nsoranzo** [comment]
@bgruening The commit LGTM, can you open a PR?

**Comment by bgruening** [comment]
@nsoranzo https://github.com/galaxyproject/tools-iuc/pull/161 Thanks for reviewing!

**Comment by nsoranzo** [comment]
Fixed by #161 and uploaded to the MTS.
