### ISSUE TITLE
Publish current version of bwameth_index_builder.py repo to MTS

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1482]
There was a typo bug in line 27 of the .py file that is correct here in GitHub but has not been pushed out to the MTS repo. Users have noticed: https://biostar.usegalaxy.org/p/24918/

Could we update the MTS (even if the tool is not conda yet)?

GitHub: https://github.com/galaxyproject/tools-iuc/blob/master/data_managers/data_manager_bwameth_index_builder/data_manager/bwameth_index_builder.py

MTS (compare to repo tip file .py): https://toolshed.g2.bx.psu.edu/view/iuc/data_manager_bwameth_index_builder/82a21d695a6b

**Comment by nsoranzo** [comment]
Thanks @jennaj for reporting, I've updated `data_manager_bwameth_index_builder` on the MTS.

**Comment by jennaj** [comment]
catching up a bit - thank you @nsoranzo. I haven't tested this but assume you have :)
