### ISSUE TITLE
DESeq2 normalized counts have bad column labels

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/tools-iuc#1484]
Someone in our local training course just noticed that the column labels in the normalized counts files have group labels, rather than sample labels. So you end up with labels like: `1: group 1`, `2: group 1`, `3: group 2`, etc. Given that people have a hard time tracking the exact order of samples within each group when the labels are removed, this should probably be changed. The relevant code [is here](https://github.com/galaxyproject/tools-iuc/blob/master/tools/deseq2/deseq2.R#L301). My preference would be to use the display name from the history item (possibly prepended with a number, as is currently done by the code to ensure things are unique).

**Comment by mvdbeek** [comment]
Yes, that's a good idea. It would be good if we can only prefix number if some of the names are not unique (collection element can't have the same name afaik).

**Comment by lparsons** [comment]
This is exactly the issue we were discussing on Gitter. Is this addressed at all in #1465?
