### ISSUE TITLE
hisat2 does not work

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1492]
When running hisat2 I get the following error 

```
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 630, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/galaxy-central/lib/galaxy/jobs/__init__.py", line 1266, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/galaxy-central/lib/galaxy/datatypes/binary.py", line 391, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

The error message of the tool is `Unable to finish job`. 

I have tested this on the RNAworkbench of @bgruening (using the default version and the most current) and a local installation of the dev branch.

**Comment by mvdbeek** [comment]
You need to have samtools installed -- either on a global path or for the metadata tool (can be done in the admin menu -- manage installed tool dependencies).

**Comment by bernt-matthias** [comment]
Thanks a lot. Shouldn't such dependencies resolved automagically?

**Comment by peterjc** [comment]
In this context, samtools is a dependency of Galaxy itself rather than a user-invoked tool. 

Cross reference https://github.com/galaxyproject/galaxy/issues/861

**Comment by bernt-matthias** [comment]
Thanks for the info. Should we close the issue (since I have a "workaround")?

**Comment by nsoranzo** [comment]
Yes, that's not an issue of this repository anyway.

**Comment by mvdbeek** [comment]
FYI the need for samtools will go away once we get a new pysam release (should be ready for 18.01)

**Comment by bgruening** [comment]
And the master branch of the galaxy docker image has samtools installed. This was added after the release.
