### ISSUE TITLE
Google Summer of Code 2015

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/tools-iuc#15]
Should we try to get some coders to work on tool or workflow integration projects? Is that realistic and if so what is involved? If it is feasible lets collect some ideas here.

Do people have wishlists with interesting projects or would they be willing to mentor? I could outline some stuff for proteomics building on work by @bgruening and the Galaxy-P project.

http://www.google-melange.com/gsoc/homepage/google/gsoc2015

**Comment by jmchilton** [comment]
So I think the tentative plan is to actually submit a proposal to be a mentoring organization. (Is this crazy?) The application FAQ says (like @saketkc mentioned) one of the most important points is to have a strong wiki presence with a good list of project ideas. I have started an [ideas page](https://wiki.galaxyproject.org/Develop/GSOC/2015Ideas) on the wiki and outlined some of the ideas we discussed at the tool meeting before the break. Please contribute to that page if you have the chance - I would love to see lots of ideas, lots of volunteers, etc... it would be great for the community.
 
https://wiki.galaxyproject.org/Develop/GSOC/2015Ideas
https://wiki.galaxyproject.org/Develop/GSOC/2015

Thanks all for the feedback - keep it coming.

**Comment by nitesh1989** [comment]
@jmchilton Found the page. Should I be elaborating on the proposal ? It is already very well written. (Talking about the bio conductor proposal).

**Comment by jmchilton** [comment]
@nitesh1989 Thanks, I just sort of transcribed my understanding of what we discussed down without understanding much about how Bioconductor works or R documentation, etc.... If you have other ideas you would want to see worked on or would want to mentor - please add them - same  goes for everyone else :).

**Comment by jj-umn** [comment]
SQLite Visualization plugin.  
Allows one to submit queries on any sqlite dataset and view the table of results.  
Bonus points if the resulting table could be visualized within the charts visualization.

**Comment by erasche** [comment]
@jj-umn I suppose @bgruening's and my answer would be "Why, use IPython of course!" but there definitely should be something standalone, that would be really neat. Might mention [RedQueryBuilder](http://redquerybuilder.appspot.com/) in the GSOC project description

**Comment by erasche** [comment]
Closing as applications are closed.

- https://wiki.galaxyproject.org/Develop/GSOC/2015Ideas
