### ISSUE TITLE
macs2 should be able to take many treatment files and a single control file. 

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-iuc#1501]
Hello, 
I've been working on this issue with @mvdbeek|:

The macs2 callpeak tool in this repo works in two scenarios: when you have 1 treatment file and 1 control file, or when you have a collection of treatment files and control files of the same length. Both these use cases make sense for ChIPseq data (which is what macs was originally developed for) but for ATACseq, which many use macs for as well, it is common to use a single control file for many treatment files. 

When I put this in my workflow editor: 

<img width="539" alt="screen shot 2017-10-02 at 1 14 32 pm" src="https://user-images.githubusercontent.com/2761597/31089887-b4efa7d2-a773-11e7-9d7a-55d5aaed175b.png">

Macs outputs a single file: peaks using the first treatment file in the collection and the control file -- none of the other treatment files is used, they're all ignored. 

Visually, if I have dataset collection [a, b, c, d, e, f, g] and control file [H], I get the results of callpeak(a, H) and nothing else. I'd like to be instead getting [callpeak(a, H), callpeak(b, H), callpeak(c, H), callpeak(d, H), ...] in a collection. 

Can we change the macs tool to operate this way?

**Comment by jmchilton** [comment]
Is this a modified version of [this tool](https://github.com/galaxyproject/tools-iuc/blob/master/tools/macs2/macs2_callpeak.xml) - like did you make "treatment" non-multiple?

**Comment by zfrenchee** [comment]
@jmchilton I'm using exactly that tool you linked. 

@mvdbeek says that by changing both the inputs to be non-multiple (and then changing the command slightly to account for that) he gets the right results. I'm trying that right now to see if I get the same. 

Assuming that fixes the issue, I'd be interested in seeing if we can add in all the possible behaviors for macs into one tool: 
1. single treatment/control files
2. equal length treatment/control collections
3. treatment collection/single control

**Comment by zfrenchee** [comment]
**Update**: that did indeed solve my problem. I'd love to see this fixed in this repo as well.

**Comment by mvdbeek** [comment]
> Visually, if I have dataset collection [a, b, c, d, e, f, g] and control file [H], I get the results of callpeak(a, H) and nothing else.

That is not exactly right, a,b,c,d,e,f,g will be treated as replicates, and the first item here determines the output name. Making the tool inputs conditionally non-multiple makes sense at the moment, but Ideally it would be better if it was easier to create nested dataset collections. In this case you would make your deepest nesting level the replicates, so that the level (from flat to deep) are Sample/Replicate, where each is one collection. That should work for the tool as it is now.

**Comment by zfrenchee** [comment]
@mvdbeek Hmm, however, I'm not even sure I have replicates in my collection. Does it not make sense for me to have `[callpeak(a, H), callpeak(b, H), callpeak(c, H), callpeak(d, H), ...]` in a collection?

**Comment by mvdbeek** [comment]
That's the nice thing, it doesn't matter, you're nesting levels just need to match. If you have no replicates you just have one item at the deepest level.

**Comment by zfrenchee** [comment]
I think I see what you're suggesting. That's a little tricky though, but I guess it seems reasonable. So what I need to do instead is nest my collections?

**Comment by mvdbeek** [comment]
Right, but the UI doesn't let you do that easily at the moment, so I think we need to make the selection of `multiple=true` or not a conditional.

**Comment by zfrenchee** [comment]
What is the use case for Macs for `multiple=True`

**Comment by zfrenchee** [comment]
I believe this was solved by @mblue9
