### ISSUE TITLE
Count.seqs error

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/tools-iuc#1505]
HI,

The Large parameter have been remove from the Count.seqs mothur tools. Please remove it

mothur > count.seqs(name=name.dat,group=grouping.group.dat,large=false)
large is not a valid parameter.
The valid parameters are: shared, name, group, processors, groups, seed, inputdir, and outputdir.

**Comment by shiltemann** [comment]
Hi @bvalot, thanks for reporting the issue :)

Could you double-check your version of mothur for me? when I do `count.seqs(help)` in mothur 1.36.1 (the version the current wrappers are written for) I get the `large` parameter listed as a valid parameter:

```
mothur v.1.36.1

[..]

mothur > count.seqs(help)
The count.seqs aka. make.table command reads a name or shared file and outputs a .count_table file.  You may also provide a group with the names file to get the counts broken down by group.
The groups parameter allows you to indicate which groups you want to include in the counts, by default all groups in your groupfile are used.
The large parameter indicates the name and group files are too large to fit in RAM.
When you use the groups parameter and a sequence does not represent any sequences from the groups you specify it is not included in the .count.summary file.
The processors parameter allows you to specify the number of processors to use. The default is 1.
The count.seqs command should be in the following format: count.seqs(name=yourNameFile).
Example count.seqs(name=amazon.names) or make.table(name=amazon.names).
Note: No spaces between parameter labels (i.e. name), '=' and parameters (i.e.yourNameFile).
```

**Comment by bvalot** [comment]
Hi,

The version that is used in my PC:
mothur v.1.38.1
Last updated: 8/9/2016

From the wiki, they remove the large parameter in 1.38 version.

```
mothur > count.seqs(help)                                                                                                                                                                                                              
The count.seqs aka. make.table command reads a name or shared file and outputs a .count_table file.  You may also provide a group with the names file to get the counts broken down by group.
The groups parameter allows you to indicate which groups you want to include in the counts, by default all groups in your groupfile are used.
When you use the groups parameter and a sequence does not represent any sequences from the groups you specify it is not included in the .count.summary file.
The processors parameter allows you to specify the number of processors to use. The default is 1.
The count.seqs command should be in the following format: count.seqs(name=yourNameFile).
Example count.seqs(name=amazon.names) or make.table(name=amazon.names).
Note: No spaces between parameter labels (i.e. name), '=' and parameters (i.e.yourNameFile)

```

**Comment by shiltemann** [comment]
ah yes, these wrappers are designed for the 1.36.1 version. Looks like Galaxy is picking up your system version instead of its own dependency. How did you install it? do you have conda dependencies enabled?

P.S. I am working on an update to 1.39.5 where I have indeed removed this parameter, but those wrappers will take a little more time to finish.

**Comment by bvalot** [comment]
HI,

I simply used the debian (strech) version of mothur. I don't really know why they search for my local version instead of the packaged dependancy.  It is a parameter in galaxy.init?

Benoit

**Comment by shiltemann** [comment]
I suspect the conda dependency was not installed properly and that is why the system version is being picked up. In the admin panel of Galaxy you can check the status of the dependency install and any errors. Which version of Galaxy are you running?

**Comment by bvalot** [comment]
OK, I look at and in fact dependancy was not installed. I add the good mothur version associated with the wrapper using conda and it works.

Thanks for you time.
