### ISSUE TITLE
Mothur: Pcr.seqs on non align fasta files

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/tools-iuc#1508]
HI,

I have a small problem with the tools pcr.seqs. Actually, it works only on mothur.align input, but this is not necessary for trim by oligos, because simple fasta file could be used for that.

Can you add fasta file as valid format input when oligos trim is choice.
Similarly, the ouput format must be the same as the input: fasta or mothur.align.

Best regards,

Benoit

**Comment by shiltemann** [comment]
thanks @bvalot! I will push a fix as soon as I can
