### ISSUE TITLE
Hisat2 unaligned reads (L) and aligned reads (L) empty

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1514]
The two files that are generated in addition to the BAM file are empty by default. 

Only if the options `Write unaligned reads (in fastq format) to separate file(s)` and/or `Write aligned reads (in fastq format) to separate file(s)` are selected the "L" files are filled (in addition to the R files).

**Comment by nsoranzo** [comment]
That should be already fixed by https://github.com/galaxyproject/tools-iuc/pull/1497 , available in the ToolShed as revision 16:21e8ea8e1adb since 2017-09-30. Can you check that you have the latest version?

**Comment by bernt-matthias** [comment]
Thanks for the info: I thought I have installed it: I install tools with ansible-galaxy-tools and had added it to my tool_list.yml file. But it was not installed because the previously installed version 15 (d5fe9aead222) vanished from the toolshed and therefore the installer could not determine if the new version was really new and skipped the installation. 

Is this normal that versions disappear from TS? Seems to contradict reproducibility. 

Anyway, the new version works. Thanks a lot.

**Comment by nsoranzo** [comment]
Revision 15 did not disappear from the ToolShed, it was updated to revision 16 with a minor fix (the one for this issue) without increasing the tool version number. So it's not possible to install revision 15 of the repo any more.
