### ISSUE TITLE
Qiime summarize_taxa - Wrong revision on the MTS

### ISSUE THREAD

**Issue by arbernard** [galaxyproject/tools-iuc#1518]
Hi everyone,

At the end of last week, I made an update pass of all the Qiime wrappers (from the IUC repository, MainToolShed) that we are using on a few Galaxy instances.

I had no issue for most of them but after the update, the qiime_summarize_taxa repo was not displaying the little green icon indicating i was now using the last revision of this repository.

So I uninstalled and reinstalled this repo and finally got the green icon.

However, when I edited a workflow that was using this tool, I noticed an error message about one of its parameters. And indeed, the parameter in question (`--upper_percentage`) was displayed in a red box with the following error message: `A real number or workflow parameter e.g. ${name} is required`

I quickly saw that the issue was coming from a missing `optional="true"` attribute but when i checked the last version of the code here on Github I noticed that the following commit from @bgruening was already fixing the issue: bd274e3 (2017-08-22)

From what I understood, there should have been a new revision of the qiime_summarize_taxa repo created after this fix but it seems it wasn't the case on the MTS .

I've just noticed this morning that the version date for both revision 5 and 6 of this repo on the MTS is **2017-08-05** while on the TTS revision 5 is from the **2017-08-04** and revision 6 from the **2017-08-22**.

On the TTS, revision 6 does include the fix for the `--upper_percentage` parameter but revision 6 on the MTS does not.

Does someone know why it's the case and how to fix it please ?

Thanks in advance

ping @shiltemann @bebatut

**Comment by nsoranzo** [comment]
Thanks @arbernard for the heads-up, I've manually pushed to the main ToolShed the following repositories:
- qiime_pick_open_reference_otus
- qiime_summarize_taxa
- suite_qiime
