### ISSUE TITLE
IUC member proposal - Maria Doyle

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1555]
I would like to propose Maria Doyle (@mblue9) to become an IUC member.

She has already contributed [a lot](https://github.com/galaxyproject/tools-iuc/pulls?q=is%3Apr+author%3Amblue9+is%3Aclosed). She added new tools, like pizzly or limma/voom, but also helped maintaining and updating already existing tools - e.g. hisat2, goseq, heatmap2.

There are also a bunch of open PRs which will be merged soon!

Please vote!

**Comment by mvdbeek** [comment]
👍

**Comment by shiltemann** [comment]
big +1!

**Comment by bebatut** [comment]
👍

**Comment by nsoranzo** [comment]
:+1:

**Comment by nekrut** [comment]
:+1:

**Comment by erasche** [comment]
:+1:

**Comment by mtekman** [comment]
:+1:

**Comment by yhoogstrate** [comment]
:+1:

**Comment by blankenberg** [comment]
+1

**Comment by bgruening** [comment]
It seems that we have a new member here! Welcome @mblue9 to the IUC!

@martenson can you add her to the

* repository
* mailing list

I will send the TS credentials.

Thanks everyone for voting!

**Comment by martenson** [comment]
Welcome @mblue9 ! I have invited you to the galaxyproject IUC team. Please share your email with me so I can sign you up for private mailing list and add your MTS account to the group.

**Comment by nsoranzo** [comment]
@mblue9 I've added you to https://galaxyproject.org/iuc/ , please double check your affiliation.

**Comment by mblue9** [comment]
Thanks all for this!! It's an honour to join this great group! 🙌 😄 🎉 🎈
