### ISSUE TITLE
IUC member proposal - Simon Gladman

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1556]
I would like to propose Simon Gladman (@Slugger70) to become an IUC member.

Simon, most famous for his trips through the world and teaching people about Conda and Galaxy, has already [18](https://github.com/galaxyproject/tools-iuc/pulls?q=is%3Apr+author%3ASlugger70+is%3Aclosed) merged PRs. Simon is also maintaining a whole bunch of Genome Annotation and Assembly tools!

Simon is also contributing to the training material project, is a Galaxy admin and GVL developer!

Please vote!

**Comment by mvdbeek** [comment]
👍

**Comment by shiltemann** [comment]
:+1: !

**Comment by bebatut** [comment]
👍

**Comment by nsoranzo** [comment]
:+1:

**Comment by erasche** [comment]
:+1:

**Comment by mtekman** [comment]
:+1:

**Comment by yhoogstrate** [comment]
:+1:

**Comment by abretaud** [comment]
👍

**Comment by blankenberg** [comment]
+1

**Comment by bgruening** [comment]
Welcome @Slugger70! Happy to have you on board!

@martenson can you add him to the

* repository
* mailing list

I will send the TS credentials.

Thanks everyone for voting!

**Comment by martenson** [comment]
Welcome @Slugger70 ! I have invited you to the galaxyproject IUC team. Please share your email with me so I can sign you up for private mailing list and add your MTS account to the group. You can use marten@bx.psu.edu.

**Comment by nsoranzo** [comment]
@Slugger70 I've added you to https://galaxyproject.org/iuc/ , please double check your affiliation.
