### ISSUE TITLE
Bowtie2 v2.3.2.2 won't submit job when passing a list:paired collection and selecting unaligned reads output

### ISSUE THREAD

**Issue by ericenns** [galaxyproject/tools-iuc#1563]
Note: This error occurs on galaxy version 17.01 and forward.

This may be more appropriate to place in galaxyproject/galaxy as this may be a galaxy error and not a tool error.

The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool: 'Dataset collection has no element_identifier with key forward.'
```
{
    "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.3.2.2",
    "tool_version": "2.3.2.2",
    "inputs": {
        "library|type": "paired_collection",
        "library|input_1": {
            "values": [
                {
                    "src": "hdca",
                    "map_over_type": "paired",
                    "hid": 3,
                    "id": "28a2498ac8ec4f9b",
                    "name": "Test"
                }
            ],
            "batch": true
        },
        "library|unaligned_file": "true",
        "library|aligned_file": "false",
        "library|paired_options|paired_options_selector": "no",
        "reference_genome|source": "indexed",
        "reference_genome|index": "Human_GRCh38_index",
        "rg|rg_selector": "do_not_set",
        "analysis_type|analysis_type_selector": "simple",
        "analysis_type|presets": "no_presets",
        "save_mapping_stats": "false"
    }
}
```

**Comment by jennaj** [comment]
I can confirm this bug. Occurs with pe collection list input. Multiple individual dataset inputs do not produce the error. Thanks for reporting the bug!

Selecting to output mapped or unmapped gives a failed job submission pop-up warning. See this by rerunning dataset 10 in the test history and changing the form to output one or the other or both.

https://usegalaxy.org/u/jen/h/test-history-bowtie2-2322-paired-end

**Comment by ericenns** [comment]
One thing to note is I only tested this on galaxy version 17.01 and forward, I am guess it doesn't work on earlier versions either.

Another thing if you execute a workflow with the same options it silently fails.

**Comment by mvdbeek** [comment]
@ericenns 
I haven't managed to reproduce this on dev or usegalaxy.org, which is running 17.09.
What was the latest commit that you have tested ?
Does this happen for all collections ?
The input collection structure is `list:paired` or `list` or is it something else ?
@jennaj your history looks fine but is using hisat2.

**Comment by ericenns** [comment]
@mvdbeek my collection is list:paired.

I tested against our local 17.01 install and using planemo serve with a brand new fetch of Galaxy.

Paired collection works, but List:Paired doesn't and will produce the error as above.

The error that shows won't be viewable in a history since a job is never created.

**Comment by ericenns** [comment]
@mvdbeek I just imported the history @jennaj created and tried to run bowtie on it and received the same error I posted above.

The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool: 'Dataset collection has no element_identifier with key forward.'
```
{
    "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.3.2.2",
    "tool_version": "2.3.2.2",
    "inputs": {
        "library|type": "paired_collection",
        "library|input_1": {
            "values": [
                {
                    "src": "hdca",
                    "name": "pairedfq",
                    "tags": [],
                    "hid": 7,
                    "map_over_type": "paired",
                    "id": "7968cdb80b22df44"
                }
            ],
            "batch": true
        },
        "library|unaligned_file": "true",
        "library|aligned_file": "false",
        "library|paired_options|paired_options_selector": "no",
        "reference_genome|source": "indexed",
        "reference_genome|index": "papHam1",
        "rg|rg_selector": "do_not_set",
        "analysis_type|analysis_type_selector": "simple",
        "analysis_type|presets": "no_presets",
        "save_mapping_stats": "false",
        "__job_resource|__job_resource__select": "no"
    }
}
```

**Comment by mvdbeek** [comment]
Ah, I see, this depends on selecting the unaligned file and is probably linked to https://github.com/galaxyproject/tools-iuc/blob/master/tools/bowtie2/bowtie2_wrapper.xml#L559 .
Not sure if that's a bowtie issue or a galaxy issue though. It may work to change this in the collection case to use `structured_like` and `inherit_format`.

**Comment by jennaj** [comment]
Thanks for retesting that. Sorry about including the wrong tool originally! Bowtie2 is problematic right now at https://usegalaxy.org ([new ticket about that](https://github.com/galaxyproject/usegalaxy-playbook/issues/62)) but it sounds like you know what the issue is, or are close ;)

**Comment by ccedmendoza** [comment]
Hi, a have the same issue and wanted to know if there was a known workaround to this or the only way is to launch the paired alignments one by one?

**Comment by mvdbeek** [comment]
This is probably a galaxy bug, I'll have a look

**Comment by ccedmendoza** [comment]
Actually I think it's a wrapper bug. When I was testing the tool I found out that this bug only happens when the **Write unaligned reads (in fastq format) to separate file(s)** or the **Write aligned reads (in fastq format) to separate file(s)** parameters corresponding to the *unaligned_file* and *aligned_file* in the *align_unalign* macro. Furthermore I believe that it has to do with the output, I'm not sure at all about this since the wrapper is quite complex and I only looked at it briefly.

**Comment by mvdbeek** [comment]
This is a galaxy bug (or at the minimum a missing feature). If you opt to get aligned or unaligned reads we will dynamically determine the output datatype based on the input datatype extension (https://github.com/galaxyproject/tools-iuc/blob/master/tools/bowtie2/bowtie2_wrapper.xml#L556). We don't however take into account the mapping over of list:paired collections to paired inputs.
