### ISSUE TITLE
Map with BWA tool doesn't install its dependencies when installed from toolshed

### ISSUE THREAD

**Issue by crashfrog** [galaxyproject/tools-iuc#1577]
Fatal error: Exit code 127 ()
[bwa_index] Pack FASTA... 0.03 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1.40 seconds elapse.
[bwa_index] Update BWT... 0.04 sec
[bwa_index] Pack forward-only FASTA... 0.02 sec
[bwa_index] Construct SA from BWT and Occ... 0.61 sec
[main] Version: 0.7.16a-r1181
[main] CMD: bwa index localref.fa
[main] Real time: 2.204 sec; CPU: 2.103 sec
samtools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

This is revision 4d82cf59895e .

**Comment by crashfrog** [comment]
This seems like possibly an issue with Conda channel order, as either by default or as configured by Galaxy:

https://github.com/bioconda/bioconda-recipes/issues/5188

The samtools binary installed as a dependency to BWA depends on a shared library that bz2-devel doesn't install, and thus can't run.

**Comment by bgruening** [comment]
@crashfrog yes I think you are right. Which Galaxy version are you using. Make sure that conda-forge has a higher priority than defaults.

**Comment by crashfrog** [comment]
We're on tag v17.05-46-gd4d558b . I don't believe we've made any changes to Conda, so the channel priorities are at however Galaxy configured them, if it did so.

**Comment by crashfrog** [comment]
Galaxy doesn't put ```conda``` on the $PATH when it installs, does it? I'm getting ```conda: command not found``` when I try to run it as the galaxy user on the server and as root, and I'm wary about installing conda via its yum package without knowing what that's going to to do Galaxy's conda.

**Comment by crashfrog** [comment]
Sorry, I guess we need some guidance on this. Installing bzip2 via conda didn't solve the problem, conda couldn't find ```samtools``` in *either* conda-forge or repo.continuum.io, and reloading the tool's config in Galaxy doesn't seem to have prompted it to grab the samtools dependency from conda-forge.

**Comment by bgruening** [comment]
@crashfrog you also need bioconda in your channel list. This is the current recommended one: https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L217

**Comment by crashfrog** [comment]
We hadn't made a change to that line in the galaxy.ini, so wouldn't Galaxy have set Conda up with those channels as default? I assumed the commented-out lines in the INI show the defaults.

**Comment by crashfrog** [comment]
Ok, so I enabled that line in the INI, and I guess it *did* change something, because now (after uninstalling and reinstalling BWA, in order to trigger a samtools re-download using the new Conda channel priority:

```
Fatal error: Exit code 127 ()
/shared/001/1355/tool_script.sh: line 9: bwa: command not found
```

I notice that there was an update to this repository a couple of days ago. Could this be related?

**Comment by crashfrog** [comment]
After clearing the Conda cache and re-installing the BWA tool:

`Traceback (most recent call last):
  File "/nfs/sw/apps/galaxy-prd/galaxy/lib/galaxy/jobs/runners/__init__.py", line 630, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/nfs/sw/apps/galaxy-prd/galaxy/lib/galaxy/jobs/__init__.py", line 1266, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/nfs/sw/apps/galaxy-prd/galaxy/lib/galaxy/datatypes/binary.py", line 391, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by mvdbeek** [comment]
Alright, now you also need to install the dependencies for the "Set External Metadata tool", which are samtools and bcftools. You can do this in the admin menu, left hand side, "Manage tool dependencies". Look for "set external metadata", tick the box and hit "Install via Conda".

**Comment by crashfrog** [comment]
Ah, ok. Got it, looks like it's working.
