### ISSUE TITLE
featureCounts metadata column names should use $element_identifier, not $dataset.name

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#1582]
Currently the metadata for each column is set using the `$dataset.name`. This often results in ugly names such as `$tool_id on dataset 1, dataset 2, and dataset 3`. Instead, it would be nicer to use `$alignment.element_identifier` in places like https://github.com/galaxyproject/tools-iuc/blob/master/tools/featurecounts/featurecounts.xml#L387.

**Comment by mblue9** [comment]
Hi @lparsons I've been trying this but it's not working for me, featurecounts is still using the "HISAT2 on" from the Name field for the header. Does it work ok for you? Is it adding the correct identifier to the header?

**Comment by lparsons** [comment]
@mblue9 Looks like you got this sorted out in the thread for https://github.com/galaxyproject/galaxy/issues/5239. I think the problem was needing to have https://github.com/galaxyproject/galaxy/pull/5049 in your Galaxy install.

**Comment by mblue9** [comment]
Yes I think so, am just waiting on the ok to update to check but hopefully that's the reason. If it works then this will be really great! As I ended up manually editing the name field for ~30 files one-by-one yesterday to get the right sample ids added to the header for featurecounts, and was really hoping I wouldn't have to do that again! So thanks a lot for adding this feature!!!!
