### ISSUE TITLE
Jbrowse - bam chunk size exceeds chunkSizeLimit

### ISSUE THREAD

**Issue by aifennng** [galaxyproject/tools-iuc#1602]
Hi
Recently I found that when I view some bam in Jbrowse, The reads not view but show "Too many BAM Features. BAM chunk size ******* bytes exceeds chunkSizeLimit of 5,000,000"
I found that, The chunkSizeLimit can modify in Configuration of Jbrowse. But I can't find the Configuration file of Jbrowse in Galaxy

![snapshot_20171124155020](https://user-images.githubusercontent.com/32814771/33200391-5455590e-d12f-11e7-9615-478a59c6a0da.jpg)

**Comment by abretaud** [comment]
Hi,
The config file is stored in the Galaxy dataset folder, something like `/galaxy-central/database/files/000/dataset_11_files/data/trackList.json`.
Currently, there's no way to change this setting from the tool form.
Did you try checking "Autogenerate SNP Track" when generating your jbrowse?
