### ISSUE TITLE
MultiQC - samtools flagstat weird output

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/tools-iuc#1608]
Just tried MultiQC (v1.2.0) on samtools flagstat (v2.0.1) and while the "General Statistics" part looks ok, the "Samtools Flagstat" part does not, it has blue dots randomnly plotted (see screenshot below), wondering if anyones's got that to work or if it's a bug?
![screen shot 2017-11-28 at 4 23 01 pm](https://user-images.githubusercontent.com/5591821/33303652-7b9d4c34-d458-11e7-9099-6a4fdaa232cf.png)

**Comment by mblue9** [comment]
This weird plot issue also happens in Galaxy Freiburg with MultiQC 1.2.0 (it is pretty cool to have multiple Galaxies to use for testing!)

**Comment by bebatut** [comment]
I have the same type of output

![screen shot 2018-04-09 at 20 55 27](https://user-images.githubusercontent.com/1842467/38516808-5edfafc2-3c38-11e8-9eb3-3b4dad8a0f07.png)

But it is not specific to MultiQC in Galaxy. I reproduce it by running MultiQC locally, so maybe a MultiQC issue

**Comment by mblue9** [comment]
Thanks for checking this @bebatut! I'll close this issue so as it's not a wrapper issue.
