### ISSUE TITLE
mothur view log files starts download of binary file

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1621]
Instead of displaying the log viewing the log files of some tools triggers a download (of a binary file). 
Examples are: 
-  Align.seqs
- Screen.seqs
- Make.contigs

Some work as expected: Unique.Seqs, Summary.Seqs

**Comment by bgruening** [comment]
Hopefully fixed with: https://github.com/galaxyproject/tools-iuc/pull/1722
