### ISSUE TITLE
Mothur - error on libboost_iostreams.so.1.57.0

### ISSUE THREAD

**Issue by vebaev** [galaxyproject/tools-iuc#1625]
Hi,
I have installed some particular tools from the Mothur tutorial (installed ok, green), however, the first tool Merge.files produce an error (Galaxy v17.09):

Fatal error: Exit code 127 ()
mothur: error while loading shared libraries: libboost_iostreams.so.1.57.0: cannot open shared object file: No such file or directory

**Comment by bgruening** [comment]
Cab you please test the latest version and let us know if it still is not working?
