### ISSUE TITLE
GetFastaBed fails to retrieve data for non-DM genomes

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1630]
Tool is looking for input where it will not exist for any genome created without a DM. More details below with error/command-line. 

**Tool**: GetFastaBed v 2.26.0.0 (updated 2017-07-05, IUC tool)

**Tool repo**: https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/b73962f8fcbf

**Test history, mm10 + mm9 fail, hg38 success, all success with Extract**: https://usegalaxy.org/u/jen/h/test-history-getfastabed

**Command line for successful hg38**
`bedtools getfasta     -fi '/galaxy/data/hg38/seq/hg38.fa' -bed '/galaxy-repl/main/files/020/919/dataset_20919268.dat' -fo '/galaxy-repl/main/files/020/919/dataset_20919271.dat'`

**Command line for UNsuccessful mm9**
`bedtools getfasta     -fi '/galaxy/data/mm9/seq/mm9.fa' -bed '/galaxy-repl/main/files/020/919/dataset_20919426.dat' -fo '/galaxy-repl/main/files/020/919/dataset_20919491.dat'`

**Error for UNsuccessful mm9**
```
Fatal error: Exit code 1 ()
index file /galaxy/data/mm9/seq/mm9.fa.fai not found, generating...
could not open index file /galaxy/data/mm9/seq/mm9.fa.fai for writing!
```

The file 'mm9.fa.fai' will not exist in this location (will be nested under /galaxy/data/mm9/samtools) for any genome not created with a Data Manager. Non-DM data is most of the content at http://usegalaxy.org.

Extract is fine because it accesses the loc for 2bit data.

**UPDATE: Moved from https://github.com/galaxyproject/galaxy/issues/4412** See comments there for @mvdbeek proposed fix (change tool to use symlinks)

**Comment by natefoo** [comment]
I updated BEDtools on Main yesterday (and Test the day before).

**Comment by jennaj** [comment]
Thanks! toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_getfastabed/2.27.0.1 fixed the problems. Tests in the history linked above.
