### ISSUE TITLE
deepvariant pipeline

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1636]
https://github.com/google/deepvariant

**Comment by HassanAmr** [comment]
I'm on it :)

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/tools-iuc/pull/1654

**Comment by gallardoalba** [comment]
It was implemented by using the Docker containter https://github.com/galaxyproject/tools-iuc/pull/3919
