### ISSUE TITLE
Bowtie2 v2.3.3.1

### ISSUE THREAD

**Issue by ccedmendoza** [galaxyproject/tools-iuc#1640]
Hi all,

Bowtie2 v2.3.3.1 has a problem reading some fastq files.
The issue is discussed here [#141](https://github.com/BenLangmead/bowtie2/issues/141).
Running Bowtie2 on a single thread seems to work fine though.

Thanks.

**Comment by bgruening** [comment]
@ccedmendoza thanks for the pointer. Please ping us if there is a fixed version.

**Comment by ccedmendoza** [comment]
The latest version of Bowtie2 (v2.3.4) seems to fix this problem.

**Comment by bgruening** [comment]
@ccedmendoza thanks!
