### ISSUE TITLE
Mothur Venn does not produce output with format/datatype set to "svg"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1643]
Venn Generate Venn diagrams for groups (Galaxy Version 1.36.1.0)
Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/iuc/mothur_venn/mothur_venn/1.36.1.0
Galaxy Tool Version: | 1.36.1.0
Tool Version: | v.1.36.1
https://toolshed.g2.bx.psu.edu/view/iuc/mothur_venn/cc4a296dd5d0

Problem: The .svg output has no "format" assigned (the tabular and logfile output are fine). When downloaded, a file name like `Galaxy223-[Venn_on_data_221__svg__0.03.sharedsobs.F3D0-F3D1-F3D2-F3D3] (1)` is given. The default extension is `.null` - but this can be changed by the user in the download dialog to be `.svg` (at least on MAC OSX). It can be difficult to modify this after download (user must know how to access file extensions....). Other Mothur tools that produce .svg output are labeled and download with the .svg extension (so users can click on the output locally and view easily)

Example of a tool with .svg properly assigned is:

Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/iuc/mothur_heatmap_sim/mothur_heatmap_sim/1.36.1.0
Galaxy Tool Version: | 1.36.1.0

Example history contains a run-through of the [GTN 16S metagenomics tutorial](http://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.html#otu-based-analysis), section "Hands-on: Venn diagram"). See dataset 223 for the venn output, dataset 220 for the heatmap output: https://usegalaxy.org/u/jen/h/16s-microbial-analysis-with-mothur---proccess

If I am misunderstanding what this tool should be outputting, please correct me. Thanks!

**Comment by bgruening** [comment]
Hopefully fixed with: https://github.com/galaxyproject/tools-iuc/pull/1722

**Comment by jennaj** [comment]
Thanks - version 1.39.5.0 resolved both tool problems!
