### ISSUE TITLE
Mothur Make.biom does not recognize tabular datatype dataset as "metadata" input

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1644]
Make.biom (version 1.36.1.0)
https://toolshed.g2.bx.psu.edu/view/iuc/mothur_make_biom/5dc4d49a238a

Dataset 10 in this test history is an example of proper tabular input for the "metadata" tool form options, but it cannot be selected: https://galaxy.uni-freiburg.de/u/jenj/h/test-history-mothur-subsample

True also at https://usegalaxy.org, so either a problem with the tool wrapper or Galaxy itself (v17.09). If not the tool, we can move this over to the /galaxy repo. The other two primary inputs capture appropriate input dataset fine.

Used in the [16S metagenomics GTN tutorial](http://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.html), step 'Hands-on: Phinch"

from `make.biom.xml`
```
 <inputs>
        <param name="otu" type="data" format="mothur.shared" label="shared - OTU Shared file"/>
        <param name="constaxonomy" type="data" format="mothur.cons.taxonomy" optional="true" label="contaxonomy - consensus taxonomy" help="The contaxonomy file is the taxonomy file outputted by classify.otu"/>
        <param name="metadata" type="data" format="tabular" label="metadata" optional="true" help="You can add sample data support here"/>
```

**Comment by vparreir** [comment]
same problem. any suggestions?

**Comment by shiltemann** [comment]
as a workaround you can change the format of your metadata file to `tabular`. 

I have been working on updating the wrappers to the latest version of mothur and have incorporated a fix for this issue there (hope to submit the PR by the end of the day)

**Comment by vparreir** [comment]
Hi Saskia,


Yes, the format of the metadata file is tabular, I also have another copy as txt, but still doesn't work.

Thank you for your quick response.

Valeria






________________________________

**Comment by shiltemann** [comment]
@vparreir oh hmm, thanks for letting me know, that is strange, I thought the problem was that the metadata file from the tutorial gets sniffed wrongly, ok, I will look into it in more detail

**Comment by shiltemann** [comment]
hmm, I don't have this issue locally or on our server. @jennaj I dont have permission to view the files in the history you shared, could you share it with me (saskia, zazkia@gmail.com on that server)

**Comment by shiltemann** [comment]
ok, in a previous version of the wrapper there was an error, it had `format="metadata"` instead of `tabular`, I think an update of the tool should help

**Comment by jennaj** [comment]
@shiltemann I both shared directly with you and changed permissions so everyone can view. Odd that happened, the config must be different on the server.

Thanks for helping with this!

**Comment by jennaj** [comment]
@davebx @bgruening Could we update to the most current version of the tool on both servers?

**Comment by vparreir** [comment]
Any news on this front?

Thanks in advance,

Valeria






________________________________

**Comment by bgruening** [comment]
Hopefully fixed with: https://github.com/galaxyproject/tools-iuc/pull/1722

**Comment by davebx** [comment]
@jennaj main has been updated with #1722

**Comment by jennaj** [comment]
Version 1.39.5.0 fixed the problem on both servers. Great & thank you!
