### ISSUE TITLE
BEDTools NucBed 2.27.0.0 fails when -pattern is used without -C

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1662]
**Tool**: NucBed profile the nucleotide content of intervals in a FASTA file (Galaxy Version 2.26.0.0)

**MTS**: https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/a8eabd2838f6

**Problem**: Defaults and all other combinations of parameters work fine, except when using `-pattern` as `yes` and `-C` as `no`. See test histories below for error details.

**Example that fails**:
```
bedtools nuc   -pattern  -fi '/data/1/galaxy_db/files/005/593/dataset_5593043.dat' -bed '/data/1/galaxy_db/files/005/593/dataset_5593044.dat' > '/data/dnb01/galaxy_db/files/005/593/dataset_5593045.dat'
```
<img width="622" alt="screen shot 2018-01-09 at 4 08 06 pm" src="https://user-images.githubusercontent.com/8999735/34749825-69148f20-f558-11e7-937d-70d08f3592ce.png">

**Example that passes**:
```
bedtools nuc   -pattern -C -fi '/data/1/galaxy_db/files/005/593/dataset_5593043.dat' -bed '/data/1/galaxy_db/files/005/593/dataset_5593044.dat' > '/data/1/galaxy_db/files/005/593/dataset_5593049.dat'
```
<img width="632" alt="screen shot 2018-01-09 at 4 07 41 pm" src="https://user-images.githubusercontent.com/8999735/34749857-b1bcb180-f558-11e7-889a-3c495fee3377.png">

**Test histories**:
 - https://usegalaxy.org/u/jen/h/bedtools-nucbed-test-history
 - https://galaxy.uni-freiburg.de/u/jenj/h/bedtools-nucbed-test-history-2

**Minor**: Param typo `Igore case when matching -pattern` should be fixed to be `Ignore` when the correction is made. Use this or add in as new PR: https://github.com/galaxyproject/tools-iuc/pull/1663

**Comment by bgruening** [comment]
@jennaj should be fixed, I updated our instance.

**Comment by jennaj** [comment]
I am getting an error when I run the updated tool at freiburg. Details in the test history above.

```
Failed to activate conda environment! Error was:

CondaValueError: Could not find environment: /usr/local/tools/_conda/envs/__bedtools@2.27.0
Fatal error: Exit code 1 ()
```

**Comment by jennaj** [comment]
Works at both servers now, must have been a transient problem.
