### ISSUE TITLE
qiime multiple mulled conda environments

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1666]
In a full qiime installation 6 mulled conda environments are installed (in addition to the basic qiime environment). 

2.3G	mulled-v1-e6c5a6a497ec60d3e5742911be11e74f97e3402dcac517afea93afbaec8bfaf5
2.4G	mulled-v1-8210996b6255041d2ad0c37525e849074757e7bc60724faa772ce53179c8cf21
2.7G	mulled-v1-3a355b0d37eb99ae165f74154871ab861dae7907f5675592b8a99ec97b779857
2.6G	mulled-v1-0d99b18574cc72e0d90f7ceca03112973ee4c042aee1f4876476a4c14d310189
2.3G	mulled-v1-211d824c28a8c0ac15b34ffa8cb2e75706b7ae21275acc1c0e312a53b7b72297
2.3G	mulled-v1-d733cfedf636f69eaa70d9498b7004d8004f7db0bb792f943589e1b267d40747
2.3G	__qiime@1.9.1

This is caused by the following tools: `./multiple_join_paired_ends.xml ./compare_categories.xml ./align_seqs.xml ./pick_otus.xml ./make_phylogeny.xml ./assign_taxonomy.xml` each having its own (disjoint) set of additional requirements.

Woudn't it be better to have two sets of requirements: 

1. basic qiime
2. qiime + additional tools 

?

Would be happy to implement this.

**Comment by nsoranzo** [comment]
I don't think that's a problem, the total disk space should be the same because conda only creates hardlinks in environments.

**Comment by bgruening** [comment]
@nsoranzo is correct for conda, at least for normal conditions, but for Singularity and Docker we waste some space here. I'm not sure what the best scenario. We could improve the situation by not using `yield` in the requirements and just use one set of deps for all tools, but on the other hand if you just want to use a few tools you get potentially more dependencies than what is needed.

+/- 0 from me.

**Comment by bernt-matthias** [comment]
@nsoranzo I did not know about the hard links. So: its fine for conda.
