### ISSUE TITLE
RFC: auto-update tools

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1676]
Given conda packages and the easy retrieval of all packages and there versions (`check_output("wget --quiet https://conda.anaconda.org/%s/%s/repodata.json.bz2 -O '%s.bz2' && bzip2 -d '%s.bz2'" % (channel, platform_tag, repo_data, repo_data))`) it should be possible to watch selected Galaxy tools and upgrade the dependencies to fit the conda version.

1. annotate selected tools (bowtie, hisat, fastqc ...) in the shed.yaml file with `auto_update: True`
2. use https://github.com/galaxyproject/planemo-monitor to also track shed.yaml files
3. upgrade the tool-requirements, the tool-version and submit a PR
    - I don't think we should do much magic here, we can define some standards that makes it easier to find the spots that needs to be changed (`@WRAPPER_VERSION@, @TOOL_VERSION@` ...)
    - submitting a PR automatically is already implemented and used in https://github.com/galaxyproject/planemo-monitor

Ideally this should be implemented in planemo with a new sub-command.
Anyone up for this task?

**Comment by abretaud** [comment]
That's done :ballot_box_with_check:
