### ISSUE TITLE
python packages have no ssl support currently

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#168]
I have some problems with our python packages, and probably all packages that are linking to the openssl package. Currently, the openssl package does not include any certificates which makes it useless for https transfers etc.

Building bx-python, which depends on python-2.7, will fail because it is not able to fetch some library via https.

We need to add somehow certificates to the openssl package to make this work. An other possibility would be to simply drop the openssl library dependency and rely on the system one. This was previously discussed here: https://github.com/galaxyproject/tools-iuc/pull/76

Any other ideas? docker-build with relocatable python binaries + certificates?
ping @natefoo

**Comment by erasche** [comment]
If you need certs, then I am +1 on removing the ssl dependency.

I trust the OS to revoke certs and update SSL in a timely manner. The IUC
simply cannot keep on top of this, as proven by our inability to keep
packages up to date on the MTS. I don't want to be adding one more thing
that *must* be regularly updated.

Especially considering that we'll be triggering new installable revisions
that require the admin to update.

I vote to get rid of SSL in the TS.
28. mai 2015 7.17 a.m. skrev "Björn Grüning" <notifications@github.com>:

**Comment by peterjc** [comment]
I've previously commented on #76 that I think we should just insist that every Galaxy Administrator install OpenSSL as a general prerequisite - ideally via their OS packaging system which will keep it up to date.

i.e. Yes, let's get rid of SSL in the TS.

**Comment by bgruening** [comment]
Great, thanks for your comments. I will wait for @natefoo to comment, he was in favour of keeping it.

**Comment by natefoo** [comment]
I'm not going to be the roadblock, +1 for dropping. =)

However, could we discuss the idea of adding requirements meta-tags that can imply something like "requires OpenSSL (and not just the runtime, we need the headers too)". That way, down the line, if granted permission by the Galaxy admin, Galaxy could `sudo apt-get install openssl-dev` / `sudo yum install openssl-devel` / etc. prior to attempting installation. Or perhaps this isn't necessary if we are ultimately moving dependencies outside of the TS.

What I'd like to avoid is "losing" the knowledge of what packages depend on what things, it makes for a more difficult user experience when someone goes to install something from the TS and it fails for reasons that are unclear to anyone not seasoned in compiling software.

**Comment by erasche** [comment]
Maybe a requirement like

```
 <requirements>
            <requirement type="package" version="2.22">bedtools</requirement>
            <requirement type="system">openssl</requirement>
            <yield/>
</requirements>
```

that could be shown to an admin?

**Comment by natefoo** [comment]
Maybe just:

```xml
<requirements>
            <requirement type="package" version="2.22">bedtools</requirement>
            <requirement type="system" description="OpenSSL runtime libraries">openssl-libs</requirement>
            <requirement type="system" description="OpenSSL headers">openssl-dev</requirement>
            <yield/>
</requirements>
```

And then somewhere in some new structured data file we have:

```xml
<system_requirements>
    <system_requirement name="openssl-libs">
        <provided_by os_family="debian">openssl</provided_by>
        <provided_by os_family="redhat">openssl</provided_by>
    </system_requirement>
    <system_requirement name="openssl-dev">
        <provided_by os_family="debian">openssl-dev</provided_by>
        <provided_by os_family="redhat">openssl-devel</provided_by>
    </system_requirement>
```

Of course, this will fail if you are using binaries compiled against OpenSSL >= 1.0 and you are installing on a system with 0.9, or vice versa, since the so's are named differently.

**Comment by erasche** [comment]
@natefoo even better. Maybe we would end up noting things like a specific version in the requirement description field.

**Comment by bgruening** [comment]
@erasche @natefoo can we close this issue and move the requirement ideas into Trello?

**Comment by erasche** [comment]
:+1:

**Comment by nsoranzo** [comment]
Closing this, @erasche if you still want to open a Galaxy GitHub issue for system requirements, this is a reminder :)

**Comment by erasche** [comment]
Thanks @nsoranzo
