### ISSUE TITLE
HISAT2 only accepts data type fastqsanger, not fastq. Why? 

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-iuc#1681]
I'm having trouble running the HISAT2 galaxy tool. I have a collection of pairs of fastq files (forward and reverse) from an RNAseq experiment and would like to align them, but I'm getting: 
```
Must be of datatype "fastqsanger" or "fasta"
```
Shouldn't HISAT2 also be able to align fastqs? Bowtie2  / TopHat2 certainly can...

**Comment by mblue9** [comment]
Hmm weird.. HISAT2 works fine for me with the files I have but they are fastqsanger.gz

**Comment by zfrenchee** [comment]
@mblue9 that's one of the supported datatypes. I'm just saying I feel like fastq should be a supported datatype?

**Comment by zfrenchee** [comment]
The HISAT2 docs seems to suggest that fastq is a valid datatype, in fact, the preferred datatype. https://ccb.jhu.edu/software/hisat2/manual.shtml

@davebx you seem to have written most of the tool. What do you think? (cc @bgruening)

**Comment by nsoranzo** [comment]
@zfrenchee Just change the datatype to fastqsanger, see https://galaxyproject.org/support/fastqsanger/

**Comment by bgruening** [comment]
@nsoranzo is correct. You need to use fastqsanger to really be sure it is a sanger formatted fastq file.

**Comment by zfrenchee** [comment]
@bgruening @nsoranzo I have >1000 files and don't want to change their types by hand. [Bioblend doesn't have an API for scripting this.](https://github.com/galaxyproject/bioblend/issues/255#issuecomment-353544609). Is there an efficient way to convert all my files from "fastq" to "fastqsanger". Otherwise, it might make more sense to let this tool accept "fastq" and then throw an error if it isn't "fastqsanger" -- this would likely solve my issue, since my files probably conform to fastqsanger, but the galaxy import job assigned them "fastq".

**Comment by peterjc** [comment]
We may have reached the point where the Galaxy import tool should pick ``fastqsanger`` more freely over the less precise and thus safer but not as helpful default of ``fastq``.

**Comment by mvdbeek** [comment]
Galaxy does that starting from 17.09, unless you set it force it to fastq .

**Comment by zfrenchee** [comment]
@peterjc I'm not familiar with the nuances with these datatypes, but I would caution against using a name the community is not familiar with, without very good cause. To everyone I know, a fastq is a fastq, and you can align it to the genome. From the HISAT2 paper:

> The samples directory contains paired-end RNA-seq reads for 12 samples, with 6 samples from each of two populations, GBR (British from England) and YRI (Yoruba from Ibadan, Nigeria). For each population there are three samples each from male and female subjects (see Table 2 for the population and sex associated with each sample). All sequence is in compressed 'fastq' format, which stores each read on four lines. Each sample in turn is contained in two files: one for read 1 and another for read 2 of each pair. Thus, for example, sample ERR188245 is contained in files ERR188245_chrX_1.fastq.gz and ERR188245_chrX_2.fastq.gz, where each file contains 855,983 reads. Note that the original data files contain reads mapping to the entire genome rather than just chromosome X, and these files are ∼25 times larger. The README file at ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol contains instructions on how to download the full data sets for those who are interested. Note that HISAT2 also provides an option, called --sra-acc, to directly work with NCBI Sequence Read Archive (SRA) data31 over the internet. This eliminates the need to manually download SRA reads and convert them into fasta/fastq format, without significantly affecting the run time.

**Comment by peterjc** [comment]
@zfrenchee The nuance is in the now largely obsolete rival encodings used in early Solexa/Illumina FASTQ, nowadays all recent data will be following the original Sanger FASTQ convention - called ``fastqsanger`` in Galaxy. Galaxy uses ``fastq`` as base class covering all the variants, and also defines ``fastqillumina`` etc. If these are mixed up, your downsteam analysis will have very misleading quality scores which can mess up SNP detection etc.

For more background, see https://doi.org/10.1093%2Fnar%2Fgkp1137

@mvdbeek good to hear Galaxy 17.09 has changed the default importing of FASTQ files, I'd missed that news 👍

**Comment by zfrenchee** [comment]
I'm still curious though: there a way to convert many fastqs into fastqsangers? Perhaps fastqgroomer or somesuch?

**Comment by peterjc** [comment]
@zfrenchee Most of the time they don't actually need converting - just the metadata tweaked. However, ``fastqgroomers`` was created for this use case so try that.
