### ISSUE TITLE
update bedtools

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#17]
bedtools needs an update

- [x] update to version 2.22
- [x] add new features introduced in latest version (e.g. fisher tool)
- [x] add CDATA tag
- [x] add more tests
- [ ] -g option should not take a tabular file but should reuse genome.len files from Galaxy (${chromInfo} plus a validator on input file)

**Comment by bgruening** [comment]
@martenson I think we are ready. At least for TTS and test.usegalaxy.org

**Comment by martenson** [comment]
@bgruening awesome! I am going to push it in the TS now

**Comment by erasche** [comment]
Since bedtools 2.22 has been on the toolshed for a month now, @bgruening want to make the PR or are you still waiting on writing the `-g` mentioned in your todo list?

**Comment by bgruening** [comment]
We can merges this. Thanks for reminding me.
