### ISSUE TITLE
DESeq2 Fatal Error

### ISSUE THREAD

**Issue by rj-price** [galaxyproject/tools-iuc#1708]
DESeq2 was working fine for me last week, but this week when I try to run the tool, it always results in the following error:

`Fatal error: An undefined error occurred, please check your input carefully and contact your administrator.
Error in library("getopt") : there is no package called ‘getopt’`

I have tried re-running the tool with previous datasets that have worked but still get the above error. The details for my last test run are below:

**Details**

Dataset Information

```
Number: | 311
Name: | DESeq2 result file on data 252, data 250, and others
Created: | Wed 07 Feb 2018 08:46:52 AM (UTC)
Filesize: | 0 bytes
Dbkey: | ?
Format: | tabular
```

Job Information

```
Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/iuc/deseq2/deseq2/2.11.39
Galaxy Tool Version: | 2.11.39
Tool Version: | R version 3.2.2 (2015-08-14) -- "Fire Safety", DESeq2 version 1.10.1
Tool Standard Output: | stdout
Tool Standard Error: | stderr
Tool Exit Code: | 1
History Content API ID: | bbd44e69cb8906b5c2756b28f158534d
Job API ID: | bbd44e69cb8906b5c8fbc38cba0b3635
History API ID: | 3c77a230794f79ab
UUID: | 1d150eff-04f4-4103-8e10-b0b1d046b488
```

Tool Parameters

```
Specify a factor name, e.g. effects_drug_x or cancer_markers | FactorName |  
Specify a factor level, typical values could be 'tumor', 'normal', 'treated' or 'control' | FactorLevel1 |  
Counts file(s) | 242: featureCounts on data 241 and data 137 , 244: featureCounts on data 241 and data 138 |  
Specify a factor level, typical values could be 'tumor', 'normal', 'treated' or 'control' | FactorLevel2 |  
Counts file(s) | 250: featureCounts on data 241 and data 141 , 252: featureCounts on data 241 and data 142 |  
Choice of Input data | count |  
Visualising the analysis results | True |  
Output normalized counts table | False |  
Output all levels vs all levels of primary factor (use when you have >2 levels for primary factor) | False |  
Fit type | parametric |  
Turn off outliers replacement (only affects with >6 replicates) | False |  
Turn off outliers filtering (only affects with >2 replicates) | False |  
Turn off independent filtering | False
```

**Comment by mvdbeek** [comment]
Two things here, this isn't the latest deseq2 version, and then I'd verify in the admin panel (Manage dependencies -> find deseq2 in the list) that all the dependencies are correctly installed.

**Comment by rj-price** [comment]
I forgot to say I'm using the public instance at usegalaxy.org

Am I correct in thinking that I'm unable to do things you've suggested?

**Comment by peterjc** [comment]
Cross reference https://support.bioconductor.org/p/95125/ which looks like the same issue from last year.

It seems that the CRAN dependency ``getopt`` has not been installed. Curiously the bioconda package ``bioconductor-deseq2`` does explicitly declare ``r-getopt`` in its dependencies:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-deseq2/meta.yaml

**Comment by mvdbeek** [comment]
@natefoo @martenson can you have a look at this? probably a dependency issue on usegalaxy.org

**Comment by natefoo** [comment]
This was due to #5470, we updated Main after it was merged and this should be fixed now.
