### ISSUE TITLE
data_manager_twobit_builder dependency problem

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1741]
When running the twobit data manager (on a dev instance) I get the following error:

```
Fatal error: Exit code 127 ()
Error building index:
faToTwoBit: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
```

The problems appears to be that in the tool_script.sh the conda environment is not loaded but only the PATH is modified:

```
#!/bin/bash

# The following block can be used by the job system
# to ensure this script is runnable before actually attempting
# to run it.
if [ -n "$ABC_TEST_JOB_SCRIPT_INTEGRITY_XYZ" ]; then
    exit 42
fi
export PATH=$PATH:'/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/__ucsc-fatotwobit@324/bin' ; python '/gpfs1/data/galaxy_server/galaxy-dev/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_twobit_builder/9946bc39c834/data_manager_twobit_builder/data_manager/twobit_builder.py' '/work/songalax/galaxy-dev/database/jobs_directory/002/2994/galaxy_dataset_5751.dat' --fasta_filename '/data/genomes/ohrentiere/homo_sapiens/hg38.fa' --fasta_dbkey 'hg38' --fasta_description 'Human (Homo sapiens): hg38'
```

Could it be that this is because `$__tool_directory__` is used?

**Comment by mvdbeek** [comment]
Conda not being sourced is intentional, see https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L501.

```
faToTwoBit: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
```
this is probably because of https://github.com/bioconda/bioconda-recipes/issues/5430, and should be resolved with https://github.com/galaxyproject/conda-iuc/pull/14 -- once that is merged updating or reinstalling the dependencies should resolve the issue.

**Comment by bernt-matthias** [comment]
The line that you are referring to **seems** to be concerned with the python environment. But my question was regarding the conda environment. What would be the intension of not loading the conda environment? 

Since https://github.com/galaxyproject/conda-iuc/pull/14 will update to version 357 which wont help for the version used in this tool. Or will this be covered? 

Note: quick (and very dirty) fix: 

```
cd database/dependencies/_conda/envs/__ucsc-fatotwobit@324/lib/
ln -s libmysqlclient.so.20.3.7 libmysqlclient.so.18
```

**Comment by bgruening** [comment]
@bernt-matthias lets see if this fixes your problem: https://github.com/bioconda/bioconda-recipes/pull/8149

**Comment by bgruening** [comment]
@bernt-matthias new package is online. Can you remove your env and try again?

**Comment by bernt-matthias** [comment]
works. excellent. thanks a lot
