### ISSUE TITLE
mergeBed should have an option to collapse a collection of BED files into a single file

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-iuc#1745]
This would provide the common bedtools use pattern: 
```
$ cat A.bed B.bed C.bed | sort | uniq > ABC_Union.bed
```
(cc @bgruening)

**Comment by bgruening** [comment]
Why not using the cat Galaxy tool for this? Such a feature should be BED tools independent and valid for all tabular or text tools, correct?

**Comment by zfrenchee** [comment]
Thanks @bgruening !
