### ISSUE TITLE
package_fatotwobit_35x1 has bad download links

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/tools-iuc#175]
File: https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_fatotwobit_35x1/tool_dependencies.xml

refers to https://github.com/bgruening/download_store/raw/master/ucsc/...., which does not exist. 

Is in the MTS at https://toolshed.g2.bx.psu.edu/view/iuc/package_fatotwobit_35x1

Was going to use for devteam's twobit data manager.

**Comment by peterjc** [comment]
FAO @bgruening

**Comment by bgruening** [comment]
@blankenberg Urg, sorry. Some one from the dev team pointed out that I was not allowed to redistribute binaries for legal issues.

Nevertheless, we now build our own with docker-build: https://github.com/galaxyproject/docker-build/tree/master/ucsc

If you can convince @natefoo to upload all binaries into the depot, than I can update the tool dependencies.

**Comment by nitesh1989** [comment]
@natefoo Since, i'm new to this why can't we get the dependencies on the depot?

**Comment by blankenberg** [comment]
@nitesh1989 this should be resolved pretty soonish @bgruening and @natefoo are on it :)

**Comment by nitesh1989** [comment]
Awesome!

**Comment by nsoranzo** [comment]
What about using the new `package_ucsc_tools_312` in the dependent packages and deprecate this?

**Comment by bgruening** [comment]
Yes, this is the idea I guess.
What about if I copy and paste the content of `package_ucsc_tools_312` into this package as well to make it functional again.

**Comment by natefoo** [comment]
@bgruening Yeah, that effectively makes it a transitional package to `package_ucsc_tools_312`. Perhaps the new tools package should just become a dependency of this package?

**Comment by bgruening** [comment]
@natefoo do you know how to do so? I need to define a new package (`package_ucsc_tools_312`) but this needs to have the same name and version than `package_fatotwobit_35x1`. Is this possible?

**Comment by natefoo** [comment]
@bgruening Would a repository dependency from `package_fatotwobit_35x1` to `package_ucsc_tools_312` work?

**Comment by bgruening** [comment]
Afaik you can not put a repository dependency into a tool_dependency repository. Any the tool needs to <require> the package name and the version which is only given by a tool dependency.

**Comment by natefoo** [comment]
D'oh, you are right. Okay, then I don't have any good ideas.

**Comment by bgruening** [comment]
This was fixed in https://github.com/galaxyproject/tools-iuc/commit/71b21c57cc781e5a623d2550d4f704521e06d5be Can we close it?
