### ISSUE TITLE
Freebayes tool form has the option "--min-coverage" annotated as just "--coverage"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1752]
True still in the latest MTS version: 1.1.0.46-0

This option is included in a few places on the dynamic form. Not sure if I should adjust this myself or if this was left as "--coverage" on purpose? The command-line correctly uses "--min-coverage".

As an aside, this particular MTS repo or the MTS itself might have a problem (although this is the only tool that has presented the problem so far). I get an error when clicking on Freebayes to "view tool metadata".  The other tool bundled with this one (BamLeftAlign) clicks through fine. 

MTS repo: https://toolshed.g2.bx.psu.edu/view/devteam/freebayes/156b60c1530f

This is the error - can anyone else reproduce?

<img width="976" alt="screen shot 2018-03-01 at 4 15 23 pm" src="https://user-images.githubusercontent.com/8999735/36876909-4cbea3b0-1d6c-11e8-939b-975e9a302e0b.png">

**Comment by bernt-matthias** [comment]
Has been solved.
