### ISSUE TITLE
What about adding collection_column_join to the Collection Operations bundle?

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/tools-iuc#1788]
I only discovered the collection_column_join tool yesterday (thanks to seeing @jennaj mentioning it in Gitter) and what a revelation!!! I've been looking for a way to create a count matrix for ages and had tried a few of the join tools but they were pretty clunky to use with collections. 

Was wondering if the tool should/could be added to the **Collection Operations** bundle? As if it had been in that I would have found it ages ago. And am wondering if other people don't know about it and how super-useful it is for e.g. joining up the individual featureCounts files from collections into a matrix.

**Comment by bgruening** [comment]
@mblue9 this is a real tool, the other collection operation tools are shipped with Galaxy and are internal tools. So this issue needs to be raised on every particular Galaxy instance. Nothing IUC can do here. However, I changed this on usegalaxy.eu

**Comment by mblue9** [comment]
@bgruening I didn't phrase my question well, as what I was asking was - could this tool be adopted into the internal Galaxy Collection Operation tools instead of being like an orphan here? 

As the other collection operations tools work like real tools for me 😄 so I'm wondering why not just include this tool with those to reduce the overhead for admins? And I've been in and out of the iuc repo hundreds of times now and never noticed this gem of a tool so also wondering if others might miss it too.

**Comment by bgruening** [comment]
There are some technical differences. The tools included in Galaxy are not normal Galaxy tools, they rely heavily on Galaxy internals and are not versioned afaik. The tool you are referring here can work decoupled from Galaxy. I do understand that this is from a user-side not really visible and a user does not care, but we try to keep tools out of Galaxy as much as possible.
