### ISSUE TITLE
scipy installation fails on missing blas

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#18]
As a part of deepTools installation on Test Galaxy the scipy package needed to be installed and failed with the following error:
https://gist.github.com/martenson/b77145f404f52f0ddc7b

**Comment by bgruening** [comment]
@martenson I was referring to https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList and here liblapack and libatlas are listed.

**Comment by erasche** [comment]
This looks like one of the issues that'll be fixed with the new scipy/numpy packages. Now that those are on main is this fixed (or will we need to re-push deepTools in order to get the latest packages?)

**Comment by martenson** [comment]
This issue should be solved thanks to @natefoo 
https://trello.com/c/ST8ogif9/70-toolshed-platform-specific-atlas-builds

**Comment by erasche** [comment]
> Now that those are on main, is this fixed (or will we need to re-push deepTools in order to get them to point at the latest packages?)

**Comment by martenson** [comment]
@erasche to answer that somebody who knows what he/she is doing should test deeptols on Test Galaxy

**Comment by bgruening** [comment]
I will do this asap ... sorry.

**Comment by erasche** [comment]
@bgruening doesn't have to be deepTools, could be anything with a dependency on scipy/numpy. I don't know how the update mechanism works hence me asking about it.

**Comment by martenson** [comment]
I am making sure that Test Galaxy has the proper packages right now, stay tuned

**Comment by erasche** [comment]
okay, great, thanks @martenson!

**Comment by martenson** [comment]
so the scipy 0.12 still fails on missing blas :(
https://gist.github.com/martenson/8be91bb26e50e44848b7

**Comment by erasche** [comment]
this is for package_scipy_0_12 installation, or for something that depends on it?

**Comment by erasche** [comment]
This *should* be fixed with the recently pushed packages. I'll double check I suppose

**Comment by martenson** [comment]
this is for package_scipy_0_12

**Comment by erasche** [comment]
According to that gist, you're getting version `4:ef12a3a11d5b` of package_numpy, but numpy should be at `8:a4bdc17eed4a`

**Comment by martenson** [comment]
funny, admin ui shows only one installed numpy package and that is a4bdc17eed4a, let me dig into filesystem

**Comment by martenson** [comment]
I might have some more grey hairs but package_scipy_0_12 was succesfully compiled on Test Galaxy

**Comment by erasche** [comment]
Sorry that that was so painful for you! Glad to hear we can close this. Thanks for testing @martenson

**Comment by martenson** [comment]
@erasche lol, 's my jaaaab :)
