### ISSUE TITLE
Shovill: KMC cannot handle gzipped FASTQ with .dat file extension

### ISSUE THREAD

**Issue by peterk87** [galaxyproject/tools-iuc#1804]
I get the following error when trying to run Shovill with paired end `*.fastq.gz` files:

```
Estimating genome size with 'kmc'
Running: kmc -m4 -sm -n256 -ci3 -k25 -t1 \/export\/galaxy\-central\/database\/files\/000\/dataset_204\.dat kmc /tmp/sLnCCgp7rc >> 20-kmc.log 2>&1
Error 256 running command
```

It works when the files are uncompressed (`*.fastq`) or if the files are supplied with the original file extension preserved (i.e. `*.fastq.gz`).

Thanks!

**Comment by rec3141** [comment]
I solved this issue with `ulimit -n 2048` as per https://github.com/sanger-pathogens/iva/issues/63

**Comment by bgruening** [comment]
> It works when the files are uncompressed (*.fastq) or if the files are supplied with the original file extension preserved (i.e. *.fastq.gz).

@peterk87 if this is true we could easily enhance the Galaxy wrapper. Simply symlink the $library's at the top to some fixed name with file extension if its compressed fastq. Similar to here: https://github.com/galaxyproject/tools-iuc/blob/d127e451bbe9267768092f1d890ab1a147c3b2cf/tools/stacks/stacks_clonefilter.xml#L12

Also ping @Slugger70

**Comment by peterk87** [comment]
@bgruening I think that would be a good and simple solution for this issue. Thanks!

**Comment by pvanheus** [comment]
@peterk87 if I understand correctly this was fix was never implemented?

**Comment by tseemann** [comment]
That is an old version of Shovill, i switched to `mash` to avoid the pain `kmc` was causing.

**Comment by pvanheus** [comment]
The updated version of this problem - that affects Trimmomatic / the `--trim` options, is fixed by: https://github.com/galaxyproject/tools-iuc/pull/2531

**Comment by bernt-matthias** [comment]
Seems fixed
