### ISSUE TITLE
[Tool Request]: A GTF data manager

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-iuc#1807]
It would be nice to have a data manager for reference genome feature files. Otherwise, these need to be uploaded or kept in a special data library. The tool could probably just grab them from [ensembl](http://useast.ensembl.org/info/data/ftp/index.html/).

**Comment by jj-umn** [comment]
@zfrenchee   I've used https://toolshed.g2.bx.psu.edu/view/scottx611x/data_manager_fetch_gene_annotation/9346d2955707
Although, I don't think I was able to use an ftp ensembl URL.

**Comment by zfrenchee** [comment]
This seems like what I was looking for. I'm slightly confused that the code is in iuc but the author is @scottx611x. Oh well...
