### ISSUE TITLE
 MultiQC: does it work with HISAT2/STAR/any-RNA-seq-mapper and collections?

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/tools-iuc#1820]
Wondering if anyone here is using MultiQC with HISAT2? As I can't get it to work e.g. if I pass in a collection of HISAT2 (v2.1.0) summary files to MultiQC (v1.3) I just get an "empty" green output :( Would be great to be able to summarise the HISAT2 stats for collections of samples if possible. Or if not HISAT2, then STAR or another mapper, I'd take anything that works at this stage. If anyone's successfully summarising RNA-seq QC stats (mapped reads etc) for collections with MultiQC with any mapper please let me know!

**Comment by bgruening** [comment]
@mblue9 not sure about HISAT directly, but @bebatut is working on a new version here: https://github.com/galaxyproject/tools-iuc/pull/1821 - can you check if this one is working for you?

**Comment by mblue9** [comment]
ok good news...multiqc 1.5 looks like it works with hisat2 and collections hooray!! and thanks @bebatut for working on it :) 
I just tested it with a hisat2 summary file that gives an empty output with multiqc 1.3 if in a collection (although it works ok with 1.3 if just a dataset).
