### ISSUE TITLE
how to upload( and make) my custom app(star wrapper)

### ISSUE THREAD

**Issue by hpcdaumsoft** [galaxyproject/tools-iuc#1825]
I've created xml wrapper  using GDC STAR alignment tools.

I  saw the good result from this galaxy (SGE)  workflow processing.

and then I created git about that.

and so I want to upload to toolshed.g2.bx.psu.edu site

and then. I wanna install this  at other user's  local galaxy.

so... How to make upload file for toolshed.g2.bx.psu.edu.

thank you.

**Comment by bgruening** [comment]
Hi @hpcdaumsoft!

The easiest way today is to create a .shed.yml file and use our Galaxy SDK for this, called planemo. Documentation can be found here: http://planemo.readthedocs.io/en/latest/publishing.html

You can also upload by hand if you want, the toolshed interface supports this, but I would always recommend planemo.

**Comment by hpcdaumsoft** [comment]
Thank you for your answer.

I am trying this as you answer me.

but I found the error bellow.

Unexpected HTTP status code: 403: {"err_msg": "API authentication required for this request", "err_code": 403001}

That I try type command is  "planemo shed_create --shed_target testtoolshed"

how  can I do this...

**Comment by bernt-matthias** [comment]
Please follow up on 

https://gitter.im/galaxy-iuc/iuc or help.galaxyproject.org
