### ISSUE TITLE
Package package_networkx_1_10 does not install

### ISSUE THREAD

**Issue by moskalenko** [galaxyproject/tools-iuc#1833]
package_networkx_1_10 depends on 'python', but the installation does not proceed:

Missing tool dependencies - click the name to install the missing dependency
-- python | 2.7 | package | Never installed

Selecting the dependency for manual install does not cause any actions to happen.

This is a dependency of dunovo

**Comment by bgruening** [comment]
@moskalenko where is the source of dunovo? These packages should not be used and there is a dunovo bioconda recipes. So you should not need this package.

**Comment by bgruening** [comment]
A bioconda package is available so skip the tool_dependencies and take the bioconda one :) https://bioconda.github.io/recipes/dunovo/README.html

See here: https://github.com/galaxyproject/dunovo/pull/12

**Comment by moskalenko** [comment]
Trying to manually install dunovo into the galaxy-18.01 conda environment results in the following:

[galaxy@galaxy3 galaxy]$ conda install dunovo
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - dunovo -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by bgruening** [comment]
Galaxy should install this tool for you, in your admin panel you have a section called `manage dependencies` ...
If you really want to do this manually do this `conda install dunovo python=2.7 -c bioconda -c conda-forge`
