### ISSUE TITLE
query_tabular does not support "UPDATE t1 SET c1 = 'foo'" syntax

### ISSUE THREAD

**Issue by eschen42** [galaxyproject/tools-iuc#1840]
The validator for query_tabular's SQL field is:
```xml
  <validator type="regex" message="">^(?ims)\s*select\s+.*\s+from\s+.*$</validator>
```

This does not support INSERT, UPDATE, and DELETE queries.  I think this validation regex should do the trick:
```
(^(?ims)\s*select\s+.*\s+from\s+.*$)|(^(?ims)\s*update\s+.*\s+set\s+.*$)|(^(?ims)\s*insert\s+into\s+.*\s+values\s+\(.*\)$)|(^(?ims)\s*insert\s+into\s+.*\s+select.*\s+from\s+.*$)|(^(?ims)\s*delete\s+from\s+.*where\s+.*$)
```

I can code this up and make a pull request when I get around to it, unless someone gets around to it before I do.

**Comment by jj-umn** [comment]
@eschen42   I have thought that it would make sense to include more operations when the desired result is a modified database rather than a tabular file.   
Should there be additional SQL input text areas strictly for DB modification statements?
Should there be multiple SQL query text areas to produce multiple tabular outputs?

**Comment by eschen42** [comment]
@jj-umn I favor restricting the scope to querying and modifying the *data* (DML and DQL)), at least for **query_tabular** *per se*. 

Modifying the *schema* (DDL) may make sense for **sqlite_to_tabular**, but I think not in **query_tabular**.

I believe that Mark Esler looked into the possibility of having a variable number of output files and found that the Galaxy tool XML does not support it.  I am comfortable having to resort to composing a workflow if I need multiple tabular outputs.

On the other hand, it *might* be a reasonable idea, and possibly quite helpful, to compose multiple outputs into an SQLite database, so you could display multiple SQL fields only when "Save the sqlite database in your history" is 'Yes' -- but then you need to decide what the output tabular file should contain ... ugh.

It might be easier to understand a new **tabular_to_sqllite** tool for composing an SQLite database from tabular files, including options to set up indexes, constraints, etc..  That way you wouldn't clutter up the **query_tabular** tool with even more choices to (mis)understand.

**Comment by jj-umn** [comment]
@eschen42   I the updates in branch:  
 https://github.com/galaxyproject/tools-iuc/tree/query_tabular_3.0.0 
I still need to add tests.
If you have a chance, see if this solves the issues you wanted to address.
