### ISSUE TITLE
Change "Tool on data N" output file naming to something without spaces?

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/tools-iuc#1843]
I've just run into a few errors from the "Tool on data N" naming e.g. https://github.com/galaxyproject/tools-iuc/pull/1842 that turned out to be very helpful for identifying I needed to handle spaces better in the wrapper. But having spaces in filenames is not something to be encouraged imho (and I'm well aware that I'm one of the people currently propagating this!). I know spaces in input filenames could be replaced in the tool wrappers, but I was wondering if the recommended default naming could be something without spaces? And maybe include the `element_identifier` instead of (or in addition to) `on_string`? 

For example, in the mageck case could I change:

`${tool.name} on ${on_string}: sgRNA Counts`

to something like below (with underscore or dot or something-not-a-space separating):

`${tool.name}_${element_identifier}_sgRNACounts`

Although if the tool.name has spaces they'd also need replacing, or could the tool.id be used instead.

**Comment by mblue9** [comment]
Oops wrong repo! I meant to open this in the standards one. Can I move this? Or do I just close this and open it over there?

**Comment by bgruening** [comment]
You need to close this as long as you don't use a third party service.

**Comment by mblue9** [comment]
Ok thanks, I've opened it here now: https://github.com/galaxy-iuc/standards/issues/53
