### ISSUE TITLE
Mothur executable installation on galaxy

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/tools-iuc#1855]
Hi,

I'm not able to install properly the dependency of mothur_suite package:

- Using the toolshed packages_mothur_1_36_1:
I have a problem of installation of dependency due to the package legacy_blast

- Using conda, mothur executable is installed, but I get an error on execution:
toolshed.g2.bx.psu.edu/repos/iuc/mothur_make_contigs/mothur_make_contigs/1.39.5.0.
mothur: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

- Using the mothur package installed in the system, I'm not able to used it on galaxy.

Thanks in advance
Benoit

**Comment by bvalot** [comment]
Hi,

I have galaxy 17.09

I uninstall the packages_mothur_1_36_1 on toolshed and install dependency with conda (mothur 1.39.5).

When i run for example make.contigs command, I get the following message:
mothur: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
On the log, conda dependency seems correctly load for the job and the libreadline.so.6 is in the mothur executable environment.
 
```
galaxy.jobs.command_factory INFO 2018-04-30 09:36:32,686 Built script [/home/galaxy/dataset/jobs_directory/000/151/tool_script.sh] for tool command [[ "$CONDA_DEFAULT_ENV" = "/home/galaxy/galaxy_dist/database/dependencies/_conda/envs/__mothur@1.39.5" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . /home/galaxy/galaxy_dist/database/dependencies/_conda/bin/activate '/home/galaxy/galaxy_dist/database/dependencies/_conda/envs/__mothur@1.39.5' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; mothur "#help()" | sed '7q;d' | cut -d" " -f2 > /home/galaxy/dataset/tmp/GALAXY_VERSION_STRING_151 2>&1; set -o pipefail;  ln -s '/home/galaxy/dataset/imported_dataset/2018_metagenomics_lisa/F10-35_S338_L001_R2_001.fastq' ffastq.dat && ln -s '/home/galaxy/dataset/imported_dataset/2018_metagenomics_lisa/F10-35_S338_L001_R2_001.fastq' rfastq.dat &&   echo 'make.contigs( ffastq=ffastq.dat, rfastq=rfastq.dat, align=needleman, match=1, mismatch=-1, gapopen=-2, gapextend=-1, rename=True processors='${GALAXY_SLOTS:-8}' )' | sed 's/ //g' | mothur | tee `mothur.out.log]

```

**Comment by bernt-matthias** [comment]
I guess we can close this now.
