### ISSUE TITLE
FeatureCounts 1.6.0.3 requires database for bam files even when using GTF from history

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#1859]
When using a GTF file from history, the BAM files may not (in our case almost always) have a database sepecified, as they were aligned to a "custom" reference (i.e. not a built in one). The changes made to address #1754 make sense, but I think the requirement needs to be relaxed when using a GTF from history. I'm reverting back to 1.6.0.2 at the moment to get a working FeatureCounts tool. Unless there is some other solution? @blankenberg @bgruening @mblue9?

**Comment by bgruening** [comment]
Shouldn't we fix your mapper to annotate the BAM file correctly, if possible?

In general I think there should be a secret button in the tool form to relax the filtering, but I do see many advantages to have these strictly defined.

**Comment by lparsons** [comment]
@bgruening I don't understand? There is nothing wrong with the BAM files. (I'm using BWA-MEM, btw, a very common mapper). And there is no database to set, since they are mapped to a fasta file in history (a very common workflow for us). Either way, I'm completely unable to use FeatureCounts 1.6.0.3 right now unless the BAM was generated from a built in reference... :disappointed:

**Comment by nsoranzo** [comment]
@ethering reported the same problem to me yesterday.

**Comment by mblue9** [comment]
I've tried to fix this issue here: https://github.com/galaxyproject/tools-iuc/pull/1867

**Comment by bgruening** [comment]
@lparsons you can always set the dbkey manually, aren't you?
What I was proposing is to offer inside the mapping tool - when the user selects "reference from history" a select box to force also setting the dbkey.

**Comment by mvdbeek** [comment]
Honestly, '?' is a valid dbkey, so a `?` reference and `?` alignment files should work.
