### ISSUE TITLE
meme_chip cannot discover output index.html

### ISSUE THREAD

**Issue by borauyar** [galaxyproject/tools-iuc#1891]
Hi,
I have just recently installed the latest version of meme_chip (see https://toolshed.g2.bx.psu.edu/repository/view_changelog?id=b50902430e629c0e - Revision:  0:6095db402811) on our galaxy server. 

The tool works fine until the job is finished. I can see that the discovered motifs are printed into folders such as 'meme', 'dreme' etc. These outputs are printed under `database/job_working_directory`. Once the job is finished the outputs in this folder are collected and moved to `database/files` folder. 

The xml wrapper for the meme-chip runs this command: 
    
    ...
    #end if
    && rm '$output'
    && ln -s $primary_output '$output'

where `$primary_output` points to the parent folder `database/job_working_directory` and `$output` points to `database/files` as the parent folder. So, the last line in the command `$primary_output` assumes the output files are still under `database/job_working_directory`, however, in our case, during the linking step, the outputs are already moved to `database/files` folder. So, the linking doesn't work as expected. 

Does your `job_working_directory` point to `database/files` ? 

Have you had a similar problem? 

Thanks

**Comment by dpryan79** [comment]
I've just been hit with this too. Since the job working directory is removed upon job completion I get a bunch of broken symlinks and Galaxy tends to break.

**Comment by dpryan79** [comment]
I can't figure out a good way to fix this. There's a whole folder of output produced in the working directory that gets moved to the actual data directory on success. The symlink is supposed to then point to that, but of course `$primary_output` is in the working directory, since it hasn't gotten moved yet.
