### ISSUE TITLE
Binary version of atlas fails on recent gcc versions

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#190]
When installing a tool that requires scipy, numpy and atlas get installed.
When running a 64bit linux system, a precompiled version of atlas will be downloaded
from https://depot.galaxyproject.org/package/linux/x86_64/atlas/atlas-3.10.2-Linux-x86_64.tar.gz,
but when importing scipy on recent versions, this results in 
```
ImportError: /home/galaxy/tool_dependency/atlas/3.10.2/iuc/package_atlas_3_10/4778b172b895/lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/galaxy/tool_dependency/scipy/0.12.0/iuc/package_scipy_0_12/0d5ee829daaa/lib/python/scipy/special/_ufuncs.so)
```
My guess here is that atlas compiled on a different gcc version will just not be compatible.
I'm running gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) on the toolshed/requirements docker image.

**Comment by bgruening** [comment]
I know that @natefoo tried hard to make the gfortran compiler happy. Hopefully, he can help us here.

**Comment by natefoo** [comment]
Yeah, it looks like compiling with a newer gfortran and using the older bundled libgfortran is not going to work.

Out of curiosity, if you move `/home/galaxy/tool_dependency/atlas/3.10.2/iuc/package_atlas_3_10/4778b172b895/lib/libgfortran.so.3` out of the way, does everything work?

**Comment by mvdbeek** [comment]
Yes, it does work when deleting the file!

**Comment by natefoo** [comment]
So unfortunately I am not sure of a good solution for this problem. We could stop bundling libgfortran, but that would require that people have gfortran installed on their Galaxy cluster nodes, which will often not be the case and not be fixable by the Galaxy administrator for centrally controlled clusters.

**Comment by bgruening** [comment]
@natefoo can we detect libgfortran with some bash magic and copy the binary only if there is not libgfortran?

**Comment by natefoo** [comment]
That'd work for the Galaxy server, but the Galaxy server is going to need to have gfortran installed to install scipy anyway.

**Comment by bgruening** [comment]
@natefoo mh ... in this case we could always copy the `libgfortran.so` from the system into the `tool_deps` directory?

**Comment by natefoo** [comment]
@bgruening I am not sure if that will work in all cases, but it will probably be better than the current situation.

**Comment by bgruening** [comment]
Please share your doubts. We need to fix this :) Otherwise, we need atlas on all nodes.
Thanks @natefoo!

**Comment by natefoo** [comment]
I guess the concern is that the system version of libgfortran will be incompatible with the libatlas/libcblas/liblapack that are part of the atlas package. Although hopefully it'd only be true if libgfortran is *older* than the one on the build platform, which, being squeeze, is pretty ancient.

If we want to be really smart we could install the system one *only* if it's newer than the bundled one.

**Comment by bgruening** [comment]
You are really smart :)
