### ISSUE TITLE
VCFfilter (Galaxy Version 1.0.0_rc1+galaxy1) -- tool help is a mismatch versus the updated form query structure, impacts Coursera tutorials

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1910]
Example of current form usage:

<img width="733" alt="screen shot 2018-05-31 at 1 03 03 pm" src="https://user-images.githubusercontent.com/8999735/40805629-c18120a2-64d3-11e8-862f-ba4b69cf5436.png">

Associated tool form help:

<img width="334" alt="screen shot 2018-05-31 at 1 09 13 pm" src="https://user-images.githubusercontent.com/8999735/40805686-e61b2ee4-64d3-11e8-904f-70185cb9c835.png">

Users are confused with whether to quote the filter value or not (they shouldn't or the tool errors). An additional complication is that this tool is included in the Corsica classes and use the prior tool version with a different form (and those tools were completely replaced at usegalaxy.org due to bugs). Things change, but we can help in small ways like this.

Another option is to have the tool be smart enough to ignore quotes and/or clearly report what is wrong (the filter term) ... would address problems users had before and now when a filter was constructed incorrectly. Right now the tool doesn't state what went wrong (bug preview or in the full bug report or in job info stderr/stdout). Something like "Filter term is malformed, see the tool help for examples" would be useful.

This is what currently is reported, for any unexpected user entered "Specify filtering value" term. We get bug reports about this frequently.

```
Job Execution and Failure Information

Command Line
ln -s '/galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat' input1.vcf && bgzip input1.vcf && tabix -p vcf input1.vcf.gz && vcffilter        input1.vcf.gz > '/galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat'

stderr
Fatal error: Exit code 134 ()
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
/galaxy-repl/main/jobdir/XXX/XXX/XXX/tool_script.sh: line 41: 33442 Aborted                 (core dumped) vcffilter input1.vcf.gz > '/galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat'

stdout
(empty)

Job Information
None

Job Traceback
None
```

**Comment by jennaj** [comment]
Related, maybe should be considered together: https://github.com/galaxyproject/tools-iuc/issues/1917

**Comment by jennaj** [comment]
Above changes are for next rev.

PR for this versions updates: #1791

**Comment by VJalili** [comment]
The following PR may fix this issue: https://github.com/galaxyproject/tools-iuc/pull/2209

**Comment by jennaj** [comment]
Final testing once the PR is done, tool in MTS and updated on main will happen in this ticket: https://github.com/galaxyproject/usegalaxy-playbook/issues/182

IUC can close this one out once dev steps are done. Can reopen if later tests on Main fail that are tool related (not server related). Works in a local.

**Comment by jennaj** [comment]
1.0.0_rc1+galaxy2: https://toolshed.g2.bx.psu.edu/view/devteam/vcffilter/de885f4afb7f
