### ISSUE TITLE
Samtools Mpileup 2.1.3 metadata output problem with BCF format + warnings about options

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1921]
MTS: https://toolshed.g2.bx.psu.edu/view/devteam/samtools_mpileup/583abf29fc8e

Test history: https://usegalaxy.org/u/jen/h/test-history-mpileup-bcftools-call

Data 10 presents with the metadata problem if BCF is chosen as the output along with "uncompressed" set (uncompressed does not change to compressed when BCF is chosen instead of VCF). Is there a reason why this option is on the tool form? Couldn't it be hidden from the user? Choosing VCF implies uncompressed already, and BCF compressed. The user shouldn't need to specify this twice -- it leaves open an easy way to create a problematic output. If BCF/compressed are both set, the job is successful (Data 13).

<img width="426" alt="screen shot 2018-06-05 at 9 02 09 am" src="https://user-images.githubusercontent.com/8999735/40988484-0a9098f2-68a0-11e8-88e3-4d3a706f7ae5.png">
<img width="250" alt="screen shot 2018-06-05 at 9 02 26 am" src="https://user-images.githubusercontent.com/8999735/40988485-0aab6556-68a0-11e8-90b4-d535241ee8c6.png">
<img width="244" alt="screen shot 2018-06-05 at 9 02 45 am" src="https://user-images.githubusercontent.com/8999735/40988486-0ac76d8c-68a0-11e8-92b7-cf572f82167c.png">

Warnings in all outputs. Looks like the tool needs an update anyway. Maybe can add in the above at the next rev?

```
[warning] tag DPR functional, but deprecated. Please switch to `AD` in future.
[warning] tag DV functional, but deprecated. Please switch to `AD` in future.
[warning] tag DP4 functional, but deprecated. Please switch to `ADF` and `ADR` in future.
[warning] tag INFO/DPR functional, but deprecated. Please switch to `INFO/AD` in future.
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
```

Found during testing for https://github.com/galaxyproject/usegalaxy-playbook/issues/123
Update for `.org` tracked here: https://github.com/galaxyproject/usegalaxy-playbook/issues/133

**Comment by bernt-matthias** [comment]
In samtools 1.9 cvf/bcf output has been deprecated and I have removed it in https://github.com/galaxyproject/tools-iuc/pull/1973 from the galaxy tool. Users should use `bcftools`. If those are available and functional we could close the issue.

**Comment by jennaj** [comment]
Hi - was on break and catching up (everywhere ;)) 

This will need some dev input for main (usegalaxy.org). Deprecating tools is a bit complicated there. I'll create a distinct tracking ticket this week around the issue/solution and close this one out then. 

Thank you! @bernt-matthias

**Comment by bernt-matthias** [comment]
Its just the output that has been deprecated. Not the complete tool

`bcftools mpileup` seems available (even if not in the latest version) but it seems to have a reasonable implementation: https://github.com/galaxyproject/tools-iuc/blob/95f1ae4ed1cdd56114df76d215f9e1ed549aa4c5/tools/bcftools/macros.xml#L252

So I will close the issue, but feel free to reopen.
