### ISSUE TITLE
Cutadapt 1.16.1 bug -q incompatible with --format

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/tools-iuc#1934]
Hello,
I tried to run cutadapt with a fastq, a fastqsanger and a fastq.gz and I always have the message:
ERROR: Running in parallel is currently not supported for the given combination of command-line parameters.
These options are not supported: --info-file, --rest-file, --wildcard-file, --untrimmed-output, --untrimmed-paired-output, --too-short-output, --too-short-paired-output, --too-long-output, --too-long-paired-output, --format, --colorspace
Indeed, I found in the xml parser:
cutadapt

        -j \${GALAXY_SLOTS:-4}

        --format=$format

but in the documentation:
http://cutadapt.readthedocs.io/en/stable/guide.html
I found:
Additionally, the following command-line arguments are not compatible with multi-core:

        --format
        --colorspace

Thanks,

Lucille

**Comment by mvdbeek** [comment]
Ugh, thanks for the heads up @lldelisle! Luckily we don't actually need the format parameter here, I'll have a fix in a minute.
