### ISSUE TITLE
GATK update to 3.4

### ISSUE THREAD

**Issue by kaktus42** [galaxyproject/tools-iuc#194]
What do you think about updating?
There are a lot of improvements.
Someone already worked on this? Because I just started and didn't want to reinvent the wheel.
Also I'm not sure how thorough I can do it in the time window I have.

**Comment by bgruening** [comment]
Afaik, nobody of us is working on it. GATK licensing is not ideal and we have worked recently on other tools. If you want to help here this would be awesome! GAKT3 is now also matured enough I guess and the Best practise guide is not changing so much anymore.

I think we need a new datatype to support `.g.vcf` files.
Moreover, we implemented together with the GATK team a JSON descriptions of all parameters from all tools - available with every release. With this in place our idea was to generate these wrappers more or less automatically.

**Comment by kaktus42** [comment]
I found that in the gatk, a new bai is always generated when a gatk tool is started. This creates quite an overhead. Isn't there a better solution?
I guess this goes back to the datatype 'bam'. Where is the bai stored? How can it be accessed?
More on this also on the mailinglist "BAM datatype - bam & bai"

**Comment by erasche** [comment]
https://github.com/galaxyproject/tools-iuc/blob/0887009a23d176b21536c9fd8a18c4fecc417d4f/tools/bedtools/multiCov.xml see L12 of that file.

**Comment by kaktus42** [comment]
Ay. Perfect. Like a charm. That helps to tackle the issue I mentioned. :+1:

**Comment by matthdsm** [comment]
Hi all,

I too am interested in an updated version of the GATK wrappers. Any idea if there is time/motivation to write an update from your side?
Where can I find the before mentioned JSON description for the programs and is there any code already in place for the automated wrapper generation?

**Comment by kaktus42** [comment]
@matthdsm I'm currently working on the new GATK.
You can find it here: https://github.com/kaktus42/galaxytools/tree/master/tools/gatk

I have implemented so far:
* RealignerTargetCreator
* IndelRealigner

**Comment by bgruening** [comment]
@kaktus42 are you still interested on this? What we could support is a subset that we are allowed to redistribute. Please have a look at: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/gatk/3.5

If we are not allowed to redistribute I would say we can not guarantee reproducible and hence we can not put this into IUC.

**Comment by kaktus42** [comment]
Hi @bgruening - thanks for the update.
Unfortunately I'm not able to put more time into this currently
