### ISSUE TITLE
IUC member proposal - Matthias Bernt

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1993]
I would like to propose Matthias Bernt (@bernt-matthias) to become an IUC member.

Matthias has contributed a lot to IUC, GalaxyP, bgruening/galaxytools, the main Galaxy codebase, bioblend and many more. He is everywhere, highly motivated and produces high quality tools. I think he would enrich our team!

Please vote!
Bjoern

**Comment by shiltemann** [comment]
+1 from me :+1:

**Comment by bebatut** [comment]
+1

**Comment by nsoranzo** [comment]
:+1:

**Comment by mblue9** [comment]
definitely 👍

**Comment by nekrut** [comment]
+1

Anton

**Comment by Slugger70** [comment]
+1

**Comment by yhoogstrate** [comment]
:+1:

**Comment by blankenberg** [comment]
+1

**Comment by gregvonkuster** [comment]
+1

**Comment by davebx** [comment]
+1

**Comment by bgruening** [comment]
Welcome @bernt-matthias to the IUC! :)

**Comment by martenson** [comment]
@bernt-matthias I sent you an invite to the corresponding github team. Welcome!
