### ISSUE TITLE
gzipped input to fastx_trimmer results in incorrect output type

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/tools-iuc#2036]
We had a user try to run cutadapt on a file that had been output by fastx_trimmer.  fastx_trimmer had been run using a fastqsanger.gz type input file.  Its output file was labeled as type fastqsanger.gz even though the output was not gzipped, thus cutadapt failed, complaining "Not a gzipped file".

I believe the problem is that the output type is set via `format_source="input"` despite the fact that the output is plain ascii which is not subsequently gzipped.  Here are my notes in coming to this conclusion:

The command that was run as a result of the cutadapt tool was:

`ln -f -s '/galaxy/files/000/364/dataset_364994.dat' 'Trim-data7-1-50.fq.gz' &&    cutadapt      -a 'GeCKO-7-29'='TCTTGTGGAAAGGACGAAACACC'    --untrimmed-output=/galaxy/files/000/364/dataset_364997.dat   --output='out1.gz' --error-rate=0.15 --times=1 --overlap=18         --minimum-length=45     'Trim-data7-1-50.fq.gz'  > report.txt`

The input `Trim-data7-1-50.fq.gz` has `.gz` in the name (linked by `/galaxy/files/000/364/dataset_364994.dat`), but it isn't gzipped:

```
[rleach@lirone ~]$ more /galaxy/files/000/364/dataset_364994.dat
@JLK5VL1:1402:HKVYHBCX2:1:1101:1240:2158 1:N:0:
TTAGGCTCTTGTGGAAAGGACGAAACACCAAGATCTCCCAAACCCTCTTA
+
DDDDDIIIIIIIIIIIIIIIIHIHIIIIIIIIIIIIIIIIIIIIIIIIII
@JLK5VL1:1402:HKVYHBCX2:1:1101:1236:2185 1:N:0:
CAGATCTCTTGTGGAAAGGACGAAACACCGAGCATCCGCTCTGTCATCCC
+
...
```

It's type listed in the user's galaxy history is `fastqsanger.gz`.

That file was produced by:

`zcat -f '/galaxy/files/000/364/dataset_364978.dat' | fastx_trimmer -v -f 1 -l 50 -o '/galaxy/files/000/364/dataset_364994.dat'   -Q 33`

The fastx_trimmer tool defines the output as:

`<data name="output" format_source="input" metadata_source="input" />`

According to the documentation, `format_source="input"` means "data type is the same as that of the input dataset".

The command in the XML is preceded by `@CATS@` which is a macro that added the zcat command, and it's followed by `@FQQUAL@`, but there's no conversion of the plain ascii output in that macro to convert the output back to gzip format, thus the output file improperly gets the type `fastqsanger.gz` without any type of corresponding conversion.

A quick fix would be to edit the datatype from `fastqsanger.gz` to `fastqsanger`.  But the real fix would be to correct the wrapper to account for gzipped input formats when creating the output format.

**Comment by mblue9** [comment]
Thanks for the report @hepcat72 !
I've tried to fix this issue in the PR here: https://github.com/galaxyproject/tools-iuc/pull/2042

**Comment by mblue9** [comment]
This should be fixed now @hepcat72 but let us know if not.
