### ISSUE TITLE
velvetoptimizer tests not running

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2038]
just wanted to add an option for one of our users, but could not run the available test: 

```
Fatal error: Exit code 2 ()
Can't locate VelvetOpt/Assembly.pm in @INC (you may need to install the VelvetOpt::Assembly module) (@INC contains: ENV/bin ENV/lib/site_perl/5.26.2/x86_64-linux-thread-multi ENV/lib/site_perl/5.26.2 ENV/lib/5.26.2/x86_64-linux-thread-multi ENV/lib/5.26.2 .) at ENV/bin/VelvetOptimiser.pl line 37.
BEGIN failed--compilation aborted at ENV/bin/VelvetOptimiser.pl line 37.
```
(replaced the long path to the environment by ENV)

the pm file is actually at `lib/perl5/site_perl/5.22.0/VelvetOpt/Assembly.pm`

So the INC path seems to miss something. 

Also strange is that two perl versions are installed.

```
    perl:                 5.26.2-h470a237_0 conda-forge
    perl-threaded:        5.22.0-13         bioconda   
```

And the INC path contains 5.26 stuff while the missing module contains 5.22...?

Since the test ran in the past I document the problem here, even if I guess that the problem is the conda package.

**Comment by bgruening** [comment]
You can fix this if you add perl=5.22 into the requirements I guess.
perl-threaded is a dummy package that installs perl. Unfortunately, just perl and not perl=5.22.

**Comment by bernt-matthias** [comment]
Hi @bgruening . Just tried to add perl=5.22 to the tool's requirements .. without success. I guess the velvet-optimizer conda packages needs fixing since even the command defined in the conda test does not run. 

I could try to fix it, but I have no experience with conda packages (is there a short tutorial/howto on how to test local conda packages?). Otherwise I could ask the maintainers of velvet-optimizer.

**Comment by bgruening** [comment]
@bernt-matthias please see the linked PR

**Comment by bernt-matthias** [comment]
I guess https://github.com/galaxyproject/tools-iuc/pull/2045 fixed this
