### ISSUE TITLE
FASTQ quality shifting in seqtk seq etc

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#204]
``tools/seqtk/seqtk_seq.xml`` contains:

```
<param checked="false" label="shift quality by '(-Q) - 33' " help="(-V)" name="V" type="boolean" falsevalue="" truevalue="-V"/>
```

I think this ``-V`` option should not be a user facing parameter, but automatic when using the ``fastqillumina`` file format.

See also https://github.com/galaxyproject/planemo/issues/252 where this is used in the planemo documentation.

**Comment by erasche** [comment]
@peterjc you're absolutely correct!

**Comment by erasche** [comment]
@peterjc, I don't suppose you have an example of checking format that you could point me at? I don't see format documented on the cheetah section, and I've forgotten where I've seen examples of such checks before.

**Comment by peterjc** [comment]
Not quite this use case, but I do some file-format specific Cheetah in the ``<configfile>`` tag for the MIRA4 wrapper:

* https://github.com/peterjc/pico_galaxy/blob/master/tools/mira4_assembler/mira4_de_novo.xml
* https://github.com/peterjc/pico_galaxy/blob/master/tools/mira4_assembler/mira4_mapping.xml

(MIRA itself works out the FASTQ flavour, so I don't have to tell it Sanger vs Illumina).

**Comment by erasche** [comment]
Ah, brilliant, thanks!
29. jul. 2015 10.07 skrev "Peter Cock" <notifications@github.com>:
