### ISSUE TITLE
License policy?

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/tools-iuc#2054]
After a brief chat in gitter, it seems like it would be worthwhile to have a conversation here about whether or not to have some guidelines about tool licenses for things wrapped by IUC.

I could not find an explicit policy, but maybe there should be one - or an explicit statement that there is no policy.

Should IUC tools be licensed with an [OSI approved](https://opensource.org/licenses) license?

**Comment by bwlang** [comment]
@nsoranzo , @martenson 
Here is the github issue we discussed.

**Comment by mblue9** [comment]
Good idea @bwlang ! 

The EGSEA Bioconductor tool I wrapped uses KEGG data and I just added the KEGG licence info to the help (https://github.com/galaxyproject/tools-iuc/pull/1686/commits/5b6dcd1fac8cce0d7f66b2cdacd0f0414d90f6a7) and copied meme's "Non-commerical use" button (https://github.com/galaxyproject/tools-iuc/pull/1686/commits/2a948d2eeea319dd5fca3911547017b3b4b35882) but not sure now if that was the right way to handle that?

**Comment by peterjc** [comment]
If we restricted ourselves to only OSI approved licenses, a lot of problems go away. I am sympathetic to this goal. Popular but not open source tools could still be in the tool shed of course, but perhaps restricting iuc-tools in this way is too idealistic?

Related to this, I assume everything the IUC is accepting nowadays has a conda package, which means the underlying tool is sufficiently openly licensed to allow for packaging, redistribution and automated installation.

(See e.g. https://github.com/bioconda/bioconda-recipes/issues/6456 where Pear was originally available like that, but was later put under new terms and this was no longer possible).

If so, we're talking about if we should accept tools which can be packaged and installed - but come with usage restrictions (like no commercial use without buying a license).

On an aside, should the Tool Shed be exposing the license information of dependencies more explicitly - especially anything not OSI approved?

**Comment by bwlang** [comment]
I should have mentioned... I apologize in advance for bringing up a thorny issue. While it's annoying and potentially contentious  - I'm sure there will be civil discourse in this community of wonderful people ;)

Great discussion so far. binary categorization is always easier, but  as @peterjc says, specific situations can be more nuanced.  Maybe it's worth mentioning more interesting examples (like the KEGG one, meme) to get a scope of the issue and consequences of a decision.

Maybe also worth mentioning examples like kallisto and gatk which are now, but were not always, OSI open-source. Did limited availability due to their closed licenses influence relicensing decisions?

**Comment by bwlang** [comment]
I just noticed this in the PR guidelines:
License permits unrestricted use (educational + commercial)

Maybe we already have and OSI policy...  I've pr'd a change to update CONTRIBUTING.md

**Comment by peterjc** [comment]
Closed via #2102
