### ISSUE TITLE
stacks upgrade

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2073]
I guess stacks will be the next on my TODO list. 

- seems that there is OpenMP support which is not enabled in the Galaxy tools yet
- there are newer versions 1.48 and 2.2

Would appreciate some comments before I start. @lecorguille @bgruening :)

- should I go directly for stacks 2.2 .. or is this something completely new .. will also depend a bit on much time I have
- bioconda contains only 2.1 so far
- any experience with OpenMP?

**Comment by lecorguille** [comment]
ping @abretaud 

@bernt-matthias 
There are new versions of stacks every 2 months and sometime 2 within a month so by the end of your review we should have the 2.3 or 2.5
It seems that there isn't drastic change in the UI between 1.x and 2.x but I haven't really used stacks since the 1.46 so ...
No experience with OpenMP. But is it really something you need to care about?

**Comment by bernt-matthias** [comment]
> There are new versions of stacks every 2 months and sometime 2 within a month so by the end of your review we should have the 2.3 or 2.5 
> It seems that there isn't drastic change in the UI between 1.x and 2.x but I haven't really used stacks since the 1.46 so ...

Good to know. Then I could go for 2.x. If there are only minor changes in upcoming versions then it should be easy to incorporate during the PR (or OK to ignore them). 

> No experience with OpenMP. But is it really something you need to care about?

Users were complaining about run time. Parallelization was one thing that I was thinking about.

**Comment by bernt-matthias** [comment]
Actually I was wrong about parallelization, its already supported by the wrappers.

**Comment by lecorguille** [comment]
> Actually I was wrong about parallelization, its already supported by the wrappers.

Actually, some steps are multi-threaded (`cstacks`) but the other take or should take dataset collection and run the data individually in batch (`ustacks`, `gstacks` and `sstacks`)

On the other hand, the "wrappers scripts" (not the Galaxy one) `denovomap` and `refmap` just lauch the individual steps and aren't so efficient for the parallelisation.

**Comment by bernt-matthias** [comment]
It seems that also u, g, and sstacks take a threads parameter, so I guess they run parallel and in batch.

**Comment by lecorguille** [comment]
Indeed :)

**Comment by bernt-matthias** [comment]
step1: https://github.com/bioconda/bioconda-recipes/pull/10942

**Comment by bernt-matthias** [comment]
started also step2: https://github.com/galaxyproject/tools-iuc/pull/2085 comments welcome

**Comment by bgruening** [comment]
Thanks @bernt-matthias! Stacks in now available and I restarte #2085

**Comment by bernt-matthias** [comment]
Boah. There seem to be so many changes in stack 2.x. Some programs are gone (eg genotypes) and many parameters are new and others gone, some are marked as not implemented ... populations -P seems to expect some catalog.gz file .... 

Is there some experienced user that could point me to some docs or provide some command lines + tests data that I could use as starting point. 

Anyway. I guess this will result in in new wrappers ..

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/tools-iuc/pull/2085
