### ISSUE TITLE
planemo lint samtools_fastx KeyError: 'filter_options'

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#2078]
Recent builds on my fork are failing linting in samtools_fastx e.g. https://travis-ci.org/peterjc/tools-iuc/builds/428090446 

```
Linting repository /home/travis/build/peterjc/tools-iuc/tool_collections/samtools/samtools_fastx
Error loading tool with path /tmp/planemo_tmp_l18Mte/e1002ebca513b874bbf929dfd207eb5a/samtools_fastx/samtools_fastx.xml
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/galaxy/tools/loader_directory.py", line 108, in _load_tools_from_path
    tool_element = loader_func(possible_tool_file)
KeyError: 'filter_options'
```

From the timing, this is likely due to planemo v0.55.0 CC @jmchilton

**Comment by jmchilton** [comment]
filter_options is a macro being expanded in that wrapper that doesn't appear to exist in the imported macros file. I'm not sure this in a Planemo problems - still trying to figure it out though...

**Comment by jmchilton** [comment]
Yeah - the macro was dropped in https://github.com/galaxyproject/tools-iuc/commit/61fa60268a971c7780ef16aef26338893a6d0528#diff-f1a57e162ec79ef340c18b909a8140c3 but is still referenced in that fastx wrappers.

**Comment by peterjc** [comment]
It looks like the new macro ``flag_options`` values are subtly different, so I don't know if the fastx wrapper should use that or not...

**Comment by jmchilton** [comment]
Ping @bernt-matthias maybe?

**Comment by bernt-matthias** [comment]
Linting and testing seems successful. I guess this was only temporary (I remember that there was some confusion with macro renaming when the separate PRs were processed). 

Just also made sure that `filter_options` is now absent.
