### ISSUE TITLE
SRA-tools --table option

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/tools-iuc#2105]
Hello,

fastq-dump step for SRA-tools download has an option `--table` which is not exposed to the galaxy wrapper. This option is crucial for noisy long-reads, otherwise the output is empty with a message like in std-err:

>Rejected 101233 READS because READLEN < 1
Read 101233 spots for SRR6982805
Written 0 spots for SRR6982805

Further info can be found in this discussion forum: http://seqanswers.com/forums/archive/index.php/t-58456.html

A test of a sample SRA entry can be found here: https://usegalaxy.org/u/miladi/h/testsra-longreads

**Comment by mmiladi** [comment]
ping @bgruening @shiltemann

**Comment by lldelisle** [comment]
It is now added.

**Comment by bernt-matthias** [comment]
closed via https://github.com/galaxyproject/tools-iuc/pull/2541
