### ISSUE TITLE
tool versions

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2119]
As described in the [guidelines](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html?highlight=version#tool-versions) Galaxy tool version should derive from the version of the actual tool. 

Are there guidelines/suggestions for older tools where the version of the Galaxy tool already departed from the version of the underlying tool. 

Examples: 
- FastQC 0.11.7 is Galaxy tool version 0.72 
- Samtools sort 1.9 is Galaxy tool version 2.0.2 

For instance we could decide to increase only minor tool version until the actual tool catches up (which might work for some tools).

**Comment by peterjc** [comment]
That might be a sensible approach, but in some cases it will never catch up.

**Comment by bernt-matthias** [comment]
Sound good.
