### ISSUE TITLE
not all samtools in toolshed 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2134]
I noticed that some of the new samtools (eg depth and merge) did not made it to the toolshed. 

I also could need some help with the definition of a suite for samtools here: https://github.com/galaxyproject/tools-iuc/pull/2110 I tried to have a central shed.yml file but failed horribly :)

**Comment by nsoranzo** [comment]
I've manually pushed `samtools_merge` to the toolshed after fixing its `.shed.yml` in commit 14e40d55fe03f5f966fbaa308c8276da1214dc9d .

Instead `samtools_depth` lacks its `.shed.yml` file, can you open a PR to add it?
