### ISSUE TITLE
package_openssl download URL is broken

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#215]
The URL https://www.openssl.org/source/old/1.0.2/openssl-1.0.2a.tar.gz no longer works.

Perhaps this would be a more stable alternative: https://www.openssl.org/source/old/1.0.2/openssl-1.0.2a.tar.gz

However, perhaps this should be updated to a more recent version? https://www.openssl.org/source/openssl-1.0.2d.tar.gz

**Comment by erasche** [comment]
Will add to #213

**Comment by yhoogstrate** [comment]
If I remember correctly, this package has had the same problem before, and will have it probably again.

A patch is good, but manually patching the URLs is not a sustainable solution I think.

There was some discussion about openssl here: https://github.com/galaxyproject/tools-iuc/issues/168

**Comment by erasche** [comment]
Closing now that openssl has been removed as a TS dependency. Packages probably need to be re-pushed.
