### ISSUE TITLE
cutadapt fails for list:paired 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2155]
Strange and confusing observation. First the confusing part 

When choosing `paired end collection` as input the tool actually expects pair (`type="data_collection" collection_type="paired"`).  This seems confusing for the user.

Strange part is that Galaxy also allows to input a paired collection (`list:paired`) which makes everything crash. I find `KeyError: 'Dataset collection has no element_identifier with key forward.'` in the logs.

To me this seems as a galaxy (I'm using dev, but a few months old) and a tool bug?

**Comment by mvdbeek** [comment]
This is the expected Galaxy behavior, everything except the crash is normal.
Can you explain what is the unexpected behavior?
Probably isn't a good idea to do tests on dev, certainly old versions of it.

**Comment by bernt-matthias** [comment]
You are right. Also checked with planemo.

> Probably isn't a good idea to do tests on dev, certainly old versions of it.

Also has its advantages :) But I certainly need to update.
