### ISSUE TITLE
NCBI SRA tool fastq-dump fails when extracting BAM from SRA archive

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2171]
**Tool:** Download and Extract Reads in BAM format from NCBI SRA (Galaxy Version 2.8.1.3)
**MTS:** https://toolshed.g2.bx.psu.edu/view/iuc/sra_tools/c38286ea7047

***Note**: This related tool works, for all three extraction types (`fastqsanger`, `.gz`, `.bgz`. Didn't test split again (an open related issue, below). Download and Extract Reads in FASTA/Q format from NCBI SRA (Galaxy Version 2.9.1.3)

**Issue:** Fails when extracting from sra archives

**Test histories:**
 - https://usegalaxy.org:/u/jen/h/test-history-ncbi-tools---sra
 - https://usegalaxy.eu/u/jenj/h/test-history-ncbi-tools---sra

**Error for BAM extract (at both ORG and EU), the command line example is for ORG:**

<img width="726" alt="screen shot 2018-11-08 at 1 17 31 pm" src="https://user-images.githubusercontent.com/8999735/48228235-83585980-e359-11e8-9702-57fa74afcfe2.png">
<img width="735" alt="screen shot 2018-11-08 at 1 17 42 pm" src="https://user-images.githubusercontent.com/8999735/48228236-83585980-e359-11e8-9f83-d2fdf0daa4ae.png">
<img width="850" alt="screen shot 2018-11-08 at 1 18 20 pm" src="https://user-images.githubusercontent.com/8999735/48228237-83f0f000-e359-11e8-9dde-36843601744b.png">

Other related issues (closed): SRA to fastq error https://github.com/galaxyproject/tools-iuc/issues/918 **I'll add this test to the existing histories then update back here.**

Other related issues (open): SRA-tools FASTQ dump fails when using a file list https://github.com/galaxyproject/tools-iuc/issues/970 && Bug: SRA tools -fastqdump not splitting PE reads https://github.com/galaxyproject/tools-iuc/issues/1099

History of recent changes: https://github.com/galaxyproject/tools-iuc/commits/master/tools/sra-tools

Not sure who usually debugs these ... ping @blankenberg @wm75 @pvanheus @bwlang

**Comment by wm75** [comment]
@jennaj @martenson version 2.8.1.3 shouldn't even be installed on main anymore (see https://docs.galaxyproject.org/en/release_18.09/releases/18.09_announce.html#security).
The sra_tool suite needs to be updated to the latest versions on main.
2.9.1.3 is the current version of for sam_dump and fastq_dump and, at that version, both tools should work as expected.
There are remaining problems though with the functionality of the third of the sra_tools, sra_pileup (the tool currently works only with a single accession number), which would have to be addressed at some point.

**Comment by wm75** [comment]
Ah, I stand corrected! Even with the latest version, this particular function of sam_dump is still not working.
Just as you reported, fastq_dump is working though.

**Comment by wm75** [comment]
So to summarize: both sam_dump and sra_pileup need some love (sra_pileup a bit more) to bring them to the same level of functionality as fastq_dump. All three wrappers require some additional tests covering all supported input sources.
All three tools need to be updated on main.

**Comment by jennaj** [comment]
@wm75 

I'll make a request to update the NCBI tools at Main and link that back for context. 

Would you be able to create a ticket that describes what is needed for the tools? Even if generalized (but include what you know!), let's not lose the info in here and get it on the radar for prioritization in a distinct ticket (or tickets, you decide how to break it down, can always link them together). Often distinct tickets per change are easier to track/work on/resolve. Can always be merged into the same PR at the end (or not) -- incremental changes simplify things: eg: 1) add test cases; 2) the next fix; 3) the next after that; 4) perfection!

Thank you!!

**Comment by jennaj** [comment]
@Delphine-L this ticket explains the details for what is needed re: https://github.com/galaxyproject/usegalaxy-playbook/projects/2#card-14811780

**Comment by jennaj** [comment]
Retesting extract from sra archive with all current tools updated from #177 

test history, data 47 (sra archive retrieved with EBI SRA) + data 48-53 bam/sam/fastq/fastq.gz/fastq.bgz/pileup https://usegalaxy.org:/u/jen/h/test-history-ncbi-tools---sra 

Looks like pileup is failing, not sure if should or not (data 53)

**Comment by jennaj** [comment]
@Delphine-L Extracting from sra archive works for all fastq + bam/sam now in latest version on main.

Pileup does not. Do you want a different issue ticket for that or just track it here?

**Comment by jennaj** [comment]
@Delphine-L decided to remove extract pileup tool from main.

@davebx will do that in https://github.com/galaxyproject/usegalaxy-playbook/issues/181

Closing out this issue!
