### ISSUE TITLE
package_bowtie2_2_2_5 binaries don't work on CentOS5

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#219]
Attempting to execute `bowtie2-align-s` results in the following errors:

```
bowtie2-align-s: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by bowtie2-align-s)
bowtie2-align-s: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by bowtie2-align-s)
```

**Comment by erasche** [comment]
`:|`

Ping @natefoo @davebx https://github.com/galaxyproject/docker-build/tree/master/bowtie2

**Comment by lparsons** [comment]
BTW: The compiled version downloaded directly from http://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.2.5/bowtie2-2.2.5-linux-x86_64.zip/download seems to work OK.
