### ISSUE TITLE
What needs to be done for snapped/snpsift v4.0 to be put on main toolshed?

### ISSUE THREAD

**Issue by jj-umn** [galaxyproject/tools-iuc#22]

**Comment by bgruening** [comment]
@martenson can we put them online?

**Comment by bgruening** [comment]
@martenson I have create a few shed.yml file for you: https://github.com/galaxyproject/tools-iuc/pull/25 Are we ready to get this into the Tool Shed? We can also do the upload.

**Comment by jj-umn** [comment]
Upload to toolshed would be great.

**Comment by jj-umn** [comment]
Wait with toolshed update!
I've just been looking at SnpEff version 4.1  and it again has a new format for reference data.   
So I plan to revise all the *.loc tables to include the snpeff version so that they can be filtered by version.  
It also means the the datatype for a downloaded database needs to be versioned.  Ideally, a DataToolParameter would allow filters on dataset metadata, i.e. "snpeff_version" = "SnpEff 4.0", so that only a new datatype subtype would not be required for each version update.

**Comment by jj-umn** [comment]
@bgruening @nsoranzo  
I updated SnpEff with tool_data_tables that should enable those to be used across multiple snpeff versions.

**Comment by bgruening** [comment]
@jj-umn this is great! You are the real master of data-managers! :+1: 
Two questions:
* do we want to move the datatypes into Galaxy
* do we want to push the 4.0 version to the ToolShed or do we skip it and release 4.1

@nekrut agreed to store the databases in the Galaxy depot. And I try to make this happen as soon as possible.

**Comment by jj-umn** [comment]
I think the base datatype with the snpeff.py code should be stable enough now.  
( This uses a pattern that may be general enough for snpeff, bwa, bowtie, etc. to warrant having a base class for any such tool that needs a directory of files, and a means of generating the path to that data recognizable by the application.  )

The only way I know of currently to restrict dataset inputs is by subclassing SnpEffDb for each version.  Is that something that should be maintained in the datatype in Galaxy as well?   That may be easier than frequent updates to a toolshed snpeff_datatypes or a new repository dependency each time, but either should work.

**Comment by nsoranzo** [comment]
>     do we want to push the 4.0 version to the ToolShed or do we skip it and release 4.1

I'd say we skip 4.0.

**Comment by jj-umn** [comment]
I vote that we push version 4.0.   
Version 4.1 switches to ANN named annotations and and uses a new version of ANTLR  so it will need some verification for SnpSift as well.   So that may require some time.  Whereas I think the 4.0 version should be ready now.

**Comment by blankenberg** [comment]
@jj-umn You can have a metadata value associated with the dataset and filter against that for DataToolParameters. For example, I added a filter for the gemini tools that will look at the gemini version from the dataset's metadata (parsed from the .sqlite database) and only list datasets with versions that match the version accepted by that version of the tool, e.g.: https://github.com/galaxyproject/tools-iuc/blob/master/tools/gemini/gemini_macros.xml#L119 and https://bitbucket.org/galaxy/galaxy-central/src/292aa159ad5b429393c7bd9855bfe28d4eb39cd3/lib/galaxy/datatypes/binary.py?at=default#cl-646.

**Comment by jj-umn** [comment]
@blankenberg Excellent!   Thanks for the example.

**Comment by jj-umn** [comment]
@bgruening @blankenberg  @nsoranzo 
Updated pull request with DataToolParameter filter as suggested by Dan.

**Comment by jj-umn** [comment]
@bgruening   @martenson 
merged bgruening pull request and updated package_snpeff_3_6,  package_snpeff_4_0, and package_snpeff_4_1 to modify the snpEff.config upon install to pull databases from: https://snpeff-data.galaxyproject.org/databases

Can we install this on the main toolshed now?

**Comment by martenson** [comment]
@jj-umn I am on it.

**Comment by jj-umn** [comment]
On 1/20/15 10:29 AM, Marten wrote:
>
> @jj-umn <https://github.com/jj-umn> I am on it.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/galaxyproject/tools-iuc/issues/22#issuecomment-70683724>.
>
I forgot to say so, but probably needs to be done in this order for default changesets:

    https://github.com/galaxyproject/tools-iuc/tree/master/datatypes
    https://github.com/galaxyproject/tools-iuc/tree/master/packages
    https://github.com/galaxyproject/tools-iuc/tree/master/data_managers
    https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections

    -- 

James E. Johnson Minnesota Supercomputing Institute University of Minnesota

**Comment by jj-umn** [comment]
@martenson @bgruening  I uploaded these to the IUC account on the toolshed this AM.

**Comment by martenson** [comment]
@jj-umn I cannot find e.g. package_snpeff_4_1  on either of the Tool Sheds. Am I missing something?

**Comment by jj-umn** [comment]
@martenson   I haven't uploaded that package as yet.  Once I make sure the 4.0 versions of the tools are working, I'll look into updating them to v4.1

**Comment by martenson** [comment]
@jj-umn Ahh. Sorry for the confusion then. Let me know when you are ready and I will help you with the hassle of uploading to the TS.
