### ISSUE TITLE
heatmap2 - missing option between versions

### ISSUE THREAD

**Issue by bagnacan** [galaxyproject/tools-iuc#2274]
Dear IUC,
heatmap2 version 2.2.1+galaxy1 is missing the advanced option "log transformation" that is instead present in tool version 2.2.1. I noticed this while testing [this workflow](https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/ref-based/tutorial.html) on on usegalaxy.eu.
Can this be corrected? Thanks for your time

**Comment by nsoranzo** [comment]
The option should be still there, just renamed to "Data transformation".

**Comment by bgruening** [comment]
Closing this @bagnacan please let me know if you still have this problem.

**Comment by bagnacan** [comment]
Thanks! Sorry, I didn't see it under the renamed field
