### ISSUE TITLE
heatmap2 - could it be removed from the ggplot suite?

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/tools-iuc#2275]
heatmap2 is currently part of the ggplot2 tool suite (here: https://github.com/galaxyproject/tools-iuc/blob/master/tools/ggplot2/heatmap2.xml), however, heatmap2 is not part of the R ggplot2 package, it's a function from a completely separate and unrelated R package called gplots. In the IUC ggplot2 tool suite there's also a separate tool called ggplot_heatmap (here: https://github.com/galaxyproject/tools-iuc/blob/master/tools/ggplot2/ggplot2_heatmap.xml). I think this may be confusing to users so wondering if heatmap2 could be made into a separate tool or if that would that break too many things?

ping @MoHeydarian

**Comment by MoHeydarian** [comment]
Thanks for opening this issue, @mblue9. I agree that this will be confusing to users and also troublesome for citing usage.

What is the best way to fix this, IUC?

**Comment by bgruening** [comment]
That should be no problem. As far as I can see only one macro is shared, so this could be copied. But we probably want to keep the tool-id stable and this tool-id is, unfortunately `ggplot2_heatmap2`.
But if it helps I think we can easily move this XML out into a separate folder.

**Comment by mblue9** [comment]
Ok great. I'll fix that when I get a chance.
