### ISSUE TITLE
edgeR comparison output file

### ISSUE THREAD

**Issue by bimbam23** [galaxyproject/tools-iuc#2283]
I think there might be a small bug in the output file. The one that provides the FDR, logFC,... If you change the correlation method of the FDR calculations (P-Value Adjustment Method) it doesn't change the output table but the plot are different. Is that wanted?

**Comment by mblue9** [comment]
Thanks for reporting that @bimbam23, I've submitted a fix for it here:https://github.com/galaxyproject/tools-iuc/pull/2284

**Comment by mblue9** [comment]
That fix is merged so this should be fixed, let us know if not.
