### ISSUE TITLE
package_freetype_2_4: error downloading source

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#229]
I have gotten a connection refused or connection timed out error for the past few days attempting to install package_freetype_2_4 from the URL: http://downloads.sourceforge.net/project/freetype/freetype2/2.4.11/freetype-2.4.11.tar.bz2

**Comment by nsoranzo** [comment]
The URL is correct, seems to be a SourceForge problem.

**Comment by lparsons** [comment]
Ahh... SourceForge... :disappointed:

**Comment by erasche** [comment]
I get a timeout, let's switch to http://download.savannah.gnu.org/releases/freetype/freetype-2.4.11.tar.bz2 since they have full archives of all downloads: http://download.savannah.gnu.org/releases/freetype/

**Comment by lparsons** [comment]
Awaiting push to TS

**Comment by bgruening** [comment]
Pushed!

**Comment by lparsons** [comment]
Fixed!

**Comment by bgruening** [comment]
Strike!
