### ISSUE TITLE
multiqc galaxy - multiqc not found

### ISSUE THREAD

**Issue by mpaya** [galaxyproject/tools-iuc#2295]
Just installed MultiQC 1.7 and got the following error message.
```
Fatal error: Exit code 127 ()
/export/galaxy-central/database/job_working_directory/002/2676/tool_script.sh: line 25: multiqc: command not found
```
Not sure if multiqc isn't well installed or loaded. Working on Docker Galaxy on linux mint Tara.

**Comment by bgruening** [comment]
@mpaya this indeed looks like MultiQC is not installed correctly. If you go to your Admin panel you will see a "Manage dependencies" option. Please use that to re-install the conda environment.

Thanks!
