### ISSUE TITLE
Enable --format-fields option

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/tools-iuc#2297]
It is possible to (re)enable this option ?
https://github.com/galaxyproject/tools-iuc/blob/16205b1cd782c5a4f7c08af7d4ee50dc5903418b/tools/bcftools/bcftools_call.xml#L98

We just need to add a `$` in front of `section.format_fields:`
```
#if $section.format_fields:
  --format-fields "${section.format_fields}"
#end if
```
It seems to work. Maybe I can avoid to create a PR for this ?

**Comment by nsoranzo** [comment]
This is also going to be fixed by https://github.com/galaxyproject/tools-iuc/pull/1416 .
