### ISSUE TITLE
Bedtools coverage 2.27.1 fails with scientific notation entered on tool form

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2314]
Tool: bedtools Compute both the depth and breadth of coverage of features in file B on the features in file A (bedtools coverage) (Galaxy Version 2.27.1)

MTS: https://toolshed.g2.bx.psu.edu/repository?repository_id=8d84903cc667dbe7

Coverage values: 
* Default (blank) == pass
* Decimal (0.000000001) == pass
* Scientific notation (1E-9) == fail
* Scientific notation (1E-09) == fail

"Default" for this wrapper translates to "left blank on the tool form". This is not constent with other Bedtools wrappers like MultiCovBed (1E-09 is specifically pre-entered). The form also has the notation in the help written as 1E-9, not 1E-09 -- be good to standardize that across all tools in the repo when this is fixed. 

Error: `***** ERROR: -f must be in the range (0.0, 1.0]. *****`

Test history: https://usegalaxy.org:/u/jen/h/bedtools-coverage 

<img width="286" alt="screen shot 2019-02-25 at 6 31 02 pm" src="https://user-images.githubusercontent.com/8999735/53383195-8fc5e980-392b-11e9-821e-45e3920087e9.png">

**Comment by jennaj** [comment]
Cross-link to update org once fixed/in MTS https://github.com/galaxyproject/usegalaxy-playbook/issues/193

**Comment by bernt-matthias** [comment]
Is the tool actually started? The validator should actually not allow this: 

https://github.com/galaxyproject/tools-iuc/blob/73c6b2baf9dda26c6809a4f36582f7cbdb161ea1/tools/bedtools/coverageBed.xml#L79

Would be also worth to link this with the overlap parameters in the macros that are used in the intersect tool:

https://github.com/galaxyproject/tools-iuc/blob/fc3616bd1463afef9681cd7c431ac29f79e37e74/tools/bedtools/macros.xml#L29

**Comment by jennaj** [comment]
hi @bernt-matthias -- I don't think anyone has done anything yet. The tool version in the MTS, usegalaxy.org, and usegalaxy.eu are still the same as before. Plus, I reran the two failed jobs in the test history, and still don't parse correctly/job fails.

Or, are you stating that Sci notation should not be allowed? Other bedtools functions accept that type of input, so I wasn't sure about your thoughts. Remove the validator (?) Change it (?). You can decide with @bgruening / IUC how to resolve this the best way :)

**Comment by bernt-matthias** [comment]
I think scientific notation should be allowed. 

But, currently (in my understanding) the validator should forbid scientific notation. This seems not to work - there should be an error in the tool form and the job should not be executed. 

Do you have access to the job properties? For example the executed command line would be of interest. Or precise error messages (stderr/stdout).

**Comment by bernt-matthias** [comment]
In what I said before replace `validator` with sanitizer.

Just tried it: with 1E-19 the command line gets `-f '19' -F '19'`, i.e. the sanitizer removes 'E' and '-'.

**Comment by jennaj** [comment]
Ok, thanks for clarifying, didn't quite understand. Agree this could solve the problem, along with the tool form changes so users know what to do & the form is consistent with other tools/same suite (include a default value, fix the help text). Thanks!

**Comment by nsoranzo** [comment]
Actually I think we shouldn't use a param of `type="text"` (with `validator`), but a `type="float"` for these. Unfortunately there is a [Galaxy issue](https://github.com/galaxyproject/galaxy/issues/7836) with the tool form UI which doesn't let type `e` or `E` in `float` fields, but that shouldn't be too difficult to fix.

**Comment by bernt-matthias** [comment]
Agreed. Will change this in the PR.
