### ISSUE TITLE
annotateMyIDs (several versions) is not really ignoring header line when option set

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2319]
Test history usegalaxy.eu: https://usegalaxy.eu:/u/jenj/h/test-hisat2-featurecounts-annotatemyids 

Test history usegalaxy.org: https://usegalaxy.org:/u/jen/h/test-hisat2-featurecounts-annotatemyids

If the header is removed first, the tool works fine, across servers and tool versions.

**Comment by jennaj** [comment]
For reference, this was first reported at Galaxy Help here: https://help.galaxyproject.org/t/annotatemyids-fatal-error/701

**Comment by mblue9** [comment]
@jennaj it's due to the spaces in the column name ("HISAT on data N"), this should fix it https://github.com/galaxyproject/tools-iuc/pull/2320

**Comment by jennaj** [comment]
@mblue9 Thank you!

**Comment by jennaj** [comment]
Looks like this was in the 3/8/19 tool update in the MTS. Only EU appears to have v 3.7.0 installed (yet). But is it really the latest version with this changeset included? GUI has `3.7.0` -- same as MTS -- but the issue doesn't seem to be fixed.

The test fails when the input has a header (single Featurecounts count file, two columns, contains spaces and tabs) + form marked "yes" the input has a header. See dataset 38 in the original test history:

Test history usegalaxy.eu: https://usegalaxy.eu:/u/jenj/h/test-hisat2-featurecounts-annotatemyids

Seems to still be splitting by header whitespace, not tabs, to create labels for data columns, even though `sep="\t"` is specified.  @mblue9 what do you think?

**Comment by mblue9** [comment]
@jennaj it works fine for me locally with your input file and settings, see screenshot below

<img width="1070" alt="Screen Shot 2019-04-13 at 11 41 06 AM" src="https://user-images.githubusercontent.com/5591821/56073018-261d7400-5de1-11e9-9ff8-0ad0ebff9ff6.png">

So maybe it just needs to be updated at EU? ping @bgruening

**Comment by bgruening** [comment]
Updated on usegalaxy.eu

**Comment by jennaj** [comment]
Great, works now at EU. I'll ping to get ORG updated, too. Going to close this out, thanks all!!

**Comment by jennaj** [comment]
@Slugger70 ping that you will probably want to update the tool at AU as well

**Comment by Slugger70** [comment]
Thanks @jennaj I'm updating tools today so will add the update for this in.
