### ISSUE TITLE
BUSCO ids need to be updated

### ISSUE THREAD

**Issue by bimbam23** [galaxyproject/tools-iuc#2321]
I recently used the busco wrapper. The lineage files are not matching with the current orthodb 10 (only with ortho9) the ids need ether be converted  see  https://v100.orthodb.org/download/v9_v10_OGs_map.tab.gz or updated https://www.orthodb.org/?page=filelist  
right now the result of the tool is difficult to use...

**Comment by abretaud** [comment]
I think busco can't use directly orthodb data, there must some kind of processing before being ready to use in busco.
Looking at https://gitlab.com/ezlab/busco, they're working on preparing v10 datasets, so I guess we have to wait a little.
There's also a 3.1.0 version, but I'm not sure if it's released yet or not (no tag, no archive)

**Comment by bimbam23** [comment]
I think the only thing that needs to be done (for the Galaxy wrapper: https://toolshed.g2.bx.psu.edu/repository?repository_id=99f4c45aebf38997&changeset_revision=5ecdeca79a0d) is to update the data manger that downloads the lineage data sets, which are found here: https://www.orthodb.org/?page=filelist

**Comment by abretaud** [comment]
Yes I know, it's just that the files at https://www.orthodb.org/?page=filelist are not the good ones, the busco folks have to generate busco specific datasets from them

**Comment by Slugger70** [comment]
I am going to update the list of files to odb10. The busco people have finished producing them.
I will update the datamanager to suit

**Comment by abretaud** [comment]
Done in #3158
