### ISSUE TITLE
MultiQC - accept list of pairs

### ISSUE THREAD

**Issue by sneumann** [galaxyproject/tools-iuc#2371]
Hi, 
@bitbarbie reported that when running FastQC on a list of pairs, MultiQC is unhappy and complains it 
cant find a "txt dataset collection". 

How to reproduce: 
1) Create a list of pairs of fastq.gz data, 
2) run FastQC on it
3) *try* to run MultiQC. 

Expected result: 
MultiQC should find the fastqc raw data collection.

Yours, Steffen

**Comment by sneumann** [comment]
Comment on gitter:
```
Marius van den Beek, @mvdbeek, 15:37
There's no good way to use fastqc in multiqc because fastqc itself doesn't really deal with paired-end information. You can run fastqc on an aligned bam, which should work fine, or use fastp (which also does trimming)
```

**Comment by bernt-matthias** [comment]
What I usually do is to flatten the collection after running fastQC.

**Comment by bernt-matthias** [comment]
Problem with my solution is that in the raw data files `Filename` is always `forward.gz` or `reverse.gz` which makes it impossible to have multiple paired samples ... :(

**Comment by bernt-matthias** [comment]
see some progress here https://github.com/galaxyproject/tools-iuc/pull/2028

**Comment by bernt-matthias** [comment]
OK. I guess at the moment the best solution is to flatten the fastq collection first (which will create unique identifiers `samplename_forward` and `samplename_reverse`). Then you apply FastQC and MultiQC. Then all samples with forward and reverse data is shown. 

I guess this is acceptable. Will continue discussion here: https://github.com/galaxyproject/tools-iuc/pull/2028
