### ISSUE TITLE
VCFfilter -- add test for "Invert Yes/No" function on the tool form

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2386]
Breakout from this PR (another added test): https://github.com/galaxyproject/tools-iuc/pull/2385#issuecomment-488872711

Related linked tickets all point there plus this will be added to a project.

@VJalili is getting this one

cc @jmchilton

**Comment by nsoranzo** [comment]
Fixed in #2401.

**Comment by jennaj** [comment]
I'm not sure if the test case will work how we want it to. 

If the invert function toggle is not working, the test will pass because of the filter term used.  If the invert toggle IS working, the test will fail. Seems like the opposite of what we intended to do here.

See https://github.com/galaxyproject/tools-iuc/pull/2401#issuecomment-491091054

Please reopen until this is sorted out.
