### ISSUE TITLE
Publishe "CollectHsMetrics (Picard)" in toolShed 

### ISSUE THREAD

**Issue by delphineboulet** [galaxyproject/tools-iuc#2400]
Hello
Can you publishe CollectHsMetrics (Picard) in toolShed of galaxy please?

Thank you.

**Comment by bernt-matthias** [comment]
Its listed in the dependencies of the picard package: https://toolshed.g2.bx.psu.edu/repository?repository_id=c45d6c51a4fcfc6c&changeset_revision=7d34178f2812

should work. Please reopen if it does not.
