### ISSUE TITLE
Element identifier substitutions allow tabs and other whitespaces in filenames

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2417]
I think it might be a good idea to replace `\s` with a space ` ` in all tools that use something like `re.sub('[^\w\-\s]` on the element identifier or name attribute of datasets. 

seem to affect the following tools:

```
./tool_collections/fastx_toolkit/fastq_quality_boxplot/fastq_quality_boxplot.xml
./tools/cutadapt/cutadapt.xml
./tools/fastp/fastp.xml
./tools/fastqc/rgFastQC.xml
./tools/fermikit/fermikit_run_calling.xml
./tools/hicexplorer/hicPlotDistVsCounts.xml
./tools/intervene/macros.xml
./tools/mothur/filter.seqs.xml
./tools/multiqc/multiqc.xml
./tools/scpipe/scpipe.xml
./tools/taxonomy_krona_chart/taxonomy_krona_chart.xml

./tools/cutadapt/cutadapt.xml
./tools/fastp/fastp.xml
./tools/scpipe/scpipe.xml
```

**Comment by nsoranzo** [comment]
Did you notice any actual problem with allowing the other whitespace characters? They seem to be allowed in all major filesystems: https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

**Comment by bernt-matthias** [comment]
Nope. Just seemed odd to me to have horizontal or vertical tabs in filenames -- in the beginning I was afraid that `\0` is in `\s`, but it seems that its not.
