### ISSUE TITLE
Add STAR --quantMode TranscriptomeSAM

### ISSUE THREAD

**Issue by GKok** [galaxyproject/tools-iuc#2428]
I'm aligning data to a genome using STAR. However, I'd like to proceed with the aligned files using riboWaltz, which only accepts alignments to the transcriptome. STAR has a function "--quantMode TranscriptomeSAM" to provide a second file with transcript names. However, this option is not available in Galaxy. Would it be possible to add it?

**Comment by bernt-matthias** [comment]
fixed by https://github.com/galaxyproject/tools-iuc/pull/2359
