### ISSUE TITLE
package_libcurl_7_35's openssl dependency won't install

### ISSUE THREAD

**Issue by afgane** [galaxyproject/tools-iuc#243]
I see the 'missing dependencies' status for *package_libcurl_7_35*. Diving in, it seems *openssl* never got installed:
![screen shot 2015-08-10 at 4 33 59 pm](https://cloud.githubusercontent.com/assets/338642/9183599/26f9cdd6-3f7e-11e5-8171-fdc74e5440d9.png)

but then trying to install it, Galaxy responds with `Missing required tool dependency dir`: https://gist.github.com/anonymous/9389cb75ce25b5d4c15f

This is on Galaxy 15.07

**Comment by erasche** [comment]
We removed the dependency on openssl [19 days ago](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_libcurl_7_35/tool_dependencies.xml) but I'm guessing we need to re-push to the TS.

Does clicking openssl allow you to install and have a functional libcurl?

**Comment by bgruening** [comment]
@afgane we are not supporting security related packages in the TS. We are requiring openssl to be installed via the package manager.

https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_libcurl_7_35/tool_dependencies.xml

It's not included anymore.

**Comment by bgruening** [comment]
@erasche are you going to upload it?

**Comment by erasche** [comment]
@bgruening yeah, I can. I'll get all of the SSL ones pushed to MTS.

**Comment by bgruening** [comment]
Ok thanks!

**Comment by afgane** [comment]
OK. So when do you think you'll upload the new version?

BTW, checking `openssl` box and clicking 'install' comes back with what's in the gist, which doesn't lead to functional libcurl.

**Comment by erasche** [comment]
@afgane within the next 15 minutes or so.

**Comment by erasche** [comment]
> but then trying to install it

ah, sorry, missing that statement. OpenSSL is broken due to a removed package, so old versions will fail to compile.

**Comment by afgane** [comment]
So super-quick - thanks!

**Comment by erasche** [comment]
@afgane done.

- package_libcurl_7_35
- package_python_2_7
- package_python_3_4
- package_ruby_2_0
- package_ruby_2_1
- package_ruby_2_2

all updated with openssl-free versions.

**Comment by afgane** [comment]
After some Reparing and reinstalling, everything is Installed. Thanks.
