### ISSUE TITLE
MultiQC dependency on Samtools

### ISSUE THREAD

**Issue by afgane** [galaxyproject/tools-iuc#2448]
It appears MultiQC uses samtoos (https://github.com/galaxyproject/tools-iuc/blob/82a0fd493f5866b3ef65019709ae5c865998f802/tools/multiqc/multiqc.xml#L355), yet the requirements do not indicate this (https://github.com/galaxyproject/tools-iuc/blob/82a0fd493f5866b3ef65019709ae5c865998f802/tools/multiqc/multiqc.xml#L57). 

When used as a (mulled?) container (`quay.io/biocontainers/multiqc:1.6--py36h24bf2e0_0`), this results in the following error: 
```
Module 'bamtools: 'Stats for BAM file(s)' not found in the file 'FastQC on data 2_ RawData'
```

This is for toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.6 on Galaxy 19.05.

Am I missing something or is there an issue with the wrapper/container?

**Comment by mvdbeek** [comment]
Our multiqc wrapper doesn't use samtool, that line is just for checking what kind of data you're adding to the report.

**Comment by bgruening** [comment]
@afgane the error is probably somewhere below that line.

**Comment by afgane** [comment]
Thanks for the quick comments. It was a user error: I didn't select `FastQC` in the tool form (so the default `bamtools` applied).
