### ISSUE TITLE
picard collectRNA-seq metrics should use actual refflat, not ucsc export

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/tools-iuc#2453]
It seems that the picard RNA-seq metrics wrapper accepts both GFF/GTF and [refflat](https://genome.ucsc.edu/goldenpath/gbdDescriptionsOld.html#RefFlat)

There are instructions for extracting  UCSC gene info at the bottom of the tool, but this does not generate actual refflat, 

refflat format:
```
DDX11L1 ENST00000456328.2       chr1    +       11868   14409   14409   14409   3       11868,12612,13220,      12227,12721,14409,
```
ucsc extract format:
```
ENST00000456328.2       chr1    +       11868   14409   14409   14409   3       11868,12612,13220,      12227,12721,14409, DDX11L1
```

2 options:
- add a ucsc extract format (and simplify instructions to allow extracting "all fields from the selected table")
- sniff which refflat we have using data in column 4 (numeric = ucsc extract, +/- = refflat)

Which should I implement?
Or a third option I've not considered?
see also #1254

**Comment by bwlang** [comment]
the sniff was simple... so I went that route.

**Comment by bernt-matthias** [comment]
Can we close this issue?

**Comment by bwlang** [comment]
The  related PR is waiting for a test case I think... I'll see about adding that.
