### ISSUE TITLE
Request: Add column rearrange functionality to "Cut columns from a table (cut) (Galaxy Version 1.1.0)"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2458]
The original "Cut" tool rearranges columns.

The IUC version of "Cut" does not.

A "Cut" tool is included in the original Galaxy 101 and other tutorials and users are getting confused. 

Example of confusion (even confused me, guess I usually just use the original one since comes up first in the tool panel listing): https://help.galaxyproject.org/t/cut-tool-text-manipulation-doesnt-rearrange-columns/1554

If decide that it is not possible to add in the "rearrange" functionality, it would be very helpful for new and existing users to state something like in help, at the top, maybe with that little yellow `!` alert icon? Or the green `?` icon. Just done in some way stands out.

> When using this version of the **Cut** tool, the original column order is preserved. To rearrange columns, please use the tool "**Cut** columns from a table (Galaxy Version N.N.N)". 
> 
> Note: If you are using a tutorial, carefully check the specified tool name. _Some versions of the *Galaxy 101 and other tutorials* use the alternate *Cut* tool._

Tricky part and why a bit vague... we have a few 101 versions. I don't think we want to add in the actual tutorial links. Those could change over time, don't want to create a dependency.

GTN Galaxy 101 doesn't use this tool: https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html

The original Galaxy 101 (_that has been cloned literally a million places over the years, mostly out of our control_) is here, the first item under "Learn" on the Hub: https://galaxyproject.org/learn/ > Galaxy 101 - the basic introduction to Galaxy's interface, its functionality, and workflows. Start here if you never used Galaxy before > https://galaxyproject.org/tutorials/g101/ 

Thoughts?? @MoHeydarian @tnabtaf @nekrut @bgruening @mvdbeek @bebatut

**Comment by nsoranzo** [comment]
> The original Galaxy 101 (that has been cloned literally a million places over the years, mostly out of our control) is here, the first item under "Learn" on the Hub: https://galaxyproject.org/learn/ > Galaxy 101 - the basic introduction to Galaxy's interface, its functionality, and workflows. Start here if you never used Galaxy before > https://galaxyproject.org/tutorials/g101/

The training-material version is better maintained and is part of the largest collection, so I'd suggest to check if anything from the hub version needs to be ported to the training-material one, and then redirect https://galaxyproject.org/tutorials/g101/ to https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html

**Comment by tnabtaf** [comment]
I would argue that cut should be able to rearrange columns, even if the training doesn't use it.  That's just a really useful feature for building datasets that conform to format.

**Comment by nsoranzo** [comment]
> The IUC version of "Cut" does not.

@jennaj The "Cut" you are referring to is not from IUC, on the ToolShed it's in https://toolshed.g2.bx.psu.edu/view/bgruening/text_processing/ and on GitHub on https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/text_processing . Can you please re-open the issue there?

> I would argue that cut should be able to rearrange columns, even if the training doesn't use it. That's just a really useful feature for building datasets that conform to format.

@tnabtaf I agree that would be nice in principle, but that's not possible in the current implementation of the tool, which is part of a suite that relies on GNU `coreutils`. In fact, the `cut` command from `coreutils` does not support rearranging, as explained in the `cut` man page: "Selected input is written in the same order that it is read, and is written exactly once."
To add rearranging, the tool would need to be reimplemented using e.g. `awk`.
