### ISSUE TITLE
deseq2 fails on pulsar runner.

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/tools-iuc#2467]
Hi all,

It seems as though the new version of deseq2 is incompatible with Pulsar.

Pulsar will transfer to the remote location all `*.R` files only if they are mentioned in the `deseq2.xml` file. As `get_deseq_dataset.R` is not, it doesn't get transferred by pulsar and so the job fails. 

`get_deseq_dataset.R` is referred to in `deseq2.R` but not in the `deseq2.xml` file.

To get around this on my server I have added a `touch '${__tool_directory__}/get_deseq_dataset.R' &&` line to the start of the command tag in the xml file. It forces pulsar to transfer over the file.. 

Should we make the change in deseq2?

**Comment by bgruening** [comment]
Uhhh, that's bad. I guess your solution would work for the time being, but we should probably add some more explicit annotation to the tool-definition (requirements type="script" ...).

ping @jmchilton

**Comment by bernt-matthias** [comment]
seems to be solved already
