### ISSUE TITLE
Enhancement: additional output types for tools that output PDF 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2477]
SGV, TIFF, etc -- something format is high resolution for a manuscript. 

Could touch many tools. Or be a stand-alone converter. Thoughts?

Question about this that came up at Galaxy Help: https://help.galaxyproject.org/t/tool-plots-pdf-output-to-svg-or-tiff/1627

Maybe a Co-Fest project? Or maybe there are reasons we don't do this already? I am getting deja vu ... so sorry if came up before!

**Comment by bernt-matthias** [comment]
How about just using https://github.com/bgruening/galaxytools/blob/master/tools/image_processing/graphicsmagick/convert.xml ?

**Comment by jennaj** [comment]
@bernt-matthias I didn't now know that tool already existed :) But it doesn't look like it will accept `pdf` as an input -- or did I miss it?

**Comment by bernt-matthias** [comment]
I guess its a limitation of the wrapper: http://www.graphicsmagick.org/formats.html

**Comment by bernt-matthias** [comment]
or `gm convert -list format`

**Comment by bernt-matthias** [comment]
added pdf here: https://github.com/bgruening/galaxytools/pull/938 svg and tiff were already in. closing this here

**Comment by jennaj** [comment]
@bernt-matthias Thank you!!
