### ISSUE TITLE
Interproscan: output file is green but is missing

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/tools-iuc#2482]
Running Interproscan in usegalaxy.eu - version 5.0.0 - the output file is green but is zero bytes. 
Error message is:
/data/dnb02/galaxy_db/job_working_directory/005/543/5543837/tool_script.sh: line 9: interproscan.sh: command not found

I am using the tool in the published workflow for genome annotation: "Workflow constructed from history 'Genome Annotation Workshop - Results'" 

I also used a test_proteins.fasta file from the Interproscan site, but I get the same problem.

test file link: https://github.com/ebi-pf-team/interproscan/blob/master/core/jms-implementation/support-mini-x86-32/test_proteins.fasta

Thank you!

**Comment by abretaud** [comment]
I think this should go to https://github.com/bgruening/galaxytools/ as interproscan is not in iuc: https://github.com/bgruening/galaxytools/blob/master/tools/iprscan5/interproscan.xml
It's an exotic tool as there is no conda package (and making one would be... complicated)

**Comment by abretaud** [comment]
Hum, so probably some env problem on usegalaxy.eu

**Comment by AnnaSyme** [comment]
Possibly a similar problem with TMHMM 2.0 - version 0.0.16 - error: Failed to activate conda environment! Error was:
Not a conda environment: /usr/local/tools/_conda/envs/__tmhmm2@_uv_

However version 0.0.13 works.
