### ISSUE TITLE
FastQC webpage output file does not display graphics

### ISSUE THREAD

**Issue by JD-Exosomes** [galaxyproject/tools-iuc#2488]
Using Chrome to access https://usegalaxy.org/.

Ran FastQC on FastQ file (human RNA-seq data), analysis completed, and can see which aspects passed/failed, but not of the graphs display (broken image icon). Have not had this problem previously, last used FastQC on Galaxy a couple of months ago. Redownloaded Java, restarted browser, restarted computer, reran FASTQC analysis and all resulted with same issue. I'm on an LG gram laptop.

**Comment by bgruening** [comment]
Do you see the same on usegalaxy.eu?

**Comment by JD-Exosomes** [comment]
Won't recognize my login credentials, creating new account and rerunning analysis. Will update as progress

**Comment by JD-Exosomes** [comment]
usegalaxy.eu works great

**Comment by bernt-matthias** [comment]
I guess the admin of your Galaxy needs to add the tool to the whitelist?

**Comment by bernt-matthias** [comment]
Closing this in the hope that my comment fixed it.
