### ISSUE TITLE
JBrowse v0.4

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#250]
- [x] take colour from qualifier
- [x] ensure scores are colouring features by default
- [x] configurable coding table
  - [x] implement on jbrowse side https://github.com/GMOD/jbrowse/pull/657
  - [x] add code to support in jbrowse.py 
- [x] more debugging/logging info
- [x] store copy of intermediary conf file IN the output folder.
- [x] #346

**Comment by erasche** [comment]
Hmm, how many options is too many?

![jbrowse-options](https://cloud.githubusercontent.com/assets/458683/9425348/96ac2b30-48d2-11e5-85b8-dbe462c5d119.png)

**Comment by bgruening** [comment]
I don't think there is something like to much options. There is something like 'it's unusable and to distracting' but if you hide everything by default, I guess this is fine. Great stuff Eric!

**Comment by erasche** [comment]
Yep, all hidden by default. Thanks for the feedback!

**Comment by erasche** [comment]
Making good progress on the next version. 

Top row shows a track which takes its colour from a `color` qualifier in the GFF3 file. Transparency here is from a user-selected scaling algorithm (In this case a linear scale 1-1000, as suggested by the gff3 docs. A couple other score->opacity algorithms are included, including one for blastxml data.)

Top two tracks have a user-specified colour, the bottom one has an automatically generated colour.

![jbrowse4](https://cloud.githubusercontent.com/assets/458683/11314096/e82e6a24-8fa7-11e5-9890-946e600d2b65.png)

**Comment by erasche** [comment]
colours can be specified in gff3, scores affect colouring: (Here "linear" means "linear scaling of the scores to opacity", and "fixed color" means "user specific colour which overrode any colour attribute in gff3)
![selection_512](https://cloud.githubusercontent.com/assets/458683/12025222/f958f764-ad71-11e5-8888-4581629b2003.png)

auto colours using brewer palletes:

![selection_513](https://cloud.githubusercontent.com/assets/458683/12025224/fc3b4806-ad71-11e5-86e7-24acb7d28a02.png)

**Comment by erasche** [comment]
Features with UTRs under "auto" colouring, just amazing:
![selection_516](https://cloud.githubusercontent.com/assets/458683/12025395/20f7b9c0-ad74-11e5-93eb-fe0eaa925df2.png)
