### ISSUE TITLE
trinotate: wget failed

### ISSUE THREAD

**Issue by loraine-gueguen** [galaxyproject/tools-iuc#2508]
wget failed when running trinotate because of not found library. 
Cross-references: https://github.com/bioconda/bioconda-recipes/issues/14288, https://github.com/bioconda/bioconda-recipes/issues/16128

```
Fatal error: Exit code 2 ()
* Running CMD: wget "http://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz"
wget: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error, cmd: wget "http://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz" died with ret 32512 No such file or directory at /usr/local/genome2/lib/perl5/Pipeliner.pm line 186.
	Pipeliner::run(Pipeliner=HASH(0x2b9c809208c0)) called at /tmp/mc/envs/mulled-v1-a8259c1b65c5d282750e47963d88f7d939acc8a28c8ab855de159198845685cc/bin/Build_Trinotate_Boilerplate_SQLite_db.pl line 119
```

**Comment by bgruening** [comment]
I will try to fix the old bioconda package as well.

**Comment by bgruening** [comment]
@loraine-gueguen can you please merge https://github.com/bioconda/bioconda-recipes/pull/16705

Than you do not need to disable your tool :)

**Comment by bgruening** [comment]
This should be fixed now, hopefully. But please we need to migrate to the conda-forge version still. Thanks for the report @loraine-gueguen!
