### ISSUE TITLE
Kraken2 Data Manager: Make cleanup optional

### ISSUE THREAD

**Issue by dfornika** [galaxyproject/tools-iuc#2511]
`kraken2-build` provides a `clean` operation that removes the `library` and `taxonomy` directories to minimize kraken database storage. It is currently run by default in the `data_manager_build_kraken2_database` tool.

But some tools (notably `bracken`) require some of the data that is removed by the cleanup process for their functionality.

It would be good to allow the user to decide whether or not to clean the kraken2 database. Cleanup should probably be enabled by default.

**Comment by dfornika** [comment]
I've got an implementation of this fix here:

https://github.com/dfornika/tools-iuc/tree/kraken2-data-manager-optional-cleanup/data_managers/data_manager_build_kraken2_database/data_manager

I need to tidy up a couple things then I'll submit a pull-request.

**Comment by bgruening** [comment]
Nice catch and really unexpected. Thanks @dfornika!
