### ISSUE TITLE
README.rst for Trinity gives incorrect instructions for setting memory limit

### ISSUE THREAD

**Issue by pjbriggs** [galaxyproject/tools-iuc#2513]
The `README.rst` file for the `trinity` tool (https://github.com/galaxyproject/tools-iuc/tree/master/tools/trinity) has incorrect instructions for setting the memory consumption limit.

The instructions indicate that values of the form `1G`, `50G` etc (i.e. a number followed by `G`) can be assigned to the `GALAXY_MEMORY_MB` environment limits, but doing this results in the following message appearing in the tool stdout:

    .../job_scripts/597189: line 53: 50G: value too great for base (error token is "50G")

and the default value of `1G` is supplied to `trinity` on the command line.

It appears that the memory limit actually needs to be assigned as a number of MB without the units, e.g. for 50G limit this would be (50*1024 =) 51200:

    <env id="GALAXY_MEMORY_MB">51200</env>

**Comment by bernt-matthias** [comment]
Fixed https://github.com/galaxyproject/tools-iuc/pull/2521
