### ISSUE TITLE
bedtools bamtobed with -bedpe option should not require name sorted bam files

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#252]
Currently, using the bedtools bamtobed tool on paired end data and specifying the bedpe option requires the user to supply a name sorted bam file. In Galaxy, this is not really doable since Galaxy requires BAM files to be sorted by chromosome location (see: galaxyproject/tools-devteam#210).

I would suggest implementing the sort within the tool and piping the result to bedtools. This eliminates the headache for the user and doesn't generate a useless (and large) sorted  BAM file. See https://github.com/lparsons/galaxy_tools/tree/master/tools/htseq_count for one example of this.

**Comment by bgruening** [comment]
@lparsons actually this is a Galaxy bug: https://github.com/galaxyproject/galaxy/pull/476
Galaxy was able to handle name sorted BAM files. Nevertheless, this suggestions seems reasonable and I would be willing to implement this. The only disadvantage is that we add a new dependency. Do you think this is worth it, given that Galaxy _can_ handle name sorted BAM files?

**Comment by lparsons** [comment]
@bgruening Thanks for pointing to the Galaxy bug, hope that gets fixed soon.
The way I see it, implementing sorting in the tool makes the tool easier to use to end users and only slightly harder to install for admins, and somewhat harder to maintain for devs. The dependency would be samtools (which is almost certainly there already). Also, devs only touch this every so often, and admins only once per version, while users interact with it potentially dozens of times. Also, reducing unnecessary files is HUGE plus (at least for me), since disk space is my number one resource constraint (gzipped fastq file anyone? :wink: ).

**Comment by bgruening** [comment]
@lparsons I'm convienced, I will put this on my ToDo list for the next bedtools release, if this is ok for you!

+1 for gzipped fastq files or unmapped BAM files.

**Comment by peterjc** [comment]
See also https://trello.com/c/3RkTDnIn/345-666-support-gzipped-gz-compressed-versions-of-standard-datatypes - but in the short term, gzipped Sanger FASTQ would be very popular and from past mailing list discussions several groups are using this already.

**Comment by bgruening** [comment]
I guess we need to make this more sexy for the devteam. They probably have way to much storage capacity to care about this at the moment :wink:

**Comment by lparsons** [comment]
I'd be extremely interested in any implementations (or just contacts for people using it). I'm also up for helping to "sell" this in any way that I can. I agree with @peterjc that gzipped Sanger FASTQ would be extremely useful, and worth doing (even if it's not quite as generalized). Especially if it was implemented in a way that would make the transition to generalized gzip support fairly easy.

**Comment by bgruening** [comment]
ping @dpryan79

**Comment by peterjc** [comment]
As I recall, the short-term hack some people are using was to simply define a new datatype (would have to find the emails) and modify key tools to accept this as an alternative to ``fastqsanger`` (with appropriate command line changes if needed - many tools auto-detect this).

For reference, the Galaxy team use a compressed file system so they don't need this. We're recently begun looking at that here too, which would solve this for our local Galaxy instance.

**Comment by dpryan79** [comment]
@bgruening I vaguely remember some sort of datatype hack, as mentioned by @peterjc , but I did that within the first week of working with Galaxy and apparently never wrote down how :(

**Comment by bgruening** [comment]
@lparsons what do you think about #293

**Comment by lparsons** [comment]
@bgruening Looks good and perhaps should be implemented for https://github.com/lparsons/galaxy_tools/blob/master/tools/htseq_count/htseq-count.xml as well.

**Comment by bgruening** [comment]
Fix by #293
