### ISSUE TITLE
RNAquast

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2527]
Just got a request for RNAquast http://cab.spbu.ru/software/rnaquast/. Seems interesting. Is there anyone with experience with this tool?

**Comment by stephanflemming** [comment]
Fixed in https://github.com/galaxyproject/tools-iuc/pull/3232 right?

**Comment by bgruening** [comment]
Yes, thanks @stephanflemming for the catch!
