### ISSUE TITLE
package_ruby_2_0 can't install from rubygems.org (SSL error)

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/tools-iuc#254]
Trying to install `package_protk_1_4_2`, which depends on `package_ruby_2_0`, produced the following error:

```
ERROR:  Could not find a valid gem 'protk' (= 1.4.2), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems.org/specs.4.8.gz)
```

It looks like [this problem](https://gist.github.com/luislavena/f064211759ee0f806c88), caused by an outdated version (in this case 2.0.14) of the RubyGems gem. I tried entering the `package_ruby_2_0` environment using `source env.sh` to upgrade RubyGems to 2.0.15 as suggested. Trying to install the updater gem produced the following error:

```
$ gem install rubygems-update-2.0.15.gem
ERROR:  Loading command: install (LoadError)
	/path/to/tool_deps/ruby/2.0/iuc/package_ruby_2_0/b579f4987433/lib/ruby/2.0.0/x86_64-linux/openssl.so: undefined symbol: SSLv2_method - /path/to/tool_deps/ruby/2.0/iuc/package_ruby_2_0/b579f4987433/lib/ruby/2.0.0/x86_64-linux/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

**Comment by bgruening** [comment]
@bcclaywell can you check if your ruby version was compiled with ssl support?
Openssl is now a requirement for the Tool Shed. So you should have libopenssl installed.

**Comment by bcclaywell** [comment]
@bgruening Yes, the box has openssl installed, and it looks like `package_ruby_2_0` compiled SSL support in:

```
$ find /path/to/tool_deps/ruby/2.0/iuc/package_ruby_2_0/b579f4987433-name 'openssl.so' | xargs ldd
	linux-vdso.so.1 =>  (0x00007fff4c9fe000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f45c5c7e000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f45c58a3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f45c5684000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45c52bf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f45c50bb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f45c6138000)
```

It looks like something distributed with this version of Ruby depends on SSLv2 (long paths to Ruby in tool_deps directory omitted):

```
$ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
[...]/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': [...]/lib/ruby/2.0.0/x86_64-linux/openssl.so: undefined symbol: SSLv2_method - [...]/lib/ruby/2.0.0/x86_64-linux/openssl.so (LoadError)
	from [...]/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from [...]/lib/ruby/2.0.0/openssl.rb:17:in `<top (required)>'
	from [...]/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from [...]/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

But [Ubuntu doesn't compile SSLv2 into their libopenssl](http://stackoverflow.com/a/13472755). I don't know why I'd be the first to run into this problem though, so something else might be wrong!

**Comment by bgruening** [comment]
Not sure, I don't think so many Galaxy users using Galaxy+Ruby+Ubuntu. Could you try to newer ruby releases. Ruby2.1, 2.2?
There is also a newer Ruby2.0 version: ruby-2.0.0-p647 I think I will update this now.

**Comment by bgruening** [comment]
Ok I updated the TTS: https://testtoolshed.g2.bx.psu.edu/view/iuc/package_ruby_2_0/b67c42c010df with a 3 days old ruby release :)

**Comment by bcclaywell** [comment]
Thanks for the quick update! Just tested installing `package_protk_4_2`, which pulled in your new `package_ruby_2_0`, and received a different error:

```
tool_shed.galaxy_install.tool_dependencies.recipe.step_handler DEBUG 2015-08-21 21:40:11,435 Handling setup_ruby_environment for tool dependency protk with install_environment.env_shell_file_paths:
['[...]/tool_deps/ruby/2.0/bgruening/package_ruby_2_0/3f8f714feac1/env.sh', '/[...]/tool_deps/libxml2/2.9.1/devteam/package_libxml2_2_9_1/926b471a2e43/env.sh']
ERROR:  Loading command: install (LoadError)
	cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

Looks like openssl didn't get compiled in at all this time:
```
$ find /path/to/tool_deps/ruby/2.0/bgruening/package_ruby_2_0/3f8f714feac1 -name 'openssl.so'
$
```

Does the new version of Ruby need an explicit compile-time flag to enable OpenSSL maybe?

**Comment by bgruening** [comment]
I updated the the protk repository as well. Just for the record I'm using the Test Tool Shed and it works for me in a fresh Docker Image. Witch OS are you using?

**Comment by bcclaywell** [comment]
@bgruening My apologies for the delay -- was wearing a different hat last week. We're running Ubuntu 14.04, also in a Docker container. I thought maybe some package in the image was out of date or missing, so I just busted the cache and rebuilt the image from scratch, and just tested the install of package_ruby_2_0_0 again. During the Ruby build I saw the following scroll past:

```
configuring openssl
Failed to configure openssl. It will not be installed.
```

I just checked, and while openssl and libssl1.0.0 is installed, libssl-dev isn't -- do you think that could be it?

**Comment by bgruening** [comment]
@bcclaywell yes this could be!

**Comment by bcclaywell** [comment]
Looks like missing libssl-dev was the culprit for the second error! With the new version of package_ruby_2_0_0 and libssl-dev installed, protk installed just fine. Thanks for all your help, Björn!

**Comment by bgruening** [comment]
@bcclaywell your are welcome!
Btw. we really appreciate any feedback for our proteomics tools @ https://github.com/galaxyproteomics/tools-galaxyp :)

**Comment by bcclaywell** [comment]
@bgruening Once I've gotten a few users up and running with the proteomics tools, I'll be sure to pass along any feedback they have!
