### ISSUE TITLE
New Roary upgrade doesn't like spaces in filenames

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/tools-iuc#2545]
Within the new version of the Roary tool, the inputs are copied and renamed with `element_identifier` which is a good idea in itself. However, in most cases with Galaxy, if these gff inputs are outputs from another tool (such as Prokka) then `element_identifier` will contain spaces and perhaps other whitespace.

Example:
Original input file in Galaxy: `177: Prokka on data 61: gff`
Becomes: `Prokka on data 61: gff.gff` which contains whitespace.

In the command block of `roary.xml`, the files to be analysed are added with `*.gff` which doesn't wrap them individually in `""`...

Therefore, roary cannot find the files as it splits them on whitespace... :(

```
<command detect_errors="exit_code"><![CDATA[
        
        #for $gff in $gff_input.gffs
          cp $gff '${gff.element_identifier}'.gff &&
        #end for

        roary
          -f out
          -p \${GALAXY_SLOTS:-1}
          -e
          -n
          -i '$percent_ident'
          -cd '$core_diff'
          -g '$advanced.maxclust'
          $advanced.split_para
          -t '$advanced.trans_tab'
          -iv '$advanced.mcl'

          *.gff
          
    ]]></command>
```

**Comment by bernt-matthias** [comment]
Fixed by https://github.com/galaxyproject/tools-iuc/pull/2546?
