### ISSUE TITLE
Cython error: undefined symbol: PyUnicodeUCS4_DecodeUTF8

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/tools-iuc#256]
I am wrapping a tool that makes use of Cython. I am using the package_cython_0_20_1 wrapper from IUC, and the package_python_2_7 wrapper from IUC. When I try to compile the tool, I crashes with the following error:

*failed to import Cython: .../galaxy/tool-dependencies/cython/0.20.1/iuc/package_cython_0_20_1/749f11b9358a/lib/python/Cython-0.20.1-py2.7-linux-x86_64.egg/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8*

After some reading I found that this issue is most likely due to different compilation settings for Cython and Python ( http://forum.dato.com/discussion/84/importerror-undefined-symbol-pyunicodeucs4-decodeutf8 ). Unicode chars can be represented by 2 or by 4 bytes, where Cython expects the 4 bytes representation, and python is probably compiled with 2 bytes.

Following the code at the bottom of this page:
https://docs.python.org/2.7/faq/extending.html#when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2
The python package from galaxy is indeed "UCS2 build", unlike most systems defaults.

So, package_python_2_7 and package_cython_0_20_1 break with each other because of this issue.
Does someone have a clue how to solve this; would the most appropriate solution be at the python or the cython side?

There are a few ways that might solve this:
* Update the package_python_2_7 wrapper and compile with the following argument: *--enable-unicode=ucs4*
 - This may lead to unexpected behavior in all packages that depend on package_python_2_7
* Let the current cython package depend on package_python_2_7 during installation (if cython is installed with a ucs2-python binary, it automatically solves it during compilation)
 - This may lead to unexpected behavior in all packages that depend on package_cython_0_20_1
* Create a new package package_python_2_7_cython_0_20_1, that depends on python_2_7 and compiles cython_0_20_1
 - This does not solve the actual problem, but is a handy workaround

**Comment by bgruening** [comment]
Hi @yhoogstrate  can you create a new cython package for version 0.23.1 and make it depend on `package_python_2_7`. So essentially the second solution you proposed but with a new cython version? 

https://pypi.python.org/packages/source/C/Cython/Cython-0.23.1.tar.gz#md5=db3c5b365e1c3f71c7cd90e96473a3ab

Thanks!

**Comment by yhoogstrate** [comment]
That is an elegant solution indeed.
