### ISSUE TITLE
hisat2 missing options

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2569]
While thinking about https://github.com/galaxyproject/tools-iuc/issues/1740 I observed that some options are missing that could be handy, e.g. setting read groups (to fixed text or element identifier).

```
--no-unal | Suppress SAM records for reads that failed to align.
--no-hd | Suppress SAM header lines (starting with @).
--no-sq | Suppress @SQ SAM header lines.
--rg-id <text> | Set the read group ID to <text>. This causes the SAM @RG header line to be printed, with <text> as the value associated with the ID: tag. It also causes the RG:Z: extra field to be attached to each SAM output record, with value set to <text>.
--rg <text> | Add <text> (usually of the form TAG:VAL, e.g. SM:Pool1) as a field on the @RG header line. Note: in order for the @RG line to appear, --rg-id must also be specified. This is because the ID tag is required by the SAM Spec. Specify --rg multiple times to set multiple fields. See the SAM Spec for details about what fields are legal.
--omit-sec-seq | When printing secondary alignments, HISAT by default will write out the SEQ and QUAL strings. Specifying this option causes HISAT to print an asterix in those fields instead.
```

**Comment by bgruening** [comment]
@astrovsky01 is looking at this one.

**Comment by astrovsky01** [comment]
Since we run samtools immediately after, the no-hd and no-sq options create opportunities for errors where samtools doesn't recognize it as a properly formatted file, and returns errored bam to the history. Thoughts on either not including those options, or turning off the auto-samtools run afterwards if those flags are present?

**Comment by bernt-matthias** [comment]
> Since we run samtools immediately after, the no-hd and no-sq options create opportunities for errors where samtools doesn't recognize it as a properly formatted file, and returns errored bam to the history. Thoughts on either not including those options, or turning off the auto-samtools run afterwards if those flags are present?

Unsure. Checked the samtools man pages a bit. Seems that `samtools view` does not print the header by default. So maybe its not a problem...
