### ISSUE TITLE
definition for datatype "mtx"

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/tools-iuc#2602]
I have been installing DropletUtils "2(20190906) onto my development server (running Galaxy 18.05). The datatype "mtx" is not recognized . As far as I can tell 'mtx' was only introduced in version 19.05. Hence the 'Minimum Galaxy Version' 16.01 in the toolshed is misleading, isn't-it?

**Comment by bgruening** [comment]
Jupp, 16.01 is the default if we do not specify anything :(
We should have specified that ... can you backport this datatype in your instance?

**Comment by hrhotz** [comment]
will try....

**Comment by hrhotz** [comment]
adding the datatype to ~/lib/galaxy/datatypes/tabular.py and ~/config/datatypes_conf.xml (based on the code from 19.05) fixed the problem
