### ISSUE TITLE
Negative values not being passed into Table Compute

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/tools-iuc#2607]
Steps to Reproduce:

* Type of table operation → "Filter rows or columns by their properties"
* Filter Criterion → "Result of function applied to"
* Keep column/row if it observed → "Minimum"
* this value → **Try to put a negative number, it will not allow it**

The culprit seems to be at this line here:
 - https://github.com/galaxyproject/tools-iuc/blob/f2ab0315fa6df9e3e917bbc112e29f384c3affba/tools/table_compute/table_compute.xml#L371

...which is odd because a min or max value for this float parameter is never given. 

Is this a larger problem?

**Comment by wm75** [comment]
Weird, it works for me

**Comment by wm75** [comment]
Did we fix this since?

**Comment by mtekman** [comment]
Looks like it ;-)
Cannot reproduce either
