### ISSUE TITLE
Error compiling Boost during package_tpp_4_6_3 install

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/tools-iuc#262]
(Sorry to keep doing this to you @bgruening!)

To work around a specific need for protk because of #254, I was trying to install the galaxyp/decoyfasta tool from the main toolshed, which depends on package_tpp_4_6_3. The build of that package failed while compiling Boost and logged the following:

```
building boost libraries...
[ERROR] Boost libary build failed (missing [...]/database/tmp/tmp-toolshed-mtdSXaXct/TPP-4.6.3/trans_proteomic_pipeline/src/../build/Ubuntu-x86_64/boost/lib/libboost_filesystem.a), please report the results of manually running the following commands:
cd [...]/database/tmp/tmp-toolshed-mtdSXaXct/TPP-4.6.3/trans_proteomic_pipeline/src/../extern/boost_1_45_0; time [...]/database/tmp/tmp-toolshed-mtdSXaXct/TPP-4.6.3/trans_proteomic_pipeline/src/../extern/boost_1_45_0/tools/build/v2/engine/src/bin.linuxx86_64/bjam -q -d0 --stagedir=[...]/database/tmp/tmp-toolshed-mtdSXaXct/TPP-4.6.3/trans_proteomic_pipeline/src/../build/Ubuntu-x86_64/boost --build-dir=[...]/database/tmp/tmp-toolshed-mtdSXaXct/TPP-4.6.3/trans_proteomic_pipeline/src/../build/Ubuntu-x86_64/boost/obj --layout=system --build-type=minimal -j3 variant=release link=static runtime-link=shared --with-filesystem --with-date_time --with-iostreams --with-program_options --with-regex --with-serialization --with-thread stage
/bin/sh: 1: time: not found
/bin/sh: 1: exit: Illegal number: -1
make: *** [boost-build-libs] Error 2
tool_shed.galaxy_install.install_manager ERROR 2015-09-01 21:10:12,184 Error installing tool dependency trans_proteomic_pipeline version 4.6.3.
Traceback (most recent call last):
  File "[...]/lib/tool_shed/galaxy_install/install_manager.py", line 141, in install_and_build_package_via_fabric
    tool_dependency = self.install_and_build_package( tool_shed_repository, tool_dependency, actions_dict )
  File "[...]/lib/tool_shed/galaxy_install/install_manager.py", line 126, in install_and_build_package
    initial_download=False )
  File "[...]/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 32, in execute_step
    initial_download=initial_download )
  File "[...]/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 1732, in execute_step
    return_output=False )
  File "[...]/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 131, in handle_command
    self.log_results( cmd, output, os.path.join( self.install_dir, basic_util.INSTALLATION_LOG ) )
  File "[...]/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 251, in log_results
    logfile = open( file_path, 'wb' )
IOError: [Errno 2] No such file or directory: u'[...]/tool_deps/trans_proteomic_pipeline/4.6.3/iuc/package_tpp_4_6_3/679b2c6a6e19/INSTALLATION.log'
```

I did try to run the command suggested in the log messages to learn more, but the temporary build directory had already been cleaned.

On the off chance this problem has the same solution as #254, installing `libssl-dev`, I'm trying to build the package again now -- but beyond that I'm out of ideas. Any thoughts?

**Comment by bgruening** [comment]
@bcclaywell do you know if we simply can upgrade to TPP-4.7? This package is pre-compiled and should have much less problems. I could update the dependencies.

**Comment by bcclaywell** [comment]
@bgruening I think that would be fine -- we're not tied to 4.6.3 for any particular reason other than that's what decoyfasta wanted to pull in.

**Comment by bgruening** [comment]
I will try to do this tomorrow, it's late here.

**Comment by bcclaywell** [comment]
No problem -- thanks for your help!

**Comment by bgruening** [comment]
@bcclaywell before I work on this and promise to much, can you please try to install TPP.4.7?

**Comment by bcclaywell** [comment]
@bgruening TPP 4.7's dependencies installed fine, but TPP itself hung up while installing some Perl CGI stuff. I think there's a missing dependency on Perl FCGI 0.67. From `INSTALLATION.log` in `tool_deps/trans_proteomic_pipeline/4.7.0/iuc/package_tpp_4_7_0/2b778f0f7a0e`:

```
Appending installation info to /mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/trans_proteomic_pipeline/4.7.0/iuc/package_tpp_4_7_0/2b778f0f7a0e/lib/perl5/x86_64-linux/perllocal.pod
#############################################

#############################################
PATH=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/perl/5.18.1/iuc/package_perl_5_18/fd34b72b501b/bin:$PATH; export PATH
PERL5LIB=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/perl/5.18.1/iuc/package_perl_5_18/fd34b72b501b/lib/perl5:$PERL5LIB; export PERL5LIB
PERL_ROOT_DIR=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/perl/5.18.1/iuc/package_perl_5_18/fd34b72b501b; export PERL_ROOT_DIR
PERL_LOCALLIB_DIR=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/perl/5.18.1/iuc/package_perl_5_18/fd34b72b501b/local-lib; export PERL_LOCALLIB_DIR
PATH=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/expat/2.1.0/iuc/package_expat_2_1/0b8d0fa6cea6/bin:$PATH; export PATH
LD_LIBRARY_PATH=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/expat/2.1.0/iuc/package_expat_2_1/0b8d0fa6cea6/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
C_INCLUDE_PATH=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/expat/2.1.0/iuc/package_expat_2_1/0b8d0fa6cea6/include:$C_INCLUDE_PATH; export C_INCLUDE_PATH
EXPAT_ROOT_DIR=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/expat/2.1.0/iuc/package_expat_2_1/0b8d0fa6cea6; export EXPAT_ROOT_DIR
PERL_MM_USE_DEFAULT=1; export PERL_MM_USE_DEFAULT; export PERL5LIB=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/trans_proteomic_pipeline/4.7.0/iuc/package_tpp_4_7_0/2b778f0f7a0e/lib/perl5:$PERL5LIB;export PATH=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/trans_proteomic_pipeline/4.7.0/iuc/package_tpp_4_7_0/2b778f0f7a0e/bin:$PATH;perl Makefile.PL INSTALL_BASE=/mnt/scdata/scdata_03/galaxy/containers/galaxy-test/tool_deps/trans_proteomic_pipeline/4.7.0/iuc/package_tpp_4_7_0/2b778f0f7a0e && make && make install
STDERR
Warning: prerequisite FCGI 0.67 not found.
#############################################
```

The installation hung here with `package_tpp_4_7_0` continuing to show "Installing tool dependencies" in the admin interface.

**Comment by yhoogstrate** [comment]
https://github.com/galaxyproject/tools-iuc/blob/48fbe322d0f3ec023186989104ae4f4188b03a1d/packages/package_tpp_4_7_0/tool_dependencies.xml#L105

That line doesn't make sense and results in an error if you don't have the directory ```/home/bag```

**Comment by bgruening** [comment]
I fixed this but we should move on and deprecate all version < 4.8.  @bcclaywell please try the TPP 4.8. I pre compiled everything, so I hope this is way faster and way more reliable.

**Comment by yhoogstrate** [comment]
@bcclaywell Does TPP solve this issue for you?

**Comment by bcclaywell** [comment]
@yhoogstrate Galaxy says package_tpp_4_8_0 installed on our test instance, but it looks like the decoyfasta tool (which is what I was trying to install at the time) still depends on TPP 4.6.3. To be honest I punted on installing proteomics tools, in part because of these issues but also because Linux builds of msconvert/ProteoWizard couldn't convert vendor files.

**Comment by bgruening** [comment]
@bcclaywell I can change the depencency of decoyfasta to tpp_4_8 if you are fine with this. We need any feedback for all of our proteomics tools ... so I'm very thankful that you test tpp_4_8.

Thanks,
Bjoern

**Comment by bcclaywell** [comment]
@bgruening That's fine with me! I was trying to install/test it for one of our users; my own knowledge of proteomics is more or less non-existent. :)

**Comment by bgruening** [comment]
@bcclaywell I updated decoyfasta to depend on tpp_4_8, testing appreciated :)

Thanks,
Bjoern

**Comment by bcclaywell** [comment]
Found this looking through my old open issues and realized I never closed it out. I just tried installing the latest version of decoyfasta depending on tpp_4_8, and it installed properly and worked when I tested it. Thanks, and sorry for the delay!

**Comment by bgruening** [comment]
Thanks @bcclaywell!
