### ISSUE TITLE
Tool update request: Transdecoder

### ISSUE THREAD

**Issue by j-batista** [galaxyproject/tools-iuc#2626]
Hi IUC - I'd like to request an update to the Transdecoder tool.

Current tool shed version is 3.0.1 (from Oct 31, 2016)
Latest version is 5.5.0 (from Oct 26, 2018)

There's been a few relevant changes since 3.0.1 which I think justify updating the repository version.

Cheers,
Jose

**Comment by stephanflemming** [comment]
I will take care of that.
