### ISSUE TITLE
IUC member proposal: Wolfgang Maier

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-iuc#2663]
I would like to propose Wolfgang Maier (@wm75) as a new IUC member.

He is working on Galaxy tools since at least 2014.
He has already contributed [27 PRs](https://github.com/galaxyproject/tools-iuc/pulls/wm75) to this repo, and he is part of the UseGalaxy.eu team.

Please vote!

**Comment by bgruening** [comment]
Yeah! :+1: 

Thanks Nicola!

**Comment by mvdbeek** [comment]
Of course, great idea! 👍

**Comment by bebatut** [comment]
👍

**Comment by abretaud** [comment]
Yes! :+1:

**Comment by shiltemann** [comment]
:+1: :tada:

**Comment by gregvonkuster** [comment]
+1

On Oct 28, 2019, at 11:57 AM, Saskia Hiltemann <notifications@github.com<mailto:notifications@github.com>> wrote:


👍 🎉

**Comment by mblue9** [comment]
👍

**Comment by nsoranzo** [comment]
Welcome @wm75 to the IUC! :)

@bgruening Can you please add Wolfgang to the mailing list?
@martenson Can you please invite him to the GitHub team?

**Comment by martenson** [comment]
Done. Welcome @wm75 !

**Comment by wm75** [comment]
:sparkles: Thank you all for your vote and confidence in me!
Still learning something new with almost every PR here, but I'll try my best contributing and reviewing. :smile:
