### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by summerghw** [galaxyproject/tools-iuc#2668]
hi, i was using galaxy 19.05 install tpp4.8.0.  and i had a error that i dont know how to fix.
```
File "lib/tool_shed/galaxy_install/install_manager.py", line 121, in install_and_build_package_via_fabric
    tool_dependency = self.install_and_build_package(install_environment, tool_dependency, actions_dict)
  File "lib/tool_shed/galaxy_install/install_manager.py", line 79, in install_and_build_package
    initial_download=True)
  File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 31, in execute_step
    initial_download=initial_download)
  File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 548, in execute_step
    dir = self.url_download(work_dir, downloaded_filename, url, extract=True, checksums=checksums)
  File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 77, in url_download
    extraction_path = archive.extract(install_dir)
  File "lib/galaxy/util/compression_utils.py", line 124, in extract
    self.archive.extractall(extraction_path, members=self.safemembers())
  File "/usr/lib/python2.7/tarfile.py", line 2075, in extractall
    for tarinfo in members:
  File "lib/galaxy/util/compression_utils.py", line 151, in safemembers
    raise Exception("Link '%s' to '%s' is blocked." % (finfo.name, finfo.linkname))

Link './lib/libbz2.so' to './libbz2.so.1.0.4' is blocked.
```
i try to install manually ,i can uncompress the tpp_package.tar.gz and the tools seems good to use. 
but i cant use them through galaxy.  please help. thanks.

**Comment by nsoranzo** [comment]
@summerghw Unfortunately Tool Shed packages are not supported any more by IUC, please use Conda to resolve dependencies for your tool.

**Comment by summerghw** [comment]
@nsoranzo  thank you for replay.  by the way would you know how to install packages (tpp.4.8.0) to galaxy by conda?     
Beause all i can do now is using conda to install tools to linux , and manually write XML scripts to make galaxy reconigse these tools.  but tpp.4.8.0 package has so many tools . is there any wrapper already done by iuc.   Or can i change url in the the tool_shed_config.yaml  to conda url.  thank you so much .

**Comment by bgruening** [comment]
@summerghw sure we also have TPP :)
But this is in our Proteomics repository. For example here: https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/decoyfasta/tools/decoyfasta.xml

Please note that there are a few tools from TPP already in Galaxy the link above is just one.

**Comment by summerghw** [comment]
@bgruening  thank you for replay.    so is there any way that i can install tpp(4.8.0) or tpp(5.2.0) with tool_shed .     i installed most tools in galaxyproteomics.  but still can't accomplish tpp workflow.  and the tpp(4.8.0) packages is buggy and nolonger surpported.   but i find that conda had tpp packages.  i want to know can i install tpp by conda ?

**Comment by bgruening** [comment]
I think you can install https://anaconda.org/bioconda/tpp/files version 5.0 via conda. Hopefully, the tools will then work. What we need to do is to update the Galaxy tools to 5.0 or create a new conda package for 5.2 and update the Galaxy tools straight to 5.2.

**Comment by summerghw** [comment]
@bgruening thank you so much.  i installed tpp(5.0) by conda, everything is ok on linux ,  i am trying to make these tools reconigsed by galaxy.
