### ISSUE TITLE
Picard SamToFastq tool fails, even prior test re-runs, at both EU and ORG

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2747]
----

**Workaround for End-users**

* Use this alternative tool: `Samtools fastx extract FASTA or FASTQ from alignment files`
* Located in the tool panel grouping `SAM/BAM` on most Galaxy servers.
* Find it using the tool search function at the top of the left tool panel.
* If running your own Galaxy server, the tool may need to be installed from the ToolShed.
  * Full Samtools suite, including this tool (strongly recommended): https://toolshed.g2.bx.psu.edu/view/iuc/suite_samtools/291529b5bbb3
  * Individual tool: https://toolshed.g2.bx.psu.edu/view/iuc/samtools_fastx/a8d69aee190e

----

**Issue details**

The tool creates two or more outputs: 
1. Active datasets with datatype `fastqsanger`. How many depends on params.
1. A hidden dataset with either `BAM` or `SAM` in a dataset with datatype `txt` 

Problems:
* Rerunning prior test fails now (at ORG, direct rerun or in a workflow)
* Running that same prior test at EU also fails
* Running with the updated tool version or a different BAM also fails
* All failures are a single dataset, no matter what the params are, instead of active + hidden datasets
* Fails whether run in workflow or directly from history
* Tool was migrated from tools-devteam to tools-iuc sometime in the last year or so
* MTS: https://toolshed.g2.bx.psu.edu/view/devteam/picard/7d34178f2812

Test histories:
Expand the annotation to find share links to workflows used for some of the tests. Everything is tagged/labeled with the input, params, tool versions.
* https://usegalaxy.org/u/jen/h/test-datatype-sam-to-fastq (includes original test for issue below)
* https://usegalaxy.eu/u/jenj/h/test-datatype-sam-to-fastq

@martenson was able to reproduce
@jmchilton confirmed this tool is a bit special, uses "dataset discovery"
~~@nsoranzo~~ @mvdbeek commented on Ghelp post that it looks like bug and gave user a workaround (post job action in workflow). That is fine but is from using some much older version of the tool.
@jennaj tested it in 7/2018 when the output datatype was updated. Test passed back then: https://github.com/galaxyproject/tools-devteam/issues/414 

A user reported that they were getting `txt` instead of `fastqsanger` outputs, but that must be from some much older version of the tool (we fixed that). They haven't confirmed which version yet or where they are working (probably ORG), but those don't matter. That was fixed and the current versions are failing, including a version that did work before (the "corrected datatype" fix). Post: https://help.galaxyproject.org/t/workflow-canvas-why-is-the-output-for-samtofastq-txt-instead-of-fastq/2630

**Comment by jennaj** [comment]
Any updates? Thx!

**Comment by bernt-matthias** [comment]
I guess this is solved in https://github.com/galaxyproject/tools-iuc/pull/2855.. Can you retry with the most recent version and reopen if needed?

**Comment by jennaj** [comment]
Tested version 2.18.2.2 -- works great now both `eu` and `org`, sorry for delay
