### ISSUE TITLE
Bad URL for RNAshapes Mac OS X download

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#280]
Getting a 404 for http://bibiserv.techfak.uni-bielefeld.de/spool/download/bibiserv_1383039523_10840/RNAshapes-2.1.6-osx.tar.gz in tools-iuc/packages/package_rnashapes_2_1_6/tool_dependencies.xml

Spotted during testing for https://github.com/galaxyproject/planemo/issues/303

**Comment by bgruening** [comment]
I contacted the authors, thanks.
