### ISSUE TITLE
picard samtofastq not usable in workflows

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/tools-iuc#2854]
This tool dynamically created different outputs depending on user selection, breaking its use workflows.

**Comment by bwlang** [comment]
this may be related to #2747

**Comment by bwlang** [comment]
@mvdbeek this looks like a mess to me...
I'm thinking about ditching all the fancy output detection stuff and just make an interleaved fastq file.  I don't backward compatibility matters much here - this tool doesn't even work.

thoughts?

**Comment by mvdbeek** [comment]
Why not use https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/samtools_fastx/samtools_fastx/1.9+galaxy1 ? This should handle everything properly.

**Comment by bwlang** [comment]
Samtools fastx tool doesn't produce interleaved output and it it’s harder to use correctly (have to carefully specify flags and prefilter)

I just got burned by it producing odd fastq that made salmon produce 20% alignment rat, I get 80 % alignment from the same reads produced by Picard sam to fastq on the command line.


--
Bradley W. Langhorst, Ph.D.
langhorst@neb.com<mailto:langhorst@neb.com>

**Comment by mvdbeek** [comment]
Thanks for fixing that @bwlang, much appreciated!
