### ISSUE TITLE
https://depot.galaxyproject.org is missing some R packages

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#286]
https://depot.galaxyproject.org is missing some R packages:
- http://depot.galaxyproject.org/package/darwin/x86_64/R/R-3.1.1-Darwin-x86_64.tgz as used in `tools-iuc/packages/package_r_3_1_1/tool_dependencies.xml`
- https://depot.galaxyproject.org/package/linux/x86_64/R/R-3.2.0-Linux-x84_64.tgz in /`tools-iuc/packages/package_r_3_2_0/tool_dependencies.xml`

These are the only precompiled binaries for these packages, otherwise it is built from source. I am puzzled why pre-built binaries for both Linux and Mac were not done for both R 3.1.1 and 3.2.0?

**Comment by blankenberg** [comment]
ping @davebx

**Comment by davebx** [comment]
@peterjc My guess, and this is only a guess, is that whoever built the packages named them incorrectly. When I find out who that was, I'll glare at them to fix it.

**Comment by davebx** [comment]
@peterjc Followup - I fixed the 3.2.0 misnamed tarball, the 3.1.1 tarball doesn't actually exist.

**Comment by peterjc** [comment]
Thanks @davebx - Is there meant to be an R 3.1.1 for Linux instead?

**Comment by davebx** [comment]
@peterjc I seem to recall versions of R starting with 3.x are not feasible to build for OSX.

**Comment by peterjc** [comment]
@davebx Should https://depot.galaxyproject.org/package/linux/x86_64/R/R-3.2.0-Linux-x84_64.tar.gz be renamed to https://depot.galaxyproject.org/package/linux/x86_64/R/R-3.2.0-Linux-x84_64.tgz or should the URL in ``tool_dependencies.xml`` be updated to use the other extension?
