### ISSUE TITLE
populations: invalid option -- 'b' error

### ISSUE THREAD

**Issue by ribaslej** [galaxyproject/tools-iuc#2863]
Hi all, 

I'm beginning to work on galaxy online and radseq data and I'm having a problem running the populations module on Stacks2. When I run denovo_map.pl it completes and give the correct outputs, but if I run again the populations on gstacks output with different parameters it fails. I tried to make all the way to populations (ustacks, cstacks, sstacks, tvs2bam and gstacks) but the same happens when I run populations module. I want to run populations with outputs for structure, vcf, Phylip format, as well as Fst statistics and HWE.

"Error Details
Execution resulted in the following messages:

Fatal error: Exit code 1 ()
Tool generated the following standard error:

   populations: invalid option --'b'   "

 I guess it is something related to my population map but i can't figure it out. Tried to sort the samples alphabetically, in order of the inputs, in sequencial numbers... Population map contains 10 populations, almost all with four individuals and one with just one individual.

Population map is a .txt file like this:

name(prefix)           pop(integer) <- not in the file
prefix_sample1TAB1
prefix_sample2TAB1
prefix_sample3TAB1
prefix_sample4TAB2
prefix_sample5TAB2
prefix_sample6TAB3

Data is a single-digested RADseq that was previously demultiplexed, trimmed and quality-filtered.

Gratefull if anyone could help! 
Luiz Eduardo

**Comment by bernt-matthias** [comment]
Hi @ribaslej do you have your analysis on a public Galaxy? Then you could share your history with us. 

Otherwise could you provide the input data and tell us which parameters you changed from the defaults?

**Comment by ribaslej** [comment]
Hello Matthias,

My input data are 34 samples, one per file, each composed of several reads with 95bp. First five bp are the restriction enzyme. Format is fastq.gz (I uploaded it as fastqsanger)

I ran the pipeline in two ways, parameters below. I see no difference between the two rans: secondary alingment reads - 2/4; and gapped assembly - FALSE/TRUE.

**ALL THE WAY DOWN (ustacks, cstacks, sstacks, tvs2bam, gstacks):**
ustacks parameters selected:
  Input file: 'stacks_inputs/CA08.1.fastq'
  Sample ID: 1
  Min depth of coverage to create a stack (m): 3
  Repeat removal algorithm: enabled
  Max distance allowed between stacks (M): 2
  Max distance allowed to align secondary reads: 2
  Max number of stacks allowed per de novo locus: 3
  Deleveraging algorithm: disabled
  Gapped assembly: disabled
  Model type: SNP
  Alpha significance level for model: 0.05

cstacks parameters selected:
  Loci matched based on sequence identity.
  Number of mismatches allowed between stacks: 1
  Gapped alignments: disabled

sstacks has no parameter in logfile

tsv2bam v2.4, executed 2020-02-10 04:56:35 (zlib-1.2.11)
tsv2bam -P stacks_inputs -M /data/dnb02/galaxy_db/files/013/370/dataset_13370361.dat --pe-reads-dir stacks_inputs -t 1
Configuration for this run:
  Stacks directory: 'stacks_inputs/'
  Population map: '/data/dnb02/galaxy_db/files/013/370/dataset_13370361.dat'
  Num. samples: 34
  Paired-end reads directory: 'stacks_inputs/'

gstacks was set to de novo mode and marikulow model

This way I receive the error message when I run populations module.

 (order of samples is not the same in this two ran, but corrected  it and still find the error)
**Parameters direct from denovo_map logfile:**
ustacks -t fastq -f stacks_inputs/PL01.fastq -o stacks_outputs -i 1 -p 1 -M 2
ustacks parameters selected:
  Input file: 'stacks_inputs/PL01.fastq'
  Sample ID: 1
  Min depth of coverage to create a stack (m): 3
  Repeat removal algorithm: enabled
  Max distance allowed between stacks (M): 2
  Max distance allowed to align secondary reads: 4
  Max number of stacks allowed per de novo locus: 3
  Deleveraging algorithm: disabled
  Gapped assembly: enabled
  Minimum alignment length: 0.8
  Model type: SNP
  Alpha significance level for model: 0.05

cstacks parameters selected:
  Loci matched based on sequence identity.
  Number of mismatches allowed between stacks: 1
  Gapped alignments: enabled
Constructing catalog from 34 samples.

gstacks -P stacks_outputs -M /data/dnb02/galaxy_db/files/013/341/dataset_13341550.dat -t 1 --var-alpha 0.01 --gt-alpha 0.05

tsv2bam -P stacks_outputs  -M /data/dnb02/galaxy_db/files/013/341/dataset_13341550.dat -t 1

**populations**
populations -P stacks_outputs -M /data/dnb02/galaxy_db/files/013/341/dataset_13341550.dat -t 1 --min-samples-per-pop 1 --min-populations 1

Logging to 'stacks_outputs/populations.log'.
Locus/sample distributions will be written to 'stacks_outputs/populations.log.distribs'.
populations parameters selected:
  Percent samples limit per population: 1
  Locus Population limit: 1
  Percent samples overall: 0
  Minor allele frequency cutoff: 0
  Maximum observed heterozygosity cutoff: 1
  Applying Fst correction: none.
  Pi/Fis kernel smoothing: off
  Fstats kernel smoothing: off
  Bootstrap resampling: off

This way it run populations module, but when I try to run again populations on gstacks with other outputs like outputs for structure, vcf, Phylip format, Fst statistics and HWE, it shows the error message. Am I correct thinking that "(-b)" is related to population map or some kind of barcode file?

population map:
CA08	2
CA13	2
CA51	2
FN65	7
FN68	7
FN69	7
FN70	7
NM81	9
NM86	9
NM89	9
NM91	9
NO19	3
NO26	3
NO27	3
NO28	3
NU131	4
NU137	4
NU254	5
NU255	5
NU256	5
NU257	5
PB40	6
PB41	6
PB48	6
PB49	6
PL01	1
PL03	1
PL14	1
PL18	1
SP76	8
SP77	8
SP78	8
SP80	8
TS92	10

Thank you,
Luiz Eduardo.

**Comment by bernt-matthias** [comment]
Hi @ribaslej .. Can you confirm if you have set a value for the parameter `Number of loci to process in a batch` (`--batch-size`). There is a bug in the Galaxy tool that would lead to the exact error message that you posted, i.e. `invalid option --'b' "`.

**Comment by ribaslej** [comment]
Yes, I set 10000.

**Comment by bernt-matthias** [comment]
OK. Then this bug will be fixed by https://github.com/galaxyproject/tools-iuc/pull/2869 

Meanwhile you may run populations and leave this parameter empty -- since 10000 is the default it does not need to be set.

**Comment by ribaslej** [comment]
Thank you for your attention and time! And quick solution.

Regards,
Luiz Eduardo.
