### ISSUE TITLE
matplotlib_1_4 fails to build due to missing freetype library

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#289]
Attempting to install package_matplotlib_1_4 from the main toolshed into an instance from docker-galaxy-stable I get the following error:

    * The following required packages can not be built:
    * freetype

I suspect it's related to https://github.com/matplotlib/matplotlib/issues/3029/

**Comment by bgruening** [comment]
@lparsons not sure this is related to the bug, `pkg-config` is installed in Docker and as far as I can see freetype has this PATH set. I need more time to figure this out.

**Comment by bgruening** [comment]
@lparsons I have a fix for this included in https://github.com/galaxyproject/tools-iuc/pull/283 and it is pushed to the TSs. Please test. 
One problem still remains and that is that we need a recent setuptools in Galaxy's virtualenv. I have a patch for the Galaxy Docker container here: https://github.com/bgruening/docker-galaxy-stable/pull/96

Hope this will solve your issues.

**Comment by lparsons** [comment]
@bgruening Those two fixes seemed to do the trick, thanks!

**Comment by bgruening** [comment]
Great, I will merge this. Thanks for testing.
