### ISSUE TITLE
datamash parameter -W should be removed

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#291]
`-W, --whitespace use whitespace (one or more spaces and/or tabs) for field delimiters`

This means that if we have a tabular file with a header that contains spaces we create more rows than columns. I think this is not what the user expects. Either we simply remove `-W` or we make it optional, maybe even with a select to the `--field-separator`.

**Comment by nsoranzo** [comment]
:+1: to remove it.
