### ISSUE TITLE
set slots to use more threads in tool xml

### ISSUE THREAD

**Issue by AjitPS** [galaxyproject/tools-iuc#2916]
Using the parameters in https://github.com/galaxyproject/tools-iuc/blob/master/tools/raxml/raxml.xml#L9 launches jobs on our own Galaxy instance (using Slurm) with `just 1 thread`. 
We have $GALAXY_SLOTS=6 set on our HPC but seems to not get picked up correctly by the worker nodes in the cluster. 

Our Galaxy job_conf already allocates 10G memory and 10 cores to RaXML jobs that I (http://github.com/AjitPS/) set a while back.

FYI, disccused with https://github.com/hughesdj and added workaround in the `raxml.xml` to set slots=6 in the xml so it picks up `--binary "raxmlHPC-PTHREADS"` --threads 6 when running now.

**Comment by bernt-matthias** [comment]
Hey @AjitPS could you test this https://github.com/galaxyproject/tools-iuc/pull/2920 .. given that the tests pass

**Comment by bgruening** [comment]
@AjitPS should be fixed in the new version.
