### ISSUE TITLE
hicCorrelate cannot find 'range_min'

### ISSUE THREAD

**Issue by cgirardot** [galaxyproject/tools-iuc#2952]
Hi, 
I just tried to use the `Range restriction (in bp)` option in the hicCorrelate (Galaxy Version 3.4.3.0) and got the error: `cannot find 'range_min'` (I did provide one of course). I guess this is a wrapper.xml issue but I cant find the bug 🙄

**Comment by bernt-matthias** [comment]
Do you have an example somewhere (or could you extend a test) in order to reproduce the issue.
