### ISSUE TITLE
Balance chunks in ci workflow

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#2959]
Currently the workload measured in terms of repos per chunk (and tests per chunk) is quite imbalanced:

chunk_id | number_of_tools | number_of_tests
-------------|------------------------|-----------------------
28|150|356
18|121|125
13|84|236
23|78|141
33|57|150
30|57|104
29|37|60
7|34|145
15|33|54
20|31|73
35|27|75
37|26|60
31|26|68
26|26|36
21|26|33
34|23|54
25|23|49
36|22|57
17|22|17
9|21|74
39|20|36
32|18|39
12|18|58
14|17|40
38|16|45
3|16|22
24|15|47
16|15|44
27|14|38
22|13|18
19|11|20
0|11|17
8|10|44
6|10|30
4|10|23
2|10|7
1|10|4
10|10|13
5|9|76
11|9|11

So I would suggest the following:

- get the list of tools
- group the tools of the same repo on a single line
- use the grouped tool list in planemo t

```
planemo ci_find_tools --chunk_count 40 --chunk ${{ matrix.chunk  }} --exclude test_repositories --exclude packages --exclude deprecated --exclude_from .tt_skip --exclude_from .tt_biocontainer_skip --output tool.list

for repo in $(while read tool; do dirname $tool; done < tool.list | uniq)
do
grep $repo tool.list | tr '\n' ' ' && echo  
done > grouped_tool.list
```

Hence we would still have (in each chunk) one call to planemo per repo, i.e. no problems with docker containers piling up. Though, over all chunks we would have a few more calls to planemo.

The stats would look like this:

chunk_id | number_of_tools | number_of_tests
-------------|------------------------|-----------------------
9|31|58
8|31|70
6|31|87
4|31|87
38|31|70
36|31|89
35|31|56
33|31|61
3|31|101
32|31|101
30|31|54
28|31|47
27|31|80
25|31|71
24|31|75
22|31|47
20|31|68
19|31|45
17|31|38
16|31|63
14|31|20
1|31|34
12|31|23
11|31|42
0|31|28
7|30|84
5|30|83
39|30|68
37|30|78
34|30|103
31|30|96
29|30|45
26|30|70
23|30|83
2|30|117
21|30|70
18|30|64
15|30|71
13|30|22
10|30|65

This would also avoid the the special treatment of data managers.

What do you think @nsoranzo and @mvdbeek

**Comment by mvdbeek** [comment]
This should be part of planemo, but otherwise that sounds great!

**Comment by bernt-matthias** [comment]
Indeed this turned out to be much easier https://github.com/galaxyproject/planemo/pull/1008
