### ISSUE TITLE
IUC member proposal - Youri Hoogstrate

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#296]
Hi Commissioners,

I would like see Youri Hoogstrate (@yhoogstrate) becoming an IUC member.
Youri already contributed a lot to the bgruening/galaxytools repository, the iuc-tools wrappers and the main Galaxy codebase. He is especially familiar with visualisations and R based tools. Youri also participated
actively at the last GCC and is proficient in tool developing and his reviews are very good!

I will try to assist him in the first month if he has IUC related questions.

Please comment and vote!
Bjoern

**Comment by nsoranzo** [comment]
:+1:

**Comment by erasche** [comment]
:+1:

**Comment by blankenberg** [comment]
:+1:

**Comment by blankenberg** [comment]
(Can we make a document listing the requirements/guidelines and process for modifying membership of the IUC available publicly?)

**Comment by davebx** [comment]
:+1:

**Comment by bgruening** [comment]
With this I would like to welcome Youri as a new IUC member! 🌻
Wonderful times ahead!
