### ISSUE TITLE
Missing Seurat Dependency

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/tools-iuc#2970]
When I run the Seurat tool (I installed it today), I get the following error when I select "Yes" on all the "Output options":

![seuratrmarkdown](https://user-images.githubusercontent.com/2300532/79380917-20e09100-7f2f-11ea-84ac-d1c6dfb23e2a.png)

```
Error in library("rmarkdown") : there is no package called ‘rmarkdown’
Execution halted
```

I do not get that error if I do not select yes on those options.

**Comment by bgruening** [comment]
Mh it seems to be defined :(

https://github.com/galaxyproject/tools-iuc/blob/master/tools/seurat/seurat.xml#L8

Can you have a look in your conda environment, which packages are installed.

**Comment by hepcat72** [comment]
Seems that it just hadn't finished installing.  The install had said it was done, but now when I run, it seems to find it.  Closing.
