### ISSUE TITLE
Cutadaptor 3'adapter anchoring 

### ISSUE THREAD

**Issue by ile87** [galaxyproject/tools-iuc#2986]
Hi,
I am running cutadapt to remove the adapters from Illumina reads. When I input the sequence of the 3’ adapter, I add the dollar character at the end to anchor the adapter. However, in the report the dollar character ($) is indicated as an X and my adapter sequence is not indicated as anchored but regular. I have no problem when using the anchoring with the 5' adapter. I assume that there is an issue with the tool in Galaxy not recognising the dollar character.
Can anyone help with this or have any suggestion?
Thanks

![image](https://user-images.githubusercontent.com/64087941/79989195-7ecd2580-84a7-11ea-90d5-76753e6dfc98.png)

**Comment by hexylena** [comment]
Moved to tools-iuc as it is an issue with the cutadapt wrapper potentially.

**Comment by peterjc** [comment]
I've used cutadapt at the command line, and would guess this is due to Galaxy mapping the special character ``$`` in the adapter argument to ``X`` under the default security rules. Can you show us the command line Galaxy ran for cutadapt which would probably confirm this guess?

If so, the wrapper can probably be fixed to allow the dollar sign with suitable precautions on single-quoting the arguments in the command line.

**Comment by ile87** [comment]
Hi peterjc,
I think what you describes might indeed be the issue.

Here is the command line from the report:

This is cutadapt 1.16 with Python 3.6.6
Command line parameters: -a brc2=ACATCGX -g ^TAATACGACTCACTATAGGGCAAGCAGTGGTATCAACGCAGAGTACATGGG --untrimmed-output=untrimmed_output.fq.gz -A CCCATGTACTCTGCGTTGATACCACTGCTTGCCCTATAGTGAGTCGTATTAX -G ^CGATGT --untrimmed-paired-output=untrimmed_paired_output.fq.gz --output=out1.fq.gz --paired-output=out2.fq.gz --error-rate=0.1 --times=1 --overlap=3 --pair-filter=any Sample1--_R1_001_fastq_gz.fq.gz Sample1--_R2_001_fastq_gz.fq.gz
Running on 1 core
Trimming 4 adapters with at most 10.0% errors in paired-end mode ...
Finished in 8.56 s (102 us/read; 0.59 M reads/minute).

Many thanks

Ileana

**Comment by peterjc** [comment]
Yes, Galaxy is calling ``cutadapt ... -A CCCATGTACTCTGCGTTGATACCACTGCTTGCCCTATAGTGAGTCGTATTAX ...`` where the trailing ``X`` ought to be a ``$``. This will need a tweak in ``macros.xml`` to single-quote wrap the ``-A`` argument (and the others like ``-a``, ``-G`` and ``-g``, and ``-B`` and ``-b``), and whitelisting the ``$`` character in those arguments.

I don't have time to work on this right now, but glad to have been able to help diagnose the problem.

**Comment by bernt-matthias** [comment]
would someone of you be able to check or test https://github.com/galaxyproject/tools-iuc/pull/3109 ?
