### ISSUE TITLE
IUC Contribution Fest - Metagenomics Tools and Workflows

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/tools-iuc#299]
Remote Contribution Fest happens on 30 Nov and 1 Dec
---

We are planning a Remote Contribution Fest on **30th of November and 1st of December** for developers to work mainly on Galaxy metagenomic tools.

The remote nature of this gives people who don't have the opportunity to come to GCC hackathons (which have always been productive and a lot of fun) a chance to participate in a Galaxy hackathon. Having a well defined topic will allow us to accomplish a lot and let people who don't have particular tasks in mind find something to work on very quickly.

We are collecting ideas to work on, but we expect to attract the most participation by simply getting tool developers interested in getting help adding collection support to their existing tools and workflows to show up and participate.

If you are interested in participating in the hackathon but not interested in actual tool development - we will assemble a list of smaller, manageable Python and JavaScript tasks to work on and certainly documentation is a chronically lacking for collections so we could use help there and no actual coding would be required.

We encourage ideas or advice about how to organize this so please let us know. A core group will be available on IRC all day and we will have 4 google hangouts across those days to organize, answer questions, and report progress.

*We will do our best to coordinate and make this hackathon a nice and productive experience and we would like to especially focus on working reasonable hours and discourage overnighters.*

**All forms of contribution are welcome!**

Original idea from @bgruening (https://github.com/galaxyproject/tools-devteam/issues/26#issuecomment-126957869). See #239 for information on the last hackathon.

# Things to work on

 - [Improve QIIME Tool Generator and Tools](http://dev.list.galaxyproject.org/QIIME-tools-for-Galaxy-WIP-call-for-collaborators-td4668035.html) as proposed by @lparsons. Please refer to https://github.com/galaxyproject/tools-iuc/issues/426
 - Generate high-quality datatypes for the **biom datatype** (http://biom-format.org/documentation/biom_format.html) as proposed by @blankenberg.
  - **Phinch** visualization (GIE?) for Biom data (https://github.com/PitchInteractiveInc/Phinch) proposed by @erasche
 - unified Mothur wrappers: https://github.com/galaxyproject/tools-iuc/issues/419
 - **Mash**: MinHash-based method for rapidly estimating pairwise distances between genomes or metagenomes. https://github.com/marbl/Mash (TS package: https://github.com/galaxyproject/tools-iuc/pull/427)
 - [diamond](https://github.com/bgruening/galaxytools/tree/master/tools/diamond) update (TS package: https://github.com/galaxyproject/tools-iuc/pull/428)
 - vegan: A couple of tools exist under IUC already, what other functions useful as first-class tools (as opposed to R via GIEs)
 - Generic tools for dealing with outputs in collections and their products. 
    - @blankenberg has a list of tabular collection to single tabular dataset joining tool and some enhancements started on cut tool to deal with step size in ranges

# Google Maps link - please add yourself
https://www.google.com/maps/d/edit?mid=zQipez5uCQ8I.khoUIhze9Fek&usp

# Google Hangout
https://hangouts.google.com/call/iems2ffkpd4s7cyjoq4mi3hgwma

# IRC
https://wiki.galaxyproject.org/News/IRCPublicLogProposal

**Comment by erasche** [comment]
:+1: to biom, I'd be happy to do a finch viz plugin/tool if a biom datatype was available

**Comment by jmchilton** [comment]
@erasche - add to the TODO list and sign yourself up :smile:

**Comment by bgruening** [comment]
It would be lovely if we could get @jennaj on-board and maybe can create a workflow that we stick into the Tool Shed and myexperiments.org.

**Comment by jennaj** [comment]
@bgruening Funny this should come up here - it was also brought up last Fri at a data hack meeting. Metagenomics is definitely on the table for the next cycle. Maybe we can combine forces :) I'll email the data hacks with a link to this.

**Comment by bgruening** [comment]
Thanks @jennaj!

**Comment by nekrut** [comment]
Perhaps we need a bit of a big picture. Improving individual tools is necessary, but we should focus on entire types of MG workflows (e.g., what are potential complete workflows for doing human microbiome studies). This is best accomplished using actual biological projects. Can you guys make a list of analyses you are currently supporting. I'll describe mine

**Comment by lparsons** [comment]
@nekrut Great point and a very good first step. I'm looking to analyze 16S data to generate OTU percentages per sample and PCA plot for diversity analysis. Following a workflow similar to that outlined in http://nbviewer.ipython.org/github/biocore/qiime/blob/1.9.1/examples/ipynb/illumina_overview_tutorial.ipynb

**Comment by bobbledavidson** [comment]
I like the idea of linking up the GalaxyScientists (@JennaJ's data hackers) with the IUC for this - it would be good to have a project to foster some dialogue between these two groups.

**Comment by tiagoantao** [comment]
I am not a metagenomics person, but I have seen people struggling with the mothur tool (if you install it, you will see what I mean). My impression is that a few workflows would help a lot. If you look at the mothur documentation, you could easily get inspiration. For example here: http://www.mothur.org/wiki/Analysis_examples

PS - You could consider doing a RAD-seq hackathon in the future. I would like to help on that one...

**Comment by bebatut** [comment]
I'm currently developing a Galaxy instance dedicated to gut microbiota data processing (metagenomics and metatranscriptomics). I made some wrappers for tools such as HUMAnN, MetaPhlAn, SortMeRNA, Reago, PRINSEQ, for which I did not find wrappers fitting my requirements. The aim is to construct a workflow to process data from intestinal microbiota.
I would like to join you on this hackathon

**Comment by bgruening** [comment]
@bebatut this is awesome. If you like please join this hackathon and we could review your wrappers if you like.
Btw.: SortMeRNA and PRINSEQ wrappers are already here
 * https://github.com/bgruening/galaxytools/tree/master/tools/prinseq
 * https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/sortmerna

@tiagoantao excellent suggestion!

**Comment by nsoranzo** [comment]
@bebatut MetaPhlAn and SortMeRNA are also on the Tool Shed, please do not reinvent the wheel, if something is missing please contribute to the already available tools!

https://toolshed.g2.bx.psu.edu/view/rnateam/sortmerna/
https://toolshed.g2.bx.psu.edu/view/dannon/metaphlan/

@bgruening Should PRINSEQ also be published on the MTS or it's not ready yet?
@dannon What about adding metaphlan wrapper code to the IUC github repo?

**Comment by bgruening** [comment]
@nsoranzo PRINSEQ It needs some more love but it was on a good way. Happy to work with @bebatut on this during the hackathon.

**Comment by bebatut** [comment]
@bgruening @nsoranzo I saw the wrappers for Prinseq and SortMeRNA, but they do not correspond to what I wanted. For example, not all the parameters are accessible with SortMeRNA wrapper. 
I developed a wrapper for MetaPhlAn 2 not for MetaPhlAn...

**Comment by bgruening** [comment]
@bebatut let's merge our wrappers during the hackthon and join (maintenance) forces!

**Comment by tiagoantao** [comment]
I think that there is a bug in the kraken data manager.
Try the following
admin>local data>Run data manager tools>Kraken

Select partial library to download> Human

Depending on my galaxy installation I am getting different errors. The most common is not being able to download human chromosomes. But works well with the other options

**Comment by nekrut** [comment]
https://test.galaxyproject.org/u/sjcc/w/16s

Here is the king of stuff we are currently doing:

Input  > Quality Trim (FASTQ Quality Trimmer) > Join R1 + R2 (fastq-join) > remove reads with ambiguous bases (Manipulate FASTQ) > remove chimeras (cd-hit-dup) > assign reads to taxon (Kraken) > filter Kraken by confidence level (Kraken-filter) > translate taxon id number into taxon name (Kraken-translate) > report Kraken results (Kraken-report) 

Filter Kraken report to see what data you want (Filter) <-- I use this to isolate a taxonomic level (i.e. P, C, O, F, G, S)

Rarefaction analysis (Vegan Rarefaction)
Diversity (Vegan Diversity)

**Comment by bgruening** [comment]
@tiagoantao can you move this bug report to a proper issue, so it get not lost?
@nekrut thanks very useful. We could work on materializing this into a TS workflow with documentation. Anything on you wishlist, preferably a "easy" tool without *.loc files?

**Comment by jmchilton** [comment]
I think we as Galaxy community should also consider a Brew related hackathon (https://github.com/Homebrew/homebrew-science/issues/2876) and I would like if we could schedule one or the other for November. Any particular thoughts on whether we should do this one in November and the Homebrew one in January or vice versa?

**Comment by bgruening** [comment]
November for the metagenomic Codefest and January for the next. Until then we can make the brew idea more concrete.

**Comment by bgruening** [comment]
What about the 5th and 6th of November? To early?

**Comment by jmchilton** [comment]
@bgruening I'll be at a conference on the 5th and traveling on the 6th. I don't know if Anton intends to participate directly with the hackathon but he will be at the same conference. Obviously I have much less to contribute to a metagenomics hackathon than a collections one though, so feel free to continue without me. I could do the 19th and 20th or the 9th and 10th.

**Comment by jennaj** [comment]
2nd Nov 9th and 10th. Some of us might or could be in PA that are not otherwise, which could be nice if the primary reason for being there does not conflict (occurs later in the week).

**Comment by blankenberg** [comment]
BIOM xref: https://github.com/galaxyproject/galaxy/issues/941

**Comment by lparsons** [comment]
I could do either of: 5th and 6th, 9th and 10th, or 19th and 20th.  That said, the 9th and 10th are looking rather nice.

**Comment by jmchilton** [comment]
@bgruening Can you do the 9th and 10th?

**Comment by bgruening** [comment]
If so I will sitting next to you and will have hard time to motivate peoples from Freiburg remotely.
But yes, I'm ok with this.

**Comment by jmchilton** [comment]
Oh - yeah I suppose that might not be the best use of your limited time here. Forgot about that.

**Comment by bgruening** [comment]
30th of November and 1st of December?

**Comment by jmchilton** [comment]
This works for me.

**Comment by lparsons** [comment]
Nov 30th-Dec 1st works for me.

**Comment by bgruening** [comment]
It seems that we have a schedule :)
If no one else speaks up I will write a mail with the announcement tomorrow.

**Comment by martenson** [comment]
edited the leading post to be more like #239

**Comment by martenson** [comment]
An inspiration how Jenkins community does virtual hackathons: http://www.meetup.com/jenkinsmeetup/events/226735213/

**Comment by erasche** [comment]
Neat! I like the presentation aspect for newcomers.

**Comment by shiltemann** [comment]
+1 to Phinch! (that was next on my to-do list) 

I have also been working on creating mothur pipelines lately, many of the tools have variable number of inputs and outputs, making them hard to use in workflows. I've been rewriting the ones I need to produce and consume collections instead, would be nice to do this for the entire toolsuite.

**Comment by yvanlebras** [comment]
Hi everyone,

Thanks for this very interesting proposal!

A litlle message to inform you that we will be ~10 people from France interessed by this Hackathon. Thanks to western France GUGGO Galaxy group, INRIA, the French Institut of Bioinformatics and the Environmental Genomics CNRS group, we will centralized some actions at INRIA, Rennes.

Anybody can consult our draft of program (https://cesgo.genouest.org/groups/guggo/wiki/MEtagenomicsHackathon) but briefly, we planned to work on
* a new INRA Metagenomics Galaxy pipeline dedicated to find OTU, named FROGS ( [poster](https://www.researchgate.net/publication/282656276_FROGS_Find_Rapidly_OTUs_with_Galaxy_Solution), [Galaxy tools](https://github.com/geraldinepascal/FROGS), [test Genocloud instance](http://cloud-55.genouest.org/galaxy/)) using [Swarm](http://www.mn.uio.no/ifi/english/research/networks/clsi/seminars/061113.html)
* an IFREMER Metagenomics Galaxy pipeline dedicated to find OTU based on Qiime
* an ECOBIO Metagenomics Galaxy pipeline dedicated to find OTU based on Mothur
* the ASaiM pipeline to work on metagenomics / metatranscriptomics data [Galaxy Day presentation](http://bebatut-slides.github.io/galaxy-day_2015/#/1/3)

We will probably focus primarily on the toolshedization / dockerization / IFB cloudification of FROGS and ASaiM. Then, if we have time and/or if people particularly interested by these tasks, we propose to work on the modification of "home-made" Mothur and Qiime Galaxy tools.

I don't really know how a remote hackathon can work, So don't hesitate to give me some advices / informations.

We canhave opportunities for visioconfernece through [Renater Rendez-vous](https://rendez-vous.renater.fr/galhackmetafr)

**Comment by bgruening** [comment]
@shiltemann So I count you in for next week? :)
@yvanlebras this France community is awesome! I looking forward to this Codefest a lot. We usually have a google hangout open for the two days to coordinate us and to answer questions. In addition we are usually all on IRC.
A few IUC members will be there and help to answer questions and reviewing code if this is desired. We can also help with Docker and any other questions. I would propose to create an IUC branch for Mothur and Qiime so we can all contribute and merge our wrappers. Maybe we can create two teams one for Mothur one for Qiime ... we will see. The aim is to have a lot of fun to hack on tools and to improve Galaxy for Metagenomic!

**Comment by shiltemann** [comment]
Yup sure :) I don't have a whole bunch of time, but I'd be happy to contribute where I can :)

**Comment by IyadKandalaft** [comment]
@bgruening 
I think the idea for having a mothur team and a qiime team makes sense.  The mothur tool suite needs to be refactored in some way to make it a little more manageable.  When we did the upgrade from 1.27 to 1.33, I had a student develop a tool that parses out the mothur documentation to list all the changes since a version that you specify.  This should allow us to do another update of the Galaxy wrappers to 1.34+.

**Comment by oxyko** [comment]
Hey,

We are two developers from AAFC-MBB group (Canada), who are interested in contributing to Mothur and/or Quiime. Let us know if there is a kick-off meeting and/or Mothur/Quiime team that we can join.

Our Galaxy repo: https://github.com/AAFC-MBB/Galaxy

**Comment by bgruening** [comment]
@IyadKandalaft sounds great!
Let's start with your latest version. If you send it to me I will create a branch and the Mothur team can work on this one.

**Comment by IyadKandalaft** [comment]
@bgruening 
Latest mothur 1.33 wrappers & tool dependencies (same as the central tool shed version):
https://github.com/AAFC-MBB/Galaxy/tree/master/wrappers/Mothur_Toolsuite

**Comment by bgruening** [comment]
@oxyko do you have time to join this hackathon on: 30th of November and 1st of December
@IyadKandalaft can I take this and put it in an IUC branch?

**Comment by IyadKandalaft** [comment]
@bgruening of course you can - we are proponents of FOSS.

**Comment by oxyko** [comment]
@bgruening yep. Just wondering about the format/schedule

**Comment by bgruening** [comment]
@oxyko it the top post not clear enough? Do you have concrete questions? This is very informal we try to get people together and organise our activities over IRC / Google-Hangouts. Code will be managed via git and we have a few expert that can help reviewing and can answer tricky questions related to the Galaxy universe.
Last time we also fixed a few bug in Galaxy to make our wrappers even more awesome!

**Comment by bgruening** [comment]
@IyadKandalaft what do you think? https://github.com/galaxyproject/tools-iuc/issues/419

**Comment by oxyko** [comment]
@bgruening My concrete questions are: 
1. Is there going to be a kick-off meeting over the hangouts?
2. How to contact the 4 mentioned google hangouts on the day of the hackathon?

**Comment by bgruening** [comment]
1. Kick-off meeting is hard because we have so many timezone. If you like I will get an introduction and show a little bit planemo. Just let me know.
2. There will be only one hangout, I will post a link over on Friday or over the weekend and everyone can connect (let see how many people can join such a hangout :))

**Comment by oxyko** [comment]
Sounds great! I would appreciate a bit of an intro, since I haven't done remote hackathons before.

**Comment by bgruening** [comment]
Sure, we can do this. In general don't hesitate to ask questions at any time.

**Comment by yvanlebras** [comment]
Hi everyone,

just an update concerning Mothur. We have, in the GUGGO Tool Shed, quite old Mothur (1.32) tools developped by our bioinformatics core facility with colleagues from the CNRS / OSUR Environmental genomics core facility : http://toolshed.genouest.org/repository/view_repository?sort=name&operation=view_or_manage_repository&f-free-text-search=mothur&id=66701dbe65507c8c

I don't know if this can be, totally or in part, of interest for the Mothur community but I remember that the engineer who has working on it, Mathieu Bahin, have made large improvements of the existing (old) Mothur Galaxy tools.... Maybe someone from the "Mothur Galaxy" (@IyadKandalaft ?) can evaluate this?
An introduction (on remote hackathon &/or on metagenomics pipeline) can be of interest

**Comment by pjbriggs** [comment]
Apologies for arriving late: I've now got the okay from my superiors to contribute to the toolfest next week. We have a number of users who would like to use Qiime within Galaxy so I'd like to offer effort towards making an "official" toolshed version of the Qiime tools as originally proposed by @lparsons.

We have a list of specific Qiime components that we're interested in, all of which are already have versions in [Lance's github repo](https://github.com/lparsons/galaxy_tools/tree/qiime/tools/qiime1.9.0). So I'll be available to contribute general programming effort to work on any identified by the organisers (if there is such a list). However if there's a better way to contribute then please let me know - mainly we just want to help move this forward.

Aside from that: a while ago I developed a [data manager for the Mothur toolsuite](https://github.com/fls-bioinformatics-core/galaxy-tools/tree/master/data_manager_mothur_toolsuite), which is available on the test toolshed but never got developed further. If this is of interest to anyone here, again please let me know.

**Comment by bgruening** [comment]
@yvanlebras nice I have added it to: https://github.com/galaxyproject/tools-iuc/issues/419
@pjbriggs I have added the data manager to list potential todo list: https://github.com/galaxyproject/tools-iuc/issues/419
@pjbriggs I guess you and @lparsons can team up for a Qiime team :)

**Comment by yvanlebras** [comment]
@erasche @jmchilton the biom datatype proposed by @fescudie , who will participate to the hackathon, for the FROGS pipeline is maybe ok to propose to do a first phinch viz plugin/tool ?

**Comment by tiagoantao** [comment]
Just a side comment from someone that does not do metagenomics but sometimes help other people doing it: The mothur tool is very very complex to use a this stage. My impression is that a couple of well thought workflows would help a lot (even if the tool maintains the current format).

For example an implementation of some of their SOPs:
http://www.mothur.org/wiki/MiSeq_SOP
You can find a list here:
http://www.mothur.org/wiki/Analysis_examples

**Comment by IyadKandalaft** [comment]
As one of the developers on the galaxy mothur tools, I agree that we need
to include some workflows.  We have some workflows in-house that are based
off the sop.  I'd consider adding them into a separate repository with a
dependency on mothur.

**Comment by bgruening** [comment]
@shujianbu do you have time tomorrow to help with Phinch integration?

**Comment by yvanlebras** [comment]
Hi everyone,

Just few slides that we will use to briefly present the initiative, our pipelines and some To-Do.... : [Presentation slides](https://cesgo.genouest.org/resources/204)

I will update this document during the hackathon event. Don't hesitate to comment / ask questions. In France this will begin in 17 minutes ;)

**Comment by bgruening** [comment]
I updated the original post with links to a google hangout and our IRC channel, feel free to join!

**Comment by shujianbu** [comment]
Hi Bjorn,

What's the context/scope of the project integration? I haven't maintained
the Phinch code for a while.

Thanks,

**Comment by bgruening** [comment]
@shujianbu we want to integrate Phinch into [Galaxy](https://galaxyproject.org/). The idea is to put Phinch in a Docker container and integrate it into Galaxy. Every biom dataset that is created in Galaxy can than be visualised with Phinch without leaving the analysis platform.

Is/will Phinch be maintained? I have a pending PR since a few month.

**Comment by bgruening** [comment]
@yvanlebras awesome. When do you start?

I will also update the main issue above regularly with news. Here is our first PR that adds the Mash package: https://github.com/galaxyproject/tools-iuc/pull/427
Anyone up to write the wrappers?

**Comment by bgruening** [comment]
@bebatut https://github.com/galaxyproject/tools-iuc/pull/428

**Comment by bgruening** [comment]
Work will continue in various branches, but I will close this one :)
A summary of this event can be found here: https://gist.github.com/bgruening/734ff541e9d1b02f7b09
