### ISSUE TITLE
Qualimap fails with long name input

### ISSUE THREAD

**Issue by DarianHole** [galaxyproject/tools-iuc#3037]
My previous change to attempt to make qualimap bamqc output easier to work with in multiqc now has qualimap failing when the name is too long or complicated (which I did not think to test my bad). An example would be after running BWA-Mem 

Solution is to just remove these two lines:

```
        #set input_name = re.sub('[^\s\w\-]', '_', str($input1.name))
        ln -s '$input1' '$input_name' &&
```

But I'm not sure if a revert or version bump is better

Darian

**Comment by bgruening** [comment]
What is the error that you get? `$input1.name` should probably be `$input1.display_name`

**Comment by mvdbeek** [comment]
Please don't use `display_name`. There is almost never a user for `display_name` or `name`, this should always be `element_identifier`, which falls back to `name`. The only time you will want to use `name` is when `element_identifier` is not defined, which should only be the case when the input is `list:paired` and your iterating over elements of the outer list.

**Comment by bgruening** [comment]
Upps, I actually meant element_identifier ... sorry.

**Comment by mvdbeek** [comment]
If you can figure out the limit it might be worth reporting that to the qualimap authors (and maybe ask if they could implement something like a `--sample_name` option).

**Comment by DarianHole** [comment]
Error is ```ERROR: input mapping file not found```.

It could also be that it doesn't like commas in the input name. I'll play around with it a bit

**Comment by DarianHole** [comment]
I'll have to rethink this more, but thanks for the help
