### ISSUE TITLE
fastq-dump --split-files command isue

### ISSUE THREAD

**Issue by dankein** [galaxyproject/tools-iuc#3045]
Fastq-dump in Galaxy uses the `--split-files` flag. BWA-mem and Snippy were failing for me on a subset of files I downloaded in Galaxy using Fastq-dump, and exported to the command line. Renaming the headers with bbrename from BBtools fixed that issue for me.

I noticed that the help text for `fastq-dump version 2.10.3` advises against this flag in the help command. I'm not however familiar if there were any technical reasons for choosing `--split-files` over `--split-e` 

fastq-dump" version 2.10.3 help text:

`--split-files                 Write reads into separate files. Read
                                     number will be suffixed to the file
                                     name. NOTE! The --split-3 (# should be --split-e?) option is  
                                     recommended. In cases where not all
                                     spots have the same number of reads,
                                     this option will produce files that WILL
                                     CAUSE ERRORS in most programs which
                                     process split pair fastq files.

 --split-e                     3-way splitting for mate-pairs. For each
                                     spot, if there are two biological reads
                                     satisfying filter conditions, the first
                                     is placed in the `*_1.fastq` file, and
                                     the second is placed in the `*_2.fastq`
                                     file. If there is only one biological
                                     read satisfying the filter conditions,
                                     it is placed in the `*.fastq` file.All
                                     other reads in the spot are ignored.
`

**Comment by bernt-matthias** [comment]
I guess it was only technical reasons .. maybe to keep the outputs section simple.

The easiest would be to use a tool like `cutadapt` to split paired and unpaired reads.

Feel free to reopen if needed.
