### ISSUE TITLE
IUC member proposal - Marius van den Beek

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#309]
Hi,

I would like see Marius van den Beek (@mvdbeek) becoming an IUC member. 
Marius already contributed to the tools-devteam and tools-iuc as well as Galaxy and the Docker containers. I had the pleasure to work with him already and think he could be a win for this community.

Please comment and vote!

**Comment by martenson** [comment]
ping @mvdbeek :)

**Comment by yhoogstrate** [comment]
+1

**Comment by erasche** [comment]
:+1:

**Comment by blankenberg** [comment]
+1

**Comment by nsoranzo** [comment]
:+1:

**Comment by mvdbeek** [comment]
Thanks you guys, really happy to join the team!

**Comment by bgruening** [comment]
Welcome @mvdbeek! 
:sunflower:
