### ISSUE TITLE
Error with Read Group in BWA-MEM

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/tools-iuc#3095]
Hi,

I have a problem with the last version of BWA wrapper (revision 22: 3fe632431b68).
When I run BWA-MEM without read group option, it works.
When I add Read Group information (ID and SM), I get the following error:

```
../shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/bwa/4f774c1e6049/bwa/bwa-mem.xml
could not convert string to float:
```
If I look at log, I have a little more information:
```
galaxy.jobs.runners ERROR 2020-06-23 10:40:42,817 (39369) Failure preparing job
Traceback (most recent call last):
  File "/home/galaxy/galaxy_dist/lib/galaxy/jobs/runners/__init__.py", line 230, in prepare_job
    job_wrapper.prepare()
  File "/home/galaxy/galaxy_dist/lib/galaxy/jobs/__init__.py", line 1066, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/home/galaxy/galaxy_dist/lib/galaxy/tools/evaluation.py", line 483, in build
    raise e
ValueError: could not convert string to float: 
```

**Comment by wm75** [comment]
Which release of Galaxy are you seeing this with?

This is not a tool error, as far as I remember, but an issue in Galaxy itself, which got fixed a while ago.

**Comment by wm75** [comment]
This is probably the corresponding PR: https://github.com/galaxyproject/galaxy/pull/9149

**Comment by bvalot** [comment]
OK. I was on 19.09 version of galaxy. I try to update to the 20.01 and checked if it works.

**Comment by nsoranzo** [comment]
@bvalot You can also just update to the tip of the `release_19.09` branch, if that's simpler.

**Comment by bvalot** [comment]
It desn't work to install a previous version of the script. But the update works correctly.
Thanks for you reply!
