### ISSUE TITLE
bulk package/tool upload for 15.10

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#311]
I would like to update all package to the TTS with the following procedure:
- planemo shed_diff -r
- checking the diff briefly
- planemo shed_upload -r

After this and rebuilding a bunch of Docker test containers I would like to upload everything in one go to the TS with the aim that admins have all our new/updated tools in time for the next Galaxy release.

Before I do this I would like to get the following merged:
- #305 
- #297 (for the upcoming hackathon)
- #288 ( @davebx )
- #292 ( @davebx )
- #255 ( me )

Anything else we need to get in?

**Comment by mvdbeek** [comment]
Sounds like a very good plan to me.

Slightly off-topic:
Could I suggest this to be a test-case for fully automatic uploads, once jenkins tool testing works reliably?
At least for the TTS? 
I was thinking that we could have a stable branch like for galaxy.
Whenever we merge something from dev into the stable branch the changed package gets uploaded to the TTS.

**Comment by nsoranzo** [comment]
@mvdbeek See https://github.com/galaxyproject/tools-iuc/issues/129 .

**Comment by bgruening** [comment]
@mvdbeek yes this is the plan as soon as everything works. Important here is that the package is only uploaded on change and not the entire tree otherwise you would override in-development packages.
The other thing is that I don't want to update the TS automatically. I would like to see somehow a release schedule of tools-iuc. So that admins can plan in advance. Urgent fixes can be made by manually for sure, but I'm not a fan of bulk uploads to the MTS at this point.

**Comment by mvdbeek** [comment]
> @mvdbeek yes this is the plan as soon as everything works. Important here is that the package is only uploaded on change and not the entire tree otherwise you would override in-development packages.

Well, we could be very strict about it by having personalized dockerized toolsheds that are in sync with the testtoolshed, to be used for development. Then we could avoid manual uploads and overwriting in-dev packages. If you're interested I could take this in charge.

**Comment by erasche** [comment]
No need to shed diff, jenkims is doing that regulalry foe us already! https://jenkins.galaxyproject.org/view/Tools/job/iuc-TTS-GH-diff/4/testReport/
