### ISSUE TITLE
Perplexity parameter too high in Seurat

### ISSUE THREAD

**Issue by carolynnielsen** [galaxyproject/tools-iuc#3115]
I'm working with one of my eight lanes of samples which was run with libraries from 49 B cells (plate-based, SmartSeq, Nextera libraries, paired Illumina reads on HiSeq4000). My collaborator sent me the demultiplexed fq.gz files which I input straight into RNA-Star, then generated a collection of 98 gene abundance estimates in StringTie, from which I have made a single table with gene counts by cell. When I now try to run Seurat I receive an error message saying that the perplexity parameter is too high, but this isn't a parameter that is exposed to the user within Galaxy. Is it possible to patch this? I'm using usegalaxy.eu.

**Comment by pcm32** [comment]
Alternatively, in https://humancellatlas.usegalaxy.eu/ we have more granularity in the Seurat tools and I suspect that the persplexity value might be exposed there in the tSNE tool. I think that by default it will show you version 2.3.x but you can switch in the Versions button to 3.1.x. You histories and users are the same as in usegalaxy.eu. I hope it helps.

**Comment by carolynnielsen** [comment]
Thanks for the suggestion- could you please point me towards any online guidance about how to use these more granular Seurat tools? For example, it seems most start with a Seurat RDS object which it looks like it should be an an optional output from the main Seurat tool, but I can't see how to choose this from the available Output Options.

**Comment by nomadscientist** [comment]
I don't know of a specific guidance document on Seurat in galaxy, but you can check out this history that uses Seurat!
https://humancellatlas.usegalaxy.eu/u/wendi.bacon/w/seurat-30

**Comment by carolynnielsen** [comment]
Thanks will have a look at that as well! Is there a SmartSeq/ non-10x version of the 'Seurat Read10x' first step?

**Comment by pcm32** [comment]
@carolynnielsen we have updated our tSNE module to allow perplexity setup (under the advanced part) and the read10x module to also be able to read tabular data as input on the Seurat tools on humancellatlas.usegalaxy.eu. I would expect the continuous integration from usegalaxy.eu to pick up the new tools overnight on its weekly run. If using @nomadscientist workflow, then you will need to switch versions on that workflow for at least those two tools from `3.1.1_0.0.6+galaxy<num>` to `3.1.1+galaxy<num>` in the versions dropdown once they are available. On that instance as well, our Scanpy tools are well tested and offer more flexibility I think.

**Comment by bgruening** [comment]
@carolynnielsen this should be fixed now. The tool will be installed in public instances in the next days. On usegalaxy.eu it will be at Saturday.
