### ISSUE TITLE
Update UMI-tools to version 1.0.0

### ISSUE THREAD

**Issue by KeelyDulmage** [galaxyproject/tools-iuc#3126]
Hi, I would like to request an upgrade of the "umi_tools" shed tool to the [most recent stable release version 1.0.0.](https://umi-tools.readthedocs.io/en/latest/INSTALL.html)  

I have a workflow that I’d like to port to Galaxy that uses umi_tools dedup. However, the Galaxy toolshed only has versions 0.5.5 and 0.5.3. Unfortunately, both these versions automatically discard chimeric reads, which we _really really_ need to keep. I think the old versions were preferred because they ran under python 2.7 but the current version runs under Python 3. It seems like Galaxy has made significant progress in the change to Python 3, so I’m wondering if there are any plans to update umi_tools to the current version?

**Comment by bernt-matthias** [comment]
See here https://github.com/galaxyproject/tools-iuc/pull/3127 seems that the new options are still missing. Maybe you can help fixing the tool tests?

**Comment by bernt-matthias** [comment]
I guess this has been fixed in https://github.com/galaxyproject/tools-iuc/pull/3800

Reopen if needed.
