### ISSUE TITLE
Make sure toolform_upgrade = False

### ISSUE THREAD

**Issue by nitesh1989** [galaxyproject/tools-iuc#32]
In the config/galaxy.ini , the parameter for toolform_upgrade has to be set to be "False" for tool\_factory\_2 to work.

\# Use new tool form
toolform_upgrade = False

**Comment by nitesh1989** [comment]
This should work with the upgraded version of galaxy-central. This is the changeset which fixes the bug : 

https://bitbucket.org/galaxy/galaxy-central/commits/5aa058b09609351defd3161754b23a27ea9bef99

**Comment by erasche** [comment]
@nitesh1989 I'm reading this as this issue is resolved with recent galaxy releases, should this be closed? (perhaps with a note of "Doesn't work with galaxy `rev #### - ####`" or "Doesn't work with galaxy release_###"?

**Comment by nitesh1989** [comment]
We should close this issue.
