### ISSUE TITLE
add KofamScan to IUC

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#3260]
-----------
I was wondering if it would be possible to include this new annotation tool from KEGG into Galaxy.

https://www.genome.jp/tools/kofamkoala/ 

There is a small program KofamScan (uses HMMER & Ruby) to simplify the job. The K-number hmms are downloaded as a database and one uses simple text files to select which subsets of K-numbers to search against.

I think this would complement the InterProScan annotations very well as only ECs are given by InterProScan and not K-numbers; the latter being more specific.

----------------------

Conda package here: https://anaconda.org/bioconda/kofamscan

**Comment by stephanflemming** [comment]
I will take care of that.
