### ISSUE TITLE
Medaka Variant call pipeline via neural networks, readgroups not supported

### ISSUE THREAD

**Issue by kscott94** [galaxyproject/tools-iuc#3270]
The Medaka Variant call pipeline via neural networks stopped working last Friday. It produced zero lines on datasets that have previously worked. The command box gives this message:
/galaxy-repl/main/jobdir/031/497/31497250/tool_script.sh: line 9: medaka_variant: command not found

Also, the tool states "Read groups are currently ignored, so the bam should only contain reads from a single sample. (-i) "
but read groups are absolutely necessary for this tool to work.

**Comment by bernt-matthias** [comment]
Is there still an issue (missing deps)?

**Comment by mvdbeek** [comment]
I've resolved the deps and verified this works.

**Comment by bernt-matthias** [comment]
@kscott94 I'm closing this since it seems that all issues are solved

- readgroups should be handled by splitting the file as suggested by @mvdbeek 
- missing dependencies should be fixed

feel free to reopen if I'm wrong.

**Comment by kscott94** [comment]
Thank you for fixing this so quickly! I will let you know if there are any other issues.

**Comment by stephanflemming** [comment]
@kscott94 Just a comment, the content of that help section was taken from command line help. 

```
$ medaka_variant -h

[...]

    -i  input bam of reads aligned to ref. Read groups are currently ignored,
        so the bam should only contain reads from a single sample.
```

**Comment by kscott94** [comment]
Stephanflemming. Yes. I just wanted to let someone know that I could not get medaka variant pipeline to work until I added the read groups. But, it is working now without read groups!
