### ISSUE TITLE
Vsearch wrapper produces FASTA format for UCLUST-like (UC) format instead of tabular format

### ISSUE THREAD

**Issue by mthang** [galaxyproject/tools-iuc#3275]
Hi Team,
Vsearch is the tool I have been using for my metagenomic data. The vsearch output (UCLUST) is what I use for the data filtering. However, the vsearch output for UCLUST (-uc) has set to "fasta" format see the link below at line 262, or simply click on the link below. Is it possible to update the output format for UC in the vsearch.xml to produce tabular format not fasta.
https://github.com/galaxyproject/tools-iuc/blob/3da28c7772346e1872b6d768b904305be0c61db7/tools/vsearch/search.xml#L262

Many thanks,
Mike

**Comment by bernt-matthias** [comment]
Here you go https://github.com/galaxyproject/tools-iuc/pull/3277 .. can you check if the output is as expected https://github.com/galaxyproject/tools-iuc/blob/c00a7b47d6fe4a05b427896fdbacac247af200ec/tools/vsearch/test-data/search_dbmatched_uc.tsv
