### ISSUE TITLE
Scatterplot with ggplot2 reference

### ISSUE THREAD

**Issue by GarethPrice-Aus** [galaxyproject/tools-iuc#3297]
Hi GalaxyProject

This one could be considered for Papercuts but the  "Scatterplot with ggplot2" references ggplot2.org website that doesn't appear to exist anymore.
Please update to https://ggplot2.tidyverse.org/

Thanks, Gareth

**Comment by bgruening** [comment]
Labelled as such! Thanks @GarethPrice-Aus

**Comment by dnbenso** [comment]
I'm assuming you mean under citations.  If so I created a pull request for this.  My first paper-cut - woot.

**Comment by bgruening** [comment]
Greta paper-cut!
