### ISSUE TITLE
data_manager_manual version issue

### ISSUE THREAD

**Issue by nagoue** [galaxyproject/tools-iuc#3302]
Hi,
I am working on galaxy 19.05, biomaj 3.1 and biomaj2galaxy 2.1.
I am getting the following error : 
` File "/storage/biodatabanks/biomaj/venv/lib/python2.7/site-packages/biomaj2galaxy/commands/add.py", line 267, in add
    wait_completion(ctx.gi, datasetid, jobid)
  File "/storage/biodatabanks/biomaj/venv/lib/python2.7/site-packages/biomaj2galaxy/utils.py", line 204, in wait_completion
    raise Exception("Job finished in error state! Aborting")
Exception: Job finished in error state! Aborting
`
I suspect it to be due to data_manager_manual version:

DM_MANUAL_TOOL_ID = 'toolshed.g2.bx.psu.edu/repos/iuc/data_manager_manual/data_manager_manual/0.0.2'

However, galaxy log is showing:
" Loaded Data Manager: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_manual/data_manager/data_manager_manual/0.0.1"

Looking at the toolshed https://toolshed.g2.bx.psu.edu/repository?repository_id=2390e16311431374, the version is back to 0.0.1

This is very curious because I could make it worked for some time with commit 744f607fac50 (which was indicating 0.0.2).

May you help please,

**Comment by abretaud** [comment]
Hi @nagoue!
I think behind the generic "Job finished in error state! Aborting" exception, there is this error when looking at the galaxy log: https://github.com/galaxyproject/galaxy/issues/10023
I haven't made any progress on this issue, it would be great to see if it's still there in 20.09

For the version number, maybe there is some confusion between 2 versions numbers for the same data manager:
https://github.com/galaxyproject/tools-iuc/blob/master/data_managers/data_manager_manual/data_manager_conf.xml#L3
https://github.com/galaxyproject/tools-iuc/blob/master/data_managers/data_manager_manual/data_manager/data_manager_manual.xml#L1

I wonder if it's a mistake or intended to have different versions...
