### ISSUE TITLE
Minor update to square root symbol in function arguments

### ISSUE THREAD

**Issue by BJWiley233** [galaxyproject/tools-iuc#3312]
Hi,

In the hisat2.xml file under tools/hisat2, for the arguments that take functions as input the symbol on the UI is incorrect.  It should be a square root `&#8730x` instead of a square `x&#178`

`Square root [f(x) = B + A * x&#178;]`

The line won't be over the x but at least it is more correct then a squaring function.

**Comment by bernt-matthias** [comment]
Seems correct. Since this is used in multiple places a macro would be nice.

**Comment by bernt-matthias** [comment]
fixes https://github.com/galaxyproject/tools-iuc/issues/3312

**Comment by bernt-matthias** [comment]
I think this has been fixed.
