### ISSUE TITLE
Bandage: error while loading shared libraries: libGL.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/tools-iuc#3320]
Seeking advice: When I install bandage it fails to run jobs with this error: `Bandage: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`.  I've read some advice about how to fix this at a system level by installing `libgl1-mesa-glx` (we are using ubuntu 20.04).  I tried symlinking the file into __bandage@0.8.1/lib but Bandage cannot find it.

We also have some tools that fail to find the `libcrypto.so.1.0.0` shared library.  Similar errors are mentioned in https://github.com/galaxyproject/tools-iuc/issues/3203.  Is there a workaround for these kinds of errors?

**Comment by bernt-matthias** [comment]
For the later: those need to be fixed in bioconda. Workaround is then to reinstall the conda env.

**Comment by cat-bro** [comment]
Thanks @bernt-matthias.  We found that by installing libg1-mesa-glx globally on our worker nodes we could get around the problem with bandage.

**Comment by bernt-matthias** [comment]
Then I guess this is solved.
