### ISSUE TITLE
vsnp_add_zero_coverage and vsnp_build_tables fail CI

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#3353]
Error is `Invalid dbkey specified [89]`

ping @gregvonkuster

**Comment by gregvonkuster** [comment]
Has something changed that has caused this?  The dbkey should be AF2122 for the tool test, and I know that the builds.txt file sets this dbkey as 89 from UCSC.  But this test was passing until recently, correct?

**Comment by bernt-matthias** [comment]
I guess this was in a test against Galaxy's dev branch .. or @mvdbeek .. should we take care of this?
