### ISSUE TITLE
Volcano Plot Head Line Issue

### ISSUE THREAD

**Issue by heylf** [galaxyproject/tools-iuc#3362]
There is a small but annoying problem with the volcanoplot tool.

 If you apply it to DESeq's results it misses the first line. Probably because it remove the first line as header
so any tabular file with a Galaxy header will miss a significant region.

So people have to be careful to get the correct results.

**Comment by bernt-matthias** [comment]
At least its clearly stated in the help: `A tabular file with a header row containing the columns below (additional columns may be present):`

But maybe the R script could check for the header in addition.

**Comment by mblue9** [comment]
I've added a check for header row here https://github.com/galaxyproject/tools-iuc/pull/3713/commits/9916123f2df8d03d29d963bee1f48b4085481fd1
And changed the help to say 
`The tool will auto-detect if a header is present, by checking if the first row in the Pvalue column is a number or not `
