### ISSUE TITLE
Integer division causes 0 ram allocation if less than 1024MB allocated

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/tools-iuc#3364]
https://github.com/galaxyproject/tools-iuc/blob/524a39e08f2bea8b8754284df606ff8dd27ed24b/tools/shovill/shovill.xml#L27

If GALAXY_MEMORY_MB == 500 this causes `[shovill] Invalid --ram 0 - need at least 1`

**Comment by bernt-matthias** [comment]
Seems reasonable.  If the `GALAXY_MEMORY_MB` is set this means that the must not use more memory. Unless one can specify  0.5GB for the tool there is no alternative, since 1GB would be wrong.

Should be solved via `job_conf.xml` ..

Reopen if needed

**Comment by mvdbeek** [comment]
Just to clarify, shovill needs 2GB minimum https://github.com/tseemann/shovill/blob/master/bin/shovill#L92, otherwise we should of course fix that in the tool.

**Comment by bernt-matthias** [comment]
I think with the default of `4096` its fine and needs no change. One might add docs in a README.
