### ISSUE TITLE
Add UShER for covid efforts?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#3379]
https://github.com/yatisht/usher looks pretty interesting and could be something to run at the conclusion of our workflows.
Maybe the newly formed tool working group (ping @davebx) would be interested in adding this ?

**Comment by nekrut** [comment]
@davebx this is indeed a very interesting tool. Can you take a look at how complex this may be?

**Comment by gallardoalba** [comment]
This issue can be closed @mvdbeek.

**Comment by mvdbeek** [comment]
Thanks @gallardoalba!
