### ISSUE TITLE
Should we get/support official Java packages 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#338]
Sarah pointed out this nice project https://github.com/alexkasko/openjdk-unofficial-builds.
So the question arises if we want to create a package for Java to get rid of the Java dependency on
https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList

What do you think?

**Comment by bgruening** [comment]
If we agree to do this it might be good project for a beginner:

The recipe should look like that:
https://github.com/peterjc/galaxy_blast/blob/master/packages/package_blast_plus_2_2_31/tool_dependencies.xml

**Comment by erasche** [comment]
Emphatic :+1:

**Comment by erasche** [comment]
However, can we leverage brew packages for this?

**Comment by bgruening** [comment]
I will close this Issue as conda packages will solve this problem.
