### ISSUE TITLE
Different owners between MTS/TTS on certain packages

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#339]
I'm not sure what to do about this. The IUC is automating uploads to the TTS right now and I'm noting a lot of ownership conflicts. These cause @jmchilton's planemo to not be able to update the repositories.

E.g.

Package | MTS Owner | TTS Owner | IUC .shed.yml 
--- | --- | --- | ---
Tool Factory 2 | fubar | iuc | fubar
rglasso | fubar | fubar (missing IUC permissions) | fubar 

In all of these instances, there's no consistency between MTS and TTS and the file, meaning it's impossible for us to automatically update these packages. I'll admit that many of the TTS packages were likely created automatically by the IUC.

The best solution I have is swapping ownership to their personal accounts, but then that requires THEM to create the repository in both the MTS and TTS, and then to grant permissions to us on it, which is unpleasant. Thoughts?

**Comment by erasche** [comment]
This is marked high priority, because until we can get it all coherent, https://jenkins.galaxyproject.org/view/Tools/job/iuc-TTS-GH-update/lastFailedBuild/testReport/ will never pass.

**Comment by bgruening** [comment]
khmer should be solved in https://github.com/galaxyproject/tools-iuc/pull/317
IUC should have write access to Krona Tax. But @nsoranzo should create a repository under TTS.
Regading the Tool Factory we need to ping @fubar2.

What means a lot? Are there more repos? This really should be an exception.

**Comment by erasche** [comment]
@bgruening okay, I'd forgotten the IUC was taking over/splitting khmer tools. 

Yep, @fubar2, can you please create `rglasso`, `tool factory 2` repositories under your personal account in the test tool shed and grant IUC permissions.

**Comment by nsoranzo** [comment]
taxonomy_krona_chart should be ok now on TTS.

**Comment by erasche** [comment]
ping @fubar2, can you please create `tool_factory_2` and `rglasso` repositories under your personal account

**Comment by erasche** [comment]
Y'all can see diff reports here: https://jenkins.galaxyproject.org/view/Tools/job/iuc-TTS-GH-diff/5/testReport/ 

@martenson and I have put some work into improving the XUnit reports to where they're really informative from shed-diff runs. Improvements to shed-update are coming soon. Just wanted to let the IUC know :)

**Comment by erasche** [comment]
Ross hasn't been active in the past 7 months. I'm going to exclude his tools from MTS/TTS updates & diffs.

**Comment by bgruening** [comment]
As these tools are included as IUC tools, I think we need to care about them and not exclude them.
If we really don't want to maintain them, we need to have a deprecation mechanism in place and move the tools under `legacy`.
@galaxyproject/iuc calling for  opinions here :)

**Comment by erasche** [comment]
The IUC was supposed to prevent this exact problem haha... ah well. More evidence we need things to be under the IUC account proper.

I don't know if they need to be deprecated, we just don't have control over what's on the MTS.

**Comment by bgruening** [comment]
But this can be easily fixed. We just create the same repos under the IUC account, right?
I will contact Ross privately.

**Comment by erasche** [comment]
Sure, we could create them ourselves, but then there would be no lineage/upgrade path for existing users of the old tools.

**Comment by jmchilton** [comment]
For this particular tool, rerun seems not particularly important - shouldn't really be user facing. I'd just get everything right now, and continue forward with the IUC account.

**Comment by erasche** [comment]
tool_factory_2 no, rglasso yes. Then again, I'm not even seeing rglasso on the MTS. O_o

**Comment by fubar2** [comment]
Eeek.
I'm kind of out of the loop being retired and haven't been paying attention. These tools need work but I have no support and think the best long term strategy is to archive them somewhere. until someone with that same itch to scratch comes along. Sorry to do this. 

As for the tool factory, well. Enough said. Time for retirement I'm afraid. Nobody seems to use it.
Sigh.

I am guessing that the relevant R repository is out of date for the lasso tool. 'Tis a pity: the lasso tool generates parsimonious regression models (cox/linear/logistic/poisson) and is designed to work fast with enormous numbers of predictors - see "datamining". Solves all possible models and selects the "best" models of various sizes using coordinate descent which is very fast, then uses cross validation to generate predictive performance metrics for the best models. Amazeballs if that's (ie unsupervised learning) is your thing.

**Comment by fubar2** [comment]
ok, FWIW the requested repos are on the test toolshed with iuc/devteam permissions but nothing uploaded. They won't work until I upgrade the dependencies to a more recent R/bioc. Sigh.
I'll see what I can get done.

**Comment by mvdbeek** [comment]
@fubar2 
I'm volunteering to take over the necessary *maintenance*, starting next week. 

So iuc ownership on the toolshed it is?

**Comment by fubar2** [comment]
@mvdbeek 
Thanks Marius! 
To make them maintainable, I need to get them installable and passing tests, then I'll populate the repositories if you like. I should have some time this week. They're both way behind in R/Bioc. Sigh.

**Comment by fubar2** [comment]
@mvdbeek
Progress! AFAIK, the test toolshed toolfactory2 repo seems to pass tests using planemo. rglasso installs and runs fine with some test data I have here (although the new UI for data_column parameters makes selecting hundreds of predictors an exercise in sheer frustration compared with the oldskool multiselect box - trello card https://trello.com/c/TSB0sIvD has been created - please vote!) on a fresh dev clone, but fails in planemo testing with a wierd error about subclasses which I'm taking a look at.
