### ISSUE TITLE
Nominate the tooldev related topics for GCC

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#340]
Hello @galaxyproject/iuc 

Let's work together on the following document to describe the tool development topics for GCC2016 in the best way possible. We plan to have 3 differing in the level of complexity/experience.

https://docs.google.com/document/d/1r4J5yAMZzJ3aLJ9oc4D6nYCvcz7qX50VEqdJKNMeE4c/edit#

I will submit the contents of the document later today as the topic nominations.

Thank you

**Comment by jmchilton** [comment]
Thanks for spearheading this @martenson. Realistically though these should go fantasticaly this year, they went well last year and we just need to polish I think.

**Comment by erasche** [comment]
yep, agreed. Went quite well minus some minor documentation/reality inconsistencies.

**Comment by bgruening** [comment]
@yhoogstrate @mvdbeek do you already know if you can participate next year?
IUC needs you :)

**Comment by bgruening** [comment]
@martenson I have added my proposals as well and included @mvdbeek and @yhoogstrate as potential instructors.

**Comment by martenson** [comment]
done, last nightI have nominated all 5 topics that were in the doc

**Comment by bgruening** [comment]
Thanks Martin!
