### ISSUE TITLE
augustus_dependencies 3_1 binary download link not workind

### ISSUE THREAD

**Issue by Eduardo-Alves** [galaxyproject/tools-iuc#343]
package_augustus_3_1 revision 1d324022239b owned by iuc 
http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.1.tar.gz has been moved to http://bioinf.uni-greifswald.de/augustus/binaries/old/augustus-3.1.tar.gz

**Comment by bgruening** [comment]
@Eduardo-Alves thanks for reporting fix is merged!

**Comment by peterjc** [comment]
Note I have not pushed this update to the Test or main Tool Shed, see also #129.

**Comment by Eduardo-Alves** [comment]
Thank you. I will wait for it to reach toolshed as I don't have disk write rights at the university instance, only galaxy admin
