### ISSUE TITLE
Community Package Cache

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#345]
# Implementation

https://github.com/erasche/community-package-cache/

# Original Proposal

I'm proposing a package caching proxy that should provide some relief from the bad-url issue. I'd like feedback from other members of the IUC/devteam before actual implementation.

## The Problem

Downloads disappear, get renamed, etc. We cannot rely on externally controlled URLs for longevity. [Bad URLs are a continuous issue for us](https://github.com/galaxyproject/tools-iuc/issues?utf8=%E2%9C%93&q=is%3Aissue+url+)

## The (Interim) Solution

A proxy which we can route requests through which cache them as long as the service is alive. 

I've proposed similar things in the past such as a download store where the storage burden is shared across multiple servers, but for an initial implementation we can avoid the complexity of a distributed solution, and just opt for the simple caching proxy which is one step above the existing situation. I.e. it fixes one problem, not all of them. Incremental improvements :)

## Implementation

Implementation shouldn't be too difficult, the RFC is more concerned with what features will be offered than how to actually write it.

I imagine the following:

- simple service where you make requests like:

  `https://gx-package-proxy/?q=http%3A%2F%2Fbioinf.uni-greifswald.de%2Faugustus%2Fbinaries%2Fold%2Faugustus-3.1.tar.gz`

  and receive their package downloads.
- registered + approved users of the service can request a URL be archived permanently

I originally proposed a reputation based system, but that seems like excessive complexity when we're not making the statement "your download will be available until the end of time", we're making the statement "This will likely be much longer lived than your existing URLs".

### Squid

I wrote some squid caching rules at one point, but:

-  those acted as per-backend URL proxies (though they were really quite nice). 
- Squid did not guarantee that things would be cached forever and if things went wrong we'd be no better off than where we are now

### Distributed

I've dreamt up alternatives that make use of TAHOE-LAFS or bittorrent over http to share the package cache amongst several groups, but that has a huge amount of complexity associated and requires a lot more engineering than I can offer this month/calendar year.

### Brew

That work is complementary to this, with things like CPAN in existence where .tar.gzs may disappear with no warning, something like this will always be required.

cc @bgruening @natefoo

**Comment by martenson** [comment]
Just a quick note: @davebx recently did our local backup of all sourceforge files that were linked from the MTS. This is the first step to providing reliable mirrors to files we require to stay reproducible.

**Comment by peterjc** [comment]
Sounds useful to me - I've found and fixed several broken URLs (stumbled on while testing ``planemo dependency_script`` which downloads all the platform-specific download actions) which is enough to convince me this is a real problem for the Galaxy Tool Shed (and beyond).

Bonus points for a future enhancement to validate checksums given as additional URL parameters as well.

**Comment by bgruening** [comment]
xref: https://github.com/bioarchive/aRchive_source_code/pull/20
The idea here was to offer a complete web service that stores archives and returns a more or less complete tool_dependency definition.

**Comment by erasche** [comment]
@martenson @davebx that's excellent to hear. 

@peterjc that's an excellent suggestion of validating checksums against the remote URLs.

@bgruening I will go out of my way to support your `tool_dependency.xml` generators :) You envision those being accessible as some sort of REST API endpoint yes? If so I'll just ensure the package cache can proxy those requests to your docker images/code running in the background.

**Comment by natefoo** [comment]
might be useful to have the proxy return a redirect to a downloadable URL to the file rather than the file itself?

**Comment by erasche** [comment]
@natefoo that's an interesting addition, but offloads storage to someone else. I'm envisioning a service where I don't have to a) ask someone to upload a package to depot or b) upload to Björn's data store. I like the forward thinking-ness of your comment, but is there any way for that to fit in with this?

**Comment by natefoo** [comment]
The redirect could still be to a place we control.

**Comment by erasche** [comment]
@natefoo okay, I'll add this as a feature. You'll be able to request two types of proxied packages:

- served from a local copy
- redirects to existing URLs

But I worry that we don't really gain so much with that, and that we're just trading one backend that could disappear for another backend.

**Comment by erasche** [comment]
@bgruening @peterjc @natefoo @martenson 

Okay... it's done! In the form of a 42 line python file and a urls.tsv file. 

- in lieu of "accounts" and "approval" process, we use a github repository and PRs.
- in lieu of an actual proxy, the script just downloads the URLs to files named after their sha256sum, and lets nginx/etc serve them up.
- in lieu of databases or any of that nonsense, there's a dead simple tab separated file which consists of three columns: (sha256, url, optional comment).
- in lieu of nate's request for redirects ... hmm. I didn't solve that one. (Sorry Nate!)
- in lieu of requests like `https://package-server/?url=https://...` we'll make requests like `https://package-server/path/to/dir/shaaaa256suuuuum#https://the-real-url`, appending the real url as a URL fragment to the end (ignored on serving files) in order to preserve some end-user transparency of which files are being downloaded.

I'd like to:

- [ ] set up a repository for this (galaxyproject or galaxy-iuc?)
- [ ] set up a jenkins job to run the downloader
- [ ] get the directory this script outputs to served by some webserver.

I'll begin pre-seeding the file with all of the IUC's URLs/sha256sums.

**Comment by yhoogstrate** [comment]
> Downloads disappear, get renamed, etc. We cannot rely on externally controlled URLs for longevity. Bad URLs are a continuous issue for us

So true! Not to mention the possibility that files get modified if no checksums are being used

> in lieu of requests like https://package-server/?url=https://... we'll make requests like https://package-server/path/to/dir/shaaaa256suuuuum#https://the-real-url, appending the real url as a URL fragment to the end (ignored on serving files) in order to preserve some end-user transparency of which files are being downloaded.

I actually prefer the first solution, and do something like:

https://package-server/get/?url=https://
https://package-server/checksum/?url=https:// or https://package-server/sig/?url=https:// and obtain Pgp signatures
https://package-server/timestamp/?url=https:// (not neccesairy if Pgp signatures are used)

I think the HTML comment suffix is a bit hacky. It requires to add these #https:// suffixes to each url within every galaxy wrapper but leaving them out can't break the system (these suffixes are never passed through to a server). Because it doesn't break when it's missing it probably get's used less frequently over time, unless planemo will be modified. I don't think html suffixes are designed for this purpose.

> in lieu of an actual proxy, the script just downloads the URLs to files named after their sha256sum, and lets nginx/etc serve them up.

(I am not sure if I understand this correctly, but I suppose you mean that files are being accessed by their sha256sum?)

If so, this implies that hash collisions will never take place ;) To me it would be easier to understand code like this:

```
<package>https://galaxy-proxy-server/get/?url=http://ftp.gnu.org/gnu/grep/grep-2.4.tar.gz</package>
```

Instead of:

```
<package>https://galaxy-proxy-server/a32032bab36208509466654df12f507600dfe0313feebbcd218c32a70bf72a16/#http://ftp.gnu.org/gnu/grep/grep-2.4.tar.gz</package>
```

whereas:

```
<package>https://galaxy-proxy-server/a32032bab36208509466654df12f507600dfe0313feebbcd218c32a70bf72a16/</package>
```

will work too.


Looking forward to this!

**Comment by erasche** [comment]
> I think the HTML comment suffix is a bit hacky. It requires to add these #https:// suffixes to each url within every galaxy wrapper but leaving them out can't break the system (these suffixes are never passed through to a server). Because it doesn't break when it's missing it probably get's used less frequently over time, unless planemo will be modified. I don't think html suffixes are designed for this purpose.

They're not, you're right, it is a bit hacky. It was the decision to have one moving part (i.e. dynamic script that has to be running 24/7) versus ZERO and I chose the latter. Agreed, there is thr chance that people use the human readabke URL fragment less. I don't have a solution for that under my current scheme.

> (I am not sure if I understand this correctly, but I suppose you mean that files are being accessed by their sha256sum?)
>
> If so, this implies that hash collisions will never take place ;)

Yep! Files are stored and accessed by their sha256. There's a reason we use that and not md5... sha256 ia a cryptogeaphically appropriate signature, the probability of a collision is really not a concern. http://stackoverflow.com/a/4014407

That said, I agree with your points. If anyone else feels similarly I'll add a script which will have to always be running, to map URLs to files on disk.

**Comment by bgruening** [comment]
@erasche this is great! Where is the code. I'm wondering why we need a web-service at all, if we just want to map the packages to a URL.

The problem of archiving tarballs has two sides for me.
 1. provide a stable URL to the tarballs 
 2. store the archives

Here is how I would imaging a solution for problem 1:
```
curl  https://raw.githubusercontent.com/bgruening/gsl/master/gsl.py | python - --package_id augustus_3_1
```

This will download a package a ID `augustus_3_1`. The ID is unique and we can use it inside of ` download_by_url` directly, if we implement something like https://github.com/bgruening/gsl/blob/master/gsl.py in Galaxy directly. We do not need to store the checksum inside of the tool_dependency as this script will take care of it. Not sure if github is happy with this usage, but essentially we do not need a server and can just collect and update all URLs in one place. But this makes it to a central point failure.

That said, for the second problem I think we need to get founding for a download store to actually store the tarballs somewhere. My idea was to ask the ELIXIR project and especially the [Sustainability Institute](http://www.sustainabilityinstitute.net/) for help.

**Comment by yhoogstrate** [comment]
> That said, I agree with your points. If anyone else feels similarly I'll add a script which will have to always be running, to map URLs to files on disk.

It shouldn't be always running. Just the tabular file you have would be sufficient. Rather than using the sha256sum as uid you could use the url as a uid.

What I like about @bgruening's idea is that it requires PRs and some kind of checking before URLs get in the system.

>  We do not need to store the checksum inside of the tool_dependency as this script will take care of it.

As long as the proxy server doesn't get hacked. The current implementation works like a 2-factor authentication because the checksums are not provided by the servers that host the packages (github excluded, but you get the point)

**Comment by erasche** [comment]
@yhoogstrate 

> It shouldn't be always running. Just the tabular file you have would be sufficient. Rather than using the sha256sum as uid you could use the url as a uid.

URLs are not safe to use as filesystem names. There has to be a mapping between a requested URL and a path that nginx can understand. Either directly in the form of a sha256, or translated via a python script from URL -> sha256 on disk.

> What I like about @bgruening's idea is that it requires PRs and some kind of checking before URLs get in the system.

my solution already covers that @yhoogstrate, the `urls.tsv` file will be part of the repository, people will PR that and we can have it be open/free for discussion.

> As long as the proxy server doesn't get hacked. The current implementation works like a 2-factor authentication because the checksums are not provided by the servers that host the packages (github excluded, but you get the point)

The only place where it matters that checksums are correct are on the end user's machine where the software is downloaded and installed. The proxy server and even upstream can have incorrect hashes associated with them as long as the end user's matches what is actually downloaded.

**Comment by erasche** [comment]
@bgruening 

> @erasche this is great! Where is the code. 

It wasn't online yet, pending discussion of the points I raised in an earlier comment, where should it go? I'll post in my personal github *pro tempore*. https://github.com/erasche/package-cache Here ya go. :)

> I'm wondering why we need a web-service at all, if we just want to map the packages to a URL.

It's no longer a web service, now just a directory full of tarballs that gets served. The only "service" aspect is the python script which downloads + mirrors tarballs as a cron job.

> This will download a package a ID augustus_3_1. The ID is unique and we can use it inside of download_by_url directly, if we implement something like https://github.com/bgruening/gsl/blob/master/gsl.py in Galaxy directly. We do not need to store the checksum inside of the tool_dependency as this script will take care of it. Not sure if github is happy with this usage, but essentially we do not need a server and can just collect and update all URLs in one place. But this makes it to a central point failure.

Yes, and more importantly it doesn't actually solve the problem of CPAN removing packages. That's the problem I'm trying to solve here. Your script could be part of this. I see no reason `gsl.py` wouldn't work with what I'm proposing. We can add an "id" column to that file and your gsl.py script to it, but we NEED to be hosting the tarballs. 

> That said, for the second problem I think we need to get founding for a download store to actually store the tarballs somewhere. My idea was to ask the ELIXIR project and especially the Sustainability Institute for help.

Eh, do we? That seems like a lot of work. The galaxy project is already hosting 200 gigs of R packages that no one will *ever* want or access due to the way bioarchive works.

**Comment by erasche** [comment]
@bgruening I've updated my repo with your GSL.py and implemented compatibility with it. The `urls.tsv` file now matches your `packages.list` (and displays more nicely on GH). 

Whenever we find a place to host these packages (I'm assuming Galaxy won't mind, failing that ELIXIR), we'll update the script with the new URL and it'll be 100% ready to go.

**Comment by bgruening** [comment]
> Eh, do we? That seems like a lot of work. The galaxy project is already hosting 200 gigs of R packages that no one will ever want or access due to the way bioarchive works.

Sorry, 3 lectures today. Just a quick note.
Not sure what we are aiming here. Do we want to mirror all R, perl ... tarballs? Databases? SNPeff databases? This is a big thing? Not sure Galaxy should pay the bill. This needs to be agreed by the entire scientific community.
But in the end if we can solve 1) we could easily migrate the tarball storage to different servers.
Talk to you later.

**Comment by erasche** [comment]
> Sorry, 3 lectures today. Just a quick note.

No problem. I really appreciate the feedback.

>  Not sure what we are aiming here. Do we want to mirror all R, perl ... tarballs?

Yes

> Databases? SNPeff databases? 

No. That one definitely needs to be brought to the wider scientific community. 

My aim here is a small, incremental improvement over where we were yesterday with URLs that disappear. That's all I want to solve, is to have a single, community maintained resource for this. I'll foot the bill myself if it's going to be an issue, s3 is pretty cheap and this is low, low processing power.

I'd like to solve the "we need to move tarballs around" problem now. I'll probably add another field to the file with "download_from" where external URLs can be specified. That really wasn't the problem I was trying to solve but both you and @natefoo raised it. If a `download_from` field is specified/non-empty, then the updater script will ignore those lines and not download from the `upstream_url` and just point there so `gsl.py` can follow that link. Updating shortly..

**Comment by erasche** [comment]
Okay. Implemented. `gsl.py` and the package cache now support an `alterate_url` column (col 6) that specifies a URL where things should be downloaded from. Otherwise they'll be downloaded from a server URL that'll be codified in gsl.py (i.e. wherever the community package cache is hosted)

See the first line of https://github.com/erasche/package-cache/blob/master/urls.tsv

**Comment by natefoo** [comment]
@erasche We'll of course host... archive.galaxyproject.org? packages.galaxyproject.org? or just the existing depot.galaxyproject.org?

**Comment by erasche** [comment]
@natefoo yay! I'm incredibly unopinionated on naming, my apologies. Probably just depot, less trouble that way. Maybe a subdirectory in there that jenkins can push things to.

I'd wait on @bgruening and @yhoogstrate for more feedback to make sure they're satisfied with this first. :)

**Comment by martenson** [comment]
@davebx could we add the sources downloaded from sourceforge to the list here? https://github.com/erasche/package-cache/blob/master/urls.tsv

**Comment by yhoogstrate** [comment]
@erasche Looks good! Go for it.

**Comment by natefoo** [comment]
let's go with depot.galaxyproject.org/software, and as a bonus, jenkins already has access. =D

**Comment by erasche** [comment]
@natefoo awesome! I'll get that set up presently.

**Comment by davebx** [comment]
I've found where I downloaded the sourceforge tarballs, am in the process of hosting them on depot.

**Comment by erasche** [comment]
@davebx if you could just `$ sha25sum *` and send that to me, I'll get it patched into the urls.tsv file. (and tell me where they'll be on depot)

**Comment by erasche** [comment]
ping @natefoo where should the data from jenkins be going? You mentioned jenkins already has credentials, could we get a directory created for the package cache?

**Comment by natefoo** [comment]
@erasche `depot@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root`

Not sure where under there. `/pkgcache` maybe?

You may not see changes until after `$TTL`

**Comment by erasche** [comment]
I think you mentioned `/software` before and that still soudns good to me. :)

Thanks for getting this set up! I'll finish the jenkins part over lunch. :beers:

**Comment by natefoo** [comment]
So I did... only 5 comments up... my short term memory `is None`.

**Comment by davebx** [comment]
Additionally, every sourceforge url in the main and test toolsheds has been downloaded to /sourceforge/

**Comment by erasche** [comment]
@natefoo anything special I need to do for jenkins to have SSH access? It seems to be rejected:
https://jenkins.galaxyproject.org/view/Meta/job/package-caching-proxy/1/console

**Comment by natefoo** [comment]
@erasche Forgot to set up ~/.ssh/config, should be working now.
