### ISSUE TITLE
HISAT2 "collection not of the correct type" for list of paired fastsq datasets

### ISSUE THREAD

**Issue by Eduardo-Alves** [galaxyproject/tools-iuc#347]
Hi

HISAT2 gives an error that collection is not of the correct type but then works fine if I execute. 
"History does not include a dataset collection of the correct type or containing the correct types of datasets"
My collection is a list of paired datasets of type fastq. If i select individual paired reads then it recognises the files so it's not a problem with file type. HISAT2 revision is 6d4d39720545 running on galaxy 15.07.

Thank you in advance

Eduardo

![screen shot 2015-10-22 at 09 18 23](https://cloud.githubusercontent.com/assets/9776977/10662008/6456c5da-78a9-11e5-98ab-06763a182c31.png)
![screen shot 2015-10-21 at 13 33 16](https://cloud.githubusercontent.com/assets/9776977/10662018/6d0cf6f4-78a9-11e5-97a8-02becdaf52be.png)

**Comment by nsoranzo** [comment]
Ping @jmchilton

**Comment by bgruening** [comment]
I guess this is more a issue for @guerler

**Comment by yhoogstrate** [comment]
Hello @Eduardo-Alves , this issue seems to be resolved at usegalaxy.org. I will close this issue. If you still encounter problems please re-open or create a new issue. Thanks for reporting, it's really appreciated :+1:
