### ISSUE TITLE
CoNvex: NGMLR not found

### ISSUE THREAD

**Issue by KeelyDulmage** [galaxyproject/tools-iuc#3470]
Hi, I tried using the ngmlr CoNvex Galaxy tool and I get this error: 

>Fatal error: Exit code 127 ()
>tool_script.sh: line 9: ngmlr: command not found

I just reinstalled Galaxy from scratch at the end of January so everything should be pretty much up to date.  Seems like a straightforward error/fix anyway.

**Comment by bgruening** [comment]
@KeelyDulmage this looks like the dependencies, most likely conda packages, have not been installed correctly. Can you check this?

**Comment by KeelyDulmage** [comment]
@bgruening, that's right, I ran `conda list` and ngmlr is not listed.  I did try uninstalling and reinstalling the tool, to no avail.

**Comment by KeelyDulmage** [comment]
@bgruening Update, I installed ngmlr on a production Galaxy instance running on our ubuntu server and it works just fine.  That is also a different version of Galaxy, 19.09.  The problem I was having was with my local dev instance running in WSL.  It's not a huge problem since I can always just install ngmlr and add it to my PATH to get it to run locally.

**Comment by bgruening** [comment]
Maybe that was a WSL problem? No sure @KeelyDulmage, sorry. Can we close this issue?

**Comment by KeelyDulmage** [comment]
@bgruening Yes, let's close it for now.  Hopefully it was just WSL.
