### ISSUE TITLE
Tool request: clipOverlap from BamUtil

### ISSUE THREAD

**Issue by monikaheinzl** [galaxyproject/tools-iuc#3484]
Hi,

I noticed that there is no tool in the toolshed for clipping read pairs that overlap in a bam file. I usually use clipOverlap from BamUtil (https://genome.sph.umich.edu/wiki/BamUtil:_clipOverlap). Is it possible to get a wrapper for this tool?

Thank you,
Monika

**Comment by gregvonkuster** [comment]
I'll take this one

**Comment by bernt-matthias** [comment]
clipOverlap from BamUtil is now available: https://github.com/galaxyproject/tools-iuc/pull/3553
