### ISSUE TITLE
Add Scoary

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#3490]
https://github.com/AdmiralenOla/Scoary

BioConda package already available: https://anaconda.org/bioconda/scoary

**Comment by heylf** [comment]
I am on it!

**Comment by heylf** [comment]
Finished. Scoary is through.

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/tools-iuc/pull/3536

Fell free to add it to https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/tools_iuc.yaml

**Comment by bgruening** [comment]
Thanks @heylf great work!
