### ISSUE TITLE
Select lines that match expression -> skip header option ?

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/tools-iuc#3511]
Dear IUC,

Using this [selection tool ](https://ecology.usegalaxy.eu/root?tool_id=Grep1) on eu, it appears to me important that an option can be added so the user can specify that the first line is a header (as on other tools) so the "select" will not apply to the header.

What do you think about that ?

Best,

Yvan

**Comment by bernt-matthias** [comment]
Hey @yvanlebras this tool is in the Galaxy sources (https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/grep.xml). Can you open an issue there .. maybe flagging it as paper cut?

**Comment by bernt-matthias** [comment]
Anyway .. here you go  https://github.com/galaxyproject/galaxy/pull/11859 :)
