### ISSUE TITLE
RNA STAR genomeSAindexNbases hidden parameter

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/tools-iuc#3512]
Recently a user has [reported an error](https://help.galaxyproject.org/t/fatal-error-exit-code-1-multiqc-and-star-erros/5452) related to his parameter in the GHelp. Would it be possible to expose it?

**Comment by wm75** [comment]
Yes, that would be a reasonable addition. The latest STAR manual at https://github.com/alexdobin/STAR/raw/master/doc/STARmanual.pdf lists many more Genome Indexing Parameters (currently in chapter 15.5 p. 26) and probably all of those should live in an experts settings section, which is only revealed when the user chooses to build an index for a custom reference.
The reason why it's not yet available is mostly just that the tool wrapper is really complicated already.

**Comment by gallardoalba** [comment]
> Yes, that would be a reasonable addition. The latest STAR manual at https://github.com/alexdobin/STAR/raw/master/doc/STARmanual.pdf lists many more Genome Indexing Parameters (currently in chapter 15.5 p. 26) and probably all of those should live in an experts settings section, which is only revealed when the user chooses to build an index for a custom reference.
> The reason why it's not yet available is mostly just that the tool wrapper is really complicated already.

The PR has been opened :) https://github.com/galaxyproject/tools-iuc/pull/3513
