### ISSUE TITLE
Error with Extract Pairwise MAF Blocks tool

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/tools-iuc#3514]
Two users have reported similar errors with this tool: The MAF source specified (xx) appears to be invalid.

- https://help.galaxyproject.org/t/help-extracting-pairwise-alignments-from-mafs/5481
- https://help.galaxyproject.org/t/error-calling-100-multiz-alignment-using-extract-maf-blocks-tool/3041

**Comment by bernt-matthias** [comment]
Which tool is this? I think this is not part of the IUC tools, but one of the tools shipped with Galaxy itself.

**Comment by gallardoalba** [comment]
True, thanks. I'll move it to the Galaxy repo.
