### ISSUE TITLE
Stacks population with option F statistics ON don't output populations.fst_summary.tsv and populations.phistats_summary.tsv files

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/tools-iuc#3526]
Hi iuc,

Hope all is ok on your side!

Using last stacks2: population tool I seen that specifying Yes for the "compute F statistics" parameter will make création of populations.fst_summary.tsv and populations.phistats_summary.tsv files, not on the history.

Best,

Yvan

**Comment by yvanlebras** [comment]
Looking at iuc xml related files, it appears to me this is maybe due to this filter in the macro.xml:

    ```  <filter>advanced_options['log_fst_comp'] and fstats_conditional['fstats']=='yes'</filter> ```

So if I am not wrong there is a need to `activate` log_fst_comp to have these 2 files as output datasets isn't it?

**Comment by yvanlebras** [comment]
... and effectively with this advanced option activated, I have the aforementioned files. I think these files are not only produced with this log_fst_comp parameter activated' if I am not wrong

**Comment by bernt-matthias** [comment]
Hi @yvanlebras I'm currently at stacks2 https://github.com/galaxyproject/tools-iuc/pull/3510 anyway. I checked the stacks2 sources a bit:

`log_fst_comp` seems to have an effect in a class `HapDivergenceExport`, i.e. add columns to some of the outputs. It appears to me that this is: - `phistats.tsv` and files of the format `out_prefix + ".phistats_" + pop_1p.name + "-" + pop_2p.name + ".tsv";` (the later ones are ignored by the tool at the moment). 

So `log_fst_comp` only modifies an output but does not disable it, i.e. it should be removed from all filters.

It seems to me that `fst_summary.tsv` and `phistats_summary.tsv` are written within the same function (`LocusDivergence.write_summary`) which is called if a boolean `calc_fstats` is `true`. This boolean is enabled by the command line parameters `--smooth/-k`, `--smooth-fstats` and `--fstats` (I guess the former two just do this implicitly). 

In addition the boolean controls two exports: `SnpDivergenceExport` and `HapDivergenceExport`

-  `HapDivergenceExport` creates the files mentioned above.
- `SnpDivergenceExport` creates files of the form `out_prefix + ".fst_" + pop_1p.name + "-" + pop_2p.name + ".tsv"` which we ignore at the moment

So, the filter should also check for `smooth/k` or `smooth-fstats` which implicitly also enable `fstats` (do we want to restructure the form? suggestions?)...

**Comment by yvanlebras** [comment]
Thank you Matthias, Björn ! Will test new version and give feedbacks
