### ISSUE TITLE
package python_2_7_10 compiled without sqlite3 support

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#356]
The subject is self-explanatory: 2.7.10 has no sqlite3 support

**Comment by bgruening** [comment]
This is unfortunate ... I have sqlite in the environment
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_python_2_7_10/tool_dependencies.xml#L42

And PKG_CONFIG_PATH is also set: https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_sqlite_3_8_3/tool_dependencies.xml#L15

I need to look more closely into this. @tiagoantao do you have your INSTALLATION.log file of Python around and get send it to me via mail/gist?
