### ISSUE TITLE
Tools that might need wrapping from #gi2015

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#361]
Collection of ideas, not all can be wrappable or plausible to wrap. Feel free to add or wrap.

To wrap:
- [ ] JunctionSeq https://github.com/hartleys/JunctionSeq;
    package being made at https://github.com/galaxyproject/tools-iuc/pull/360
  wrapper progress tracking at #355 
- [ ] QoRTs, as part of the JunctionSeq pipeline. https://github.com/hartleys/QoRTs
- [ ] Basset https://github.com/davek44/Basset
- [ ] Kraken2 available December'15?
- [ ] sv-autopilot https://github.com/ALLBio/allbiotc2
- [ ] RareVariantVis http://bioconductor.org/packages/devel/bioc/html/RareVariantVis.html
- [ ] ginkgo https://github.com/robertaboukhalil/ginkgo
- [ ] discordant? https://github.com/siskac/discordant
- [ ] vcfanno https://github.com/brentp/vcfanno
- [ ] Mash https://github.com/marbl/Mash
- [ ] Monocle http://cole-trapnell-lab.github.io/monocle-release/
- [ ] Sleuth http://pachterlab.github.io/sleuth/about.html
- [ ] Genotype Query Tools https://github.com/ryanlayer/gqt
- [ ] lobSTR http://melissagymrek.com/lobstr-code/
- [ ] QoRTs https://github.com/hartleys/QoRTs
- [ ] Rail: https://github.com/nellore/rail

Done:
- [x] HISAT2 https://github.com/infphilo/hisat2 available at https://toolshed.g2.bx.psu.edu/view/iuc/hisat2

Others:
- [ ] Scikit-ribo [_not public yet_]
- [ ] Centrifuge [_not ready yet_]  -  a metagenomics classifier. https://github.com/infphilo/centrifuge
- [ ] Kallisto [_non FOSS_] https://github.com/pachterlab/kallisto

**Comment by erasche** [comment]
fyi we have a global todo list in https://github.com/galaxyproject/tools-iuc/issues/33

**Comment by martenson** [comment]
yeah I know, but that is a list of things you actually want to wrap, this is just a brain dump

**Comment by erasche** [comment]
Ah ok :)

+1 to basset, scikit-ribo seems to have disappeared from the internet.

**Comment by davebx** [comment]
JunctionSeq also has an issue at #355

**Comment by martenson** [comment]
thanks @davebx - updated

**Comment by nsoranzo** [comment]
+1 to Kallisto, I'm going to need it soon.

**Comment by michaelmhoffman** [comment]
Would love to see Cytomod in there eventually although source is not yet public. @cviner

**Comment by bgruening** [comment]
@nsoranzo any reason you need kallisto and not sailfish?

**Comment by hanfang** [comment]
@erasche scikit-ribo has not yet hit beta. I will make the repo public asap. Thanks!

**Comment by nsoranzo** [comment]
@bgruening It's for a RNA-Seq pipeline in development by my colleague @lucventurini.

**Comment by martenson** [comment]
Blog post with list of #gi2015 sw and relevant papers (useful for citations tags) http://www.gettinggeneticsdone.com/2015/11/software-from-cshl-genome-informatics.html

**Comment by erasche** [comment]
Volunteering for mash.

**Comment by bgruening** [comment]
@martenson I have moved a few items over to the Metagenomic hackathon. @erasche especially mash and centrifuge is a good start for new codefest participants I guess.

**Comment by erasche** [comment]
@bgruening you would think that... but it:

- fails to compile nicely
- depends on libcapnp
- detects a stack smash and coredumps when running the example command

(I wanted to play around with/test it this morning).

**Comment by bgruening** [comment]
@erasche bioinformatics software is like a box of chocolate you never know what you gonna get :(

Monocle work started here: https://github.com/bgruening/galaxytools/commits/monocle

**Comment by nsoranzo** [comment]
@KeywanHP is also interested in a Kallisto wrapper.

**Comment by KeywanHP** [comment]
Kallisto/Sleuth :+1:

**Comment by davebx** [comment]
Talked to @infphilo, centrifuge should be postponed until further notice.

**Comment by nsoranzo** [comment]
I have been informed that Kallisto is not Free/Open Source Software, so I'm :-1: on this.

**Comment by bgruening** [comment]
Sailfish and Salmon is a good (even better) alternative for Kallisto and afaik it also works with Sleuth.

**Comment by martenson** [comment]
@nsoranzo I remember now that there was a discussion about their licence. I even made a PR for some detail there. (https://github.com/pachterlab/kallisto/pull/64) :)

I agree though. Wrapping closed source or for-profit tools sounds like a waste of resources.
