### ISSUE TITLE
Enhancement: NCBI SRA query tools should remove/ignore extra whitespace around accession IDs

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#3616]
Tools: https://github.com/galaxyproject/tools-iuc/tree/master/tools/sra-tools 

Impact: Any NCBI query tool that accepts accessions as input. These can be entered as individual accessions or a list of accessions (one per line). When whitespace is added to the tool form, or within a list, this causes the tools to fail. Trailing blank line(s) can also lead to avoidable failures. 

Proposed fix: Strip any extra whitespace, empty newlines, or lines that contain only whitespace before making the query against NCBI. Any whitespace is not important to retain as far as I know, and cleaning up data seems like a practical "make it easier to use" change for these tools. Doesn't come up too often, but enough to address. **Papercut?**

Example of the error in the command line for a failure:

`acc='SRR1234567	'`

What the `stderr` reports:

> stderr
> /galaxy-repl/main/jobdir/XXX/XXX/XXXXXXXX/tool_script.sh: line 60: [: SRR1234567: unary operator expected

Thanks for considering

**Comment by jennaj** [comment]
Also, could consider allowing a list of accessions to be in a tab-delimited file, and let the user choose the column.

**Papercut?**

**Comment by bgruening** [comment]
Yes Papercut! :)

**Comment by jennaj** [comment]
Still open problem (reported yesterday at `org`). Be nice to get this picked up/deployed to usegalaxy.* servers before the Smorg Tapas :)

**Comment by vebaev** [comment]
Also some more observations - I have explored the tool in `eu` and `org`, and I found the `org` version more fine-tuned - when for example you retrieve SRA single-end it creates fastq straightforward as one history entry (also gz option is there). In `eu` it retrieves several entries as collections, some (PE) empty, and the real fastq is within another collection, which makes downstream work busier.

**Comment by bgruening** [comment]
@vebaev please always provide the tool version and make sure to compare the same versions if available.

**Comment by vebaev** [comment]
@bgruening the tool is this one - https://toolshed.g2.bx.psu.edu/repository?repository_id=cb2d31dfab58ee88
It is same version 2.11.0, however, I'm also confused as in `org` there is 2 tool entries "Faster Download and Extract Reads in FASTQ" same as in `eu`, and also "Download and Extract Reads in FASTQ" which I was talking about and is missing in `eu` with different tool options?

**Comment by bgruening** [comment]
Do you mean this tool https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/2.11.0+galaxy1

There is also: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fastq_dump/2.11.0+galaxy0
and https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fastq_dump/2.11.0+galaxy0

I guess a few are not showing up in the tool panel.

**Comment by vebaev** [comment]
Oh yes, it is the 2nd and 3rd link (I think it is the same one) I was searching in the panel and couldn't find! Thanks! Can we make it to show up in pannel somehow?

**Comment by jennaj** [comment]
I see the space fix in the command line of the current versions hosted at the servers, so considering this closed! 

toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.1.1+galaxy1
toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fastq_dump/3.1.1+galaxy1

I am testing whether a _trailing blank line_ will trigger a failure, too (have an example this morning!). I'll open a new ticket for that if needed.
