### ISSUE TITLE
Missing URLs from CPC

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#363]
https://jenkins.galaxyproject.org/view/Meta/job/community-package-cache/lastCompletedBuild/testReport/

we're only missing two!

- http://biowhat.ucsd.edu/homer/homer.v4.2.zip seems to be gone? Everything at biowhat.ucsd.edu
- XZ is refusing to serve their old versions, see their notice on http://tukaani.org/xz/old.html until the end of november. After that we'll be fine again.

Dunno what's up with pirhana, I'll have to double check the urls/sha256/etc.

**Comment by peterjc** [comment]
Yeah, http://biowhat.ucsd.edu/homer/homer.v4.2.zip came up on #212 and I'd spotted it via the indirect URL testing in ``planemo dependency_script`` too. I'd made a mental note to check this again in case the server was just briefly offline, but this seems to be a long term problem :(
