### ISSUE TITLE
jq error: "which: command not found"

### ISSUE THREAD

**Issue by npinter** [galaxyproject/tools-iuc#3645]
Hi,

I was using jq to parse a JSON file. It worked a few weeks ago but now raises an error with the exact same jq command and JSON file:

`/data/dnb03/galaxy_db/job_working_directory/018/971/18971896/tool_script.sh: line 39: which: command not found`

Thanks
Niko

**Comment by bgruening** [comment]
We are running this tool now in a container. I will revert that, but we need to add this dependency to the Docker container I guess.

**Comment by npinter** [comment]
It's working again! Thank you!
