### ISSUE TITLE
Adding "samtools coverage" into Galaxy

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/tools-iuc#3659]
Hi folks,

I have seen in the latest version of samtools a tool called "coverage" (http://www.htslib.org/doc/1.12/samtools-coverage.html).

I am wondering if there are plans to add this into Galaxy via the toolshed?

Thanks,

Darren

**Comment by bernt-matthias** [comment]
With this we should also try to upgrade from `1.9` to `1.12`

**Comment by heylf** [comment]
I am currently working on it. https://github.com/galaxyproject/tools-iuc/pull/3740
