### ISSUE TITLE
report a bug: Jbrowse can not find biopython

### ISSUE THREAD

**Issue by songshuang1996** [galaxyproject/tools-iuc#3667]
Dear developers:
I want to use Jbrowse on galaxy, however it is not working.The error is as below:
Traceback (most recent call last):
  File "/Users/songshuang/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b5c5470d7c09/jbrowse/jbrowse.py", line 16, in <module>
    from Bio.Data import CodonTable
ModuleNotFoundError: No module named 'Bio'

I found many other had the same problem. (https://biostar.usegalaxy.org/p/21815/index.html).And I tried many version of Jbrowse on galaxy(1.16.11+galaxy1,1.16.5+galaxy7,1.16.1+galaxy0,0.7.0), even reinstalled galaxy, however either of them failed.

How can I fix this problem? Thank you.

**Comment by bernt-matthias** [comment]
@songshuang1996 can you check in the Galaxy admin interface under `Manage Dependencies` if the dependency for jbrowse are resolved with conda (there should be a green checkmark).

**Comment by songshuang1996** [comment]
Thank you for reply. Yes, I checked dependencies. Everything looked fine(python 2.7 Jbrowse biopython etc), with green checkmark on the right. Sorry I left my computer in my office, thus I can not provide screenshot of that page now. I will provide it as soon as possible.

**Comment by songshuang1996** [comment]
![Screen Shot 2021-05-14 at 8 35 07 AM](https://user-images.githubusercontent.com/81628468/118203837-833bf600-b48f-11eb-8c62-dc9aad564e0f.png)

**Comment by bernt-matthias** [comment]
Can you post the content of `tool_script.sh` from the job's working dir?

**Comment by bernt-matthias** [comment]
If the working dir is purged you also find it in the logs?

**Comment by songshuang1996** [comment]
The tool_script.sh only appear in a flash, and then removed automatically with the folder(like rm -r ~/galaxy/database/jobs_directory/000/20) containing it.
This might be the working dir you mentioned: ~/galaxy/database/jobs_directory/000/20/tool_script.sh
[tool_script.txt](https://github.com/galaxyproject/tools-iuc/files/6482263/tool_script.txt)

**Comment by bernt-matthias** [comment]
Set `cleanup_job` to `onsuccess` in galaxy.yml and restart. Then the working dir of failed jobs won't be deleted. Then we need the content of the tool_script.sh.

**Comment by songshuang1996** [comment]
Yes, I have post it in last comment. That file I renamed to tool_script.txt.

**Comment by songshuang1996** [comment]
#!/bin/bash

# The following block can be used by the job system
# to ensure this script is runnable before actually attempting
# to run it.
if [ -n "$ABC_TEST_JOB_SCRIPT_INTEGRITY_XYZ" ]; then
    exit 42
fi
[ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58')" ] || {
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done
} ; python '/Users/songshuang/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/a6e57ff585c0/jbrowse/jbrowse.py' --version > /Users/songshuang/galaxy/database/jobs_directory/000/20/outputs/COMMAND_VERSION 2>&1; mkdir -p /Users/songshuang/galaxy/database/jobs_directory/000/20/working/dataset_cb845411-d29a-4377-a553-78ce2c9d04da_files &&  cp /Users/songshuang/galaxy/database/jobs_directory/000/20/configs/tmptrzsp0l0 /Users/songshuang/galaxy/database/jobs_directory/000/20/working/dataset_cb845411-d29a-4377-a553-78ce2c9d04da_files/galaxy.xml &&  export JBROWSE_SOURCE_DIR=$(dirname $(which prepare-refseqs.pl))/../opt/jbrowse  &&  python '/Users/songshuang/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/a6e57ff585c0/jbrowse/jbrowse.py'  --jbrowse ${JBROWSE_SOURCE_DIR} --standalone 'minimal'  --outdir /Users/songshuang/galaxy/database/jobs_directory/000/20/working/dataset_cb845411-d29a-4377-a553-78ce2c9d04da_files /Users/songshuang/galaxy/database/jobs_directory/000/20/configs/tmptrzsp0l0 &&  cp /Users/songshuang/galaxy/database/jobs_directory/000/20/working/dataset_cb845411-d29a-4377-a553-78ce2c9d04da_files/index.html /Users/songshuang/galaxy/database/objects/c/b/8/dataset_cb845411-d29a-4377-a553-78ce2c9d04da.dat

**Comment by bernt-matthias** [comment]
Can you 

- login to the computer that is executing the job
- change to the `job working dir / working`
- activate the conda env `. '/Users/songshuang/galaxy/database/dependencies/_conda/bin/activate' '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58'`
- get the output of `conda list` (it should contain biopython)
- try to execute the commands on the last line of the tool script (probably you have to clear everything in the `working` dir)

**Comment by bernt-matthias** [comment]
Do you have any conda or python virtual env activated by default?

**Comment by songshuang1996** [comment]
I do have a base conda env activated.[base_conda_list.txt](https://github.com/galaxyproject/tools-iuc/files/6489172/base_conda_list.txt)
After I activate '/Users/songshuang/galaxy/database/dependencies/_conda/envs/mulled-v1-8caab3d6756f1460da0538aac50a0ca397d7e8b4a8ff79d7d838af7830f44e58' you mentioned, and execute the last commands in the  tool_script.sh. The commands seemingly work well.
The output is: 'WARNING: No feature names found for indexing, only reference sequence names will be indexed.'
![Screen Shot 2021-05-16 at 8 14 57 PM](https://user-images.githubusercontent.com/81628468/118396759-944d5880-b683-11eb-844b-4303156df7c4.png)

And my computer is M1 mac. But I think it will not influence conda environment.
Hope these information can be helpful. Thank you.

**Comment by bernt-matthias** [comment]
Can you try to configure conda to not activate base by default and try again to execute via galaxy?

**Comment by songshuang1996** [comment]
It works when deactivating conda environment. Thank you. And sorry for disturbing you.
I have one more question, I face the same error when using Jbrowse on my local galaxy and https://usegalaxy.org/.
![Screen Shot 2021-05-17 at 4 03 40 PM](https://user-images.githubusercontent.com/81628468/118453316-a71a6880-b729-11eb-9589-ecd147ccf160.png)
Is there any way to fix this problem? Thank you.

**Comment by bernt-matthias** [comment]
Wonderful. I think for the other problem the following helps: 

- Admin
- Manage Allowlist
- Check all JBrowse tools
- Submit new allow list

The reason is that Galaxy forbids to show html output of tools by default. 

I'm going to close this issue. Please feel free to reopen if needed.

**Comment by mjbludwig** [comment]
I am having the exact same symptoms but I do not think I have a base environment being loaded? The environment is definitely built correctly since importing works fine on the command line with it loaded. 

I can only imagine its due to the same issue of having a base conda env active but I am not sure where its getting that from?
