### ISSUE TITLE
Jellyfish tool: can't find counts file

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/tools-iuc#3685]
Hi, 

I'm trying to use Jellyfish to count kmers in illumina sequencing reads. This seems to work ok (using the `count` command), and outputs a binary file. It also works with the selected option to `dump in text format`, outputting a text file.  

Then I want to use Jellyfish again with the `histo` option, to convert the counts file (I'm assuming this is the binary file) to a histogram, but it can't seem to find the file in the history. The file has a format `jellyfish`. I've tried changing the datatype to binary but it has no effect. 

Thanks if anyone knows how to fix! 

Anna

**Comment by bgruening** [comment]
@AnnaSyme the `jellyfish` datatype is new, you probably need to add this to your Galaxy instance (update to the latest revision, or maybe you need to backport or upgrade Galaxy).

**Comment by bernt-matthias** [comment]
@AnnaSyme please reopen if needed.
