### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#3691]
Works already for the CI.

**Comment by nsoranzo** [comment]
xref. https://github.com/galaxyproject/galaxy/issues/10850

**Comment by bernt-matthias** [comment]
Is 6 already a majority? :) 

Just noticed that the CI and PR badges in the README already point to the main branch ..

**Comment by nsoranzo** [comment]
As a testbed I've now renamed the https://github.com/galaxyproject/tools-devteam repository.

**Comment by peterjc** [comment]
As long as we're on top of the CI and documentation changes, this seems like a good idea. It's something I've been thinking about not acted on yet for other projects.

**Comment by peterjc** [comment]
I was thinking some of the repositories might have some command line git usage instructions, perhaps in the CONTRIBUTING files. Tools IUC looks OK in that file at least.

Note searching for master in this repository shows a lot of data URLs using the master branch of other repositories.

Also many (all?) our ``.shed.yml`` files have the master branch in their ``remote_repository_url`` values. We may need to bulk update those?

**Comment by bernt-matthias** [comment]
> Also many (all?) our .shed.yml ...

Indeed .. good point. Maybe we can use the opportunity and check them.

**Comment by nsoranzo** [comment]
> Note searching for master in this repository shows a lot of data URLs using the master branch of other repositories.
> 
> Also many (all?) our `.shed.yml` files have the master branch in their `remote_repository_url` values. We may need to bulk update those?

We could bulk update those, but we don't need to because GitHub redirects them automatically, try e.g. https://github.com/galaxyproject/tools-devteam/tree/master/tools/express

**Comment by bernt-matthias** [comment]
> GitHub redirects them automatically

Cool. Was already wondering how we could manage  this. :)

**Comment by peterjc** [comment]
Might this redirection depend on how the main to master default branch change was done on GitHub?

**Comment by nsoranzo** [comment]
> Might this redirection depend on how the main to master default branch change was done on GitHub?

Maybe? We will do it in the same way it was done on tools-devteam and many other Galaxy repos.

**Comment by nsoranzo** [comment]
I went ahead and rename the `master` branch to `main`.

If you have a fork of this repository, you can do the same from its GitHub page by clicking the "Settings" top tab, then selecting "Branches" on the left menu and rename the default branch to `main`.

Then, on the command line:
```shell
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

and if the remote for galaxyproject's tools-iuc repository is called `upstream`:

```shell
git fetch upstream
git remote set-head upstream -a
```

**Comment by bernt-matthias** [comment]
Wonderful. Thanks.
