### ISSUE TITLE
Gemini Tools lack test cases

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#37]
Most tests for Gemini are failing with

```
RunToolException: Error creating a job for these tool inputs - {u'type': u'error', u'data': {u'infile': u'History does not include a dataset of the required format / build', u'annotate_source': u'History does not include a dataset of the required format / build'}}
```
[reference test report](https://gx.hx42.org/job/IUC-Github/lastCompletedBuild/testReport/)

which turns out to be because there aren't any test cases. Anyone want to write some? :) @bgruening @blankenberg

**Comment by erasche** [comment]
Ping @bgruening @blankenberg would it be possible to get GEMIMI, snpsift, and snpeff test cases? Is there someone else who knows about these things who could write them?

We are really close to having everything under test. https://travis-ci.org/galaxyproject/tools-iuc/builds/61457586

**Comment by bgruening** [comment]
Test cases and a updated version is needed :( I will have no time the next 2 weeks. Will see if I can do this afterwards.

**Comment by erasche** [comment]
Okay, thanks for the timeline!

**Comment by yhoogstrate** [comment]
Solution is proposed here: https://github.com/galaxyproject/tools-iuc/pull/534

**Comment by yhoogstrate** [comment]
I think this has been solved. Thanks @bgruening @TorHou @blankenberg @matthdsm
