### ISSUE TITLE
DropletUtils rank barcodes error

### ISSUE THREAD

**Issue by bellenger-l** [galaxyproject/tools-iuc#3705]
Hello,

I saw that the DropletUtils tool doesn't print the knee and the inflexion point on the [rank barcode plot](https://github.com/galaxyproject/tools-iuc/blob/master/tools/dropletutils/test-data/defs_barcoderankings.png). Can you explain why this feature isn't working anymore ?

Thanks,
Best,
Léa

**Comment by bernt-matthias** [comment]
Should be fixed in https://github.com/galaxyproject/tools-iuc/pull/3781
