### ISSUE TITLE
CI does not fail with malformed XML

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#3712]
https://github.com/galaxyproject/tools-iuc/runs/2737777649 passes but has XML errors as it seems.

Found by @mblue9, see here: https://github.com/galaxyproject/tools-iuc/pull/3330#issuecomment-853911863

**Comment by bgruening** [comment]
@bernt-matthias maybe you can look at that?

**Comment by bernt-matthias** [comment]
Should be fixed by https://github.com/galaxyproject/planemo-ci-action/pull/19.. @mvdbeek @nsoranzo do you think this is good to go?

**Comment by mvdbeek** [comment]
Sorry, i forgot about this one. Yeah, that looks great!

**Comment by bernt-matthias** [comment]
Thanks @mvdbeek .. I released 1.0.4. of the action and restarted CI to check if the linting failure is now detected.

**Comment by bernt-matthias** [comment]
Works now: https://github.com/galaxyproject/tools-iuc/runs/2758309143

**Comment by bgruening** [comment]
Awesome! Thanks!
