### ISSUE TITLE
query_tabular - request add support for built-in math functions

### ISSUE THREAD

**Issue by eschen42** [galaxyproject/tools-iuc#3739]
For query_tabular Galaxy Version 3.0.0, I have tried `floor` and `exp` from the SQLite3 math built-in functions [https://sqlite.org/lang_mathfunc.html](https://sqlite.org/lang_mathfunc.html) but got:

- `Error: no such function: floor`
- `Error: no such function: exp`

e.g., 
```sql
select t1.mz, floor(999 * t2.c6/t3.c6_max) as intensity
from t1, t2, (select max(c6) as c6_max from t2) t3 
where t1.variableMetadata = t2.c1 and 999 * t2.c6/t3.c6_max > 1
```

**Comment by jj-umn** [comment]
I don't think we can count on python sqlite3 being compiled with the math functions enabled.  
I'll see if I can include most of those using sqlite user-defined functions 
using 
https://docs.python.org/3.9/library/math.html

**Comment by jj-umn** [comment]
@eschen42  I've entered a pull request to add python math functions to query_tabular:
https://github.com/galaxyproject/tools-iuc/pull/3746
