### ISSUE TITLE
Bam to Wiggle reported error

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/tools-iuc#3751]
Recently a user reported the following error while running the Bam to Wiggle tool:

![Screenshot from 2021-06-22 13-53-20](https://user-images.githubusercontent.com/26678117/122920069-43efa780-d361-11eb-9f73-5da7f1713607.png)

It can be reproduced in usegalaxy.org but not in usegalaxy.eu. Histories:
- https://usegalaxy.org/u/gallardoalba/h/bam-to-wiggle-error
- https://usegalaxy.eu/u/gallardoalba/h/bam-to-wiggle

Tool link: https://toolshed.g2.bx.psu.edu/repository?repository_id=96f36d05c72851a8

**Comment by bgruening** [comment]
@jennaj that was solved, isn't it? It was a to-less-memory error?

**Comment by jennaj** [comment]
Cleaning up some old issues -- just confirmed is still "fixed" at `org`. I don't have permissions to close this out -- could one of you do that? Thanks!

Ref: https://github.com/mvdbeek/usegalaxy-tests/issues/23
