### ISSUE TITLE
Gatk2 Missing phiX.fasta

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#38]
[Test Results](https://gx.hx42.org/job/IUC-Github/lastCompletedBuild/testReport/functional.test_toolbox/TestForTool_gatk2_variant_combine/functional_test_toolbox_TestForTool_gatk2_variant_combine_test_tool_000000/)

```
IOError: [Errno 2] No such file or directory: '/var/lib/jenkins/workspace/IUC-Github/tools/gatk2/test-data/phiX.fasta'
```

relevant for variant_combine and variant_eval

**Comment by nsoranzo** [comment]
It's a 8Kb file from Galaxy test-data/ directory, I will add it.

**Comment by erasche** [comment]
Thanks Nicola!
