### ISSUE TITLE
Inconsistent results with dada2 tutorial pipeline

### ISSUE THREAD

**Issue by o-william-white** [galaxyproject/tools-iuc#3848]
Hello,

I am trying to replicate the dada2 tutorial https://benjjneb.github.io/dada2/tutorial.html on galaxy.eu.

I have noticed that the number of ASVs identified by my galaxy analysis is quite different to the results when I run the same analysis in R. Specifically, I get 398 ASVs with galaxy whereas I get 233 with R.

In addition, the output is slightly different with regards to the number of ASVs each time I run the analysis in galaxy. I get the same result every time in R.

Please see the history of my analysis https://usegalaxy.eu/u/ollie_white/h/dada2-workflow-test and workflow https://usegalaxy.eu/u/ollie_white/w/dada2-tutorial-pipeline

I have attached my Rscript for the tutorial too if helpful. 

I am fairly confident that my galaxy pipeline is working as expected compared to the Rscript so was wondering if it might be something different with galaxy? 

Do let me know if anything is not clear

Best wishes
Ollie

[tutorial_script.txt](https://github.com/galaxyproject/tools-iuc/files/6863846/tutorial_script.txt)

**Comment by o-william-white** [comment]
Hello again, 

I have been trying to hone in the a specific cause of the issue that can be replicated. 

The first issue I can find is that "dada2: learnErrors" does not work as expected with a collection of pairs with more than one pair of samples. See history here https://usegalaxy.eu/u/ollie_white/h/dada2learnerrorsthreesamples 

See data number 29 for the learn errors step on the forward reads which states that "8279053 total bases in 33051 reads from 3 samples will be used for learning the error rates." 

Also see data number 27 for the reverse reads which says "8289090 total bases in 33051 reads from 3 samples will be used for learning the error rates."

However, I know that the number of bases should be 8292222 and 8275921 for forwards and reverse reads respectively based on the same analysis in R. For some reason not all of the bases are being used in this step. Perhaps this is having a knock on effect on the rest of the pipeline?

However, this does not seem to be an issue with a collection of pairs with only one pair of samples. See history here  https://usegalaxy.eu/u/ollie_white/h/dada2-learnerrors-single-sample

If anyone has any insight into this it would be much appreciated. I will keep trying to figure out what the issue might be. 

Best wishes
Ollie

**Comment by o-william-white** [comment]
Hi @bernt-matthias 

Thanks for adding dada2 to galaxy, I am enjoying working with it. 

Is it possible that the learnErrors step is taking a subsample of bases from the input data? 

I am struggling to replicate the dada2 tutorial analysis https://benjjneb.github.io/dada2/tutorial.html and I have found some differences with the output from R.

If there is anything I can run or any way I can help to assist with this please do let me know

Best wishes
Ollie

**Comment by o-william-white** [comment]
Here is an updated link to a galaxy history https://usegalaxy.eu/u/ollie_white/h/dada2-learnerrors

The history has the filtered reads as generated in R. The learn error step has been run for the forward reads and should read "33514080 total bases in 139642 reads from 20 samples will be used for learning the error rates."

Cheers
Ollie

**Comment by bernt-matthias** [comment]
I will have a look. First thing that I noticed is that `learnErrors` and `dada` should be applied independently on forward and reverse reads as shown here: https://github.com/galaxyproject/tools-iuc/blob/master/tools/dada2/static/images/pairpipe.png (the image should actually be shown on the help section .. seems to be a bug)

**Comment by bernt-matthias** [comment]
> Is it possible that the learnErrors step is taking a subsample of bases from the input data?

Yes. This can be controlled with the parameter `Magnitude of number of bases to use for learning`

**Comment by o-william-white** [comment]
Hi @bernt-matthias 

Thanks for the message and details.  It was interesting that the image said that the collection should be sorted after it is unzipped because I hadn't done this. I sorted the unzipped collection but I got the same result unfortunately. 

I also ran filterAndTrim before the forwards and reverse reads were unzipped. However, the filterAndTrim has the option to take paired collection data and the summary stats stats are the same for the R package so I think this is okay.

As far as I am aware, I have applied learnErrors and dada on the forward and reverse reads independently. See workflow here https://usegalaxy.eu/u/ollie_white/w/dada2-tutorial-pipeline for more details

I noticed the parameter for the 'Magnitude of number of bases to use for learning'. I assumed this is the same as nbases in for the learnErrors command in R, which has a default value of 1e8. I left this as 8 to match the default for the R package. Note that I tried to increase this value in Galaxy but I got the same result again.

Would be great to know what you think? I would like to use dada2 for a training course and I just want to make sure I can replicate the tutorial.

Cheers
Ollie

**Comment by bernt-matthias** [comment]
> Hi @bernt-matthias
> 
> Thanks for the message and details. It was interesting that the image said that the collection should be sorted after it is unzipped because I hadn't done this. I sorted the unzipped collection but I got the same result unfortunately.

Sorting the collections is only needed if they are not provided as pairs. Then the input collections might have different order  which would mix up samples. But in your workflow this seems fine.

> I also ran filterAndTrim before the forwards and reverse reads were unzipped. However, the filterAndTrim has the option to take paired collection data and the summary stats are the same for the R package so I think this is okay.

This is good. So we can focus on `learnErrors`.

> As far as I am aware, I have applied learnErrors and dada on the forward and reverse reads independently. See workflow here https://usegalaxy.eu/u/ollie_white/w/dada2-tutorial-pipeline for more details

Yes, the workflow looks good to me. I was just wondering because in one of the shared histories forward and reverse were used as inputs together.

> I noticed the parameter for the 'Magnitude of number of bases to use for learning'. I assumed this is the same as nbases in for the learnErrors command in R, which has a default value of 1e8. I left this as 8 to match the default for the R package. Note that I tried to increase this value in Galaxy but I got the same result again.

We set this as `10**8` here: https://github.com/galaxyproject/tools-iuc/blob/c2a498bd93a857c2c5bdd77d4974ed71235ad47a/tools/dada2/dada2_learnErrors.xml#L25 .. 

> Would be great to know what you think? 

Can you share me a history that was created with the workflow. Then I can try to re-run `learnErrors` localy and provide the R code that is generated by the Galaxy tool. Then we can check for differences.

> I would like to use dada2 for a training course and I just want to make sure I can replicate the tutorial.

One question that I have in mind is if the numbers from the dada2 tutorial are up-to-date with the latest dada2 version?

**Comment by o-william-white** [comment]
I have restarted the workflow in this history https://usegalaxy.eu/u/ollie_white/h/dada2-tutorial-workflow

Let me know if you have any issues accessing the data you need.

I expect that the numbers in the tutorial page could be slightly different given package updates. 

My concern was that the number of ASVs produced by my workflow was slightly different each time I repeated the workflow, and different to the results produced when I ran the same data through the pipeline in R, which had the same results every time. 

I ran the tutorial data in R using dada2 version 1.20.0. 

Cheers
Ollie

**Comment by bernt-matthias** [comment]
The Rscript that is executed should be something like this:

```
library(ggplot2, quietly=T)
library(dada2, quietly=T)

args <- commandArgs(trailingOnly = TRUE)
nthreads <- as.integer(args[1])

files <- c()
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_89.dat') #F3D0_S188_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_84.dat') #F3D1_S189_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_82.dat') #F3D2_S190_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_98.dat') #F3D3_S191_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_97.dat') #F3D5_S193_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_95.dat') #F3D6_S194_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_90.dat') #F3D7_S195_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_88.dat') #F3D8_S196_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_83.dat') #F3D9_S197_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_100.dat') #F3D141_S207_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_91.dat') #F3D142_S208_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_92.dat') #F3D143_S209_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_81.dat') #F3D144_S210_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_99.dat') #F3D145_S211_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_94.dat') #F3D146_S212_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_85.dat') #F3D147_S213_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_93.dat') #F3D148_S214_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_87.dat') #F3D149_S215_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_86.dat') #F3D150_S216_L001_001
files <- c(files, '/tmp/tmpa27973nd/files/000/dataset_96.dat') #Mock_S280_L001_001

err <- learnErrors(files, nbases = 10**8,
           errorEstimationFunction = loessErrfun, multithread = nthreads,
           randomize = FALSE, MAX_CONSIST = 10, OMEGA_C = 0.0)

saveRDS(err, file='/tmp/tmpa27973nd/files/000/dataset_497.dat')

plot <- plotErrors(err, obs = TRUE, err_out = TRUE, err_in = FALSE, nominalQ = TRUE)
ggsave('plot.pdf', plot, width = 20,height = 15,units = c("cm"))
```

**Comment by bernt-matthias** [comment]
I get `26535920 total bases in 139642 reads from 20 samples will be used for learning the error rates.` for the forward reads after `filterAndTrim`.

**Comment by bernt-matthias** [comment]
According to the Galaxy tool output we have `26535920 total bases in 139642 reads`

I downloaded the forward collection and counted the reads with: `zcat * | grep "^@M00" | wc -l ` which gave me the correct number: 139642

Also counting the number of bases (`zcat * | grep "^@M00" -A1  | grep -E -v "^@M00|--" | awk '{printf("%s", $0)}' | wc -m`) seems to give the correct number `26535920`

**Comment by o-william-white** [comment]
> I get `26535920 total bases in 139642 reads from 20 samples will be used for learning the error rates.` for the forward reads after `filterAndTrim`.

I got this with the galaxy script too, but the numbers don't add up I think. 

The filterAndTrim step should have truncated the forward reads to 240 and the reverse reads to 160. 

Assuming we have 139642 filtered reads, we should have 240 x 139642 = 33514080 forward bases and 160 x 139642 = 22342720 reverse bases. These are the numbers returned when I run the tutorial in R.

Note that when I was checking these numbers again, I found an error in the pipeline which has now been updated apologies. I called the reverse reads the forward reads and vice versa. The pipeline has been updated and ran again and is accessible by the same link above.

**Comment by o-william-white** [comment]
After looking into this in more detail I think learnErrors is behaving exactly as it should be. I looked at the read length distribution for the forward reads used by learnErrors to check my assumption and there seem to be a mix of reads with a length of 240 and 160. See length distribution below.
![image](https://user-images.githubusercontent.com/10031094/127378825-d4b3f9fc-ec4e-4f92-b3de-9785d05f1bbc.png)

**Comment by o-william-white** [comment]
When I run the unzip collection step, it looks like the forward and reverse reads have been mixed together. 

The first few samples are behaving as I would have expected, and these are the files I would have checked so I never spotted this. I will look into it. See F3D3 and F3D5 as examples of samples where the forwards and reverse reads have been switched.

Thanks again for your help, really appreciate your thoughts on this

Best wishes
Ollie

**Comment by bernt-matthias** [comment]
>  it looks like the forward and reverse reads have been mixed together.

I also just noticed this. Trying to find out why.

**Comment by bernt-matthias** [comment]
Seems that usegalaxy.org is not affected by the problem with `unzip collection`

**Comment by bgruening** [comment]
I don't understand that. We don't have modifications for this tool. https://github.com/galaxyproject/galaxy/compare/release_21.05...usegalaxy-eu:release_21.01_europe?expand=1

Is the sorting affected by some local-settings? But even that we have fixed to some US locale.

**Comment by bernt-matthias** [comment]
> I don't understand that.

Me neither. And I'm wondering how to debug this. Seems difficult because its an internal tool.

> Is the sorting affected by some local-settings?

I can't imagine that it is the sorting / locale because I do not know a way how to mix up sorting of `"forward"` and `"reverse"`, or? Can you check if all jobs ran on the same compute node?

My best guess (but a very wild guess) is that somewhere in the Galaxy sources a data structure is used that does not guarantee the order.

**Comment by o-william-white** [comment]
I re-ran the unzip step and it seems that each time you run it you get a different mix of forward and reverse reads. This explains the inconsistency in my output. 



> Can you check if all jobs ran on the same compute node?

How would I check which compute node a job ran on? 

Do I need to close this issue and raise an issue somewhere else? 

Thanks again for all the feedback on this, pleased to have a better idea of the issue

Best wishes
Ollie

**Comment by bernt-matthias** [comment]
> I re-ran the unzip step and it seems that each time you run it you get a different mix of forward and reverse reads. This explains the inconsistency in my output.

Thanks for checking.

> How would I check which compute node a job ran on?

This is more a question for @bgruening 

> Do I need to close this issue and raise an issue somewhere else?

Should be fine with this issue for now. 

> Thanks again for all the feedback on this, pleased to have a better idea of the issue

For your course I would suggest to keep forward and reverse reads in separate collections (sort them to be sure). Then the unzip tool is not needed. 

Btw. do you use any (Galaxy) tools for downstream analyses of the dada2 results in you course?

**Comment by o-william-white** [comment]
I will try to repeat but upload the input data with rules to distinguish forward and reverse.



> Btw. do you use any (Galaxy) tools for downstream analyses of the dada2 results in you course?

Yes I am hoping to use galaxy for downstream analyses too. I would like to use R as an interactive session within galaxy but that seems to be an issue at the moment too.

**Comment by bernt-matthias** [comment]
The `Unzip collection` problem might be solved soon: https://github.com/galaxyproject/galaxy/pull/12305

**Comment by o-william-white** [comment]
@bernt-matthias thanks for letting me know, this was a really quick turnaround. Will it be automatically updated on the galaxy.eu server?

**Comment by bernt-matthias** [comment]
@bgruening do you know if https://github.com/galaxyproject/galaxy/pull/12305 is already integrated on eu?

**Comment by bgruening** [comment]
@bernt-matthias it was not. But now it is.

**Comment by bernt-matthias** [comment]
Then I'm closing this. Thanks for reporting @o-william-white. Feel free to reopen if there are still problems.

**Comment by o-william-white** [comment]
Thanks very much for your help throughout @bernt-matthias
