### ISSUE TITLE
Racon polishing tool does not accept fastqsanger format

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/tools-iuc#3856]
Hi all, 

I am using Racon in Galaxy Australia. Racon needs reads in fastq format. Is it possible to have this tool accept reads in fastqsanger format? 

The reason I ask is because I am running a polishing workflow on a large input dataset- the workflow alternates several times between the tools Minimap2 (which requires input in fastqsanger format) and Racon (requires fastq). Rather that duplicate the input file before the analysis and assign a different file type to each, I wanted to only have one input into the workflow. As most other tools require fastqsanger format, I use this. To change this input into fastq format during the workflow, I use FASTQ Groomer, but this takes a very long time. 

Thank you if possible!

**Comment by bgruening** [comment]
Mh, that is wired it should accept all FASTQ files https://github.com/bgruening/galaxytools/blob/master/tools/racon/racon.xml#L37

It also seems to work on EU. Could you check this on EU please and share a history?

Thanks!

**Comment by AnnaSyme** [comment]
Thanks @bgruening - I have tested on Galaxy Eu and seems to still be a problem. The input file (which I am fairly sure is in fastqsanger format) will only work in Racon if the datatype is changed to fastq. 

Here is a history:    https://usegalaxy.eu/u/annasyme/h/testing-racon-with-file-formats

File 1 is the reads in fastq format, file 6 is a copy of the file but datatype changed to fastqsanger. 

Racon will show that either are allowed as inputs when filling in the tool settings, but if the fastqsanger file is used, the job (file 8) fails with the error: 

```
[racon::createPolisher] error: file reads.fastqsanger has unsupported format extension (valid extensions: .fasta, .fasta.gz, .fna, .fna.gz, .fa, .fa.gz, .fastq, .fastq.gz, .fq, .fq.gz)!
```

The job runs ok (file 9) if the fastq file is used. 

Thanks, Anna

**Comment by bernt-matthias** [comment]
Fix is here https://github.com/bgruening/galaxytools/pull/1149
