### ISSUE TITLE
Error RCorrector

### ISSUE THREAD

**Issue by Melisa-Magallanes** [galaxyproject/tools-iuc#3862]
Hi all! I've been trying tu run Rcorrector but I'm getting this error:

error
An error occurred with this dataset:
This job was resubmitted to the queue because it encountered a tool detected error condition on its compute resource.
/data/dnb03/galaxy_db/job_working_directory/026/623/26623482/tool_script.sh: line 43: run_rcorrector.pl: command not found

What I'm doing wrong??

**Comment by bernt-matthias** [comment]
Sounds like a problem with the conda environment. On which server did this happen?

**Comment by Melisa-Magallanes** [comment]
it's hapenning at https://usegalaxy.eu/

**Comment by bgruening** [comment]
I try to work on it as soon as I can.

**Comment by bgruening** [comment]
@Melisa-Magallanes can you please try it again?

**Comment by Melisa-Magallanes** [comment]
It's working!! it's running now, i'll let you now later if it finish correctly. Thank you very much
