### ISSUE TITLE
ERROR RUNNING TRINITY

### ISSUE THREAD

**Issue by Melisa-Magallanes** [galaxyproject/tools-iuc#3866]
Hi there, 
I've tried all but I'm still getting this error:
Remote job server indicated a problem running or monitoring this job.
code 17: slurm_submit_batch_job error: Invalid qos specification.

What can I do?

**Comment by Melisa-Magallanes** [comment]
It's happening on usegalaxy.org

**Comment by bernt-matthias** [comment]
Can you report the error via the `report error` button of the dataset. Then the admins may take over.

**Comment by bernt-matthias** [comment]
See here https://training.galaxyproject.org/training-material/faqs/galaxy/analysis_troubleshooting.html

and here

https://training.galaxyproject.org/training-material/faqs/gtn/issues_galaxy.html
