### ISSUE TITLE
cstacks2 error - Galaxy Europe

### ISSUE THREAD

**Issue by ribaslej** [galaxyproject/tools-iuc#3868]
Hi Galaxy Team,

I'm running Stacks2 on usegalaxy.eu but the cstacks2 module gives me the following error message:
"tool error
An error occurred with this dataset:
Conda dependency seemingly installed but failed to build job environment."

Everything works fine with ustacks2 module. Below I share my population-map, the only file that was not generated from ustacks2 and are needed to upload.

LIV02	1
LIV03	1
LIV01	1
QUA01	2
QUA02	2
QUA03	2
QUA04	2
ALE01	3
ALE02	3
ALE03	3
ALE04	3
URU01	4
URU02	4
URU03	4
URU04	4
ITA01	5
ITA02	5
ITA03	5
UY001	6
UY002	6
ROS01	7
ROS02	7
ROS03	7
ROS04	7
SAO01	8
SAO02	8
SAO03	8
SAO04	8
DOM01	9
DOM02	9
DOM03	9
CAND1	10
CAND2	10
CAND3	10
CAND4	10
PEL01	11
PEL02	11
PEL03	11
PEL04	11
TAIM1	12
TAIM2	12
TAIM3	12
TAIM4	12
SM1-1	13
SM1-2	13
SM1-3	13
SM1-4	13
SM1-5	13
SM2-1	14
SM2-2	14
SM2-3	14
CAC01	15
CAC02	15
CAC03	15
CAC04	15
BUT01	16
BUT02	16
BUT03	16
BUT04	16

Thank you in advance for any help.

Best regards,
Luiz Eduardo.

**Comment by bgruening** [comment]
@ribaslej can you sent an error report via Galaxy please. This gives the admins more information. Thanks.

**Comment by bgruening** [comment]
Ah I see it, thanks!

**Comment by ribaslej** [comment]
Yes, after writing here I sent the report. I also noted that my fastq files were gzipped. Now I'm uploading unzipped, maybe is it?

Thanks.

**Comment by bgruening** [comment]
That is not the problem afaik. Can you try rerunning it again? I will follow up per mail and close this one, ok?
