### ISSUE TITLE
dada2 derepFastq

### ISSUE THREAD

**Issue by o-william-white** [galaxyproject/tools-iuc#3877]
Hello, 

I am using dada2 on Galaxy but noticed that one of the commands derepFastq was not available in Galaxy. I have searched for alternative within galaxy but I wasn't able to find one. Would it be possible to have this included please? 

It is needed as a step in the analyses of ITS using dada2

@bernt-matthias I am linking you here because you have been really helpful with dada2 before but no worries if not possible.

Best wishes
Oliver

**Comment by bernt-matthias** [comment]
Since 1.12 there is no need for dereplicatio anymore, see https://benjjneb.github.io/dada2/ReleaseNotes_1_12.html

> The dada function can now accept fastq filenames rather than requiring files be dereplicated and stored into memory first. This allows memory requirements to remain flat when processing large numbers of samples.

**Comment by o-william-white** [comment]
Hi @bernt-matthias, this is great, thank you for letting me know! 

Best wishes
Ollie
