### ISSUE TITLE
package_bx_python_0_7_2 doesn't compile bx.bbi.bigbed_file

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/tools-iuc#388]
When I install package_bx_python_0_7_2 it seems to skip compilation of the c libraries in lib/bx/bbi, and therefore only creates lib bx.bbi.bigwig_test.

This is what I get:

```
>>> from bx.bbi import bigbed_file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name bigbed_file
```

This is what I expected: 

```
>>> from bx.bbi import bigbed_file
>>> bigbed_file
<module 'bx.bbi.bigbed_file' from '....egg/bx/bbi/bigbed_file.so'>
>>>
```

As you can see the shared objects are also not present while the original code was downloaded:

![screenshot from 2015-11-12 11-52-57](https://cloud.githubusercontent.com/assets/2264697/11116649/45788c84-8934-11e5-8cc9-8f377bd401f3.png)

**Comment by yhoogstrate** [comment]
What I suspect that happens is:

- During installation of bx_python, presence of numpy is defined using "try: import numpy"
- If not present, the bbi files are not compiled
- When I import the galaxy build of numpy I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

```

**Comment by yhoogstrate** [comment]
I am closing this issue because this package is not in the master branch or the main toolshed.

**Comment by bgruening** [comment]
Not sure if I'm following here:
This is the TS package: https://toolshed.g2.bx.psu.edu/view/iuc/package_python_2_7_bx_python_0_7/9e4101fb24af
and this is the iuc package right?
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_python_2_7_bx_python_0_7_2/tool_dependencies.xml
