### ISSUE TITLE
Updating QC tools on main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#392]
This would include add/updating the following:
- [trimmomatic](https://toolshed.g2.bx.psu.edu/view/pjbriggs/trimmomatic)
  - [x] Test
  - [x] Main
- [trim_galore](https://github.com/bgruening/galaxytools/tree/master/tools/trim_galore)
  - [x] Test
  - [x] Main
- [QORTS](https://github.com/hartleys/QoRTs) wrapping not finished yet (in IUC repo)
  - [ ] Test
  - [ ] Main
- [datamash](https://toolshed.g2.bx.psu.edu/view/iuc/suite_datamash/fbe724ced39e)
  - [x] Test
  - [x] Main

**Comment by bgruening** [comment]
@davebx is working on QORTS afaik.

**Comment by martenson** [comment]
Existing tools are now deployed on Test. Note that one datamash tool was already there, from Asaf, so it is there twice now.

**Comment by bgruening** [comment]
@martenson can we hide Asaf's tool?

**Comment by martenson** [comment]
@bgruening I will uninstall it, it is Test after all.

**Comment by bgruening** [comment]
@davebx do you have your work for QORTS somewhere?
