### ISSUE TITLE
New datasources for Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#393]
- [x] ncbi sra
- [ ] [dorina](http://dorina.mdc-berlin.de/)

**Comment by mvdbeek** [comment]
@nekrut I did some work on https://github.com/mdshw5/sra-tools-galaxy @mdshw5  which you can find here https://toolshed.g2.bx.psu.edu/view/mvdbeek/sra_tools/9f74a22d2060
I'd be happy if we can take this up in the iuc

**Comment by mdshw5** [comment]
@mvdbeek that's fantastic! Could I get your to submit a pull request with your changes? I'll gladly add you as a collaborator on the repo - and don't mind at all if you or someone else wants to maintain the toolshed repo.

**Comment by mdshw5** [comment]
Possible stakeholders for this are @aboshkin and @kwrodarmer.

**Comment by mvdbeek** [comment]
@mdshw5 done, I meant to do a PR for a while now.

**Comment by bgruening** [comment]
@mdshw5 would it be possible to give the IUC group access to the toolshed repo? We would like to include SRA tools into usegalaxy.org. But we would need to have emergency access to the repository as well?

**Comment by mdshw5** [comment]
I've just deprecated the toolshed repository I was maintaining, as @mvdbeek significantly improved on it in his. Currently working on getting test passing in @travis-ci, but looks like they should pass on the toolshed. Maybe @mvdbeek could add us both to his repo?

**Comment by blankenberg** [comment]
I am also +1 for IUC adoption of SRA tools. There are some enhancements possible which would be easier to maintain this way.

**Comment by mdshw5** [comment]
Would you need to pull the source into the IUC repo on GitHub? If so that's not a problem.

**Comment by nekrut** [comment]
@mvdbeek Do a PR! How are things in Paris right now? I know Alban and Olivier are OK.

**Comment by mvdbeek** [comment]
I can do a PR to the IUC, no problem.
I'd be in favor of creating a new repo for the IUC, up to now my repo has only been cloned twice,
and that was me ;).
@drosofff and me are alright and not personally affected, it's still a horror though.

**Comment by martenson** [comment]
https://github.com/galaxyproject/tools-iuc/tree/master/tools/sra-tools is now installed on Main
