### ISSUE TITLE
FSD: Regions and FSD: Before/After should probably use the Galaxy-generated BAM index rather than generating one

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/tools-iuc#3931]
These tools call `pysam.index(bam_file)` which indexes next to the BAM, which in Galaxy is not going to be a writable path. These tools use pysam 0.15, but later versions have an option to specify the path when creating an index. However, these tools should probably just make use of the BAM index that is automatically generated for all BAM datasets in Galaxy, I haven't dug super deep but it looks like the input in question should have the index?

**Comment by nsoranzo** [comment]
Ping @NickSto @mvdbeek
