### ISSUE TITLE
New text processing tools for Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#395]
* [text_processing](https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/text_processing)
  * [x] Test
  * [x] Main
* [idconversion](https://github.com/bgruening/galaxytools/tree/master/tools/uniprot_rest_interface) (mapping gene and protein ids across databases)
  * [x] Test
  * [x] Main

**Comment by martenson** [comment]
text processing tools installed on Test

for idconversion the package_python_2_7 installation fails on Test with:

```
Error - <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'strip'
URL: https://test.galaxyproject.org/user/login
File 'lib/galaxy/web/framework/middleware/error.py', line 236 in next
  return self.app_iterator.next()
File 'lib/galaxy/web/framework/middleware/sentry.py', line 32 in __call__
  iterable = self.application(environ, start_response)
File '/srv/galaxy/test/venv/lib/python2.7/site-packages/paste/recursive.py', line 84 in __call__
  return self.application(environ, start_response)
File '/srv/galaxy/test/venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 633 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 126 in __call__
  return self.handle_request( environ, start_response )
File 'lib/galaxy/web/framework/base.py', line 184 in handle_request
  body = method( trans, **kwargs )
File 'lib/galaxy/webapps/galaxy/controllers/user.py', line 466 in login
  redirect = self.__get_redirect_url( kwd.get( 'redirect', trans.request.referer ).strip() )
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by blankenberg** [comment]
@martenson That error is from the login form being hit with no referer provided.  Should have been fixed in: https://github.com/galaxyproject/galaxy/pull/1091

Has test been updated?

**Comment by martenson** [comment]
@blankenberg thanks, I updated Test
Hovewer even before that, the tool actually installed everything and is showing up. Ready for testing.

**Comment by martenson** [comment]
done via https://github.com/galaxyproject/tools-iuc/issues/488
