### ISSUE TITLE
Genotyping Tools on Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#396]
Updating Main tools for variant analysis
- [bamleftalign](https://github.com/nekrut/tools-devteam/blob/master/tools/freebayes/leftalign.xml)
  - [x] Test
  - [x] Main
- [freebayes parallel implementaion](https://github.com/galaxyproject/tools-devteam/pull/265) - still WIP
  - [ ] Test
  - [ ] Main
- VCF IOBIO (as an IE)
  - [ ] Test
  - [ ] Main
- [snpeff](https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/snpeff) error during installation (@martenson)
  - [x] Test
  - [x] Main
- [vcflib](https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/vcflib) (update)
  - [ ] Test
  - [ ] Main
- vcftools (worth updating ?)
  - [ ] Test
  - [ ] Main
- create ped file from RG (using standard tags for P, M, C etc) (does not exist)
  - [ ] Test
  - [ ] Main
- [GEMINI](https://github.com/galaxyproject/tools-iuc/tree/master/tools/gemini) (update by Bjorn)
  - [ ] Test
  - [ ] Main
- Create tutorial for PLoS ComBio on tools wrapping philosophy and practice (possibly ask Frances) 
  - [ ] Test
  - [ ] Main
- wrap [angsd](http://popgen.dk/wiki/index.php/Main_Page)
  - [ ] Test
  - [ ] Main
- NVC
  - [x] Test
  - [x] Main
- [Duplex Novo](https://github.com/NickSto/duplex) for duplex sequencing analysis
  - [x] Test
  - [x] Main

**Comment by TorHou** [comment]
A new GEMINI version would be fantastic. There are problems compiling the versions 0.17.x. Only the newest version 0.18.0.a would compile for me.

**Comment by bgruening** [comment]
We should aim for 0.18. This on has a conda only install that hopefully works oob.

**Comment by martenson** [comment]
I updated freebayes on Test and duplex novo is now on Test thanks to @davebx. snpeff has trouble installing on Test.

I am not sure what is the plan with the others. E.g. NVC needs to be updated? What about vcflib? ping @nekrut

**Comment by nekrut** [comment]
The latest NVC will do. vcflib as well.

**Comment by martenson** [comment]
@nekrut latest NVC is on Test and Main, I will update vcflib next

**Comment by martenson** [comment]
remaining items moved to https://github.com/galaxyproject/tools-iuc/projects/2
