### ISSUE TITLE
ChIP-seq Tools on Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#397]
Update ChIP-seq tools on main:
- [bowtie2](https://github.com/galaxyproject/tools-devteam/tree/master/tools/bowtie2) (maybe update)
  - [x] Test (galaxy version 2.2.6)
  - [x] Main
- [DeepTools](https://github.com/deeptools) (version 2 comping soon!)
  - [x] Test (unable to install)
  - [ ] Main
- [MACS2](https://github.com/galaxyproject/tools-iuc/tree/master/tools/macs2) (update?)
  - [x] Test
  - [x] Main
- [diffBind](https://github.com/bgruening/galaxytools/tree/master/tools/diffbind)
  - [x] Test (galaxy version 2.0.2)
  - [x] Main
- [BAMfilter](https://github.com/galaxyproject/tools-iuc/blob/master/tools/ngsutils/bam_filter.xml) (remove 
  uninteresting regions)
  - [x] Test (galaxy version 0.5.7)
  - [x] Main

---

Something else to consider:
- IDR ?
- phantomPeaks ? 
- (ask Shaun about [MultiGPS/GPS/GEM](http://mahonylab.org/software/multigps/))

**Comment by martenson** [comment]
selected tools deployed on Test

**Comment by lparsons** [comment]
For MACS2 see PR #570

**Comment by martenson** [comment]
deeptools2 are on Test and seem ok, is it ready to go to Main? ping @bgruening @nekrut

**Comment by bgruening** [comment]
We are planning to have a 2.2.1 release early next week, with minor fixed. But I think 2.1 is, besides of the CSS bug a solid one. It's up to you.

**Comment by bgruening** [comment]
I think this can be closed. @nekrut please open id anything is missing. New training material with these tools is here: http://bgruening.github.io/training-material//ChIP-Seq/tutorials/TAL1_binding_site_identification
