### ISSUE TITLE
UMI tools targeting 21.01

### ISSUE THREAD

**Issue by chambm** [galaxyproject/tools-iuc#3975]
Is there a reason for the very recent Galaxy requirement? I have a client who isn't keen on upgrading right now from 19.09 but they want to use the latest fixes/features in umi_dedup.

**Comment by bernt-matthias** [comment]
IUC guidelines require a recent profile (max 1 year). Usually I take the latest release subtract 1 year .. which should have been 20.05. Can't remember why I have chosen 21.01 .. probably mixed up the years. 

Still, also 20.05 would not help your client. 

My suggestion would be to manually modify the profile and run a `planemo test --galaxy_branch release_19.09`  against the tools 

We could also lower the profile here .. but I guess not below 20.x

**Comment by chambm** [comment]
Ended up creating a newer version Galaxy server. Manually editing the wrapper to use a lower profile caused an error when loading the tool (i.e. it used some feature not available in 19.09).
