### ISSUE TITLE
HiC Tools on Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#398]
To deploy Hi-C tools on main:
- [x] [HiFive](https://github.com/bxlab/hifive)
- [x] [DeepTools 2](https://github.com/fidelram/deepTools) will support HiC
- **anything we are missing?**

**Comment by bgruening** [comment]
@jxtx any new about HiFive? We are close for a TS release for HiCExplorer + IE.

**Comment by jxtx** [comment]
@msauria What's preventing hifive from being in the ToolShed? It has a conda package so dependencies are easily handled now.

**Comment by martenson** [comment]
@jxtx some version (2/11/16) of hifive is on toolshed: https://toolshed.g2.bx.psu.edu/view/sauria/hifive/20dfaec1678c

**Comment by jxtx** [comment]
Right, my understanding was something prevented this from being deployed to main but I don't know what.

**Comment by jxtx** [comment]
@msauria update the hifive tools to use conda for dependencies and we tested the install last week. He is planning to add more tests by I don't think we should wait for that. This is ready to go to main @martenson. Can we create an "NGS: Chromosome Conformation" section with these tools in it and a "HiFive" section label, any other tools can go in this section with their own label.

**Comment by martenson** [comment]
Will do.

**Comment by martenson** [comment]
hifive is on Main now @jxtx @msauria - once cvmfs publishes the thing it should be visible
I will adjust the sections and labels tomorrow.

**Comment by jxtx** [comment]
Awesome!

**Comment by martenson** [comment]
hifive's section now in the right place in toolpanel under a label and with a label

**Comment by jennaj** [comment]
The link to the tool github repo (for the galaxy wrapped version, not the line-command version) is incorrect in the Tool Shed, and I didn't find it in tools-devteam or tools-iuc, so I am not sure where to put this issue with the wrapper. Please move it to where it would be appropriate.

At Galaxy Main, the wrapper is failing for option `-c`  ("Included chromosomes"). This is under the operation "Create HiC Project". As an aside, if that field is left empty, the tool fails for another reason. Both are below for troubleshooting.

**When a chromosome is entered on form, this error:**
```
Command Line

hifive  hic-project   -c chr14   -f 20 -j 1000 -n 100   -m 1000000 -x 0  /galaxy-repl/main/files/018/933/dataset_18933773.dat /galaxy-repl/main/files/018/933/dataset_18933827.dat -q
```

```
stderr

Fatal error: Exit code 2 ()
usage: hifive [-h] [--version]
              {fragments,5c-data,5c-project,5c-normalize,5c-complete,5c-heatmap,5c-interval,5c-combine-replicates,fends,hic-data,hic-project,hic-normalize,hic-complete,hic-heatmap,hic-mrheatmap,hic-interval,hic-combine-replicates}
              ...
hifive: error: unrecognized arguments: -c /galaxy-repl/main/files/018/933/dataset_18933827.dat
```

```
example:

Job ID	15106165 (bbd44e69cb8906b58a44c5361b6b5a72)
Tool ID	toolshed.g2.bx.psu.edu/repos/sauria/hifive/hifive/0.1.0
Tool Version	0.1.0
Job PID or DRM id	9261176.roundup
```

**When no chromosome is entered on form, this error:** (should this be required input at job submission?)

```
Command Line

hifive  hic-project     -f 20 -j 1000 -n 100   -m 1000000 -x 0  /galaxy-repl/main/files/018/933/dataset_18933773.dat /galaxy-repl/main/files/018/944/dataset_18944613.dat -q
```

```
stderr

Fatal error: Exit code 1 ()
divide by zero encountered in log
invalid value encountered in multiply
Traceback (most recent call last):
  File "/galaxy/main/deps/_conda/envs/__hifive@1.3/bin/hifive", line 4, in <module>
    __import__('pkg_resources').run_script('hifive==1.3.0', 'hifive')
  File "/galaxy/main/deps/_conda/envs/__hifive@1.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/galaxy/main/deps/_conda/envs/__hifive@1.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/cvmfs/main.galaxyproject.org/deps/_conda/envs/__hifive@1.3/lib/python2.7/site-packages/hifive-1.3.0-py2.7-linux-x86_64.egg-info/scripts/hifive", line 791, in <module>
    main()
  File "/cvmfs/main.galaxyproject.org/deps/_conda/envs/__hifive@1.3/lib/python2.7/site-packages/hifive-1.3.0-py2.7-linux-x86_64.egg-info/scripts/hifive", line 69, in main
    run(args)
  File "/galaxy/main/deps/_conda/envs/__hifive@1.3/lib/python2.7/site-packages/hifive/commands/create_hic_project.py", line 32, in run
    hic.find_distance_parameters(minsize=args.minbin, numbins=args.numbins)
  File "/galaxy/main/deps/_conda/envs/__hifive@1.3/lib/python2.7/site-packages/hifive/hic.py", line 491, in find_distance_parameters
    distance_parameters = numpy.zeros((valid.shape[0] - 1, 3), dtype=numpy.float32)
ValueError: negative dimensions are not allowed
```

```
example: 

Job ID	15113738 (bbd44e69cb8906b52b808b92b4de2e28)
Tool ID	toolshed.g2.bx.psu.edu/repos/sauria/hifive/hifive/0.1.0
Tool Version	0.1.0
Job PID or DRM id	9268351.roundup
```

**Comment by bgruening** [comment]
@jxtx can we move these tools into tools-iuc?

**Comment by jxtx** [comment]
Up to @msauria

**Comment by jxtx** [comment]
@bgruening I just talked to @msauria. He is pushing a new version of HiFive to address the issues and he is happy to have the IUC adopt the wrappers.

**Comment by bgruening** [comment]
Awesome, thanks @msauria and @jxtx!
