### ISSUE TITLE
RNA-seq tools on Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#399]
Update RNA-seq tools on Main:
## Installation
-  [x] [DEseq](https://github.com/galaxyproject/tools-iuc/tree/master/tools/deseq2) (only works on genes)
-  [x] [hisat2](http://ccb.jhu.edu/software/hisat2/index.shtml)
-  [x] [Htseq-count](http://www-huber.embl.de/users/anders/HTSeq/doc/count.html)
-  [x] [stringtie](https://github.com/galaxyproject/tools-iuc/tree/master/tools/stringtie)
-  [x] [sailfish](https://github.com/bgruening/galaxytools/tree/master/tools/sailfish) (on fastqfiles)
-  [ ] [dexseq](https://github.com/galaxyproject/tools-iuc/tree/master/tools/dexseq)
## Wrapper needed
-  [x] [salmon](https://github.com/COMBINE-lab/salmon)
-  [ ] [sleuth](https://github.com/pachterlab/sleuth) (also [see](https://github.com/pachterlab/sleuth/pull/27))
## Wrapper exists, discussion needed 
-  [x] featureCounts ?
-  [ ] [rnateam tools](https://hub.docker.com/r/bgruening/galaxy-rna-workbench/~/dockerfile/)

**Comment by yhoogstrate** [comment]
Hi @nekrut , I am happy to include thefeatureCounts wrapper (https://github.com/ErasmusMC-Bioinformatics/featurecounts_galaxy_wrapper) but it needs some changes to be compatible with both deseq2 and edger. Further development is pending on https://github.com/galaxyproject/galaxy/pull/961.

**Comment by nekrut** [comment]
@yhoogstrate Awesome. Can we help in any way?

**Comment by bwlang** [comment]
A former intern of mine started a [wrapper for salmon](https://testtoolshed.g2.bx.psu.edu/view/ericpeterson/salmon_tool_wrapper/32b33b0233a2) in case anyone cares to polish it further (it's out of date, and has a not quite working tool dependency)

**Comment by bgruening** [comment]
@bwlang I have a sailfish wrappers here: https://github.com/bgruening/galaxytools/tree/master/tools/sailfish
And would love to add a salmon wrapper. Still not clear if salmon is ready for prime-time or if sailfish is preferential.

**Comment by martenson** [comment]
transfered to https://github.com/galaxyproject/tools-iuc/projects/2
