### ISSUE TITLE
host visualization plugins

### ISSUE THREAD

**Issue by greenify** [galaxyproject/tools-iuc#4]
@bgruening had the great idea to host visualization plugins inside this repo (until the ToolShed supports thems).

-> would you be interested (a) in hosting visualization plugins in this repo or (b) do you want to create a separate repo (e.g. `vis-iuc`) or (c) do you have another idea?

Minimal list of contributors with visualization plugins:

* [@saketc](https://github.com/saketkc/galaxy_tools/tree/master/visualisation_plugins/)
* [@carlfeberhard](https://bitbucket.org/carlfeberhard/galaxy-visualization-dataset-choice/src/7dbaf921428a13586950104b98687920ebda3233?at=default)
* [@greenify](https://github.com/greenify/galaxy_vis_plugins)
[...]

For more infos [#71](https://github.com/biojs/biojs/issues/71).

**Comment by erasche** [comment]
@galaxyproject/iuc can this be closed? Viz plugins have been merged in so a decision seems to have been made regarding this. (On that note I deprecated my video viz plugin and added that to this repo)

**Comment by bgruening** [comment]
I think this can be closed. I'm in contact with @greenify and will work on more VIS from biojs.
