### ISSUE TITLE
MethylC-seq tools on Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#400]
MethylC-seq tools to release to main
- [ ] [bismark](https://github.com/bgruening/galaxytools/tree/master/tools/bismark)
- [ ] [PileOMeth](https://github.com/bgruening/galaxytools/tree/master/tools/pileometh)

**Comment by martenson** [comment]
remaining items moved to https://github.com/galaxyproject/tools-iuc/projects/2
