### ISSUE TITLE
All Join Tools are failing on simple datasets with some duplicated entries

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/tools-iuc#4003]
# Description of Error on Server

| Join Tool | Output Description | Tool Link |
|:---|:---|:---|
| *Join Two Datasets*  | Task fails with green output, 0 lines |  https://usegalaxy.eu/root?tool_id=join1 |
| *Join Two Files*  | Task fails with red output | https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/join_files_on_column_fuzzy/join_files_on_column_fuzzy/1.0.1 |
| *Join* | Task fails with green output, 0 lines | https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_easyjoin_tool/1.1.2 | 

Galaxy History:  https://usegalaxy.eu/u/mehmet-tekman/h/join-tools-not-working

Input Datasets:

* [file1_index4.txt](https://github.com/galaxyproject/tools-iuc/files/7271333/file1_index4.txt)
* [file2_index2.txt](https://github.com/galaxyproject/tools-iuc/files/7271334/file2_index2.txt)

File2 contains many duplicated entries, but this should not be a reason for the join operation to fail.

# Expected Result

Running with `coreutils==8.3.2` join tool from conda-forge:

    > ~/miniconda3/envs/join/bin/join -1 4 -2 2 file1_index4.txt file2_index2.txt | wc -l
    416

416 matches

# Solutions

I'm happy to wrap the `join` tool into galaxy based on the above conda environment, but I was wondering if somebody had already done this?

**Comment by bgruening** [comment]
@mtekman in one file you have a space at the end of the column. And one file is of filetype "interval" and not tabular. Can you fix that and try again?

**Comment by mtekman** [comment]
Great spot! I never would have seen that -- it looks like it was a leftover quirk from a previous awk reformatting I did

I tried again again with success (416 matches):

* (very quick!) https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_easyjoin_tool/1.1.2
* (very slow!) https://usegalaxy.eu/root?tool_id=join1

Thank you so much!
