### ISSUE TITLE
Guidelines for additional output parameters

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#4008]
In a recent (short) discussion (https://github.com/galaxyproject/tools-iuc/pull/4006#discussion_r721666177) we were wondering what's the best way to choose which outputs a tool should produce:

- multiple booleans 
- one select 

Wondering if we should try to standardize this in the IUC guidelines?

For me a select is favorable for the following reasons:

- its more compact (except for one output)
- one can contrain them, e.g. requiering at least one (`min="1"`) or requiring exactly one (`type="radio"`)

Here is how the two options look: 

![bool](https://user-images.githubusercontent.com/25689525/135995952-b7e25fa7-3d30-4f9c-a4dd-4f2c9a2d30da.png)
![select](https://user-images.githubusercontent.com/25689525/135995978-2308b735-ff06-40ce-ada4-1380a4c95d13.png)

Maybe add thumbs up/down reactions to the issue if you support/not support standardization... or add comments with arguments.

**Comment by bgruening** [comment]
You can move this to https://github.com/galaxy-iuc/standards/issues if you like.

**Comment by bgruening** [comment]
I prefer the multi-select.

**Comment by wm75** [comment]
One disadvantage of the select is that you cannot provide separate help/command line args for the options (as visible in the screenshots).

**Comment by wm75** [comment]
Also, restrictions on the select can only be enforced in the command section (after the user hits Execute). So it's not very clear what the allowed combinations are.

**Comment by wm75** [comment]
It's also easy to abuse the one select box like e.g. here:

![Screenshot from 2021-10-05 12-19-51](https://user-images.githubusercontent.com/4742081/136005354-d7082096-4fe8-4259-b2e1-8f1ed607edff.png)

Clearly the VCF or BCF output is the main output of Delly, while the other two are optional outputs. The single select box doesn't convey that at all.

**Comment by bernt-matthias** [comment]
Closing this here https://github.com/galaxy-iuc/standards/issues/66 .. Also copied the comments
