### ISSUE TITLE
Metagenomics tools for Main

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#401]
Metagenomics tools to be released

* [PEAR](https://github.com/galaxyproject/tools-iuc/tree/master/tools/pear)
  * [x] Test
  * [x] Main
* [cd-hit-dup](https://github.com/galaxyproject/tools-devteam/tree/master/tools/cd_hit_dup)
  * [x] Test
  * [x] Main
* Kraken2? (not released yet)
  * [ ] Test
  * [ ] Main
* [Vegan collection](https://github.com/galaxyproject/tools-iuc/tree/master/tools/vegan)
  * [x] Test
  * [x] Main
* [Vsearch](https://github.com/galaxyproject/tools-iuc/tree/master/tools/vsearch)
  * [x] Test
  * [x] Main
* [diamond](https://github.com/bgruening/galaxytools/tree/master/tools/diamond) + diamond DM
  * [x] Test
  * [x] Main

**Comment by martenson** [comment]
I rewrote the issue to allow tracking of deployment to Test/Main. It would also be nice to provide link directly to the toolshed page so I know what to install. Sometimes it is not clear.

**Comment by bgruening** [comment]
Thanks Martin: 
* https://toolshed.g2.bx.psu.edu/view/iuc/vsearch/8c4e2933a17a
* https://toolshed.g2.bx.psu.edu/view/bgruening/diamond/98037ef3d2a9
* https://toolshed.g2.bx.psu.edu/view/bgruening/data_manager_diamond_database_builder/ce62d0912b10

**Comment by martenson** [comment]
@bgruening not needed, the github links are enough, my bad, but thanks! :)

**Comment by bgruening** [comment]
Should we create PR against the ansible playrole?

**Comment by martenson** [comment]
All available tools installed on Test and ready for testing. 
@bgruening what do you mean by that?

**Comment by bgruening** [comment]
To get them on main. I remember that we can add them to a tools.yaml file to get them on main. Just wonder how I can help here.

**Comment by martenson** [comment]
Main is not maintained that way yet. Would love to do it like that though (https://github.com/galaxyproject/galaxy/issues/1115)

**Comment by jennaj** [comment]
@martenson OK, testing to start. I may need test data for some if I can't figure it out. 

@nekrut If you want to share some data with me that would be great.

For both - could we add testing to the checklist? For test & main? Or will that complicated it too much?

And what about testing install/function in the default galaxy master (local) and cloudman? Or is that too much? 

Are any parts of this useful here? some could apply to any tool (new, updated, bugged or not) https://github.com/galaxyproject/galaxy/issues/1056

**Comment by martenson** [comment]
everything done, except of kraken2 which is not released yet, it remains listed here: https://github.com/galaxyproject/tools-iuc/issues/361

**Comment by jennaj** [comment]
I will retest on Test and give feedback (Megablast) so we can update then test on Main.

**Comment by martenson** [comment]
@jennaj I am not sure what are you responding to here, is it the ping for testing from `Nov 18, 2015` ?

**Comment by jennaj** [comment]
@martenson After reviewing other tickets (including the one specifically for this tool, which Nate has now addressed), my comments in this ticket can be tossed out. I agree that keeping the items distinct (new vs existing tools) is best. Tx!
