### ISSUE TITLE
ChIP-exo tools for main

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/tools-iuc#404]
The following tools are a subset of those that define the Galaxy ChIP-exo flavor and are needed for the ChIP-exo workflow soon to be available on Galaxy main.  To clarify, the ChIP-exo workflow is complete, and it will be made available on Galaxy main as soon as these tool versions have been installed into that environment.
- [x] Bam_to_Scidx - must be version 1.0.0
- [x] Genetrack - must be version 1.0.0
- [x] Cwpair2 - must be version 1.0.0
- [x] Repmatch_gff3 - must be version 1.0.0
- [x] meme - must be version 4.11.0.1
- [x] fimo - must be version 4.11.0.4 (version 4.11.0.3 currently on main): https://toolshed.g2.bx.psu.edu/view/iuc/meme_fimo/b3f7ff168b9a
- [x] Resize coordinate window - must be version 1.0.1
- [ ] Extract genomic DNA - must be version 3.0.2: https://toolshed.g2.bx.psu.edu/view/iuc/extract_genomic_dna/702970e4a134
- [x] fasta_nucleotide_color_plot - must be version 1.0.0: https://toolshed.g2.bx.psu.edu/view/iuc/fasta_nucleotide_color_plot/260f7da5a7e5
- [x] pe_histogram - must be version 1.0.0: https://toolshed.g2.bx.psu.edu/view/iuc/pe_histogram/2f6c7f82ad4a
- [x] tag_pileup_frequency - must be version 1.0.0: https://toolshed.g2.bx.psu.edu/view/iuc/tag_pileup_frequency/fa82c3c9ced3
- [ ] repeat_masker - must be version 0.1.2: https://toolshed.g2.bx.psu.edu/view/bgruening/repeat_masker/5673e72241aa - @martenson due to licensing restrictions, it is unlikely that you will be able to install RepeatMasker (http://www.repeatmasker.org/RMDownload.html) on Galaxy main.  This tool improves the ChIP-exo analysis by eliminating repeats,  but if you cannot install it on main, it is ok.  I have a version of the ChIP-exo workflow that does not use this tool, so we can upload that version on main if needed.
- [x] multigps - version 0.73.0: https://toolshed.g2.bx.psu.edu/view/iuc/multigps/4aa531981208 (this PR https://github.com/galaxyproject/tools-iuc/pull/1206 is now available on the MTS)

**Comment by gregvonkuster** [comment]
@martenson @natefoo When it is convenient, can we get this tool installed on main: https://toolshed.g2.bx.psu.edu/view/iuc/resize_coordinate_window/0164d2edba9f
This will allow us to check off the "Resize Coordinate Window" tool in the above list.  This is not urgent.
Thanks!  ;)

**Comment by martenson** [comment]
@gregvonkuster done

**Comment by martenson** [comment]
are the two last tools ready?

**Comment by gregvonkuster** [comment]
Hi @martenson 

I have the MultiGPS tool finished, but I think the ChIP-exo PIs want the underlying package updated before it goes to open source.  So it is on the back-burner for now.

I'm not quite sure how the dev team wants to handle the modern version of the Extract Genomic DNA tool since the old version is still installed on main.  I have a very useful enhancement for the modern version that I will be submitting this evening or tomorrow morning to the tool-iic repo, so if we can hold off on updating main until we have that enhancement it would be great.

I will be adding 6 or 7 additional tools that I will be submitting to tools-iuc in the next few days, and I'll add checkboxes for them.

Thanks!

**Comment by martenson** [comment]
@gregvonkuster thanks for the update, I will keep my eyes peeled

**Comment by martenson** [comment]
meme_fimo updated on Main

**Comment by gregvonkuster** [comment]
Thanks @martenson !  FYI - the fix for bam_to_scidx is available in the MTS.  This is the fix for linking bam and bai files.  This may correct the issues on main with this tool, but I'm not sure...

**Comment by martenson** [comment]
That has been installed as well.

**Comment by gregvonkuster** [comment]
Thanks a bunch @martenson You're the best!  ;)

**Comment by martenson** [comment]
* fimo updated
* fasta_nucleotide_color_plot installed
* pe_histogram installed
* tag_pileup_frequency installed

* Extract genomic DNA is waiting on migration
* repeatmasker is not packaged (http://www.repeatmasker.org/RMDownload.html)

**Comment by martenson** [comment]
latest multigps installed too

**Comment by bgruening** [comment]
@gregvonkuster still relevant?

**Comment by bernt-matthias** [comment]
Will close this now. Seems that everything was done.
