### ISSUE TITLE
package_cairo_1_12_14 lacks pkg-config ?

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/tools-iuc#407]
https://github.com/galaxyproject/tools-iuc/blob/bd2c6cb3dc48e0e7b1a768d51f5a192c00e9bf41/packages/package_cairo_1_12_14/tool_dependencies.xml#L12

I think that package_cairo_1_12_14 does not install well on a super clean Galaxy instance because of a lack of the pkg pkg-config in Galaxy default environment. A number of tools depending on cairo fail to install in the same way.

Sorry if the issue has already been raised

cairo	1.12.14	package	Error	/bin/sh: 13:  : not found
configure: error: pkg-config >=  required but not found (http://pkgconfig.freedesktop.org/)

**Comment by bgruening** [comment]
@drosofff actually pkg-config is a required dependency if you install tools from the TS

**Comment by mvdbeek** [comment]
@bgruening alright, so I guess that https://github.com/galaxyproject/ansible-galaxy-os/blob/master/tasks/packages.yml is missing pkg-config. I'll report it over there,
