### ISSUE TITLE
SPAdes crashes, complains about output dir not being empty

### ISSUE THREAD

**Issue by yzhernand** [galaxyproject/tools-iuc#4074]
Hi all,

I've been having trouble with running SPAdes 3.12.0 on Galaxy 20.01, though previous versions of SPAdes also gave me the same issue. SPAdes crashes and complains about the output directory not being empty, then throws an error that the file is not found.

Here is the output on stdout:

```
== Warning ==  output dir is not empty! Please, clean output directory before run.




== Warning ==  No assembly mode was specified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.




== Error ==  file not found: /data01/galaxy/galaxy/database/jobs_directory/019/19519/working/fastq.gz:/data01/galaxy/galaxy/database/files/000/799/dataset_799972.dat (left reads, library number: 1, library type: paired-end)
```

and here is the command line according to the details page:

```
if [ -n "$GALAXY_MEMORY_MB" ]; then GALAXY_MEMORY_GB=$(( GALAXY_MEMORY_MB / 1024 )); fi &&  spades.py -o . --tmp-dir "${TMPDIR:-.}" --disable-gzip-output   --careful -t ${GALAXY_SLOTS:-16} -m ${GALAXY_MEMORY_GB:-250}  --pe1-fr --pe1-1 fastq.gz:fastq.gz:/data01/galaxy/galaxy/database/files/000/799/dataset_799972.dat --pe1-2 fastq.gz:fastq.gz:/data01/galaxy/galaxy/database/files/000/799/dataset_799973.dat --trusted-contigs fasta:/data01/galaxy/galaxy/database/files/000/799/dataset_799975.dat && python '/data01/galaxy/galaxy/database/jobs_directory/019/19519/configs/tmpoml3sf_h' < contigs.fasta > '/data01/galaxy/galaxy/database/files/000/800/dataset_800019.dat' && python '/data01/galaxy/galaxy/database/jobs_directory/019/19519/configs/tmpoml3sf_h' < scaffolds.fasta > '/data01/galaxy/galaxy/database/files/000/800/dataset_800020.dat'
```

This is on a self-hosted instance of Galaxy. The reads are passed first to seqtk trimfq then to SPAdes. They are saved as a paired list in the history.

**Comment by bernt-matthias** [comment]
Can you reproduce this on a public instance and share the history?

**Comment by yzhernand** [comment]
Hi, I was NOT able to reproduce this on a public instance. Do you still want me to share the history?

I'm not sure what the difference is in the instances in this case. I can see that the tool ID matches, but the public instance's command line invocation on SPAdes is pretty different (see below). It isn't duplicating the leading "fastq.gz:" and isn't running the "&&"d python command after the spades command.

```
/cvmfs/main.galaxyproject.org/deps/_conda/envs/__spades@3.12.0/bin/spades.py	-o	/corral4/main/jobs/038/359/38359693/working	--disable-gzip-output	--careful	-t	6	-m	30	-k	21,33,55	--pe1-fr	--pe1-1	fastq.gz:/corral4/main/objects/e/8/f/dataset_e8ff59ac-f5a0-43fb-a5c2-834af263af4a.dat	--pe1-2	fastq.gz:/corral4/main/objects/8/5/f/dataset_85fdb493-fc2e-4ef0-8707-355f98cf9108.dat
```

Any idea how I could debug this on my end? I'm not very experienced with administering Galaxy and the person who first installed this instance is no longer here.
