### ISSUE TITLE
Missing .shed.yml file in some repositories.

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-iuc#408]
- [x] `data_managers/data_manager_bowtie_index_builder/`
- [x] `data_managers/data_manager_gemini_database_downloader/`
- [x] `data_managers/data_manager_sailfish_index_builder/`
- [x] `data_managers/data_manager_snpeff/`
- [x] `data_managers/data_manager_star_index_builder/`
- [ ] All in `datatypes/`
- [x] `tools/blastxml_to_gapped_gff3/`
- [x] `tools/gff3_rebase/`

The suspects can be found with:

```
find . -maxdepth 2 -type 'd' '!' -exec test -e "{}/.shed.yml" ';' -print|sort
```

I guess @martenson can help with the script he used for `tools-devteam`.

**Comment by martenson** [comment]
I modified a bit the original code from @erasche 
https://gist.github.com/martenson/bbf2f7612dae4fb0f17b
