### ISSUE TITLE
BioJS-MSA doesn't use galaxy prefix

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#41]
If galaxy is running with a prefix like `/galaxy/`, BioJS-MSA is not aware of this.

**Comment by saketkc** [comment]
cc @greenify

**Comment by greenify** [comment]
[Last time](https://github.com/galaxyproject/tools-iuc/pull/5#issuecomment-59204695) I asked whether there is a variable or configuration from which the MSA can get the browser path to itself.

I would be happy to change that if Galaxy can give the visualization plugins the absolute url to the them...

**Comment by erasche** [comment]
Yes, it can. We've done this with our IPython Viz plugin though I'll have to dig into the code to figure out how we did it. I was seconds away from submitting this issue on [biojs2galaxy](https://github.com/biojs/biojs2galaxy/).

**Comment by erasche** [comment]
You've already done it in a couple places, you're just missing some of the others. In [galaxy.mako](https://github.com/biojs/biojs2galaxy/blob/master/template/galaxy.mako), you have `root` which will correctly determine the correct root, you just need to use that for `url` and `jsonURL` on L43-44

**Comment by greenify** [comment]
Oh sry, I was replying too fast - I was referring to the plugin path which is hard-coded to `plugins/visualizations` in biojs2galaxy. 

thanks to @erasche I [updated biojs2galaxy](https://github.com/biojs/biojs2galaxy/commit/c3560ceb529cc69abf625ee471f6af612eb4b327) with the correct root url :)

**Comment by erasche** [comment]
Oh, yeah, it would be nice if there was a method that'd get the full URL for a viz plugin. Anyway, great, thanks so much for getting this fixed in upstream!
