### ISSUE TITLE
tool request for TETranscripts

### ISSUE THREAD

**Issue by abasel13** [galaxyproject/tools-iuc#4143]
I would like to have access to the tool TETranscript on my UseGalaxy account

**Comment by bernt-matthias** [comment]
Should be available https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/tetoolkit_tetranscripts/tetoolkit_tetranscripts/2.2.1+galaxy0

**Comment by bernt-matthias** [comment]
Please reopen if this did not solve it
