### ISSUE TITLE
 tetoolkit_tetranscripts

### ISSUE THREAD

**Issue by sanatbhadsavle** [galaxyproject/tools-iuc#4144]

**Comment by bernt-matthias** [comment]
duplicate of https://github.com/galaxyproject/tools-iuc/issues/4143 ?

**Comment by bernt-matthias** [comment]
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/tetoolkit_tetranscripts/tetoolkit_tetranscripts/2.2.1+galaxy0
