### ISSUE TITLE
Bug on package_r_3_0_3

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#416]
The LD_LIBRARY_PATH does not include
$INSTALL_DIR/lib
If you inspect this, there are quite a few libs there. And they are needed (at least on a modern linux).

For example this makes the clustered heatmap (visualization) to fail with a missing of libgfortran.so.1

**Comment by mvdbeek** [comment]
@tiagoantao could you post the error message?
I'd like to confirm that LD_LIBRARY_PATH is the only issue (see issue #325, for which we pushed out a fix only for R 3.2.1 ... this might need backporting to older R versions).

**Comment by tiagoantao** [comment]
@mvdbeek:
/data/homes/galaxy/galaxy/dependencies/R/3.0.3/iuc/package_r_3_0_3/a8438aa1207c/lib/R/bin/exec/R: error while loading shared libraries: libgfortran.so.1: cannot open shared object file: No such file or directory

This is solved by changing env.sh and adding
/data/homes/galaxy/galaxy/dependencies/R/3.0.3/iuc/package_r_3_0_3/a8438aa1207c/lib/R/lib
to LD_LIBRARY_PATH

**Comment by mvdbeek** [comment]
@tiagoantao From the directory in your installation path I see that you are on changeset revision [a8438aa1207c](https://iuc@toolshed.g2.bx.psu.edu/repos/iuc/package_r_3_0_3/rev/a8438aa1207c),
so you're supposed to have LD_LIBRARY_PATH pointing to `$INSTALL_DIR/lib/R/lib`.
Any chance a simple update/reinstallation suffices ?
Installing charts from the toolshed into a clean instance works, and I can produce a clustered heatmap with the test data.

**Comment by tiagoantao** [comment]
I have upgraded everything and now works like a charm. Sorry for this...

**Comment by mvdbeek** [comment]
No worries, glad it works now.
