### ISSUE TITLE
package_python_2_7_matplotlib_1_4 can fail due to package_freetype_2_5_2 setting environment variables

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/tools-iuc#417]
I've recently run into problems getting package_python_2_7_matplotlib_1_4 to install on Galaxy within Docker (yes, this is the instance from @bgruening). The reason seems to be that matplotlib's setupext.py script needs `pkg-config --cflags freetype2` to return something, but `package_freetype_2_5_2` sets `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH`. If one runs  `pkg-config --cflags --debug freetype2` then one can see that the appropriate Cflags: line is then excluded, since pkg-config will only output what's *required*. Reverting the environment changes from done by `package_freetype_2_5_2` seems to fix that, though a likely better solution would be to modify the tool_dependencies.xml file from matplotlib to just have it exclude paths from the aforementioned environment variables.

**Comment by bgruening** [comment]
This seem to be a real problem on the matplotlib site. Since we can not remove an environment variable I see no other solution to remove it from the freetype package. Or create a new on without these exports and use this one solely for matplotlib.

@erasche any ideas here?

**Comment by erasche** [comment]
Will check out in a bit @bgruening. Sorry!
26. nov. 2015 10.30 a.m. skrev "Björn Grüning" <notifications@github.com>:

**Comment by erasche** [comment]
@bgruening okay, read over it now. yikes. 

No, I really don't have any ideas. I don't like the idea of a special package just for matplotlib, since there's definitely an underlying issue if pkg-config won't work nicely. Maybe someone has time to dig into why pkg-config doesn't play nicely with sC*_INCLUDE PATH`s

**Comment by bgruening** [comment]
@erasche this seems to be a matplotlib error as say do not use the correct variables. Not sure why :(

**Comment by dpryan79** [comment]
@erasche: pkg-config is doing the correct thing. Compilers like gcc/clang/etc. look through directories specified by `-I` options first, followed by those set in `C*_INCLUDE_PATH` and finally the default system directories (e.g., `/usr/include`) when looking for headers. Since disks aren't always fast and many programs will require compiling a large number of files, it's best if the compiler doesn't need to look through the same directory twice. My understanding is that that's why `pkg-config` is behaving in this manner.

Since this is completely the fault of matplotlib, I'll post a bug report there. That won't resolve the immediate problem but will at least prevent this in the future :)

**Comment by dpryan79** [comment]
Looks like this will get fixed in matplotlib 1.5.1 due to https://github.com/matplotlib/matplotlib/pull/5578.

**Comment by dpryan79** [comment]
This is fixed now, I'll close it.
