### ISSUE TITLE
pretext map: typo

### ISSUE THREAD

**Issue by mthang** [galaxyproject/tools-iuc#4171]
I think there is a typo in this wrapper . Under the sortorder option, it should be descend instead of decend 
https://github.com/galaxyproject/tools-iuc/blob/b9ec351920dbc83fa14bd1f8cfdd0a6a19b89473/tools/pretext/pretext_map.xml#L48

**Comment by bgruening** [comment]
@mthang if you want to check: https://github.com/galaxyproject/tools-iuc/pull/4190
