### ISSUE TITLE
IUC Contribution Fest - Metagenomics and mothur

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#419]
I will start this issue to list all idea specifically for all people that are interested in working on mothur during our Metagenomic Hackathon (https://github.com/galaxyproject/tools-iuc/issues/299).

I have created an initial branch with wrappers from [@IyadKandalaft and team](https://github.com/AAFC-MBB/Galaxy): https://github.com/galaxyproject/tools-iuc/tree/mothur

My idea is to use this issue to collect ideas specific to the mothur wrapper, coordinate efforts and create PR against this branch.
- [ ] improve datatypes and move them into Galaxy core
- [ ] evaluate tools from @yvanlebras http://toolshed.genouest.org/repository/view_repository?sort=name&operation=view_or_manage_repository&f-free-text-search=mothur&id=66701dbe65507c8c
- [ ] evaluate the usage of a data manager: https://github.com/fls-bioinformatics-core/galaxy-tools/tree/master/data_manager_mothur_toolsuite
- [ ] fix planemo lint issues
- [ ] Add test cases (Oksana)
- [ ] fix dataset collection integration
- [ ] improve usability as much as we can :)
- [ ] prepare some workflows to ship with the ToolShed and to demonstrate our achievements 

Thanks everyone! This will be awesome!

**Comment by oxyko** [comment]
We have existing issue reported for this wrapper, so I'm pasting it here for everyone to be aware:

Problem with 2 of the Chimera tools (both in galaxy tool version 1.22 and 1.23) Chimera.slayer and Chimera.uchime.

In spite of the fact that in the drop down menu for the tool it states that a groups file is optional and a count file is optional instead of leaving these parameters out of the mothur command it uses "groups=None" and then the tool fails due to not being able to open file "None" 

```
mothur > chimera.uchime(fasta=dataset_37011.dat,group=None,count=None,reference=self,abskew=1.9,minh=0.3,mindiv=0.5,xn=8.0,dn=1.4,xa=1.0,chunks=4,minchunk=64,idsmoothwindow=32,maxp=2,processors=8)
Unable to open None. Trying output directory None
Unable to open None. It will be disregarded.
Unable to open None. Trying output directory None
Unable to open None. It will be disregarded.
[ERROR]: no valid group files.
[ERROR]: The number of groupfiles does not match the number of fastafiles, please correct.

Using 8 processors.
[ERROR]: did not complete chimera.uchime.
```
```
mothur > chimera.slayer(fasta=dataset_37011.dat,reference=self,group=None,count=None,processors=8)
Unable to open None. Trying output directory None
Unable to open None. It will be disregarded.
Unable to open None. Trying output directory None
Unable to open None. It will be disregarded.
[ERROR]: no valid group files.
[ERROR]: The number of groupfiles does not match the number of fastafiles, please correct.

Using 8 processors.
[ERROR]: did not complete chimera.slayer.
```

![screen shot 2015-06-10 at 1 09 31 pm](https://cloud.githubusercontent.com/assets/2932487/11442414/191afff4-94e3-11e5-8eca-5ca9a2407a77.png)
![screen shot 2015-06-10 at 1 11 34 pm](https://cloud.githubusercontent.com/assets/2932487/11442415/1cd2b736-94e3-11e5-8d32-dace76840cac.png)

**Comment by jmchilton** [comment]
I think the mothur datatypes should be modified so the short extension includes a prefix ``mothur.`` like ``mothur.otu``.

**Comment by oxyko** [comment]
Will be installing and figuring out planemo and then working on the chimera tools issue and tests for them.

**Comment by jj-umn** [comment]
@jmchilton Agree on prefixing datatypes.   Also, should see if any of these could just be subclassed, rather than python class.  I guess that would depend on whether there is any useful metadata for the datatype.

**Comment by IyadKandalaft** [comment]
I'm looking at patching to support v1.36.1 of mothur

**Comment by bgruening** [comment]
Anyone up for a discussion round about mothur and the current state?
I have made an initial review of https://github.com/galaxyproject/tools-iuc/pull/429 and we can talk about it if you like.

**Comment by oxyko** [comment]
I've refactored all wrappers to use macros, as discussed earlier today. Currently macros takes care of <requirements>, <citations> and some common text from <help>. Wanted to extract the wrapper version as well, but the versions are all over the place: from 1.20.0 to 1.27.0. So not sure if it is better to use one version for all the wrappers, and if yes, then which one. Any thoughts?

**Comment by bgruening** [comment]
@oxyko this is a great work!

**Comment by shiltemann** [comment]
@oxyko awesome! :) 

Also, since all files pretty consistently use 1-space indentation, I could do something like sed -i 's/^\(\ *\)/\1\1\1\1/g ' to all xml files to quadruple all leading spaces? ..or shall we we not worry about this for now?

**Comment by bgruening** [comment]
@shiltemann I think this is a good idea. I would wait before we have merged @oxyko PR to prevent more merge conflicts. But yes this is the way to go.

**Comment by bgruening** [comment]
@oxyko I think we should aim to target the latest release, right. So fix the latest release available in the requirement tag :)

**Comment by bgruening** [comment]
@shiltemann did a huge cleanup PR in https://github.com/galaxyproject/tools-iuc/pull/447
Please rebase your work to the latest changes. Thanks!
@oxyko you also need to rebase

**Comment by blankenberg** [comment]
Just a drive-by to +1 making Mothur paired dataset collection aware, especially for e.g. `Make.contigs` (and possibly others).

**Comment by shiltemann** [comment]
@blankenberg thanks, see #853

**Comment by martenson** [comment]
Closing this issue since this codefest is long finished.
