### ISSUE TITLE
propose Cristóbal Gallardo as a new IUC member

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#4208]
I would like to propose Cristóbal Gallardo (@gallardoalba) as a new IUC member.

He is working on Galaxy tools for over a year now. He has 67 PRs on IUC already and the quality of his tools is great.
https://github.com/galaxyproject/tools-iuc/pulls/gallardoalba

Cristo is working with the European Galaxy team and is part of the global Galaxy Support team, part of the GOATS working group.

Please vote!

**Comment by bgruening** [comment]
Welcome @gallardoalba to the IUC!

It's great to have you on board! :balloon: 🎉

**Comment by nsoranzo** [comment]
Congratulations @gallardoalba 

@bgruening Should we move the list of IUC members from https://galaxyproject.org/iuc/ to this repo? So future votings can be a PR.

**Comment by bgruening** [comment]
Good idea, but something that should the Hub people decide. We should avoid having two lists to maintain, or not?

**Comment by nsoranzo** [comment]
Absolutely, that's why I said "move" :)

Not sure the decision is up to the Hub, aren't we a self-governing group of people?

**Comment by bgruening** [comment]
I think we are, but the IUC should also be present in the Hub? No idea to be honest. Please do it and we will find a solution with the hub as well.

**Comment by gallardoalba** [comment]
Thank you so much!

**Comment by NickSto** [comment]
We at the Hub have a plan to have a directory of people and their various memberships, including automatically gathering the data from the original sources. But that's a little ways off at the moment, so definitely proceed as usual here and we'll manually update for now.
