### ISSUE TITLE
Error run-in g latest version of freebayes

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/tools-iuc#4270]
I'm running Galaxy 21.09, and executing this version of freebayes: 
```
toolshed.g2.bx.psu.edu/repos/devteam/freebayes/freebayes/1.3.5+galaxy0
```
produces this error:
```
tool error
An error occurred with this dataset:
cannot find 'standard_filters'
```
This may be related to this recent change - https://github.com/galaxyproject/tools-iuc/pull/4250

Is this a bug, or have I missed something during the tool install?

**Comment by bernt-matthias** [comment]
@gregvonkuster can you have a look: https://github.com/galaxyproject/tools-iuc/pull/4271
