### ISSUE TITLE
Cannot properly install data_manager_diamond_database_builder version 0.0.3 from the TS

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/tools-iuc#4277]
The latest version of this tool in the TS https://toolshed.g2.bx.psu.edu/view/bgruening/data_manager_diamond_database_builder/5558f74bd296 displays this on the View Repository page:

```
Invalid tools - click the tool config file name to see why the tool is invalid
--
data_manager_diamond_database_builder.xml

Invalid Data Managers
--
1 | Unable to determine tools metadata
```
Attempting to install the tool with ephemeris will install version 0.0.1 of the tool instead of version 0.0.3, and version 0.0.1 uses Python 2.

**Comment by bernt-matthias** [comment]
Closed via https://github.com/galaxyproject/tools-iuc/pull/4279
