### ISSUE TITLE
ustacks Conda dependency failed to build a job environment

### ISSUE THREAD

**Issue by angellcarrasquillo** [galaxyproject/tools-iuc#4303]
I tried to input an SRA dataset downloaded with fasterq into ustacks and was given this error "Conda dependency seemingly installed but failed to build job environment.". I am on a windows 10 desktop running Galaxy on an ubuntu subsystem. I had tested a subset of this data on another computer with similar specs, and did not have this problem. I am using my desktop however for increased storage space. I followed all the instructions for installing galaxy and tools.

**Comment by bernt-matthias** [comment]
Guess the conda installation failed. Can you check the env dir? Do the logs tell anything?

**Comment by angellcarrasquillo** [comment]
Yes, I think this is where the tool failed:

Collecting package metadata: ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from
current channels:

  - setuptools==60.1.0=pypi_0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


galaxy.tool_util.deps.conda_util DEBUG 2021-12-29 09:22:48,786
[pN:main.web.1,p:125,w:1,m:0,tN:LocalRunner.work_thread-2] Executing
command: /home/alc/galaxy/database/dependencies/_conda/bin/conda clean
--tarballs -y
Cache location:
There are no tarballs to remove
galaxy.jobs.runners ERROR 2021-12-29 09:22:48,974
[pN:main.web.1,p:125,w:1,m:0,tN:LocalRunner.work_thread-2] (19) Failure
preparing job
Traceback (most recent call last):
  File "/home/alc/galaxy/lib/galaxy/jobs/runners/__init__.py", line 249, in
prepare_job
    job_wrapper.runner_command_line = self.build_command_line(
  File "/home/alc/galaxy/lib/galaxy/jobs/runners/__init__.py", line 288, in
build_command_line
    return build_command(
  File "/home/alc/galaxy/lib/galaxy/jobs/command_factory.py", line 70, in
build_command
    __handle_dependency_resolution(commands_builder, job_wrapper,
remote_command_params)
  File "/home/alc/galaxy/lib/galaxy/jobs/command_factory.py", line 194, in
__handle_dependency_resolution
    if local_dependency_resolution and
job_wrapper.dependency_shell_commands:
  File "/home/alc/galaxy/lib/galaxy/jobs/__init__.py", line 1046, in
dependency_shell_commands
    self._dependency_shell_commands =
self.tool.build_dependency_shell_commands(
  File "/home/alc/galaxy/lib/galaxy/tools/__init__.py", line 1976, in
build_dependency_shell_commands
    return self.app.toolbox.dependency_manager.dependency_shell_commands(
  File "/home/alc/galaxy/lib/galaxy/tool_util/deps/__init__.py", line 186,
in dependency_shell_commands
    return [dependency.shell_commands() for dependency in
ordered_dependencies if not isinstance(dependency, ContainerDependency)]
  File "/home/alc/galaxy/lib/galaxy/tool_util/deps/__init__.py", line 186,
in <listcomp>
    return [dependency.shell_commands() for dependency in
ordered_dependencies if not isinstance(dependency, ContainerDependency)]
  File "/home/alc/galaxy/lib/galaxy/tool_util/deps/resolvers/conda.py",
line 475, in shell_commands
    self.build_environment()
  File "/home/alc/galaxy/lib/galaxy/tool_util/deps/resolvers/conda.py",
line 470, in build_environment
    raise DependencyException("Conda dependency seemingly installed but
failed to build job environment.")
galaxy.tool_util.deps.resolvers.DependencyException: Conda dependency
seemingly installed but failed to build job environment.

**Comment by bernt-matthias** [comment]
Are you using stacks 1.x? If so, can you switch to stacks2?

**Comment by bernt-matthias** [comment]
Local test shows me that the conda envs for stacks1 and stack2 should be resolvable. 

Maybe you can try to remove the conda env (you can find the path in the dependency tab of Galaxy's admin UI) and install it from the admin UI. If possible try to monitor the conda run with `ps aux | grep conda` in order to get the complete conda command line that is used for installation.

**Comment by angellcarrasquillo** [comment]
I am using stacks2 and installed a bunch of dependencies from the admin UI
and was able to start ustacks. The job is still running and I will update
you if the process fails for any reason.

**Comment by bernt-matthias** [comment]
Cool. Just reopen if needed.
