### ISSUE TITLE
IUC Contribution Fest - Vegan, Vsearch, BIOM, Finch

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#432]
We'll try to work out the following pipeline

- load very large number of datasets (figure out upload problems @martenson )
- run Kraken (explore Kraken2 @nekrut ) https://github.com/galaxyproject/tools-devteam/pull/297
- test diamond (@nekrut)
- reduce Kraken datasets to a single tab-delimited file (@blankenberg)
- run Vegan
- run VSearch
- write a converter for Galaxy Taxonomy to BIOM 1.0 (@davebx)
- explore Finch for viz (@davebx)
- explore standalone options for Unifrac beta diversity (http://pycogent.org/ --> http://pycogent.org/cookbook/community_analysis.html#unifrac is used by QIIME/ defunct? FastUnifrac) (@blankenberg)

**Comment by bgruening** [comment]
Awesome! @bebatut are you working currently on Diamond?

**Comment by bebatut** [comment]
@bgruening I'm tested the PR #428

**Comment by bgruening** [comment]
@bebatut please comment on it. If you think it's good or bad :) Thanks!

**Comment by blankenberg** [comment]
* reduce Kraken datasets to a single tab-delimited file (@blankenberg)
  - Collections join on tabular columns: https://github.com/galaxyproject/tools-iuc/pull/434
  - Cut tool to accept stepsize in ranges: https://github.com/galaxyproject/galaxy/pull/1190

**Comment by blankenberg** [comment]
Fix for PEAR: https://github.com/galaxyproject/tools-iuc/pull/438

**Comment by nekrut** [comment]
Added tests for Kraken https://github.com/galaxyproject/tools-devteam/pull/297

**Comment by jxtx** [comment]
For converting to BIOM, would it make sense to go directly from Kraken output? It looks like this would be a relatively simple modification to kraken-report. A --biom option has been requested multiple times on their mailing list so this would be a valuable upstream contribution rather than just good for Galaxy. Would require somebody to hack some Perl however.

**Comment by nekrut** [comment]
@jxtx: yep, this is what @davebx is currently working on

**Comment by nekrut** [comment]
It appears diamond will have to wait: it cannot format standard `nr` database from ncbi https://github.com/bbuchfink/diamond/issues/25

**Comment by bgruening** [comment]
@nekrut Looking in my old histories I think the old version of diamond and the data manager was working for me on NR.
I hope he can fix it.

**Comment by nekrut** [comment]
looks like it cannot tolerate dashes. They should not be happening in nr,
but who knows. Editing nr is really out of question I think.

On Wed, Dec 2, 2015 at 12:14 PM, Björn Grüning <notifications@github.com>
wrote:

> @nekrut <https://github.com/nekrut> Looking in my old histories I think
> the old version of diamond and the data manager was working for me on NR.
> I hope he can fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/issues/432#issuecomment-161368653>
> .
>



-- 
Anton Nekrutenko
Professor of Biochemistry
and Molecular Biology
*http://nekrut.bx.psu.edu <http://nekrut.bx.psu.edu>*
(814) 826-3051

**Comment by nekrut** [comment]
Also, it appears that Diamond is virtually dead - there is no active development there

**Comment by bgruening** [comment]
@nekrut still interested in Diamond?

**Comment by peterjc** [comment]
Diamond lives! :)

v0.7.10 was just released - see GitHub https://github.com/bbuchfink/diamond/ - including a fix for the strange minus signs in protein sequences (treats them as X).

**Comment by bgruening** [comment]
@peterjc https://github.com/galaxyproject/tools-iuc/pull/465 :)

**Comment by nekrut** [comment]
cool. I'll finish it

**Comment by bgruening** [comment]
@nekrut I have updated VSearch and put it under automatic [travis testing](https://github.com/galaxyproject/tools-iuc/pull/590). Phinch in also now part of Galaxy-dev (thanks to @shiltemann). 
Moreover, I added Vegan and Phinch to the [metagenomic-flavour](https://github.com/bgruening/galaxy-metagenomics).

Please feel free to check those off and let us know where we can help.
