### ISSUE TITLE
Range of allowed values for max-depth parameter of bcftools mpileup

### ISSUE THREAD

**Issue by profgiuseppe** [galaxyproject/tools-iuc#4322]
Greetings, one user asked why the max-depth parameter of the bcftools mpileup tool has a [maximum allowed value of 1024](https://github.com/galaxyproject/tools-iuc/blob/master/tools/bcftools/bcftools_mpileup.xml#L226), given that the corresponding command line argument has no such boundary., according to the tool [man page](https://samtools.github.io/bcftools/bcftools.html)
Is there a galaxy-related reason for the choice of boundary? I would rather avoid having a custom xml for one tool the local installation of galaxy.
Thanks!

**Comment by nsoranzo** [comment]
@profgiuseppe I don't think there is a Galaxy-specific reason, a PR removing the `max` value from the parameter looks the best way forward.

**Comment by bernt-matthias** [comment]
Solved by https://github.com/galaxyproject/tools-iuc/pull/4326
