### ISSUE TITLE
Synthax error 

### ISSUE THREAD

**Issue by ksTL20** [galaxyproject/tools-iuc#4333]
Hi, 

I have tried running the table_compute script with the test data examples.1.tsv using the below script:

cp examples.1.tsv. ./userconfig.py && cp scripts/safety.py ./safety.py && cp scripts/table_compute.py ./table_compute.py && python3 ./table_compute.py

However, I keep getting back this error:

Traceback (most recent call last):
  File "./table_compute.py", line 24, in <module>
    import userconfig as uc  # noqa: I100,I202
  File "/home/tools-devteam/tools-iuc/table_compute/userconfig.py", line 1
    c1 	c2 	c3
    ^
IndentationError: unexpected indent

Does anyone have any suggestions of how I can solve this problem?

**Comment by bernt-matthias** [comment]
You are copying the tsv file to the python file (`cp examples.1.tsv. ./userconfig.py`), So essentially you try to execute the tsv file which makes no sense. 

But this does not happen during the tool execution, or? What are you trying to do?
