### ISSUE TITLE
A possible solution for Extract Genomics DNA sees twobit file from CVMFS

### ISSUE THREAD

**Issue by AliNemat** [galaxyproject/tools-iuc#4354]
Extract Genomic DNA is a very useful tool in nearly any bioinformatic pipeline. However, it seems that in the current format does not see the Twobit files on CVMFS, so for example in:
 https://usegalaxy.org/ ->Extract Genomic DNA -> locally cached-> **No options available.**
The behavior of the tool is the same on my local Galaxy.
I noticed in my local galaxy if I remove the following line from the XML wrapper, it will start see the References on CVMFS:
<filter type="data_meta" key="dbkey" ref="input" column="value"/>

The line is located at:
https://github.com/galaxyproject/tools-iuc/blob/master/tools/extract_genomic_dna/extract_genomic_dna.xml#L55

**Comment by wm75** [comment]
Hi @AliNemat !
The tool will only offer you ref sequences that match the dbkey you set on your interval dataset in your history (pencil icon, then "Database/Build"). If you select, e.g. hg19 there you should be offered the hg19 twobit file when working with that dataset.
This feature is intended to prevent genome mixups.

**Comment by AliNemat** [comment]
Hi @wm75 
Thank you for your quick response and clarification.

**Comment by bernt-matthias** [comment]
Seems that the issue is solved. Feel free to reopen if needed.
