### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by Raynooo** [galaxyproject/tools-iuc#441]
Hi, this is my first contribution here so I'll almost copy Anthony's issue 

For #299, we need to have a package for Flash (used by frogs suite)
I have locally created and tested it and will make a PR for it.

Renaud

**Comment by bgruening** [comment]
This will be a great contribution! Also please have a look at our PEAR wrapper, that does mostly the same.

**Comment by Raynooo** [comment]
Yeah I saw after I started that it got sent back in the priority list, but at least that will be useful as practice for me, I'll look into PEAR next.
