### ISSUE TITLE
populations not creating fst file.

### ISSUE THREAD

**Issue by angellcarrasquillo** [galaxyproject/tools-iuc#4412]
I am trying to calculate Fst values for each variable site between populations for a set of 9 populations. I have enabled fstats, and while this does generate a file with the mean Fst values between populations a populations.fst_Y-Z file is not produced, is there something I am doing wrong?

**Comment by bernt-matthias** [comment]
Which tool version is this?

**Comment by angellcarrasquillo** [comment]
Version 20.05, and I am running on Galaxy on AnVIL.

**Comment by bernt-matthias** [comment]
@angellcarrasquillo sorry, I meant which version of stacks you are using?

**Comment by angellcarrasquillo** [comment]
Sorry, it is stacks2 the tool itself is version 2.55+galaxy1

**Comment by bernt-matthias** [comment]
I can't even get these files on the command line. Do you have input and parameters that should produce these files?

**Comment by angellcarrasquillo** [comment]
Yes, I used the output from gstacks which was aligned to a reference genome and selected calculate fstats, along with —smooth. I followed the manual on the Stacks website.

**Comment by bernt-matthias** [comment]
@angellcarrasquillo .. can you deposit the gstacks output and the used command line somewhere? Otherwise I can't reproduce it.

**Comment by angellcarrasquillo** [comment]
The gstacks output was a list containing a vcf file and a .gz file, I was able to download the .gz file, however I am only able to provide a link for the vcf file due to some other error.

https://drive.google.com/file/d/17YdUQgEBYcNbvU3lPeLrie3pQo_7gHRE/view?usp=sharing

https://notebooks.firecloud.org/proxy/google/v1/apps/terra-ff29b765/terra-app-d257bb16-f444-4edf-80d7-dedeb4013db0/galaxy/datasets/ebba498991d43172/display?to_ext=data&hdca_id=f742044d2f735446&element_identifier=catalog.calls.vcf

**Comment by bernt-matthias** [comment]
@angellcarrasquillo I'm not able to produce a combination of command line and input files that produces a fst file. If you have one it would be much appreciated. Otherwise I'm not sure how to continue.

**Comment by TomHarrop** [comment]
@bernt-matthias I haven't used stacks in a while. I'm not sure if this helps!

I think the files @angellcarrasquillo is looking for are different to `populations.sumstats_summary.tsv`. In addition to that file, `populations` outputs a file for every pairwise combination of populations in the population map, called `populations.fst_Y-Z.tsv`, where Y and Z are the two populations.

Something like this should work:
```bash
populations \
    -P path/to/stacks_dir \
    -M population_map.txt \
    --fstats \
    --fst-correction \
    --smooth    
```




I don't think we pick up the additional files in the output: https://github.com/galaxyproject/tools-iuc/blob/1e2ff437ec47f8789e2309ee8c940c6451abfa0c/tools/stacks2/macros.xml#L474-L476

**Comment by bernt-matthias** [comment]
Thanks for the feedback. I think test number 8 should cover this parameter combination, but the files in question are not created. Could this be a shortcoming of the used data set? 

Since the Galaxy tool wrapper does wrap the latest version of stacks (currently 2.55) this might also be a feature that has been added later, or?

You are right that these files are not covered yet in the output section. This should be the easy to add, but at first a test case would be needed that creates the files.

**Comment by TomHarrop** [comment]
Ah OK. You're right, it looks like the popmap used for test 8 only has one population. I'm guessing those files only get created if there are multiple populations.

https://github.com/galaxyproject/tools-iuc/blob/1e2ff437ec47f8789e2309ee8c940c6451abfa0c/tools/stacks2/stacks_populations.xml#L537

**Comment by bernt-matthias** [comment]
Thanks @TomHarrop this helped: https://github.com/galaxyproject/tools-iuc/pull/4557
