### ISSUE TITLE
bcftools on toolshed cannot be installed

### ISSUE THREAD

**Issue by profgiuseppe** [galaxyproject/tools-iuc#4421]
Greetings, with respect to #4322 and its associated pull request #4326 for bcftools mpileup, I see that revision 10 of the tool on toolshed is marked as 

**This revision can be installed:** False 

By clicking on the info at [the end of the page](https://toolshed.g2.bx.psu.edu/repository?repository_id=b976c253f6b0d084&changeset_revision=6d7dc9a1bef3) the error message displayed is the following:

**bcftools_mpileup.xml** - This file refers to a file named **fasta_indexes.loc**. Upload a file named **fasta_indexes.loc.sampl**e to the repository to correct this error.

However, a local planemo test succeed without issues. 

Would it be solved if I create a pull request copying the test-data/fasta_indexes.loc to test-data/fasta_indexes.loc.sample? Is there any documentation about the testing process on toolshed that I can replicate so to provide a working patch?

Thanks!

**Comment by nsoranzo** [comment]
The issue is with the ToolShed repository metadata of all bcftools tools, I am in the process of resetting them (it takes some time). No action on your part should be needed, thanks for the heads up!

**Comment by nsoranzo** [comment]
I've reset all bcftools packages' metadata, all should be installable now.
