### ISSUE TITLE
validator of --set-id  for bcftools annotate 

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/tools-iuc#4438]
Hi,

I need help on this one.

https://github.com/galaxyproject/tools-iuc/blob/d1004c06207be773c278e12745aada276b63172e/tools/bcftools/bcftools_annotate.xml#L140

The current regexp does not allow to use `%CHROM\_%POS` it fails in `lib/galaxy/tools/parameters/validation.py`

I've tried to set it to `^([+]?(%[A-Z]+)(\\_%[A-Z]+)*)?$` but it does not match either... I don't really understand right now.

The match occurs with three \ or I need to add the raw string notation `r` (https://docs.python.org/3/howto/regex.html#the-backslash-plague) before the regexp string.

With the help of https://regex101.com/ I've tried:

```
import re
reg = '^([+]?(%[A-Z]+)(\\_%[A-Z]+)*)?$'
set_id = "%CHROM\_%POS"
print(re.match(reg, set_id), 'set_id', set_id)
None set_id %CHROM\_%POS
```

```
import re
reg = '^([+]?(%[A-Z]+)(\\\_%[A-Z]+)*)?$'
set_id = "%CHROM\_%POS"
print(re.match(reg, set_id), 'set_id', set_id)
<_sre.SRE_Match object; span=(0, 12), match='%CHROM\\_%POS'> set_id %CHROM\_%POS
```

```
import re
reg = r'^([+]?(%[A-Z]+)(\\_%[A-Z]+)*)?$'
set_id = "%CHROM\_%POS"
print(re.match(reg, set_id), 'set_id', set_id)
<_sre.SRE_Match object; span=(0, 12), match='%CHROM\\_%POS'> set_id %CHROM\_%POS
```

So? Do I need to use `\\\` (and then create a PR and a test for bcftools annotate)
Or use only `\\`  and raw string notation (and then create a PR and a test for bcftools annotate and a PR for  `lib/galaxy/tools/parameters/validation.py`?

Thank you.

**Comment by bernt-matthias** [comment]
Adding a test (or extending a present test) seems like a great idea, since the parameter is untested at the moment.

I guess 3 backslashes are correct.

**Comment by FredericBGA** [comment]
Solved in https://github.com/galaxyproject/tools-iuc/pull/4442
