### ISSUE TITLE
Pangolin API / SSL error 

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [galaxyproject/tools-iuc#4469]
Dear, when I run Pangolin on [usegalaxy.fr](https://usegalaxy.fr) I got this error 
`Unable to connect to reach github API --update/--data_update requires internet connectivity so may not work on certain systems or if your IP has exceeded the 5,000 request per hour limit
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>`
How can I fix it ? thanks ! 

Dependency | Dependency Type | Version
$pangolin | $conda | $3.1.20
$scorpio | $conda | $0.3.16
$csvtk | $conda | $0.23.0

**Comment by abretaud** [comment]
Hi @BenjaminDEMAILLE 
Yes there's a problem with some conda install on usegalaxy.fr, we're investigating.
Closing this issue as it's specific to usegalaxy.fr, we'll keep you informed in https://community.france-bioinformatique.fr/t/pangolin-https-error/1994/3
