### ISSUE TITLE
IUC member proposal: Peter van Heusden

### ISSUE THREAD

**Issue by wm75** [galaxyproject/tools-iuc#4470]
I would like to propose Peter van Heusden (@pvanheus) as new IUC member.

Peter has been contributing and maintaining many tools constantly for many years now.
He has contributed enormously to our arsenal of pathogen-related tools, in particular but not only, over the course of the Covid-19 pandemic.

Nearly all of you know him very well as an active member of the Galaxy community, so please just vote!

**Comment by mvdbeek** [comment]
Yes, great idea!

**Comment by bgruening** [comment]
👍

**Comment by wm75** [comment]
Oops, forgot about this over Easter.
If anyone still wants to vote, this is your last chance ;)

**Comment by wm75** [comment]
So ... high time :sweat_smile: to pronounce a result here: Welcome @pvanheus to the IUC :tada:

@bgruening can you add Peter to the organization?

**Comment by martenson** [comment]
Awesome, thanks for joining @pvanheus!

@wm75 I've added Peter to the GH team.
