### ISSUE TITLE
Pangolin data manager needs an update

### ISSUE THREAD

**Issue by wm75** [galaxyproject/tools-iuc#4504]
https://github.com/galaxyproject/tools-iuc/pull/4494 updates pangolin to version 4.

Since the facts about the pangolin 3->4 switch are fresh on my mind just now, I'll document the challenges on the DM side here:

- the current DM is called data_manager_pangolearn and looks for pangolearn model releases at https://github.com/cov-lineages/pangoLEARN/releases/
- this repo is currently still seeing new releases with pangolin 3 compatible models
- pangolin 4, however, uses pangolin 3-incompatible (random forest instead of decision tree) models that are released in https://github.com/cov-lineages/pangolin-data/releases
- the data table "pangolearn" populated by the current DM has a version column used by the pangolin tool to offer only compatible entries in its tool interface

Instead of bloating the current DM with extra logic to select the repo to install from, I would tend to add a new data_manager_pangolin_data that installs pangolin-data releases into the existing datatable and adds 4.0 to the version column. The existing DM can still be used to add legacy v3 entries to that table. Since the pangolearn releases use dates as release tags, while pangolin-data releases use proper version strings there should be no "value" collisions in the shared data table.

Just a suggestion right now for anyone who wants to pick this up.

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/tools-iuc/pull/4505

**Comment by wm75** [comment]
This is still relevant. #4505 only fixed installation of legacy v3 models from the pangoLEARN repo, but didn't add support for v4 models from pangolin-data.

**Comment by wm75** [comment]
addressed by: #4633
