### ISSUE TITLE
[SPAdes]--cov-cutoff option with user specific value isn't parsed correctly by the wrapper 

### ISSUE THREAD

**Issue by jvanbraekel** [galaxyproject/tools-iuc#4555]
Hello IUC team,

There is an issue with the SPAdes tool's wrapper. When the --cov-cutoff option is set with a  user specific value, "value" is written in the command line instead of the actual value pick by the user in the additional form field.  Command line looks like : `--cov-cutoff value ` and SPades crash with the following error : ` error: argument --cov-cutoff: wrong value value (should be a positive float number, or 'auto', or 'off')` .  It does work with the default value ('off') and the 'auto' value too  because the wrapper does this : 
` ## parameter
    --cov-cutoff $cov_cond.cov_cutoff` ,

That 'cov_cond' parameter is set in the macro xml : 

```
<xml name="covcutoff">
        <conditional name="cov_cond">
            <param argument="--cov-cutoff" type="select" label="Set coverage cutoff option" help="When set to 'auto' SPAdes automatically computes coverage threshold using conservative strategy">
                <option value="off">Off</option>
                <option value="auto">Auto</option>
                <option value="value">User specific</option>
            </param>
            <when value="off"/>
            <when value="auto"/>
            <when value="value">
                <param name="manual" type="float" min="0" value="" label="Set value"/>
            </when>
        </conditional>
    </xml>
```

So in the 'User specific case' ,  the parameter should be set to $cov_cond.manual, or the conditional should be updated to change the value of the 'cov_cutoff' dropdown instead.

**Comment by bgruening** [comment]
Thanks for the detailed report. I tried to fix it here: https://github.com/galaxyproject/tools-iuc/pull/4556

You can also dive into the code if you like, we are mostly friendly and accept Pull requests :)

Thanks a lot!

**Comment by jvanbraekel** [comment]
Hello Bjorn,

Thank you for your the fix.
You went faster than me, a was about to make a PR for it :) .

**Comment by JayanthiGangiredla** [comment]
Hi,

I need help in figuring this out. Using new version of spades i am unable to generate assembly for each sample separately  on galaxy, when i provide paired collection as input. Instead, it's merging all sample assemblies in to one. I dont understand where am i doing wrong. I am facing the same issue on all new version of spades(spades, metaspades, metaviralspades, metaplasmidspades).


Thanks,
Jayanthhi

**Comment by gallardoalba** [comment]
Hi @JayanthiGangiredla,
yes, this is a known issue.  Would you mind opening a new issue about that?
