### ISSUE TITLE
Tool request: AGAT

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/tools-iuc#4584]
From the original repository: https://github.com/NBISweden/AGAT

> AGAT has the power to check, fix, pad missing information (features/attributes) of any kind of GTF and GFF to create complete, sorted and standardised gff3 format. Over the years it has been enriched by many many tools to perform just about any tasks that is possible related to GTF/GFF format files (sanitizing, conversions, merging, modifying, filtering, FASTA sequence extraction, adding information, etc).

**Comment by bernt-matthias** [comment]
Good request. In particular since their docs mention that gff2gtf conversion is done correctly https://agat.readthedocs.io/en/latest/gff_to_gtf.html .. compared to other tools

**Comment by gallardoalba** [comment]
Included here https://github.com/bgruening/galaxytools/pull/1310
