### ISSUE TITLE
MACS2 not in main tool shed

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#46]
On IRC:

```irc
jelle_: Any reason the macs2 suite maintained by iuc is only available in the test toolshed?
```

I'm preparing to push this now, so file your complaints if you have them!

**Comment by erasche** [comment]
Pushed to main TS

**Comment by bgruening** [comment]
Upps ... ;) Ok, let's wait for bug reports. The reason was that it is currently tested on test.galaxyproject.org.

**Comment by bgruening** [comment]
But thanks for doing this!

**Comment by erasche** [comment]
It passes [most of my tests](
http://gx.hx42.org/job/IUC-Github/Planemo_HTML_Reports/macs2.html)


2015-02-11 9:26 GMT-06:00 Björn Grüning <notifications@github.com>:

> But thanks for doing this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/issues/46#issuecomment-73899398>
> .
>



-- 
Eric Rasche

**Comment by erasche** [comment]
It passes [most of my tests](http://gx.hx42.org/job/IUC-Github/Planemo_HTML_Reports/macs2.html), sorry, didn't realise that it was undergoing manual testing on test.galaxyproject.org
