### ISSUE TITLE
Nex tool ReferenceSeeker: rapid determination of appropriate reference genomes

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/tools-iuc#4651]
Referenceseeker is a tool which calculate ANI score and determine close reference genome to a query.
Could be interesting for ANI score --> close species determination and reference genome could be link to Quast for better estimation of genome assembly

**Comment by pvanheus** [comment]
This is [this tool](https://github.com/oschwengers/referenceseeker) and indeed it looks good. It will need a data manager (DM) as well as a tool.

**Comment by pimarin** [comment]
Hi @pvanheus, thank you to the suggestion of refseq_masher which feel pretty good ! 
I write the xml referenceseeker tool, but I don't understand how to make a data manager, referenceseeker use the refseq database, so I need to link with the refseq data manager ?
Furthermore, refseq_masher don't update the refseq database ? I don't see any options related to the database.

**Comment by pvanheus** [comment]
Hi @pimarin - yes, I don't think refseq_masher has an option for updating its database.

As to a data manager: this is a special kind of tool that updates a "data table". These tools are not run by users but rather by the Galaxy server admin. Unfortunately there are not very good docs for writing them but there are several examples in the [data_managers](https://github.com/galaxyproject/tools-iuc/tree/master/data_managers) section of this Github repository. I don't think we should wait till a data manager can be built to support referenceseeker though. It is something useful to have for the future.

The referenceseeker tool expects the database to be in a directory, unpacked from the .tar.gz files that they provide. There is no easy way to provide a directory as a dataset in Galaxy, so the user would have to, I think, put the .tar.gz for the database in their history and then the tool would have to unpack it before using it. This is resource intensive but I don't see another way to write a wrapper right now. Maybe others have other suggestions.
