### ISSUE TITLE
add repeat elements to `Add_a_column1`

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/tools-iuc#4656]
The `Add_a_column1` tool aka "Compute" is sometimes used repeatedly in workflows such as the [COVID-19: variant analysis reporting](https://github.com/galaxyproject/iwc/tree/main/workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting) workflow. This repetition can be supported in the tool by adding a `<repeat>` element to the tool, allowing multiple columns to be added in a single operation.

**Comment by pvanheus** [comment]
See also [this issue](https://github.com/bgruening/galaxytools/issues/1227).

**Comment by wm75** [comment]
:+1:
Ideally, the tool would let you also specify, for each operation, where to insert the new column and whether to do so in insert or overwrite mode. Currently such extras require a separate run of the `Cut1` tool.

All of this is not exactly a low-hanging fruit given the way `Add_a_column1` is implemented, but we should try.

**Comment by bgruening** [comment]
Is table_compute not able to help here?

**Comment by wm75** [comment]
> Is table_compute not able to help here?

Not really. It would allow you to do all this with a single tool, but would also require multiple runs.
