### ISSUE TITLE
flake8 all Python files and add check to Travis.

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-iuc#467]
Excluding the usual E201,E202 and E501 errors, I got:
```
$ flake8 --ignore=E201,E202,E501 --count .
1642
```

Would you all be happy if I start fixing these? When we finish, we can add a new check for this to TravisCI.

**Comment by peterjc** [comment]
In principle yes, and this would become a *de facto* IUC coding convention. I think we should document setting up a pre-commit git hook for IUC contributors to try to catch this locally before pushing to Git.

The downside of adding this to TravisCI to enforce this is it would remove any developer discretion - the PEP8 style guidelines are guidelines. So, for example I fully agree with leaving E501 to author discretion in line with the PEP8 wording:

* E501 line too long (82 characters)

I'd have to skim the full flake8 error list in case there's anything else which might be contentious - but you'll likely be doing this yourself if you start the cleanup process.

P.S. I would vote to fix all the E201 and E202 errors as well, a pet peeve in the current Galaxy codebase ;)

*  E201 whitespace after '['
*  E202 whitespace before ')'

**Comment by bgruening** [comment]
I would be very happy to merge such a PR :)

**Comment by bgruening** [comment]
@nsoranzo do you need help here? We could organise a Codefest dedicated to closing/fixing Issues before GCC?

**Comment by nsoranzo** [comment]
@bgruening First step in #753.
