### ISSUE TITLE
Magicblast : DB not found

### ISSUE THREAD

**Issue by eHirchaud** [galaxyproject/tools-iuc#4687]
## Bug description:

I Install  magic blast tool on local Galaxy instance.

I use local db like blast tool.

And I have this error message

`BLAST Database error: No alias or index file found for nucleotide database [/db/nt_blast/nt/blastdb] in search path [/srv/galaxy/jobs/003/3361/working::]`

* My blastdb.loc :

`nt      NCBI Partially non-redundant (nt)       /srv/db//nt_db/nt`

This works for ncbi_blast_plus

In magicblast.xml wrapper I see this line for db selection `'${os.path.join($db_opts.database.fields.path, "blastdb")}'`

This assumes that  index name  is allways blastdb.

**Comment by gregvonkuster** [comment]
This should be fixed by this PR https://github.com/galaxyproject/tools-iuc/pull/4707

**Comment by bernt-matthias** [comment]
@eHirchaud feel free to reopen if the problem persists.
