### ISSUE TITLE
Featurecount error

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/tools-iuc#4772]
Hello,

I install featureCounts wrapper to my galaxy instance (v. 2.0.1+galaxy2). 
The dependancy is correctly install (load conda env and try tools manually), but I get the following error when I performed a run:
`This tool was disabled before the job completed.  Please contact your Galaxy administrator.`

I try to test the wrapper with ephemeris but all test failed.

**Comment by bernt-matthias** [comment]
Is there any other message about featurecounts in the logs?

Which galaxy version are you using? Fc requires 20.05.

**Comment by bvalot** [comment]
Hello,

Finally, it was a problem of update the job_conf. Reboot galaxy resolve the problems.

Sorry,
