### ISSUE TITLE
Bug Arriba using WGS Structural Variants

### ISSUE THREAD

**Issue by JasperO98** [galaxyproject/tools-iuc#4799]
When running Arriba with Structural Variant data (VCF) it returns the following error:
`cannot find 'use_wgs' while searching for 'wgs.use_wgs'`

Probably the wgs.use_wgs is not recognized in the xml file, but I cannot find the issue.

![image](https://user-images.githubusercontent.com/38041391/191797767-7d222801-96f5-4dad-b198-97ccb40ab03a.png)

**Comment by bernt-matthias** [comment]
Odd, can't see a problem in the tool sources.

Can you share the history?

**Comment by JasperO98** [comment]
Sure no problem.
https://usegalaxy.eu/u/jaspero/h/squid

**Comment by JasperO98** [comment]
Thanks!
