### ISSUE TITLE
shovill output problem for workflow

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/tools-iuc#4804]
Hi,
I have some problem with my PR about shovill and bam file : 

- I make an error in the script with the filtering option because bam output is not present when logfile yes and the inverse is true, I will make a PR to fix it
- I have a problem about the bam output which is in unsorted.bam format but when I want to bind it with samtool stat ou depth, I failed because samtool require just .bam

**Comment by bernt-matthias** [comment]
For the 2nd problem you just need to add a samtools sort tool in between, or?

**Comment by pimarin** [comment]
My bad, it seem the samtool version on the galaxy was too old and the last version accept unsorted bam !
I will fix the probleme with the log and bam file and that's all !
Thank you !
