### ISSUE TITLE
Fix emboss tool versions

### ISSUE THREAD

**Issue by rogmei** [galaxyproject/tools-iuc#4829]
The tool sixpack on usegalaxy.eu only acepts fasta files, but throws an error every time I try.
Have tried both single fasta and multifasta, always with the same result. 
Under is an example of a fasta that fails in Galaxy. Pasting this same sequence into the EMBOS online sixpack tool works. 
Other Galaxy tools like seqret does work.

The Galaxy error:

An error occurred with this dataset:
format sixpack database [?](https://usegalaxy.eu/#)
Died: Value required for '-uppercase' before '-number'

>contig_10
TGAAATGAATGATAAGCCAGTTTTGTTGTCAAATAGTTTCTGTGTGGCTTCGGTAGATAA
TATCGATAGGAATAGTGCTTATGCATCAGTTAAAGTTGGTGAGGCTAATAGAGGATTTCA
TGGAACTTCTGTTCAGTCTGTAGAGCCTTTGCCTATTTCAACCTCAGTCGGAAGGACTGC
TTGTAATTCGTTACATACTTCCAGTAGAGTTGGTCAACAAAGCAATTTGTCAGCTGCAGA
TATCAGGGATTATCAACACACTTTTACTCAAACTTCTCATTCAGAAGTTACATCTTATAG

**Comment by bernt-matthias** [comment]
Thanks for reporting. Which tool version do you use and on which galaxy are you working? Can you tell us which non default parameters values you are using? If you see the executed command line in the dataset info page this would also be of interest.

**Comment by rogmei** [comment]
Hi


Thanks for getting back to me.

Using default values on
https://usegalaxy.eu/
sixpack Display a DNA sequence with 6-frame translation and ORFs (Galaxy Version 5.0.0.1)
toolshed.g2.bx.psu.edu/repos/devteam/emboss_5/EMBOSS: sixpack90/5.0.0.1

For each run of sixpack singlefasta or multifasta, two separate instances opens. I guess this is divided in the three forward and three reverse reading frames.
Regardless it always ends with this error message after a short time running.
***@***.***

Hope you can find out what is going wrong here.


Best regards
Roger



Fra: M Bernt ***@***.***>
Sendt: fredag 7. oktober 2022 08:43
Til: galaxyproject/tools-iuc ***@***.***>
Kopi: Roger Meisal ***@***.***>; Author ***@***.***>
Emne: Re: [galaxyproject/tools-iuc] Sixpack tool not working (Issue #4829)


Thanks for reporting. Which tool version do you use and on which galaxy are you working? Can you tell us which non default parameters values you are using? If you see the executed command line in the dataset info page this would also be of interest.

-

**Comment by bernt-matthias** [comment]
@rogmei plase share the history or data set and post the link

**Comment by bernt-matthias** [comment]
Seems that we messed up the versions. `5.0.0.1` is not the latest version, but `5.0.0+galaxy2` as a workaround you can manually switch the version on the top of the tool form (the button with the 3 boxes on the top right.

I guess to fix this we need to readd `.1`  to the tool versions

**Comment by rogmei** [comment]
Thanks for solving this. 
Switching versions works. 
Would never have guessed this had to do with a version conflict.

**Comment by rogmei** [comment]
Solved
