### ISSUE TITLE
[request] bcftools 1.3

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#483]

**Comment by jj-umn** [comment]
@erasche   I started with your bctools1.2 branch and created branch bcftools1.3 with most bctools commands and plugins now implemented and initially tested.  
It uses the existing galaxy datatypes Vcf and Bcf.   It relies on macros to bgzip and index input files as required by bcftools commands.  

@bgruening  The cnv and stats commands can generate plots but this will require adding a matplotlib dependency.  I thought you might be able to suggest the most appropriate version.

**Comment by bgruening** [comment]
@jj-umn `package_python_2_7_matplotlib_1_4` is good to use. Moreover you will get conda dependencies for free :)

**Comment by bgruening** [comment]
@jj-umn can you please create a PR, so we can comment on it.
Thanks

**Comment by erasche** [comment]
@jj-umn amazing. I'm sorry I never made more progress on this -- priorities changed and it was unfortunate :( Will look forward to reviewing your work!

**Comment by jj-umn** [comment]
On 3/17/16 3:11 PM, Eric Rasche wrote:
>
> @jj-umn <https://github.com/jj-umn> amazing. I'm sorry I never made more progress on this -- priorities changed and it was unfortunate :( Will look forward to reviewing your work!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/galaxyproject/tools-iuc/issues/483#issuecomment-198063408>
>
Eric,

Thanks for getting it started.
When I needed an updated bcftools I was very pleased to find the template you provided.

JJ

-- 
James E. Johnson Minnesota Supercomputing Institute University of Minnesota

**Comment by chambm** [comment]
Is this in the toolshed? bcftools_call is the only one I see recently in either the MTS or TTS. bcftools_view is old and doesn't use the -S flag for my VCF input. I have a very simple patch for that, but there appears to be a lot of new work here. However, I'm just trying to call variants on a large VCF input file, so I'm not sure that the mandatory bgzip+index step that I see in macros.xml should be forced.

Actually I'd rather pipe the output of `mpileup` straight to `bcftools view` and avoid writing the intermediate 3GB file.

**Comment by bgruening** [comment]
Hi @chambm I updated both TSs. Sorry for the trouble.

**Comment by jj-umn** [comment]
@chambm @erasche @bgruening   
These haven't been put in the toolshed.  The remaining failing tests need the the package_bcftools_1_3 to set the environment variables BCFTOOLS_ROOT_PATH and BCFTOOLS_PLUGINS

I agree that samtools_mpileup should add a dependency for package_bcftools_1_3 and optionally allow piping through bcftools view.

**Comment by chambm** [comment]
@jj-umn would that explain why the tool that is there, bcftools_call, gives me:

    Fatal error: Exit code 1 ()
    [main] Unrecognized command.

**Comment by jj-umn** [comment]
@chambm  I don't think so.  
I was referring to pull-request #681 in which I tried to provide tool wrappers for the complete bcftools 1.3
package.

**Comment by nsoranzo** [comment]
I think that has been solved by #681, if not feel free to reopen.
