### ISSUE TITLE
MEME

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#49]
@bgruening `jelle_` was asking about this on IRC. 

You seem to have a meme package in the TTS, but while the [development  repo](https://testtoolshed.g2.bx.psu.edu/view/iuc/package_meme_4_10_0) is listed as this one but there's no meme package here.

Additionally, are you planning on writing wrappers for it?

Needed:

- [x] package https://github.com/galaxyproject/tools-iuc/pull/75
- [ ] tools

**Comment by nsoranzo** [comment]
There are already some wrappers for MEME in the ```tools/meme/``` directory of galaxy-central (no idea of their status).

**Comment by bgruening** [comment]
I was planning to write some, but had no time. I will put it back into my queue.

**Comment by blankenberg** [comment]
As @nsoranzo mentioned, we do have some wrappers for MEME and FIMO in the distribution. IIRC, they should be in pretty decent shape when they were added. One outstanding item was that they were letting the user set sequence sizes and maxsize, which might be better off hidden.

**Comment by bgruening** [comment]
@scholtalbers @erasche can we close this issue?
@blankenberg is a migration to the TS planned?
