### ISSUE TITLE
Bug: Pathview Galaxy Version 1.34.0+galaxy0

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#4901]
MTS https://toolshed.g2.bx.psu.edu/view/iuc/pathview/f1691de443a7
Dev https://github.com/galaxyproject/tools-iuc/tree/master/tools/pathview

Fails at both `org` and `eu` the same way

Test history using tool tests https://usegalaxy.eu/u/jenj/h/test-pathview

```
Loading required namespace: org.Dm.eg.db

'select()' returned 1:many mapping between keys and columns
Info: Getting gene ID data from KEGG...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
Calls: run_pathview ... request_fetch -> request_fetch.write_memory -> <Anonymous>
```

> **Workaround for end-users at either server**:
> 
> - Use Galaxy Version **1.24.0+galaxy2** or **1.24.0+galaxy0** instead until resolved
> 
> 1. Load the tool form from the tool panel
> 2. Switch to a prior version using the **Versions** menu (upper right corner)

**Comment by bgruening** [comment]
@jennaj I think EU is "fixed". 

@natefoo I needed to get openssl 1.1 installed in the venv to make it work. Not sure that is the best way.

**Comment by natefoo** [comment]
We're using the Singularity BioContainer, which uses OpenSSL 3.0.3:

```console
$ singularity exec /cvmfs/singularity.galaxyproject.org/all/mulled-v2-8311fc606069e8940fa5f252c3c6c0f0d3e85e45:7065540c2140705b6c16b897a10f1e3ae199420f-0 /bin/sh -c 'ls -l /usr/local/conda-meta/openssl-*'
-rw-r--r--    1 root     root         55038 May 10 01:30 /usr/local/conda-meta/openssl-3.0.3-h166bdaf_0.json
```

So I'm a little confused how we're encountering the same issue.

**Comment by jennaj** [comment]
> I think EU is "fixed".

Looks good at EU now, thanks @bgruening 

> So I'm a little confused how we're encountering the same issue.

I was too. I just broke out and reran the test at ORG in a smaller history, maybe helps? @natefoo 

**TEST**
https://github.com/mvdbeek/usegalaxy-tests/issues/66 

**ORG**
https://usegalaxy.org/u/jen/h/test-pathview
data 3 failed (1.34.0+galaxy0)
data 4 success (1.24.0+galaxy0)


**EU**
https://usegalaxy.eu/u/jenj/h/test-pathview
data 11 failed (1.34.0+galaxy0)
data 19 success (rerun of data 11, 1.34.0+galaxy0)

**Comment by bgruening** [comment]
3.03 I think. I can give you my new env if this helps?

**Comment by natefoo** [comment]
Sure, if you don't mind.

**Comment by bgruening** [comment]
Hope that helps, https://gist.github.com/bgruening/34e44732659d80904f3ca55078065191 also see the comment.

**Comment by natefoo** [comment]
Do we need to pin it to 1.1 then, for the mulled container image?

**Comment by bgruening** [comment]
I don't understand why, but this at least works for me. Can you confirm that? Then we can try to create a new container. I do not understand why this would help, but it does in my case.

**Comment by natefoo** [comment]
I'll try to build a new container locally to test. I don't really have a setup for this, but I kind of need one, so I guess this is a good test case.

**Comment by bernt-matthias** [comment]
Weekly CI also fails with the exact same reason.

**Comment by bernt-matthias** [comment]
I tested this on my Galaxy (which uses conda) .. downgrading to openssl 1.1 helped. 

How to proceed. Pin at bioconda? Pin at the tool requirements?

**Comment by bernt-matthias** [comment]
https://github.com/conda-forge/r-curl-feedstock/pull/21

**Comment by bernt-matthias** [comment]
Should be solved by https://github.com/BioContainers/multi-package-containers/pull/2618 (based on https://github.com/conda-forge/r-curl-feedstock/pull/21 and https://github.com/conda-forge/r-base-feedstock/pull/236). Tested locally.
