### ISSUE TITLE
Test against galaxy branch topic/output-filter-multiple-select 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#4933]
xref https://github.com/galaxyproject/galaxy/pull/14998

**Comment by bernt-matthias** [comment]
/run-all-tool-tests fork-bernt-matthias branch=topic/output-filter-multiple-select

**Comment by bgruening** [comment]
/run-all-tool-tests fork-bernt-matthias branch=topic/output-filter-multiple-select

**Comment by bernt-matthias** [comment]
Hey @bgruening unfortunately there was a typo in the command, it should be 

/run-all-tool-tests fork=bernt-matthias branch=topic/output-filter-multiple-select

good thing is that it revealed a typo https://github.com/galaxyproject/planemo/pull/1325
