### ISSUE TITLE
BUSCO update & gff output

### ISSUE THREAD

**Issue by aabaricalla** [galaxyproject/tools-iuc#5001]
Hi there!

There is a new update for [BUSCO (5.4.4)](https://busco.ezlab.org/) that could be especially interesting because this version adds a GFF output file that could be retrieved as a desirable output.

[The maintainer said:](https://gitlab.com/ezlab/busco/-/issues/268)
"BUSCO v5.4.1 has now been released. GFF files are now provided in the `busco_sequences` output folders." 
The Manual established that the GFF output is in the "MetaEuk" folder.

Hope this could be an update and improvement.

**Comment by abretaud** [comment]
Hi! An automated update pull request was created in https://github.com/galaxyproject/tools-iuc/pull/4819
Tests are failing for now, I'll see if I can fix them easily

**Comment by abretaud** [comment]
@aabaricalla have you already used this new gff output? From first tests it looks like busco is not always creating it, and that there can be multiple gff files. Do you know which file should be kept by the galaxy tool?

**Comment by abretaud** [comment]
:+1: makes sense, thanks
I guess I can merge all individual gff into a single one?

**Comment by aabaricalla** [comment]
I was working with BUSCO 5.4.4 in usegalaxy.eu and the GFF file works perfectly!
This Issue can be closed.
Thanks, @abretaud !!
