### ISSUE TITLE
Bakta 1.6.1 is failing

### ISSUE THREAD

**Issue by oschwengers** [galaxyproject/tools-iuc#5046]
Hi @pimarin, @bgruening and @bernt-matthias, thanks a lot for all the efforts to get Bakta v1.6.1 into Galaxy.

Unfortunately, it is still not working. I faced the following two issues.

```
ERROR: AMRFinderPlus database not installed! Please, install AMRFinderPlus's internal database by executing: 'amrfinder_update --database $/data/jwd04/main/054/184/54184377/working/database_path/amrfinderplus-db'. This must be done only once.
```
I guess this one was introduced and somehow missed in https://github.com/galaxyproject/tools-iuc/pull/4947. It is occurring on the EU (Bakta 1.6.1) but not on the Au (Bakta 1.5.0) usegalaxy instance.

```
ERROR: deepsig not found or not executable! Please make sure deepsig is installed and executable or skip requiring workflow steps via via '--gram ?'.
```
This is occurring on both usegalaxy instances (EU & Au) using different Bakta versions (1.6.1 & 1.5.0). Dependency-wise,`DeepSig` is not the easiest tool. Therefore, it is only available via Conda on Linux. Maybe it's best to just hide the `--gram` parameter, as by default the detection of signaling peptides via DeepSig is only active if a gram type was selected by the user, but not as default.

I'll have a look at the `--gram` parameter. As I'm not too familiar neither with `Galaxy` nor with `iuc`, I guess I can only report and support. Please, let me know if there's anything I can potentially help with.
Thanks again an best regards,
Oliver

**Comment by bernt-matthias** [comment]
We could add `deepsig` to bioconda or here in the tool and see what happens. 

> I'll have a look at the --gram parameter.

Would be cool if you could report to us if its helpful.

**Comment by bernt-matthias** [comment]
Regarding the database: Can you see the generated command line in the job info page? Could you report it here?

**Comment by oschwengers** [comment]
> We could add `deepsig` to bioconda or here in the tool and see what happens.

It is already available on Bioconda (https://bioconda.github.io/recipes/deepsig/README.html) for Linux. Because it is not available for MacOS, I decided to exclude it from the Conda dependencies. Otherwise, users would not be able to install it via Conda on MacOS systems. I don't know how or if this is possible, but if the Galaxy workers run on Linux, one could maybe just add Deepsig as an additional Bakta depdendency? But as I said, if this is not working or too complex, we could just deactivate its usage by pinning the `--gram` parameter to `?`.

**Comment by oschwengers** [comment]
> Regarding the database: Can you see the generated command line in the job info page? Could you report it here?

```
mkdir ./database_path && ln -s '/data/db/data_managers/bakta_database/7025248/'* database_path && ln -s '/data/db/data_managers/amrfinderplus-db/amrfinderplus_V3.11_2022-12-19.1/' database_path/amrfinderplus-db &&  bakta --threads ${GALAXY_SLOTS:-1} --db ./database_path --min-contig-length 1 --prefix bakta_output  --translation-table '11' --gram '?'     '/data/dnb07/galaxy_db/files/0/6/b/dataset_06bf7ccd-9da3-4536-9d22-1e277ad5a06e.dat' | tee '/data/jwd02f/main/054/199/54199833/outputs/galaxy_dataset_00dc3de6-a282-475d-913d-8620ce8c3ccf.dat'
```

**Comment by bgruening** [comment]
I'm debugging it since yesterday, the DM location does not work with the Tool atm. Both are not in sync. Will report back when I have time and find something. The DM also misses a name attribute.

**Comment by oschwengers** [comment]
Maybe it's a mere misconception regarding the content of `database_path/amrfinderplus-db`. AMRfinderplus puts date schema-named subfolders for each database version into its database path, *along* with a `latest` link pointing to the latest db version. Bakta expects this `latest` link within the `database_path/amrfinderplus-db` dir. I hope this is helpful.

```
$ ls -l databases/bakta/db-v4.0/amrfinderplus-db/
drwxrwxr-x 2 oliver oliver 4,0K Aug 26 10:37 2022-08-09.1/
lrwxrwxrwx 1 oliver oliver   70 Sep 27 09:21 latest -> /home/foo/databases/bakta/db-v4.0/amrfinderplus-db/2022-08-09.1/
```

**Comment by bgruening** [comment]
Oh that is a good one. The latest symlink is missing, urgs. Thanks!

**Comment by pimarin** [comment]
Hi everyone, 
I will update the tool to fix the AMRfinderplus error, and I'll try on my local instance to confirm bakta 1.6.1 works fine,
I apologize for this error which was not present during planemo test...

**Comment by bernt-matthias** [comment]
> I apologize for this error which was not present during planemo test...

No worries. It's just quite complicated to test a tool + datamanager. If you really want to be sure deploy them to the test toolshed and install both in a local Galaxy instance.

**Comment by oschwengers** [comment]
I just successfully tested Bakta v1.6.1 on usegalaxy.eu. Fantastic job! Thanks to everyone involved!

**Comment by pimarin** [comment]
Happy for that !
Next step the 1.7 release and light database ;)

**Comment by oschwengers** [comment]
I'm very much looking forward to that. Contact me if I can help in any kind.
