### ISSUE TITLE
Scatterplot with ggplot2 multiple user defined points broken

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/tools-iuc#5089]
Attempting to set a `relative size of points` under `Advanced options` in `Scatterplot with ggplot2`, together with the option `Plot multiple groups of data on one plot` (as seen in [Galaxy 101 for everyone](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html)) causes the job(s) to fail. Each option works on it's own.

Tested in galaxy 23.0 on usegalaxy.org
Version of `Scatterplot with ggplot2`: (Galaxy Version 3.4.0+galaxy0)
Tool ID: toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point/3.4.0+galaxy0

Tool Standard error:
```
Warning message:
In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
Warning message:
package 'ggplot2' was built under R version 4.1.3 
Error: unexpected symbol in:
"        gg_point = geom_point(size=2.0, alpha=1.0, gg_factor, shape=as.numeric('0')
        gg_line"
```

**Comment by bernt-matthias** [comment]
Fixed in https://github.com/galaxyproject/tools-iuc/pull/5090?
