### ISSUE TITLE
Extending xml tool wrapper with "Tutorials associated with this tool" section?

### ISSUE THREAD

**Issue by michauhl** [galaxyproject/tools-iuc#5148]
Hi, 
it might be useful to list tutorials that use the tool the user is currently looking at in the tool wrapper. Maybe an additional section (like output, input)? Or inside the help section?
Thanks & Best,
Michael

**Comment by bernt-matthias** [comment]
Might be covered directly from Galaxy https://github.com/galaxyproject/galaxy/pull/15628

**Comment by michauhl** [comment]
Sounds like the same thing yes thanks :) Looking forward to it!
