### ISSUE TITLE
Make a tool to aggregate results to json parsable format 

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/tools-iuc#5164]
I'm searching a tool which can be used a the end of a galaxyworkflow to extract all results from files, path of file and generate a json final file which coulde be used to feed a database for example or later to make an automatic generated report of the workflow.

**Comment by bernt-matthias** [comment]
I guess the API might be of help here.. Maybe via bioblend?

**Comment by bgruening** [comment]
@pimarin can you link to the pr that has resolved it for future reference please.
