### ISSUE TITLE
problem in SHM and immune repertoire pepline

### ISSUE THREAD

**Issue by loub9** [galaxyproject/tools-iuc#5190]
When I upload my files (IMGT/High-V quest zip.txz format), and when I run the SHM or immune repertoire pepline, it becomes green in the history but when I try to open the analysis by clicking on the eye icon, I don't get any result!

**Comment by bernt-matthias** [comment]
Can you share the history?

**Comment by loub9** [comment]
yeah sure! That what I get. 
![image](https://user-images.githubusercontent.com/127764180/227129708-3e8dc73b-4874-4df5-93a7-44b50ae8fb22.png)

**Comment by bernt-matthias** [comment]
@loub9 this tool is not maintained by IUC. Please contact the author @rhpvorderman at https://github.com/LUMC/shm_csr or the admins of the Galaxy instance. 

Closing the issue here.
