### ISSUE TITLE
Deprecate package_r_3_2_0

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#520]
Since it has [issues](http://trac.sagemath.org/ticket/18254#comment:61) on OS X, and a quick grep shows no iuc tool is using this package.

Would be interesting to be able to see which tools/packages on the toolshed rely on other packages!

**Comment by gregvonkuster** [comment]
Click on Repository dependency definitions in the left panel under the Valid Galaxy Utilities section.  This shows all repository dependencies, and package_r_3_2_0 does not display, implying that nothing is depending upon it.

**Comment by mvdbeek** [comment]
Ah, good to know! Thanks

**Comment by nsoranzo** [comment]
:+1:

**Comment by bgruening** [comment]
:+1:

**Comment by martenson** [comment]
thanks @mvdbeek
