### ISSUE TITLE
Installation of Python 2.7 on MacOS 10.10.2

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/tools-iuc#524]
Hello,

On MacOS 10.10.2, I have issue with installation of packages involving Python 2.7 (`package_python_2_7_10`, `package_python_2_7`): 

```
configure: error: cannot compute sizeof (size_t)
```

I tested it manual installation following instructions used in these wrappers and I have same errors.
I fixed it by adding `--enable-universalsdk=/` to configure step with manual installation.

Did anyone have this issue? 
I am not sure that the found command is "correct" and "universal". Do you have a better solution?

Bérénice

**Comment by bgruening** [comment]
Hi,

it seems to be MAC specific:

http://svn.python.org/projects/python/trunk/Mac/README

:(
