### ISSUE TITLE
Using one of pbed (plink) files without downloading it

### ISSUE THREAD

**Issue by shaldr23** [galaxyproject/tools-iuc#5289]
Hello!
Thank you for great work.
I wonder if there is any option to use just one file from pbed dataset without downloading it, e.g. if I want to use just .bim or .fam file in workflow. I haven't find instruments in Galaxy to break composite dataset into separate files. There are also no options in galaxy plink equal to "--make-just-bim" or "--make-just-fam".

**Comment by shaldr23** [comment]
Thank you for the answer.
"If you like I could transfer it." - It would be great!

**Comment by jennaj** [comment]
Xref https://github.com/galaxyproject/galaxy/issues/14050
