### ISSUE TITLE
Add tool virAnnot

### ISSUE THREAD

**Issue by marieBvr** [galaxyproject/tools-iuc#5322]
VirAnnot tool is a pipeline for automated viral diversity estimation and operational taxonomy units assignation for virome HTS.
This tools is associated with this publication: "The VirAnnot Pipeline: A Resource for Automated Viral Diversity Estimation and Operational Taxonomy Units Assignation for Virome Sequencing Data". Phytobiomes Journal 2019. https://doi.org/10.1094/PBIOMES-07-19-0037-A.
This tool was tested with planemo (planemo lint, planemo test and planemo serve).

**Comment by bgruening** [comment]
The tools will be installed on EU in a 7 days. Thanks @marieBvr
