### ISSUE TITLE
GTDB-Tk output files missing

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/tools-iuc#5344]
I am reviewing a ticket from a user who is missing output files from their GTDB-Tk jobs.
On closer inspection it seems that the wrapper might not be picking up some of the output files, due to an error in the `discover_datasets` declaration. To debug this, I have run `gtdb classify_wf` manually on the CLI and observed the outputs produced by the same run. The user reported that the `.tree` and `.fasta` outputs were missing, but I can see them in the output directory of my local run. It seems that the `output_dir` of `discover_datasets` is incorrect, leading to silent failure and empty collection outputs with `success` status.

Outputs declared in the wrapper:

https://github.com/galaxyproject/tools-iuc/blob/f173f58bc695c22364685c2ffbb9f3e95708f00f/tools/gtdbtk/gtdbtk_classify_wf.xml#L52-L65

`output_dir` as seen on the server: 

```
.
├── align
│   ├── gtdbtk.bac120.filtered.tsv
│   ├── gtdbtk.bac120.msa.fasta.gz
│   └── gtdbtk.bac120.user_msa.fasta.gz
├── classify
│   ├── gtdbtk.bac120.classify.tree.1.tree
│   ├── gtdbtk.bac120.classify.tree.3.tree
│   ├── gtdbtk.bac120.classify.tree.4.tree
│   ├── gtdbtk.bac120.classify.tree.6.tree
│   ├── gtdbtk.bac120.classify.tree.7.tree
│   ├── gtdbtk.bac120.summary.tsv
│   ├── gtdbtk.bac120.tree.mapping.tsv
│   └── gtdbtk.backbone.bac120.classify.tree
├── gtdbtk.bac120.summary.tsv -> classify/gtdbtk.bac120.summary.tsv
├── gtdbtk.json
├── gtdbtk.log
├── gtdbtk.warnings.log
└── identify
    ├── gtdbtk.ar53.markers_summary.tsv
    ├── gtdbtk.bac120.markers_summary.tsv
    ├── gtdbtk.failed_genomes.tsv
    └── gtdbtk.translation_table_summary.tsv
```

So it seems that the directory for `output_newick` and `output_fasta` are incorrect:

```xml
<!-- dir should be "output_dir/classify" -->
<discover_datasets pattern="(?P&lt;designation&gt;.+)\.tree" ext="newick" directory="output_dir"/>

<!-- dir should be "output_dir/align" -->
<discover_datasets pattern="(?P&lt;designation&gt;.+)\.fasta" ext="fasta" directory="output_dir"/>
```

**Comment by gregvonkuster** [comment]
Thanks for reporting this @neoformit - I think this should fix things up https://github.com/galaxyproject/tools-iuc/pull/5345.

**Comment by gregvonkuster** [comment]
This fix has not yet made it to the TS - https://asaim.readthedocs.io/en/latest/workflows.html

**Comment by mvdbeek** [comment]
I've uploaded this manually now, the linting passes locally with the latest tool-util + planemo release but I couldn't rerun the job, probably since it was too old at this point.
