### ISSUE TITLE
DESeq2: allow to pass factors and contrast definitions as files as an alternative to UI selections.

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/tools-iuc#5357]
My impression is that the current DESeq2 wrapper requires the user to provide the factors and contrasts desired as UI elements, which means that it is very difficult to re-use a workflow that includes DESeq2 because the layout of the workflow and its parameters will depend on the factors and contrasts definitions of each experiment. Towards uses of DESeq2 in a more production oriented manner (where you can re-apply a workflow regardless of the choice of factors and contrasts) it would be nice I think to be able to pass a file (YAML or JSON, possibly the first) to the DESeq2 wrapper as an alternative to the definition of factors and contrasts to the UI. Looking at the source code of the wrapper, it seems to me that the wrapper is already building such file, so I suspect it shouldn't be a lot of effort to optionally just pass it instead of building it there.

Is this an addition that would be welcomed? Thanks.

**Comment by pavanvidem** [comment]
Hi @pcm32 , 
Yes, that can be done and needed. The R script requires a  JSON of factors. Probably, the reason it was not implemented in the place is that it is one of the final steps in the analysis. But it is true we need something like that to make it workflow compatible. There are already ideas being collected [here](https://github.com/galaxyproject/tools-iuc/issues/3613). Let's move the discussion there?

**Comment by pcm32** [comment]
Thanks for pointing out the other issue, probably didn't come up on my search due to different capitalization. Will follow up there.
