### ISSUE TITLE
FASTQ to FASTA tool: gzipped output has fasta datatype

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/tools-iuc#5366]
Just popped this out of https://github.com/galaxyproject/tools-iuc/issues/5333.

This is for the fastx_toolkit tool: https://github.com/galaxyproject/tools-iuc/tree/main/tool_collections/fastx_toolkit/fastq_to_fasta

**Issue:** The tool attempts to infer the FASTA output compression (none, gz or bz) from the input datatype. The tool does compress the data correctly, but always sets the output datatype as `fasta` resulting in a broken/weird dataset.

I like the suggestion from @bernt-matthias :+1: 
> My preference would be to have zipping/unzipping controlled by a select with the following options:
>
> - same as input (default)
> - zipped
> - unzipped
>
> So we have the best of both worlds. Unfortunately this brings a bit of "heavy" logic for determining the output format. Could be implemented with tool provided metadata (galaxy.json).
> 
> Otherwise my (weak) preference would be "same as input"...
> 
> What about fastqsanger.bz
> 
> Is this a thing? :)

... so will implement that.

I'm working on a solution for inferring the output datatype that uses two outputs (one `fasta`, one `fasta.gz`) with a filter on each. Something like:

```xml
        <data name="output" format="fasta" metadata_source="input">
            <filter>
                compress_output == 'no'
                or compress_output == 'infer'
                and input.is_of_type('fasta', 'fastqsanger', 'fastqsolexa', 'fastqillumina')
            </filter>
        </data>
        <data name="output" format="fasta.gz" metadata_source="input">
            <filter>
                compress_output == 'yes'
                or compress_output == 'infer'
                and input.is_of_type(
                    'fasta.gz',
                    'fastqsanger.gz',
                    'fastqsolexa.gz',
                    'fastqillumina.gz',
                    'fastqsanger.bz2',
                    'fastqsolexa.bz2',
                    'fastqillumina.bz2',
                )
            </filter>
        </data>
```

Looks somewhat hacky to me, but it's the only way I could see to make the `format` attribute dynamic (unless there is some magic to be done with metadata as Matthias suggests). At least it's fairly readable.

**Comment by neoformit** [comment]
@bernt-matthias

**Comment by bernt-matthias** [comment]
Might work. Worth a try. Maybe you can simplify `input.is_of_type(...)` to `input.ext.endswith('.gz') or input.ext.endswith('.bz2')`

Alternatively `galaxy.json` like here: 
https://github.com/galaxyproject/tools-iuc/blob/41716a0929d9eb829e0772016ae9c24f24cf4b7e/tools/obitools/macros.xml#L36

**Comment by neoformit** [comment]
Will opt for the former as I think that's a bit more readable in the wrapper. Is the `galaxy.json` approach conventional? Haven't come across that before. Seems like that's the best approach for dynamic output metadata?

**Comment by bernt-matthias** [comment]
Maybe. Docs are missing. Not sure how this behaves in workflows. But any dynamic behavior might create trouble for workflows.
