### ISSUE TITLE
plasmidfinder database error of the database location

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/tools-iuc#5409]
Hello, 

After trying to re-use the plasmidfinder datamanager it seem to have a problem with path location.

- [X] Test the data manager seem okay to make the final json but no file pointed the expected location (to the latest or the 2.1 version of the database)
- [X] Test using planemo --> seem to work to create the json and add a string into the .loc file
- [X] Test the data manager manually using the python script works --> a database is downloaded and a json file is created with expected value
I don't understand why at the end of the process the path modified by galaxy don't exist

Do you have an idea ?

**Comment by bernt-matthias** [comment]
I just started a local galaxy instance and installed the data manager and the tool. Seemed to work well. 

The entry in the data table was created in:

```
tool-data/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_fetch_plasmidfinder/b56071bdecad/plasmidfinder.loc
```

and it was also found by the tool.

**Comment by pimarin** [comment]
thank's a lot @bernt-matthias  !
