### ISSUE TITLE
About INS annoation 

### ISSUE THREAD

**Issue by ClarenceHsiang** [galaxyproject/tools-iuc#5417]
![image](https://github.com/galaxyproject/tools-iuc/assets/57841470/b45dc0cf-c307-4b1c-b03b-c3b865f79eca)

Dear snpEff team,

I ran the INS annotation, and found most variants showed "." on INFO column.

Does that mean no annotated features?

Thank you

**Comment by bernt-matthias** [comment]
Please ask upstream at snpEff or maybe at https://help.galaxyproject.org/
