### ISSUE TITLE
Unused parameters in Scmap tools

### ISSUE THREAD

**Issue by hexhowells** [galaxyproject/tools-iuc#5444]
Some scmap tools in Galaxy have parameters which don't seem to be utilised. Additionally there are some parameters which could be included which can help get the best results from the tools.

### Select features

```Scmap select features``` includes the parameter **Number of features** which looking in scmap-cli ([here](https://github.com/ebi-gene-expression-group/scmap-cli/blob/develop/scmap-select-features.R#L21)) isn't being used in any of the code.

From the scmap [documentation](https://rdrr.io/bioc/scmap/man/selectFeatures.html) the parameter ```n_features``` should be used in the following way:
```R
selectFeatures(
    object, 
    n_features=500, 
    suppress_plot=FALSE
)
```

### Cluster projection

```Scmap cluster projection``` includes the parameter **threshold** which also seems to not be utilised in the scmap-cli tool [here](https://github.com/ebi-gene-expression-group/scmap-cli/blob/develop/scmap-scmap-cluster.R#L28)

Looking at the scmap [documentation](https://rdrr.io/bioc/scmap/man/scmapCluster.html) for that function the ```threshold``` parameter is used in the following way:
```R
scmapCluster(
    projection, 
    index_list, 
    threshold=0.7
)
```

### Cell projection

The ```Scmap cell projection``` tool could also include two additional parameters which aren't required but would aid in refining the results of the annotation. Specifically the function ```scmapCell2Cluster``` function (found [here](https://github.com/ebi-gene-expression-group/scmap-cli/blob/develop/scmap-scmap-cell.R#L103)) in the scmap-cli tool can take two additional parameters:
- ```w``` an integer specifying the number of nearest neighbours to find
- ```threshold``` the threshold which the maximum similarity between the query and a reference cell must exceed for the cell-type to be assigned

These parameters can be found in the documentation [here](https://rdrr.io/bioc/scmap/man/scmapCell2Cluster.html)

---

For context I am running these tools in a Galaxy workflow on the usegalaxy.eu server.
<br>

**Comment by pcm32** [comment]
@hexhowells unfortunately all of those tools have no one with funding to support them :-( and I left the EBI (where we had some involvement with them). I keep supporting the scanpy part there, but not the cell mapping part. What I could offer is that if you attempt a PR on that scmap-cli with your changes and the test pass without infinite re-arrangements of its conda dependencies, we could make a new release and then, if you help us with the few galaxy wrapper changes and they keep passing tests on the new scmap-cli release, we could push them to the toolshed via our CI.

I did try to make changes on scPred-cli to be able to help you on other issues (on my own time - I have no funding for this) but as you can see certain things with conda are not playing ball :-( there (see https://github.com/ebi-gene-expression-group/scpred-cli/pull/22).

**Comment by bgruening** [comment]
@pcm32 @hexhowells can this one be closed?

**Comment by hexhowells** [comment]
Yes! This has now been resolved here: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/pull/318
