### ISSUE TITLE
Issue with `biom` commands and QIIME

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/tools-iuc#551]
Hello,

I'm working on QIIME wrappers with dependency on `package_

When executing several QIIME commands implying `biom` command in Galaxy environment, I have this error:

```
Traceback (most recent call last):
  File "/path/to/venv/bin/pyqi", line 25, in <module>
    from pyqi.core.interface import get_command_names, get_command_config
ImportError: No module named pyqi.core.interface
```

There is no error with execution of same commands with command lines in same virtual environment.

Do you have any suggestion ?

Thanks,

Bérénice

**Comment by yhoogstrate** [comment]
@bebatut was this resolved?

**Comment by bebatut** [comment]
Probably yes :) Specially with conda now
We still need to work on QIIME wrappers
