### ISSUE TITLE
funannotate_annotate completes but wrapper fails to collect output 

### ISSUE THREAD

**Issue by TomHarrop** [galaxyproject/tools-iuc#5527]
We're sometimes getting the following error running funannotate_annotate on Galaxy Australia

```
[Oct 17 05:12 AM]: Funannotate annotate has completed successfully!

...

mv: target 'out.tbl' is not a directory
```

I guess this means there is more than one *.tbl file in `output/annotate_results`

https://github.com/galaxyproject/tools-iuc/blob/576069ce2296ef58daa8a4e03c993d5900608c4c/tools/funannotate/funannotate_annotate.xml#L78

We could just use a discover dataset (see [draft PR](https://github.com/galaxyproject/tools-iuc/compare/main...TomHarrop:tools-iuc:fa_collect?diff=split)) but I thought I'd check with the author @abretaud first.

Thanks!

**Comment by abretaud** [comment]
Hu strange, do you know what are the differences between the multiple tbl files? Not sure if they are all interesting

**Comment by TomHarrop** [comment]
I don’t know what they are, the failed jobs were on our production Galaxy and I haven’t found a way to reproduce it with a test dataset. I’ll keep trying and comment again if I find something.

**Comment by TomHarrop** [comment]
It's happening because funannotate doesn't clean up the `*part_n.tbl` files that are combined into the final tbl file.
```
$ ls -lh full_run_output/annotate_results/*.tbl
-rw-rw-r-- 1 tom tom 2.4M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_10.tbl
-rw-rw-r-- 1 tom tom 2.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_11.tbl
-rw-rw-r-- 1 tom tom 2.4M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_12.tbl
-rw-rw-r-- 1 tom tom 5.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_1.tbl
-rw-rw-r-- 1 tom tom 2.9M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_2.tbl
-rw-rw-r-- 1 tom tom 2.6M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_3.tbl
-rw-rw-r-- 1 tom tom 2.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_4.tbl
-rw-rw-r-- 1 tom tom 2.4M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_5.tbl
-rw-rw-r-- 1 tom tom 2.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_6.tbl
-rw-rw-r-- 1 tom tom 2.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_7.tbl
-rw-rw-r-- 1 tom tom 2.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_8.tbl
-rw-rw-r-- 1 tom tom 2.5M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.part_9.tbl
-rw-rw-r-- 1 tom tom  33M Oct 19 15:20 full_run_output/annotate_results/funannotate_subject.tbl
```

There are also multiple `*.part_n.sqn` files.

I assume this is because there are a lot of annotations, which will make it hard to test in the wrapper.

I think funannotate takes the species name from the genbank file and uses that for the output.

They not needed so I guess I could just delete the part files before the move, e.g.

```
find output/annotate_results 
-regex ".*part_[0-9]\+\.\(sqn\|tbl\)$"
-delete
```

@abretaud  Please let me know if there's a nicer way :)

**Comment by bernt-matthias** [comment]
Closed by https://github.com/galaxyproject/tools-iuc/pull/5528
