### ISSUE TITLE
phyml : command not found

### ISSUE THREAD

**Issue by SalihaZ** [galaxyproject/tools-iuc#5535]
#5532 phyml does not work on all the instances of galaxy and on galaxy planemo as well despite the validity of the planemo test. 
May be a problem with dependencies on the galaxy virtual env?

Actually when running phyml (on galaxy planemo and on other servers), I got the error: "command not found". 

I had to specify on the xml file, the path to the binary and it worked.

Is there another solution then adding the binary?

Thanks for your help

**Comment by bgruening** [comment]
@SalihaZ can you please submit an error report from the EU instance. This way I can have a look. phyml seems to be installed correctly. Maybe another dependency is missing. To investigate I need your error report from the EU instance.

On the test data and with defaul settings phyml works on EU. https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/phyml/phyml/3.3.20190909

**Comment by SalihaZ** [comment]
@bgruening  Thanks for your reply. I managed to get it working on the EU instance but I stilll have an errors on the France instance:  https://usegalaxy.fr/datasets/541fe965f404cd0c/error

**Comment by bgruening** [comment]
We will deploy a new version soon, see here: https://github.com/galaxyproject/tools-iuc/pull/5536

Can you maybe test this new version when it arrives in your favorite Galaxy instance?


ping @abretaud fyi ...

**Comment by bernt-matthias** [comment]
For problems with the French instance I would redirect you to https://community.cluster.france-bioinformatique.fr/c/galaxy

Last question from my side: how do you run planemo? Or is it working now?
