### ISSUE TITLE
DiffBind has repo installation problems triggering usage errors

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#555]
Error message:
> Error in library("DiffBind") : there is no package called 'DiffBind'

Tool Shed repo: https://toolshed.g2.bx.psu.edu/view/bgruening/diffbind/9e9f85c20d99

**Comment by nsoranzo** [comment]
@jennaj Please move this issue to https://github.com/bgruening/galaxytools

**Comment by bgruening** [comment]
@martenson could you send me the INSTALLTION.log from usegalaxy.org DEXSeq?

**Comment by martenson** [comment]
@bgruening dexseq (https://toolshed.g2.bx.psu.edu/view/iuc/dexseq/4ca0e679f21e) is not on Main

**Comment by bgruening** [comment]
Uh, ok this was about diffbind, sorry. Can you check diffbind, please?

**Comment by martenson** [comment]
@bgruening I think I fixed this on Main, @jennaj is testing it

**Comment by bgruening** [comment]
Even better! :)

**Comment by jennaj** [comment]
Still a a problem this morning, but I expect you all are working on it. I'll watch this ticket for updates and will test again when given a go. :)

**Comment by jennaj** [comment]
Just saw @nsoranzo's comments. Did this get migrated or is this the primary ticket (comments followed after he asked to move it to the other repo). Let me know if should still move. If primary, we should probably unclose it. Still active.

**Comment by nsoranzo** [comment]
I'd prefer to have the issue migrated where it belongs, especially if it needs code fixes.

**Comment by martenson** [comment]
@nsoranzo that is the thing, we do not know what is wrong with it
@jennaj do you know if it ever worked?

**Comment by bgruening** [comment]
It works here in FR. So you have any error message for me from the INSTALLATION log, usually one R package fails to install ...

**Comment by martenson** [comment]
@bgruening I re-installed all the dependencies and have I now have no errors in logs whatsoever

**Comment by martenson** [comment]
![screenshot 2016-01-26 11 26 52](https://cloud.githubusercontent.com/assets/1814954/12586802/b98caa12-c41f-11e5-93fe-5df2a03c6813.png)
![screenshot 2016-01-26 11 27 11](https://cloud.githubusercontent.com/assets/1814954/12586816/c1b24008-c41f-11e5-916d-176293c95a09.png)

**Comment by martenson** [comment]
I am trying 'repair' now
![screenshot 2016-01-26 11 29 07](https://cloud.githubusercontent.com/assets/1814954/12586896/0dcf3856-c420-11e5-88e3-95643cc4c790.png)

**Comment by martenson** [comment]
everything above turned green after repair, but still

Tool execution generated the following error message:
```Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
Error in library("DiffBind") : there is no package called 'DiffBind'```
The tool produced the following additional output:
```WARNING: ignoring environment value of R_HOME
[1] "en_US.UTF-8"```

**Comment by bgruening** [comment]
re-installing diffbind? Can you check if you see a diffbind folder in the tree. Or forward me the INSTALLTION.log please?

**Comment by martenson** [comment]
@blankenberg any luck with testing this?

**Comment by martenson** [comment]
According to recent testing by @jennaj this now works. Tool dependency reinstallation helped.

**Comment by jennaj** [comment]
Yes, all functions now correctly on http://usegalaxy.org. 

Users reading this ticket should re-run all prior failed jobs. If a new problem is uncovered, please send in a bug report from the error dataset via the "green bug" icon. 

Thanks all!
