### ISSUE TITLE
Text transformation with sed process fasta.gz as tabular 

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/tools-iuc#5555]
I noticed this strange behavior with the tool "Text transformation with sed ". When used on a fasta.gz files, it converts the fasta to tabular instead of using it as a fasta file. See screenshot : 

![Screenshot 2023-10-30 at 5 23 18 PM](https://github.com/galaxyproject/tools-iuc/assets/11195061/c81fa557-47ff-4425-b62e-11c9f0c19f63)

**Comment by mvdbeek** [comment]
That's a known Galaxy issue

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/issues/16383 is the same issue in a different flavor, and I'm sure we have other issues in Galaxy about the same thing
