### ISSUE TITLE
CI: planemo unable to detect python in conda environment at run time

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/tools-iuc#5585]
Related: https://github.com/galaxyproject/tools-iuc/pull/5519

I'm trying to get this R library to pass tests. They work fine locally via `planemo t sceasy.xml` but fail on the CI.

The library uses Reticulate.

**Reticulate** 

 Reticulate is an R library that allows one to interact with Python libraries. 

-   It works by [being told which Python to use](https://rstudio.github.io/reticulate/articles/versions.html#providing-hints).
    -   It does this (in order of discovery) by checking:
        1.  `RETICULATE_PYTHON` environment variable needs to be set.
            -   By default, r-reticulate installs its own python to `~/.virtualenvs/r-reticulate/`
            -   This works fine locally, but fails when run via github actions.
        2.  `RETICULATE_PYTHON_ENV` path to conda env
        3.  `use_python()`, `use_virtualenv()`, `use_condaenv()` (with required=TRUE)
        4.  `VIRTUAL_ENV` is defined
        5.  a venv, virtualenv, .venv, .virtualenv folder exists in that directory
        6.  `use_python()`, `use_virtualenv()`,  `use_condaenv()` (with required=FALSE)
        7.  `RETICULATE_PYTHON_FALLBACK` path to a python binary
        8.  `r-reticulate` is created in the absence of all
        9.  `PATH` use system python.

- Ideally, I'd just do something like  
       `<environment_variable name="RETICULATE_PYTHON">$CONDA_PREFIX/bin/python<environment_variable>`  
  and pass that in, but the conda prefix is not one of the  [reserved variables](https://docs.galaxyproject.org/en/release_20.05/dev/schema.html#reserved-variables) exposed to the developers, mostly because the name (e.g. "mulled-v2-123456") is not known until runtime.

-   One can get around this restraint by calling `RETICULATE_PYTHON="\$CONDA_PREFIX" R myscript` from within the `<command>` section, or retrieving the environment variable in R via `Sys.getenv("CONDA_PREFIX")`
     - This works fine in local tests
     - This fails miserably in CI

**Why does it fail in CI?**

After much probing (apologies if this counts as CI abuse), the conda command on the CI is:
 
```bash
/opt/conda/bin/mamba install \
   -c conda-forge -c bioconda -c defaults \
   r-sceasy=0.0.7 loompy=3.0.6 anndata=0.10.0 python=3.10 r-anndata=0.7.5.4 r-reticulate=1.32.0 \
   --strict-channel-priority \
   -p /usr/local \
    --copy --yes --quiet
```
which looks like it installs the entire environment to `/usr/local` , and indeed when I `echo "\$CONDA_PREFIX"` it does indeed evaluate to ` \"/usr/local\"`

- By this logic, the python binary should then be at location `/usr/local/bin/python`, but when I set this (via: `Sys.setenv("RETICULATE_PYTHON"=file.path(Sys.getenv("CONDA_PREFIX", "bin", "python"))`, it fails with the error:

         Job in error state.. tool_id: sceasy_convert, exit_code: 1, stderr: Loading required package: reticulate
         Error in normalizePath(conda, winslash = \"/\", mustWork = TRUE) : 
         path[1]=\"# cmd: /opt/conda/bin/mamba install -c conda-forge -c bioconda -c defaults r-sceasy=0.0.7 
                 loompy=3.0.6 anndata=0.10.0 python=3.10 r-anndata=0.7.5.4 r-reticulate=1.32.0 --strict-channel-priority
                 -p /usr/local --copy --yes --quiet\": No such file or directory 

This is a really weird message, since `normalizePath` is just a function in R to get absolute filename of a file, and it's telling me that it can't evaluate the path "#cmd blah blah entire mamba create script".

***Somehow `$CONDA_PREFIX/bin/python` is being replaced by a mamba command.***

How do I get around this?

**Comment by mtekman** [comment]
This could be a problem with mamba or reticulate: https://github.com/rstudio/reticulate/issues/1460

**Comment by bernt-matthias** [comment]
The CI uses a container, ie the conda env is created in the container. That's why it is `/usr/local`. 

What is the output of `which python ` if you put it in the command block. Can you execute this python, eg with `--version`? If yes then `export 
RETICULATE_PYTHON=\$(which python)` should be a workaround. 

But ideally you should try to avoid mixing R an python on my opinion.... Sounds horrible to me.

**Comment by mtekman** [comment]
Hey @bernt-matthias 

I've tried this before by the suggestion of @astrovsky01 over a zoom call, but to no avail. The problem seems to stem from the reticulate package itself, which checks for a conda environment by looking for the existence of `/usr/local/conda-meta`. 

But, from what I understand about biocontainers (**and do correct me if I'm wrong!**), the conda environment is built outside of the container, and then copied in, but without conda inside. 

So when reticulate tries to find conda/mamba it fails.

The current workaround I have found is to mask the function that detects conda, and then everything seems to work:

    library(reticulate)
    assignInNamespace("is_conda_python", function(x){ return(FALSE) }, ns="reticulate")
    reticulate:::use_python("/usr/local/bin/python")   ## failed on normalizePath error previously

This is a horrible hack, but it works.

Between biocontainers and reticulate, I'm not actually sure whose  problem this is. I believe reticulate is not incorrect in detecting a conda installation from the conda-meta directory.

**Comment by bernt-matthias** [comment]
This sounds like madness to me. `PATH` should be the only source of truth here. If different priorities are needed other paths can be prepended to `PATH`.

All this would be more than enough reason for me to try to avoid such a library...

**Comment by mtekman** [comment]
Well yeah, I'm not a fan of reticulate much myself, but SCEasy is a useful library for converting between single cell formats, and some formats just don't have R parsers.

I've tried appending to `PATH=$PATH:\$(which python)`  and also `RETICULATE_PYTHON=/usr/local/bin/python` but it just doesn't work. Existence of `/usr/local/conda-bin/history` seems to change the detected python.

**Comment by mtekman** [comment]
This turned out to be a problem with reticulate, interpreting the existence of `/usr/local/conda-meta` as  existence of a conda binary. This is not the case in biocontainers, which copy the conda env into a docker container, but do not actually install conda.

See: https://github.com/rstudio/reticulate/issues/1460#issuecomment-1803762448
