### ISSUE TITLE
Bugs from Jenkins+Planemo Testing

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#56]
## [rgDifferentialCount](https://github.com/galaxyproject/tools-iuc/blob/master/tools/differential_count_models/rgedgeRpaired_nocamera.xml)

@fubar2 

- also need to run through `xmllint --pretty 1`
- Given `rgedgeRpaired_nocamera.xml`, should `rgedgeRpaired.xml.camera` be `.camera.xml`?

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/var/lib/jenkins/galaxy/default/test/functional/test_toolbox.py", line 268, in test_tool
    self.do_it( td )
  File "/var/lib/jenkins/galaxy/default/test/functional/test_toolbox.py", line 70, in do_it
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 127: ordinal not in range(128)
```

## [gatk2_base_recalibrator](https://github.com/galaxyproject/tools-iuc/blob/master/tools/gatk2/base_recalibrator.xml)

@bgruening @nsoranzo 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/var/lib/jenkins/galaxy/default/test/functional/test_toolbox.py", line 268, in test_tool
    self.do_it( td )
  File "/var/lib/jenkins/galaxy/default/test/functional/test_toolbox.py", line 55, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - {u'type': u'error', u'data': {u'covariates': u"An invalid option was selected for covariates, u'ReadGroupCovariate', please verify."}}
```

## [gatk2_haploytype_caller](https://github.com/galaxyproject/tools-iuc/blob/master/tools/gatk2/haplotype_caller.xml)

```
RunToolException: Error creating a job for these tool inputs - {u'type': u'error', u'data': {u'dbsnp_rod_bind_type': {u'dbsnp_input_rod': u'History does not include a dataset of the required format / build'}}}
```

## bedtools_closestbed

@bgruening, strange error, IMO. It's bedtools 2.22 not 2.21, but that shouldn't cause a -3 all of a sudden.

```
JobOutputsError: History item  different than expected, difference (using diff):
( /var/lib/jenkins/workspace/IUC-Github/tools/bedtools/test-data/closestBed_result4.bed v. /tmp/tmpjL76HD/tmp/tmpHWM575closestBed_result4.bed )
--- local_file
+++ history_data
@@ -1,2 +1,2 @@
 chr1	10	20	a1	1	+	chr1	7	8	b1	1	+	-3
-chr1	10	20	a1	1	+	chr1	22	23	b2	2	-	3
+chr1	10	20	a1	1	+	chr1	22	23	b2	2	-	-3
```

For tests 3, 4 

## gemini

Just a missing datatype definition here...

gemini_windower, gemini_stats, gemini_roh, gemini_region, gemini_recessive_and_dominant, ....
```
RunToolException: Error creating a job for these tool inputs - {u'type': u'error', u'data': {u'infile': u'History does not include a dataset of the required format / build'}}
```

**Comment by fubar2** [comment]
@erasche - thanks!
rgDifferentialCount: On the non-xml ending file - I should remove it. xmllint done. 
Are tool dependencies installed/available during Jenkins tests?

**Comment by erasche** [comment]
Tool dependencies are not available yet, I've manually installed some of
the easy ones. Anything you want installed?

Hopefully work by @jmchilton on planemo will make this automatically
possible soon.
26. feb. 2015 11.28 skrev "Ross" <notifications@github.com>:

**Comment by fubar2** [comment]
There's a boatload of dependencies needed for all my tools - so they'll fail until those dependencies are installed - but IMHO it's not important enough to divert any effort to installing dependencies manually - let's wait until planemo can do it for us automagically.

**Comment by khoegenauer** [comment]
@erasche 
Would you mind sharing your (minimal) Jenkins config? I'd like the opportunity to break things, here in the privacy of the lab. 

I'm sure I could put it together on my own; but when I got started with PHP applications, http://jenkins-php.org/ made life much easier.

**Comment by erasche** [comment]
Sure, no problem. I'll get those pushed somewhere tomorrow morning for you.
10. apr. 2015 19.13 skrev "Kevin Hoegenauer" <notifications@github.com>:

**Comment by erasche** [comment]
@khoegenauer https://github.com/galaxy-iuc/jenkins-testing
