### ISSUE TITLE
package_samtools_1_3

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#561]
I started on this based on the samtools 1.2 package, but realised I don't have the infrastructure in place to properly test it.

As an aside, I found https://github.com/galaxyproject/planemo/issues/404

**Comment by bgruening** [comment]
@peterjc is a conda package also ok for you? 
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/samtools/meta.yaml

**Comment by peterjc** [comment]
I've not kept up to date on how conda packages fit into the Galaxy Tool Shed dependency chain, so maybe?

**Comment by peterjc** [comment]
I still need a ``package_samtools_1_3`` (or ``package_samtools_1_3_1`` would be fine) as we've not moved to Conda yet.

**Comment by yhoogstrate** [comment]
@peterjc why don't you move to conda instead? You can install a compiled binary of samtools 1.3.1 with just a one-liner..

**Comment by peterjc** [comment]
It isn't just me that needs to move to conda, its all the potential users of my tools ;)

Does the IUC / Galaxy Team have a feel for how many existing Galaxy instances are not yet using Conda, but still using the old XML installation recipes? From a tool author perspective by only using conda do we exclude a sizeable pool of potential users?

**Comment by nsoranzo** [comment]
More pushing them towards Conda than excluding them :)

I think we should not abandon existing package recipes, but I'm not investing time in new ones.

**Comment by martenson** [comment]
@peterjc starting with 17.01 all Galaxies will have Conda auto initiated at first startup

**Comment by peterjc** [comment]
I'll give up on a legacy Tool Shed package for samtools 1.3.x or later.

Would there be any reason to have these precompiled on https://depot.galaxyproject.org/package/linux/x86_64/samtools/ or has that project also taken a back-seat to bioconda?

**Comment by bgruening** [comment]
We don't use this project anymore for tool dependencies, but for building wheels. In same rare cases we use it to build binaries that are shipped then with Conda.
