### ISSUE TITLE
Error downloading from URL for hmmer

### ISSUE THREAD

**Issue by gad83** [galaxyproject/tools-iuc#563]
Hello,

I'm trying to install from Galaxy's Tool shed repository, the 'package_hmmer_3_1b2' tool dependencies.

However, I'm getting this error:
Error downloading from URL
ftp://selab.janelia.org/pub/software/hmmer3/3.1b2/hmmer-3.1b2.tar.gz:
<urlopen error ftp error: [Errno 110] Connection timed out>

Can someone please help me?

Salutations!

**Comment by nsoranzo** [comment]
HMMER download have moved to http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2.tar.gz

**Comment by erasche** [comment]
HMMER download moved to our galaxy cargo port. We should update the HMMER URL there.

**Comment by erasche** [comment]
Hi @gad83, the updated packages should be on the main toolshed now. Thanks for reporting this!

**Comment by martenson** [comment]
thanks @erasche !
