### ISSUE TITLE
Add tool: ChewBBACA

### ISSUE THREAD

**Issue by jessemartin132** [galaxyproject/tools-iuc#5638]
Hi there, i was wanting to know if it would be possible to add ChewBBACA to the galaxy EU server? 

Cheers,
Jesse

**Comment by bgruening** [comment]
Hi @jessemartin132!

We will put this on our list to work on. It might take some time, but we will inform you here.

Thanks for reaching out. 
Bjoern

**Comment by bgruening** [comment]
@jessemartin132 we could start working on it. Is there any subcommand(s) of ChewBBACA that you need most?

**Comment by jessemartin132** [comment]
@bgruening 
It would be helpful to have the following;
AlleleCall
AlleleCallEvaluator
PrepExternalSchema
JoinProfiles
DownloadSchema
LoadSchema
NSStats
ExtractCgMLST

Thank you once again
Jesse MArtin

**Comment by nilchia** [comment]
Hi, @jessemartin132!

The tools are now implemented into the galaxy.

Good luck with your analysis!

Cheers
Amirhossein

**Comment by bgruening** [comment]
The tools are available here: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/chewbbaca_createschema/chewbbaca_createschema/3.3.3+galaxy0

Happy research!
