### ISSUE TITLE
Bedtools genomeCoverageBed cannot find 'zero_regions'

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#57]
For version 2.22.0 of genomeCoverageBed, I see the Cheetah error `NotFound: cannot find 'zero_regions'`. This is because it lacks the `$report` prefix on the conditional variables.

Additionally the [validator](https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/genomeCoverageBed.xml#L46) for `unspecified_build` seems odd, I had to hack that out to get it to function.

**Comment by erasche** [comment]
Will make a PR once it's tested.

**Comment by bgruening** [comment]
Seems so, also for `scale`

**Comment by erasche** [comment]
yep, adding test cases for it now.

**Comment by blankenberg** [comment]
See also https://github.com/galaxyproject/tools-iuc/pull/54

**Comment by erasche** [comment]
@blankenberg thanks for that--that should've been merged a while ago. Now that I'm using the tools I suppose I'm qualified to review that PR! Merged, I'll push test cases once I figure out how genomecov will get the results I expect out of it.

**Comment by cheezemeister** [comment]
Has this issue been resolved?  I'm still getting this error using a small bacterial genome BAM with a custom build from a FASTA file in Galaxy.

**Comment by erasche** [comment]
It'll be in the test tool shed, I don't think anyone pushdd to the MTS yet.
12. mar. 2015 10.42 skrev "cheezemeister" <notifications@github.com>:
