### ISSUE TITLE
Names of log files from Trimmomatic don't correctly reflect inputs

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/tools-iuc#5703]
Issue with Trimmomatic output log files: 

Summary: can outputs be renamed differently? 

Running on Galaxy Australia, Trimmomatic version 0.36.6

Inputs: Paired-end reads: 2 collections (one of R1 files, one of R2 files)

Output required: Trimmed reads, and a collection of log files (not trimlog files). 

(Edited to update with a more general problem with output file naming, not only relevant to output log files)

Issue: when input files are named in the format `sample123_R1.fastqsanger` and `sample123_R2.fastqsanger`, output file names all take on the former name only, e.g. `sample123_R1.fastqsanger`

I think it would be better if outputs (where they refer to both R1 and R2 files) could be labelled without the R1 extension, such as `sample123.fastqsanger`

This would be clearer for the user, and also for downstream tools (such as plots in MultiQC, which are thus also labelled as being R1 files, when they are actually relating to both R1 and R2 files).

**Comment by AnnaSyme** [comment]
I don't know if this is related to the issue about element identifiers? https://github.com/galaxyproject/tools-iuc/issues/1595

posting in case it might be.

**Comment by bernt-matthias** [comment]
Guess the problem only occurs if `Paired-end (two separate input files)` is used (and not `Paired-end (as collection)`?

**Comment by AnnaSyme** [comment]
I'm not sure @bernt-matthias, but in this case yes the input is `Paired-end (two separate input files)` (except that each of these inputs is, itself, a collection). I'll give it a try with a single input collection.

**Comment by AnnaSyme** [comment]
Update: this tools is in a different repo - thanks @neoformit for pointing this out! - However it seems that it may be transferred here to the iuc quite sooon so perhaps any changes can take place here when it does.

**Comment by neoformit** [comment]
Looks like it's [merged to IUC](https://github.com/galaxyproject/tools-iuc/pull/5698) now, I will take a look at this today.

**Comment by neoformit** [comment]
Anna and I just had a chat about this. It seems more like a Galaxy Collections bug than tool wrapper issue:

![image](https://github.com/galaxyproject/tools-iuc/assets/42562517/0246723d-c231-48c0-9a3d-2b9f7e61d2ce)

1. The Trimmomatic job was submitted with paired reads in two collections: R1 and R2
2. The job outputs four collections: Unpaired R1, Unpaired R2, Paired R1, Paired R2
3. In the screenshot above the "Unpaired R2" collection is selected in the History
4. Note the input files `gah.fastqsanger` (R1) and `GSM461181_2.fastqsanger` (R2)
5. Now look at the first element in the History. It has been named after the first input dataset in the job (R1), and not after `${readtype.fastq_r2_in.name}` (highlighted in Dataset info panel) as I would have expected.
6. The result is that the `XXX_R2.fastqsanger` files are being named `XXX_R1.fastqsanger` which looks like a bug?

@bernt-matthias can you make any sense of this? Does Galaxy indeed infer collection element names from input dataset names? Does the tool developer have any control over this?

**Comment by bernt-matthias** [comment]
The tool wrapper is not responsible for naming collection elements. It just gets two datasets inputs and outputs 4 dataset outputs. Then Galaxy assigns this to the output collections, i.e. Galaxy maps the tool over the input collections. Without help Galaxy can't know from which of the two input collections the output collections should get their names. 

So I guess this should be fixed by setting `default_identifier_source` for the outputs (or refrain from using unpaired collection inputs/outputs for paired data). Didn't know about this one yet :) 

I think we should generalize this issue since there seem to be a few tools that have this problem (`grep "<data" tools -r | grep R1` or grep "<data" tools -r | grep forward` .. but this will contain some false positives) . Maybe `default_identifier_source` could be covered better in the docs somewhere?

For the example I was wondering if the two inputs are supposed to be paired? But I guess this was just for demonstrating the issue.

**Comment by neoformit** [comment]
I can only see one IUC example of `default_identifier_source` in [macs2_callpeak](../tree/main/tools/macs2/macs2_callpeak.xml#L258). And yes, the docs would not lead me to believe that this could be used to solve the current problem! It is a very abstract problem though and not easy to describe.

So the solution would be something like this? (Have not tested this yet)

https://github.com/neoformit/tools-iuc/blob/80d32a2f08e55424892f03db85d695fbede2dfb4/tools/trimmomatic/trimmomatic.xml#L225-L239

> For the example I was wondering if the two inputs are supposed to be paired? But I guess this was just for demonstrating the issue.

Yes they are paired datasets, we just renamed the first to "gah" so we could confirm that this is where the element identifier was coming from.

> I think we should generalize this issue

Yes, I suppose every tool that takes paired input files and maps them to paired outputs will suffer from this issue? Fixing all those would take some time!

**Comment by bernt-matthias** [comment]
> So the solution would be something like this?

That's how I imagined it. 

> (Have not tested this yet)

Guess this needs to be tested manually, e.g. with `planemo serve`. Guess a tool test can't cover this.

**Comment by neoformit** [comment]
Seems like Trimmomatic doesn't `planemo serve` very well - I got a 'not such command: java'. So I installed java into the conda env and then got:

```
Error: Unable to access jarfile /trimmomatic.jar
readlink: missing operand
```

I will test this on the Galaxy AU dev server instead.

**Comment by neoformit** [comment]
Tested on Galaxy AU dev (dev.gvl.org.au)

`default_identifier_source` seems to make no difference to the output collection element IDs:

```xml
        <data name="fastq_out_r2_paired" default_identifier_source="readtype|readtype.fastq_r2_in" label="${tool.name} on ${readtype.fastq_r2_in.name} (R2 paired)" format_source="fastq_r2_in">
            <filter>
                readtype['single_or_paired'] == "pair_of_files"
            </filter>
        </data>
```

**Comment by neoformit** [comment]
Tested on Galaxy AU dev (dev.gvl.org.au)

`default_identifier_source` fixes the output collection element IDs for R1/R1 outputs:

```xml
        <data name="fastq_out_r2_paired" default_identifier_source="readtype|fastq_r2_in" label="${tool.name} on ${readtype.fastq_r2_in.name} (R2 paired)" format_source="fastq_r2_in">
            <filter>
                readtype['single_or_paired'] == "pair_of_files"
            </filter>
        </data>
```

![image](https://github.com/galaxyproject/tools-iuc/assets/42562517/9f98b749-fd9e-4624-90f1-b38c81dd7ad0)

But I don't think there is a good way to name neutral output elements, like log messages? They should be like `GSM461181.fastqsanger`. This probably isn't syntactically correct but something like this might be a compromise?

```xml
default_identifier_source="readtype|fastq_r1 + readtype|fastq_r2"
```

**Comment by bernt-matthias** [comment]
Thanks for testing and opening a PR.

> But I don't think there is a good way to name neutral output elements, like log messages? They should be like `GSM461181.fastqsanger`. This probably isn't syntactically correct but something like this might be a compromise?
> 
> ```
> default_identifier_source="readtype|fastq_r1 + readtype|fastq_r2"
> ```

I guess this won't work. I would keep it simple. IMO users should just use paired collections anyway.
