### ISSUE TITLE
Update Dimet suite to 0.2.1

### ISSUE THREAD

**Issue by bdartigues** [galaxyproject/tools-iuc#5736]
Dimet gain one tool in the suite (bivariate analysis) and so upgrade to Minor version 0.2.1

**Comment by SaimMomin12** [comment]
Hi @bdartigues,

I noticed that DIMET has been upgraded by you to version **0.2.4** and merged in https://github.com/galaxyproject/tools-iuc/pull/5901.

Thank you for your valuable contribution! Given this, I believe we can close this issue.

Best regards,
Saim
