### ISSUE TITLE
package_infernal_1_1 and ftp link

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/tools-iuc#576]
Hello,

I have an issue with `package_infernal_1_1` installation from TTS and TS. 
FTP link (ftp://selab.janelia.org/pub/software/infernal/infernal-1.1.tar.gz)  seems dead.
In `tool_dependencies.xml` on current GitHub repository, FTP link was changed. 

Is it possible to push this version on TTS?

Thanks :)

**Comment by bgruening** [comment]
Updated :)

**Comment by bebatut** [comment]
Thanks :)
