### ISSUE TITLE
Shared Data, Data Libraries - Uncaught exception in exposed API method

### ISSUE THREAD

**Issue by gad83** [galaxyproject/tools-iuc#582]
Hello,

When I click on Shared Data --> Data Libraries a message appears: "Uncaught exception in exposed API method" (ref. picture attached).

Here is the logs:
`192.168.0.1 - - [29/Jan/2016:13:13:18 -0400] "GET /galaxy-prod/library/list HTTP/1.1" 200 - "http://my.galaxy.my.network.com:8081/galaxy-prod/library/list" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
192.168.0.1 - - [29/Jan/2016:13:13:19 -0400] "GET /galaxy-prod/api/datatypes?extension_only=False& HTTP/1.1" 200 - "http://my.galaxy.my.network.com:8081/galaxy-prod/library/list" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
192.168.0.1 - - [29/Jan/2016:13:13:19 -0400] "GET /galaxy-prod/api/genomes HTTP/1.1" 200 - "http://my.galaxy.my.network.com:8081/galaxy-prod/library/list" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
galaxy.web.framework.decorators ERROR 2016-01-29 13:13:19,311 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/home/galaxy/galaxy-prod/lib/galaxy/web/framework/decorators.py", line 260, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/home/galaxy/galaxy-prod/lib/galaxy/webapps/galaxy/api/libraries.py", line 43, in index
    libraries.append( self.library_manager.get_library_dict( trans, library ) )
  File "/home/galaxy/galaxy-prod/lib/galaxy/managers/libraries.py", line 189, in get_library_dict
    library_dict[ 'create_time_pretty'] = pretty_print_time_interval( library_dict[ 'create_time' ], precise=True )
  File "/home/galaxy/galaxy-prod/lib/galaxy/util/__init__.py", line 355, in pretty_print_time_interval
    time = datetime.strptime( time, "%Y-%m-%dT%H:%M:%S.%f" )
  File "/usr/lib64/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2015-01-30T13:37:07' does not match format '%Y-%m-%dT%H:%M:%S.%f'
192.168.0.1 - - [29/Jan/2016:13:13:19 -0400] "GET /galaxy-prod/api/libraries HTTP/1.1" 500 - "http://my.galaxy.my.network.com:8081/galaxy-prod/library/list" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
`
I believe it's a simple typo (because the T is next to the %)

![untitled](https://cloud.githubusercontent.com/assets/16885762/12684195/756006f4-c68b-11e5-97aa-2be47b2adac8.jpg)

**Comment by nsoranzo** [comment]
Hi @gad83,
this repository is for Galaxy tools maintained by the IUC team, while your issue is about a Galaxy bug. Can you please open a new issue on https://github.com/galaxyproject/galaxy/issues/new ?

Thanks for using Galaxy!
