### ISSUE TITLE
MACS2 Callpeak has a few wrapper/option problems

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#583]
**MACS2 Callpeak**

_Problem: Wrapper option *_--foldenrichment*\* not recognized? 

tool id: toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak/2.1.0.20140616.0
tool version: 2.1.0.20140616.0
job pid or drm id: 5896379.roundup
job tool version: macs2 2.1.0.20140616
## Fatal error: Exit code 2 ()

job stdout:
usage: macs2 [-h] [--version]
     {callpeak,diffpeak,bdgpeakcall,bdgbroadcall,bdgcmp,bdgdiff,filterdup,predictd,pileup,randsample,refinepeak}
             ...
macs2: error: unrecognized arguments: --foldenrichment 4

**Comment by lparsons** [comment]
This is implemented in the wrapper as a selection between p-value, q-value, and fold enrichment for peak detection. However, looking at the docs for MACS2, p-value and q-value appear to be mutually exclusive options as cutoffs for peak detection, while fold enrichment is implemented as a post-processing step only to filter out peaks.

Thus, I would propose that fold enrichment be moved to a separate parameter in the "Advanced" section and set to the default of 1.0. Also, it should be ` --fe-cutoff FECUTOFF `.

On a related note, I don't see why `--call-summits` is only available when ``broad-peaks` is not selected.

**Comment by jennaj** [comment]
@lparsons Agree, what you outline would be a better parameter model on the tool form

**Comment by jennaj** [comment]
@lparsons Is anyone working on this? I searched and couldn't the relevant pull request if so. If you know, and have time and can link it in here, would really appreciate it :)

**Comment by lparsons** [comment]
@jennaj I don't think anyone is actually working on this at the moment. I'm keeping track of this as well, and will try to help if/when I can. Thanks for staying on top of it.

**Comment by bgruening** [comment]
@lparsons are you working on this or planning to work on it? I have created a new conda package just in case you want to bump the version as well.
https://github.com/bioconda/bioconda-recipes/pull/1499

**Comment by jennaj** [comment]
Still an issue users are encountering. Any updates you all can share? Thx!

**Comment by jennaj** [comment]
Fixed in version 2.1.1.20160309.0, closing
