### ISSUE TITLE
bedtools tool lineage not correct

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#584]
After updating bedtools to version 2.24 I see issues with various tools (e.g. bedtools_bamtobed). The tool lineage shows:
```
bedtools_bamtobed
toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.19.0
toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.24.0
```
separately from:
`toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.22.0`

**Comment by bgruening** [comment]
@lparsons I have reset all metadata in the TS can you get the newest metadata in you Galaxy instance and see if this fixes your problem?

**Comment by nsoranzo** [comment]
I also had this problem and already resetted the metadata few days ago, sorry I missed this bug report. It's fixed for our server after running "Set tool versions".

**Comment by lparsons** [comment]
Fixed for me too after running "Set tool versions"
