### ISSUE TITLE
Define Repmatch tool's input format on the tool form and possibly filter types in input section

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#586]
**Usage Issue** 

Knowing what input format is accepted by Repmatch has been confusing for users. One has to know what the tool is already and general usage to use the tool in Galaxy effectively. Or, they to know how to go about examine the repo directly or in the tool shed to determine the type in the code.

**Tool**

 https://toolshed.g2.bx.psu.edu/view/iuc/repmatch_gff3/a072f0f30ea3

*_Wrapper display name *_ 

RepMatch Match paired peaks from two or more replicates (Galaxy Version 1.0.0)

**Enhancement Lobby**

The remainder of the tool documentation is one the best, so this may seem to be a small cosmetic change but a is actually very important for user-friendliness of all experience levels. (No one knows all tools in detail!)

Needs this at a minimum:
1. Add in help about the input type in details - gff is clear with link or example format on tool from.

Then, optional (and not always desirable), an ancillary request:
1. Filter the input dataset choices by datatype assignment.

**Code**

<img width="724" alt="repmatch_gff3_1" src="https://cloud.githubusercontent.com/assets/8999735/12935318/c8843fa0-cf49-11e5-96eb-ee2762807d0f.png">
<img width="816" alt="repmatch_gff3_2" src="https://cloud.githubusercontent.com/assets/8999735/12935322/cc491336-cf49-11e5-9853-6427f4ad2b27.png">

**Comment by bernt-matthias** [comment]
hey @jennaj happy with this: https://github.com/galaxyproject/tools-iuc/issues/586 ?

Not sure what you meant with "Filter the input dataset choices by datatype assignment."
