### ISSUE TITLE
package_fontconfig_2_11_1 can't be installed on CentOS 6.6

### ISSUE THREAD

**Issue by methylome** [galaxyproject/tools-iuc#587]
Hello,

CentOS 6.6 has zlib-1.2.3 but this package requires zlib-1.2.3.4.
fcfreetype.c:70:2: warning: #warning "No FT_Get_BDF_Property: Please install freetype 2.1.4 or later"
fcfreetype.c:74:2: warning: #warning "No FT_Get_PS_Font_Info: Please install freetype 2.1.1 or later"
fcfreetype.c:1833:2: warning: #warning "No FT_Get_Next_Char: Please install freetype version 2.1.0 or newer"
fcfreetype.c:895: warning: 'FcStringIsConst' defined but not used
fcfreetype.c:2116: warning: 'FcHashGlyphName' defined but not used
test-migration.o: In function `fc_mkdtemp':
/home/galaxy/dev/database/tmp/tmp-toolshed-mtdmJphM_/fontconfig-2.11.1/test/test-migration.c:44: warning: the use of `mktemp' is dangerous, better use `mkstemp'
/home/galaxy/dev/database/tmp/tmp-toolshed-mtdmJphM_/fontconfig-2.11.1/fc-cache/.libs/lt-fc-cache: /lib64/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /home/galaxy/dev/software/libpng/1.6.7/iuc/package_libpng_1_6_7/7da8c5e453cc/lib/libpng16.so.16)
make[2]: *** [install-data-local] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

Thanks,
Justin.

**Comment by methylome** [comment]
I've fixed this problem by adding the dependency on package_zlib_1_2_8 and package_libpng_1_6_7.

**Comment by mvdbeek** [comment]
That should have already been fixed with https://github.com/galaxyproject/tools-iuc/pull/578 ... .
What was the context in which fontconfig got installed?
The current version on the toolshed is fetching libpng at revision 588666932a32, which includes a dependency on zlib.
Maybe we have to do a metadata reset on whatever causes fontconfig to be installed.

**Comment by methylome** [comment]
Yes, package_libpng_1_6_7 has no problem, but package_fontconfig_2_11_1 can't use zlib_1_2_8 and libpng_1_6_7 during installation. I thought it's because there is no configuration in tool_dependencies.xml in package_fontconfig_2_11_1. I've attached the modified file.

Thanks,
Justin.
[tool_dependencies.xml.gz](https://github.com/galaxyproject/tools-iuc/files/126490/tool_dependencies.xml.gz)

**Comment by mvdbeek** [comment]
If you want, you can do a Pull request with your modification, I would accept this.
I can also do this for you, if you prefer.

**Comment by methylome** [comment]
If it's helpful, I'd like to share my modification. When I clone this repository, the source file packages/package_fontconfig_2_11_1/tool_dependencies.xml is more different from I expected. Do you still want to push it?

**Comment by bgruening** [comment]
@methylome please share and we can do the rest. I'm wondering if we just need to sync this github account with the TS if you have seen larger differences.

**Comment by methylome** [comment]
I got it. Thanks.

**Comment by htc502** [comment]
got the same problem. need help too..

**Comment by bgruening** [comment]
@methylome @mvdbeek is this one resolved? @htc502 can you please test the latest version from the main TS?

**Comment by methylome** [comment]
@mvdbeek yes.
