### ISSUE TITLE
package ncurses 6.0 download url broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#589]
reported here: https://github.com/galaxyproject/galaxy/issues/1720 by @mgangel

dead link: ftp://invisible-island.net/ncurses/current/ncurses-6.0-20150725.tgz

https://github.com/galaxyproject/tools-iuc/blob/86a44bf15f8184b690ee1af98aa1d5f86ad2fb3d/packages/package_ncurses_6_0/tool_dependencies.xml#L6

**Comment by bgruening** [comment]
@mgangel can you please check if this is fixed with the latest update? I uploaded the newest package to the Tool Sheds.

Thanks for reporting!

**Comment by mgangel** [comment]
Works perfectly! Thank you!

**Comment by martenson** [comment]
thanks @bgruening !
