### ISSUE TITLE
package_matplotlib_1_2 cannot find numpy dependency

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#59]
I tried to install `package_matplotlib_1_2` on test.galaxyproject.org but did not succeed in spite of the package having numpy 1.7 in set_environment_for_install. Scipy seems to install correctly and it depends on the same numpy version.

```
install_environment.STDOUT DEBUG 2015-02-25 16:30:19,819 ============================================================================
install_environment.STDOUT DEBUG 2015-02-25 16:30:19,821                         * matplotlib.
basedirlist is: ['/usr/local', '/usr']
BUILDING MATPLOTLIB
            matplotlib: 1.2.1
                python: 2.7.5 (default, Oct 17 2013, 10:00:15)  [GCC 4.4.7
                        20120313 (Red Hat 4.4.7-3)]
              platform: linux2
REQUIRED DEPENDENCIES
                 numpy: no
============================================================================
                        * You must install numpy 1.4 or later to build
                        * matplotlib.
```

**Comment by bgruening** [comment]
TTS has no tests for it but TS reports all tests passing. You are installing from the TS?

**Comment by martenson** [comment]
@bgruening  Yeah, I am always using the Main TS.

**Comment by bgruening** [comment]
I tried it in docker and it worked for me. This is strange @martenson. Any recent Galaxy bug? I currently rebuild all docker containers to get the latest version and test again.

**Comment by martenson** [comment]
I tried again and succeeded. As usual I do not know why.

 Thanks to this `deeptools` is fully installed including all its dependencies. Thanks for help guys.
