### ISSUE TITLE
Add Sage (search engine) on usegalaxy.eu

### ISSUE THREAD

**Issue by sciordia** [galaxyproject/tools-iuc#5960]
I was wondering if it would be possible to add a new proteomics tool (link below) to the public [usegalaxy.eu](https://usegalaxy.eu/) server that is associated with the protein identification using a FASTA Database?.

SageAdapter

[Sage: The fastest search engine 1](https://github.com/lazear/sage)

Sage is well-integrated into the open-source proteomics ecosystem, e.g. in the OpenMS package (which is already partly integrated in useGalaxy).

It would be great if you could add it to the public server.

Thank you very much.

Bests,
Sergio

**Comment by bernt-matthias** [comment]
This should come with https://github.com/galaxyproteomics/tools-galaxyp/pull/697 which is unfortunately delayed...

**Comment by sciordia** [comment]
Thank you very much @bernt-matthias for including my request. I really appreciate it.

Could you let me know when you release the next release of OpenMS, please?.

Thanks again.

Best regards,
Sergio

**Comment by bernt-matthias** [comment]
Will try, but you could also subscribe to the linked PR.

**Comment by sciordia** [comment]
Thank you @bernt-matthias , you are right it is easier if I subscribe. Done.

Since I have your attention, hehe, I wanted to make a second suggestion. The SAGE data output can be processed (re-scoring) by both the percolator tool (already included in galaxyp) and mokapot. The latter re-scoring tool is becoming fashionable in proteomics.

Here is the link: https://mokapot.readthedocs.io/en/latest/

Do you think you could also include it in the next release, please?. If necessary I could create a new post.

That would be great but obviously I leave it up to you.

Thanks again for everything.

Best regards,
Sergio
