### ISSUE TITLE
Maaslin2: error during version update

### ISSUE THREAD

**Issue by renu-pal** [galaxyproject/tools-iuc#5988]
@bgruening How can I add something to dependencies as suggested in the following :

https://github.com/bioconda/bioconda-recipes/pull/46915#issuecomment-2093515652

**Comment by bernt-matthias** [comment]
@renu-pal I guess you should add it to the requirements in the bioconda recipes / pin the version.

**Comment by bgruening** [comment]
Please try again. A new version of r-glmmtmb has been released.

**Comment by renu-pal** [comment]
@bgruening What do I need to do to pull this release into my branch.

**Comment by paulzierep** [comment]
Hi @renu-pal, planemo will use the conda env you have locally on your machine, if the version is not bumped, to use the new env, that hopefully has the new version of r-glmmtmb you need to manually remove the conda env, e.g. use 
```
conda env list
```
Look for something like: `__maaslin2@1.16.0             /home/paul/miniconda3/envs/__maaslin2@1.16.0`

Remove that env with: `conda remove --name __maaslin2@1.16.0 --all`
Then run planemo again and it should be build with the new  r-glmmtmb release

Now that I think about it, how can one get the newest biocontainer in such as case ? I guess for this we need to bump the build number ? @bernt-matthias ?

**Comment by bernt-matthias** [comment]
> Now that I think about it, how can one get the newest biocontainer in such as case ? I guess for this we need to bump the build number 

Yep, container needs to be rebuilt first. You can test first with conda or directly bump the conda recipe and test with the docker container in the artifacts, see docs [here](https://planemo.readthedocs.io/en/latest/writing_how_do_i.html#test-tools-against-a-package-or-container-in-a-bioconda-pull-request).
