### ISSUE TITLE
package_samtools_0_1_19 installation fails

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#60]
On test.galaxyproject.org

```
phase.o: In function `loadpos':
/galaxy-repl/test/scratch/tmp-toolshed-mtdQrCRU1/samtools-0.1.19/phase.c:475: undefined reference to `gzopen64'
bedcov.o: In function `main_bedcov':
/galaxy-repl/test/scratch/tmp-toolshed-mtdQrCRU1/samtools-0.1.19/bedcov.c:69: undefined reference to `gzopen64'
libbam.a(bam_import.o): In function `__bam_get_lines':
/galaxy-repl/test/scratch/tmp-toolshed-mtdQrCRU1/samtools-0.1.19/bam_import.c:76: undefined reference to `gzopen64'
libbam.a(bam_import.o): In function `sam_open':
/galaxy-repl/test/scratch/tmp-toolshed-mtdQrCRU1/samtools-0.1.19/bam_import.c:472: undefined reference to `gzopen64'
libbam.a(bam_import.o): In function `sam_header_read2':
/galaxy-repl/test/scratch/tmp-toolshed-mtdQrCRU1/samtools-0.1.19/bam_import.c:126: undefined reference to `gzopen64'
libbam.a(bedidx.o):/galaxy-repl/test/scratch/tmp-toolshed-mtdQrCRU1/samtools-0.1.19/bedidx.c:107: more undefined references to `gzopen64' follow
collect2: ld returned 1 exit status
make[1]: *** [samtools] Error 1
make: *** [all-recur] Error 1
```

**Comment by erasche** [comment]
looks like missing zlib, which definitely should be available. Huh.

**Comment by martenson** [comment]
is it possible we are missing zlib on Test @natefoo ?

**Comment by erasche** [comment]
shouldn't be--that's a [required](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_samtools_0_1_19/tool_dependencies.xml#L6), [packaged](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_zlib_1_2_8/tool_dependencies.xml) dependency.

**Comment by martenson** [comment]
Yeah it is installed on test and reports all fine.

**Comment by bgruening** [comment]
I will copy and paste the devteam package to the IUC package to get this resolved. The TTS and the TS seems to be fine with the packages. Don't know what going on in test.galaxyproject.org. Maybe this is an systematic error. Resetting metadata can help in some cases.

**Comment by bgruening** [comment]
I have copied the content of the devteam repository to the IUC one and pushed it into TTS.

**Comment by bgruening** [comment]
If this is ok with you, we can move it to MTS and close this issue.

**Comment by martenson** [comment]
It is fine with me. Sorry for the delay. I will test once in MTS.

**Comment by erasche** [comment]
@bgruening pushed to MTS?

**Comment by erasche** [comment]
(How I wish I could write a jenkins task to check for phrases "push X to MTS"...that'd solve this nicely)

**Comment by martenson** [comment]
I am pushing it now.

**Comment by martenson** [comment]
It seems there is a bug. By updating the package_samtools_0_1_19 we got rid of ncurses and zlib tool dependencies but even after uninstall&install of the newest package revision they are showing up as missing dependencies (i.e. the record for the dependency in the DB is preserved).
![screenshot 2015-02-26 15 15 37](https://cloud.githubusercontent.com/assets/1814954/6400951/938afda2-bdca-11e4-82a3-382b3cef7a08.png)

**Comment by martenson** [comment]
Thanks for the help guys.

**Comment by bgruening** [comment]
I have resetted the metadata maybe this helps?
