### ISSUE TITLE
SnpEff tool form passes deprecated options to command line

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#604]
**Repo**

https://toolshed.g2.bx.psu.edu/view/iuc/snpeff/500832f27cbc

**Issue**

Deprecated options are still available on the tool form. This results in errors when used.

**Change for deprecated options (may be others)**

https://github.com/galaxyproject/tools-iuc/pull/273

**Example Error (many non-default options result in tool failure)**

<img width="444" alt="screen shot 2016-02-18 at 9 02 02 am" src="https://cloud.githubusercontent.com/assets/8999735/13151277/55bc323a-d61e-11e5-8319-3ba10dff772b.png">

> Fatal error: Exit code 1 (Error)
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch
> Error        :	Unknow option '-snp'
> Command line :	SnpEff  -i vcf -o vcf **-snp** -stats /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat AgamP3.22 /gala

> snpEff version SnpEff 4.0e (build 2014-09-13), by Pablo Cingolani
> Usage: snpEff [eff] [options] genome_version [input_file]

**History with testing**

 https://usegalaxy.org/u/jen/h/agamp3-snpeff-test

**Comment by jj-umn** [comment]
@jennaj   I've gone through the snpEff wrapper and put in extensive changes for SnpEff version 4.0
I'll update the toolshed when I've tested it more.

**Comment by jj-umn** [comment]
@jennaj  Updated toolshed

**Comment by jennaj** [comment]
Great! Thanks @jj-umn 

@davebx any chance would could put this on test for testing? lmk when ready

**Comment by martenson** [comment]
@jennaj iuc/snpeff has been updated on Main
please close when tested

**Comment by jennaj** [comment]
Thanks & will do, testing in progress.

**Comment by jennaj** [comment]
Works now on Main, thanks

**Comment by martenson** [comment]
thanks @jennaj
