### ISSUE TITLE
Gemini load issues (0.18.1.0)

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/tools-iuc#607]
@bgruening 
Hi Björn,

I noticed the latest version of the gemini load tool puts the wrong version number in the metadata of the sqlite db. This causes all other tools to "not see" the created database. Could you fix this please?

I think the issue is within the package installer, when I do
<pre>
<em>tool-dependency-dir</em>/gemini/0.18.1/iuc/package_gemini_0_18_1/b90d6db50590/bin/gemini
 --version 
</pre>

I get 0.18.0 instead of 0.18.1

thanks
M

**Comment by bgruening** [comment]
Oh no, this is then a gemini bug :(

**Comment by bgruening** [comment]
@matthdsm actually mine is returning /usr/local/tools/gemini/0.18.1/iuc/package_gemini_0_18_1/be869e11582f/bin/gemini --version

There is a newer version of the package in the repo. Can you try this one?

**Comment by matthdsm** [comment]
I was still using the version from the TTS, I reïnstalled everything and now the version output checks out. Seems like it was a local issue, but it's fixed now.

Thanks for looking into it, I'll close the issue now.
Matthias
