### ISSUE TITLE
Krakentools - Combine has the Galaxy Directory labelled as the sample name in the output file - improvement required.

### ISSUE THREAD

**Issue by mthang** [galaxyproject/tools-iuc#6081]
@EngyNasr @paulzierep 
 My colleague has included the Krakentools combine in the workflow, but the sample names are converted to the Galaxy directory as the sample names. Then, the Galaxy directory in the sample column got propagated to the downstream steps. It would be great if the output file produces the sample name instead of the Galaxy directory. I can fix this by adding a few lines to the wrapper if that's ok. 
https://github.com/galaxyproject/tools-iuc/blob/ab38fa3d5ec06729c1efa86240ec57b8143b21ed/tools/krakentools/combine_kreports.xml#L10
![Krakentool_combine_output](https://github.com/galaxyproject/tools-iuc/assets/19919190/891efe0b-3e95-4a9f-b9f6-d0b7155c0a61)

**Comment by mthang** [comment]
Done

**Comment by bgruening** [comment]
Thanks @mthang
