### ISSUE TITLE
Use samtools -@ for multithread compression

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#614]
bowtie2, hisat2 and star are pretty fast nowadays.
I haven't done the exact benchmarking, but when running hisat2 and allocating a reasonable amount of GALAXY_SLOTS (we use 8), most time is spent in samtools. Is there any opposition to introducing -@ GALAXY_SLOTS in the [samtools view](https://github.com/galaxyproject/tools-iuc/blob/master/tools/hisat2/hisat2.xml#L86) step?
ping @davebx @bgruening @yhoogstrate

**Comment by bgruening** [comment]
I see no disadvantages in using it. Maybe we should use sambamba instead of samtools if speed matters so much?

xref: https://github.com/bgruening/galaxytools/pull/285

**Comment by mvdbeek** [comment]
We can get a nice speedup by not compressing in the view, but in the sort step, as point out in `samtools view --help`:
```
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam | samtools view -bS - | samtools sort - -@1 -o hsbam > standard.bam

real	0m1.274s
user	0m1.292s
sys	0m0.036s
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam | samtools view -u - | samtools sort - -@1 -l 6 -o hsbam > l6.bam

real	0m0.856s
user	0m0.840s
sys	0m0.036s
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ ls -l
total 1409716
-rw-rw-r-- 1 marius marius   19648618 févr. 24 19:03 100k.sam
-rw-r----- 1 marius marius 1418464214 févr. 24 19:02 Galaxy392-[HISAT2_on_data_5_and_data_388].bam
-rw-rw-r-- 1 marius marius    2708323 févr. 24 19:31 l6.bam
-rw-rw-r-- 1 marius marius    2708323 févr. 24 19:30 standard.bam
```
Compressing with 2 threads also gives a speedup:
```
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam | samtools view -u - | samtools sort - -@2 -l 6 -o hsbam > l6.bam

real	0m0.550s
user	0m0.776s
sys	0m0.064s
```
More than that doesn't really help:
```
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam | samtools view -u - | samtools sort - -@3 -l 6 -o hsbam > l6.bam

real	0m0.523s
user	0m0.856s
sys	0m0.056s
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam | samtools view -u - | samtools sort - -@4 -l 6 -o hsbam > l6.bam

real	0m0.501s
user	0m0.900s
sys	0m0.072s

```

We can also completely skip the view:
```
(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam  | samtools sort - -@2 -l 6 -o hsbam > l6.bam

real	0m0.524s
user	0m0.732s
sys	0m0.028s

(.venv)marius@iMac-ubuntu:~/src/samtools_sambamba_comp$ time cat 100k.sam  | samtools sort - -@4 -l 6 -o hsbam > l6.bam

real	0m0.420s
user	0m0.828s
sys	0m0.048s

```

I didn't get sambamba to work with piped sam input, I'm not sure this is a supported pattern,
but if anyone know how to do this I'd be interested to compare.

Let's see how that translates into the hisat2 wrapper. I guess.

**Comment by yhoogstrate** [comment]
The STAR wrapper has this option already built-in for exactly the same reason but I am not sure what the gain is. I have heard really positive feedback on sambamba but I think we should do a bit benchmarking before making a definitive choice. If I remember correctly @lparsons is involved in sambamba and maybe he can help us out (upstream) if we get stuck on using pipes.

**Comment by mvdbeek** [comment]
well, I already got a 2.5X speedup in the tests above, using just 2 threads, so as long as samtools doesn't trail behind, performance is not that critical. It's just that I'm seeing hisat2 run ~ 40 minutes, and then I'm waiting 20 minutes for samtools to catch up.
If the above benchmarks are indicative of real performance, 2 threads should be enough to avoid this, so I would prefer not exchanging dependencies on existing aligner wrappers.

**Comment by yhoogstrate** [comment]
:+1:

**Comment by bgruening** [comment]
@davebx thanks for the patch and @mvdbeek for the idea and the benchmarks.
