### ISSUE TITLE
Kraken Issues

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/tools-iuc#615]
- [x] Reads missing from classify output: https://github.com/DerrickWood/kraken/pull/37
- [x] Error in kraken-report when 0 reads have been classified: https://github.com/DerrickWood/kraken/pull/38

**Comment by blankenberg** [comment]
xref https://github.com/galaxyproject/tools-devteam/pull/352

**Comment by bgruening** [comment]
This should be fixed.
