### ISSUE TITLE
Enhancement: Add in server indexed reference genomes to "basil Breakpoint detection, including large insertions"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#6173]
toolshed.g2.bx.psu.edu/repos/iuc/basil/basil/1.2.0
https://toolshed.g2.bx.psu.edu/view/iuc/basil/e6ef29001647

The forum currently expects the reference genome to be a fasta in the history (only). This creates friction for people who used a server indexed reference in upstream steps. A toggle to choose between a server index or the history would be great.

**Comment by bgruening** [comment]
This should be fixed with the next update
