### ISSUE TITLE
clair3 breaks galaxy due to discrepancy in all_fasta columns

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/tools-iuc#6211]
Galaxy Australia's staging server failed to restart this morning. This entry in the shed_tool_data_table_conf.xml

```
    <table name="all_fasta" comment_char="#">
        <columns>value, name, path</columns>
        <file path="/mnt/galaxy/tool-data/shed_tool_data/toolshed.g2.bx.psu.edu/repos/iuc/clair3/c8ba8286e7c0/all_fasta.loc"/>
        <tool_shed_repository>
            <tool_shed>toolshed.g2.bx.psu.edu</tool_shed>
            <repository_name>clair3</repository_name>
            <repository_owner>iuc</repository_owner>
            <installed_changeset_revision>c8ba8286e7c0</installed_changeset_revision>
        </tool_shed_repository>
    </table>
```

has the wrong columns in `columns`. Each other entry for all_fasta has `<columns>value, dbkey, name, path</columns>` and galaxy would not start until this new entry was commented out.

**Comment by bernt-matthias** [comment]
I would consider this a bug in galaxy.

**Comment by bernt-matthias** [comment]
> We can't really do anything there in Galaxy, failing to boot is probably the correct thing to do.

We could just fail to load the tool, like we do for xml parsing errors, etc.

**Comment by mvdbeek** [comment]
This is a server misconfiguration that might have a huge impact, this needs to be fixed, failing is the right thing to do.

**Comment by wm75** [comment]
is all_fasta even the right table to use? wouldn't fasta_indexes be the correct one?

**Comment by bernt-matthias** [comment]
Still don't get why this break on au and not eu?

**Comment by mvdbeek** [comment]
`all_fasta` is for fasta files, `fasta_indexes` would be for `.fai` files as produced by `samtools faidx`

**Comment by wm75** [comment]
> `all_fasta` is for fasta files, `fasta_indexes` would be for `.fai` files as produced by `samtools faidx`

https://github.com/galaxyproject/tools-iuc/blob/6da96d865a3a557cfa3ad09e1cfa830519e73748/tools/clair3/clair3.xml#L20

yes, that's why

**Comment by mvdbeek** [comment]
I guess the idea was that all_fasta is more widely populated ? I have no particular problem with this, of course it would be a little faster to go with fasta indexes.

**Comment by wm75** [comment]
> Still don't get why this break on au and not eu?

so for sure all three versions of the tool that we have installed on .eu carry that faulty tool data table file with them, but the these tables are not listed in our installed data tables.
Maybe @bgruening has cleaned this up and fixed .eu when we first installed the tool?

**Comment by cat-bro** [comment]
this PR might be enough https://github.com/galaxyproject/tools-iuc/pull/6311
