### ISSUE TITLE
Toolshed website bug

### ISSUE THREAD

**Issue by mihai-sysbio** [galaxyproject/tools-iuc#6229]
_Note: sorry if this is not the right place to create the issue, please move it to the right repository_

I've randomly stumbled upon a rendering on error Firefox 129 on macOS from https://toolshed.g2.bx.psu.edu/repository?repository_id=fbf58be74d681b04:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/181d2053-e0a5-4ee6-a868-fddbb1553f58">

**Comment by bgruening** [comment]
@mihai-sysbio thanks for reporting. I don't think we will touch the old toolshed and concentrate on rolling out the new Tool Shed 2.0 instead. We are hopeful this will happen in the next months.

But thanks again for reporting.
