### ISSUE TITLE
Update virAnnot

### ISSUE THREAD

**Issue by marieBvr** [galaxyproject/tools-iuc#6272]
Hi,

Kindly please update the virAnnot suite to version 0.0.1.
Uniprot URL was broken for rps2tsv tool. Blast2tsv tool did not use the right Blast attribute (in XML).
The output format has been modified for better use in the workflow.

The version 0.0.1 fixes these issues.

Thank you!

**Comment by bgruening** [comment]
@marieBvr do you mean those updates? https://github.com/galaxyproject/tools-iuc/pull/6241/

Depending on which Galaxy server you are using the updates will be deployed automatically over the weekend.
