### ISSUE TITLE
Krona on MTS?

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/tools-iuc#628]
Hi,

I tested Krona from Test ToolShed. It works well :)
Is it planned to push it on MTS?

Thanks

Bérénice

**Comment by bgruening** [comment]
taxonomy_krona_chart? I updated it.

**Comment by bebatut** [comment]
Yes, this one.
I did not see you updated it.
Can you update it on TTS, please? I will test it
Thanks

**Comment by bgruening** [comment]
It's this one: https://toolshed.g2.bx.psu.edu/view/crs4/taxonomy_krona_chart/50f204c82159
The IUC took it over from crs4 but we keep the repository.

**Comment by bebatut** [comment]
Ah ok. I did not know
Thanks !
