### ISSUE TITLE
package_perl_xml_parser_expat_2_41 error

### ISSUE THREAD

**Issue by methylome** [galaxyproject/tools-iuc#630]
On Galaxy 16_10 and CentOS 6.6, the installation has been failed.

Expat.xs:12:19: error: expat.h: No such file or directory
Expat.xs:60: error: expected specifier-qualifier-list before ‘XML_Parser’
Expat.xs:111: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘nsdelim’
Expat.xs:194: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ms’
Expat.xs:197: error: expected ‘)’ before ‘parser’
Expat.xs:249: error: expected ‘)’ before ‘*’ token
Expat.xs:286: error: expected ‘)’ before ‘parser’
Expat.xs: In function ‘characterData’:
Expat.xs:470: error: ‘CallbackVector’ has no member named ‘char_sv’
...

**Comment by mvdbeek** [comment]
You'll need the expat headers, on centos you should be able to get them like this:
```
yum install expat-devel
```

**Comment by methylome** [comment]
Yes, it works. Thanks a lot.

**Comment by bgruening** [comment]
Not sure if we should close this. We should add expat as a dependency isn't it?
