### ISSUE TITLE
IDR download error: ` FATAL: stat /bin/bash: no such file or directory `

### ISSUE THREAD

**Issue by MicheleBortol** [galaxyproject/tools-iuc#6327]
Dear all,

I was trying a small workflow on https://usegalaxy.eu using the " Download IDR/OMERO" (ID = `idr_download_by_ids`) tool: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/idr_download_by_ids/idr_download_by_ids/0.44.1

 https://usegalaxy.eu/published/workflow?id=7d7550ce7004d71e

The job always fails with this error for all versions > 0.41:
` FATAL: stat /bin/bash: no such file or directory `

See this workflow as an example:
https://imaging.usegalaxy.eu/published/workflow?id=7d7550ce7004d71e

Versions <=0.41 seem to be OK.

**Comment by bgruening** [comment]
Hi @MicheleBortol, thanks for you bug report. That was very helpful. It seems that we had a broken container in our cache. I removed it and it seems to work. Can you please test it and reopen this issue if its still a problem.

I hope everything is working now, thanks again for raising this issue!
Happy research!
