### ISSUE TITLE
Need new Kraken Package

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/tools-iuc#637]
Version `0.10.6-unreleased+hash` or similar (as listed in source: https://github.com/DerrickWood/kraken/blob/adfaa267ebdc9f16946fa4a19ddb1bb6e7cb5a97/install_kraken.sh#L22). 

Not sure when these changes will be migrated up to the official downloads: http://ccb.jhu.edu/software/kraken/.

https://github.com/DerrickWood/kraken/

Resolves these issues: https://github.com/galaxyproject/tools-iuc/issues/615

**Comment by blankenberg** [comment]
ping @davebx

**Comment by davebx** [comment]
Why did I not close this when #638 got merged?
