### ISSUE TITLE
lofreq_call error log collection fails

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/tools-iuc#6394]
The wrapper attempts to [collect the parallel log outputs upon failure](https://github.com/galaxyproject/tools-iuc/blob/f28d66c0bcad8ac29be2afec28bc639317239775/tools/lofreq/lofreq_call.xml#L94), but the quotes around the glob expression prevent it from actually matching and expanding.

It should be safe to just quote the var instead

```bash
cat "\$TMPDIR"/lofreq2_call_parallel*/*.log
```

**Comment by wm75** [comment]
Thanks for catching this @natefoo !

**Comment by bernt-matthias** [comment]
fixed in https://github.com/galaxyproject/tools-iuc/pull/6396
