### ISSUE TITLE
SRST2 has incorrect format on discover datasets outputs.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/tools-iuc#6459]
```
$ ag discover_datasets.*format.*,
tools/srst2/srst2.xml
200:            <discover_datasets pattern="(?P&lt;designation&gt;.+)" directory="geneTypingOutput" format="txt,tabular"/>
```

srst2 is the only tool to use a format with a `,` which seems incorrect, as the file gets marked 'binary or unknown' in galaxy even though it's a plain old tabular file. 

For me the results are tabular but I'm not very familiar with this tool so I'm guessing that `txt` was there for a reason.

@bernt-matthias perhaps this is something that should be linted against? The XSD does not have a problem with a comma there (or maybe the case where a format has a comma in the name is permitted? though that would be confusing.)

**Comment by hexylena** [comment]
@EngyNasr I see you're the author of this wrapper, did you experience txt outputs from srst2?

**Comment by bernt-matthias** [comment]
Et voila: https://github.com/galaxyproject/galaxy/pull/17600 .. maybe we get it with 24.2 :)

**Comment by hexylena** [comment]
Incredible work @bernt-matthias !
