### ISSUE TITLE
abritAMR has incorrect output format

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/tools-iuc#6461]
@WhoisDonlee hey coworker! abritamr has incorrect output formats, as far as I can tell all outputs are actually `tabular` not `txt` except for the log file. Or were your abritamr outputs returning non-tab separated values?

**Comment by WhoisDonlee** [comment]
You are absolutely right! The output file extensions are `txt` but the content is indeed `tsv`. I see there's already a pull request, do you want me to do anything?

**Comment by hexylena** [comment]
This confirmation was exactly what I needed, cheers :)
