### ISSUE TITLE
cuffmerge fails with more than 2 GTF files selected

### ISSUE THREAD

**Issue by cmdickens** [galaxyproject/tools-iuc#6480]
cuffmerge_wrapper.xml fails when selecting more than 2 GTF files produced by Cufflinks.
The assembly_GTF_list.txt generated only has 2 lines when selecting 3 or more GTF files. 
sed command needs global substitution:

 currenty
`sed 's/\s\+/\n/'`

 fixed
`sed 's/\s\+/\n/g'`

**Comment by bernt-matthias** [comment]
Good catch - thanks. Should be fixed in  https://github.com/galaxyproject/tools-iuc/pull/6485
