### ISSUE TITLE
Incorrect fasta_nucleotide_color_plot tool id

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/tools-iuc#652]
Not sure how this crept in - must have been some kind of merge issue with all of the changes made to the original PR.  Should I change the tool id or leave it?  If it should be changed, should the version change?  Not quite sure of the process for this scenario.  :(

https://github.com/galaxyproject/tools-iuc/blob/master/tools/fasta_nucleotide_color_plot/fasta_nucleotide_color_plot.xml#L1

**Comment by mvdbeek** [comment]
I would say lat's change it now, before people use it (from MTS: `
Times cloned / installed: 0`)

**Comment by gregvonkuster** [comment]
Just to confirm, is it ok then to leave the version string as is "1.0.0"?

**Comment by mvdbeek** [comment]
I think I would apply our normal strategy of bumping the version when the output changes.
Since it should be the same output, I'd go with 1.0.0. Thoughts on that @bgruening ?

**Comment by gregvonkuster** [comment]
I have a PR waiting to commit.  If I do it now, can you upload to the TSs now.  This should then pose no problems since no one has installed it.

**Comment by mvdbeek** [comment]
sure, go ahead.

**Comment by mvdbeek** [comment]
Closed with PR #653, I guess.
