### ISSUE TITLE
Conda dependecy : Error in manhattan_plot on usegalaxy.fr -

### ISSUE THREAD

**Issue by SalihaZ** [galaxyproject/tools-iuc#6540]
Hi,
I've encountered an error while running the manhattan_plot tool on [usegalaxy.fr](https://usegalaxy.fr/). The error message is as follows:

`  "Conda dependency seemingly installed but failed to build job environment"`

It appears that this issue might be related to outdated dependencies or configuration issues within the tool. Would it be possible to update manhattan_plot on the Galaxy ToolShed to ensure compatibility with the latest environment setups?

Thank you for your help.

Best regards,

Saliha

**Comment by abretaud** [comment]
Hi @SalihaZ ! We'll look into it, it's an installation problem on usegalaxy.fr, not the tool itself so I close this issue
