### ISSUE TITLE
fastp latest version sets read output types to "auto"

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/tools-iuc#6560]
Issue with tool fastp – the outputs.

Running on Galaxy Australia (but same issue appears on Galaxy Eu). 

When using the latest version of this tool in a workflow (version 0.23.4+galaxy2), the output reads are listed as type = auto and they can’t connect to the next tool.
 
The error I get when I try to connect them to the tool Shovill is “Effective output data type(s) [auto] unknown. This tool cannot be run on this Galaxy Server at this moment”
 
I could manually change the outputs to be, for example, fastq and then it will work, but would it be possible to reset the output formats to how they were in the previous fastp tool version?

In the previous version of fastp, (Version 0.23.4+galaxy1) the output reads are listed as type = input.

**Comment by bernt-matthias** [comment]
There should be 0.24.0 already https://github.com/galaxyproject/tools-iuc/pull/6499/files

**Comment by mvdbeek** [comment]
Yep, should be fixed now, let us know if you still see this on 0.24.3 or newer.

**Comment by AnnaSyme** [comment]
thanks @mvdbeek
