### ISSUE TITLE
Flye output assembly_gfa in format gfa not gfa1

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/tools-iuc#6561]
Tool issue: Flye (version 2.9.5+galaxy0). 
Running on: Galaxy Australia (but seems the same in Galaxy Eu). 

The current version of the tool Flye outputs a "graphical fragment assembly" in gfa format. However, downstream tools (e.g. Bandage Image) will not accept this unless the file type has been changed (e.g. to gfa1). 

When I try to assign a datatype to a file, I only see the options for gfa1 or gfa2, so I'm wondering if gfa is a recognized datatype in Galaxy? 

In past versions of Flye (versions 2.9.3+galaxy0 and earlier), the output of this file was set at 'txt'.

**Comment by AnnaSyme** [comment]
Edited to add: at https://help.galaxyproject.org/ I can see a few questions filed that may also relate to this issue, when I search for "gfa".

**Comment by bernt-matthias** [comment]
Indeed, there is no `gfa` datatype. Only `gfa1` and `gfa2`.

https://github.com/galaxyproject/galaxy/blob/9960c312656afd345c3ee9d20a45c920264c6314/lib/galaxy/config/sample/datatypes_conf.xml.sample#L31

I hope that a new linter that will be added with the next release will reduce the number of such mistakes https://github.com/galaxyproject/galaxy/pull/17600.

**Comment by bgruening** [comment]
@AnnaSyme do you know what does flye produce gfa1 or gfa2?

**Comment by AnnaSyme** [comment]
@bgruening I did auto-detect on the file and it said it was gfa1

**Comment by bernt-matthias** [comment]
https://github.com/bgruening/galaxytools/pull/1556
