### ISSUE TITLE
Stacks velvet dependency not included

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#658]
Some stacks functionality requires velvet, but the dependency is not working on the stacks tool

**Comment by bgruening** [comment]
Stacks tool means conda package? Or galaxy dependency?

**Comment by tiagoantao** [comment]
Both, actually :(
I will take care of bioconda

**Comment by yhoogstrate** [comment]
Do I see it correctly that the bioconda dep. has been fixed @tiagoantao ? Would you mind adding package_velvet_1_2_10 by devteam to  package_stacks_1_40 by iuc?

**Comment by yhoogstrate** [comment]
Thanks for reporting @tiagoantao! I think this has been solved in the meantime.
