### ISSUE TITLE
bioperl tools are failing

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#659]
```
Fatal error: Exit code 2 ()
Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC contains: blib/lib /usr/local/galaxy/bioperl-live /usr/local/tools/bioperl/1.6.922/iuc/package_bioperl_1_6/5ef71da82044/lib/perl5/x86_64-linux /usr/local/tools/bioperl/1.6.922/iuc/package_bioperl_1_6/5ef71da82044/lib/perl5 /usr/local/tools/perl/5.18.1/iuc/package_perl_5_18/28865aa39fbb/lib/perl5 /usr/local/tools/perl/5.18.1/iuc/package_perl_5_18/28865aa39fbb/lib/site_perl/5.18.1/x86_64-linux /usr/local/tools/perl/5.18.1/iuc/package_perl_5_18/28865aa39fbb/lib/site_perl/5.18.1 /usr/local/tools/perl/5.18.1/iuc/package_perl_5_18/28865aa39fbb/lib/5.18.1/x86_64-linux /usr/local/tools/perl/5.18.1/iuc/package_perl_5_18/28865aa39fbb/lib/5.18.1 .) at /usr/local/tools/bioperl/1.6.922/iuc/package_bioperl_1_6/5ef71da82044/bin/bp_genbank2gff3.pl line 224.
BEGIN failed--compilation aborted at /usr/local/tools/bioperl/1.6.922/iuc/package_bioperl_1_6/5ef71da82044/bin/bp_genbank2gff3.pl line 224.
```

I guess YAML and the entire dependency chain is missing like we already discovered in the conda packages.

ping @erasche

**Comment by erasche** [comment]
@bgruening this is... unfortunate. this is for the IUC dependency chain or is this specific to conda?

**Comment by bgruening** [comment]
both :(

**Comment by erasche** [comment]
@bgruening :( ok, will look into later this week.

**Comment by lparsons** [comment]
Not really sure where to start with dependencies these days... Anyone have thoughts on this?

**Comment by yhoogstrate** [comment]
@lparsons This is probably the list it requires: http://search.cpan.org/~cjfields/Bundle-BioPerl-2.1.9/BioPerl.pm#CONTENTS . Be aware that CPAN urls are not persistent and such packages should go into cargo-port for a final PR.

**Comment by lparsons** [comment]
@yhoogstrate Thanks, good to know what's missing, but I have to be honest, I don't really know how to add this stuff to a `tool_dependencies.xml` to get it to install, let along a "cargo-port". ;-)

**Comment by bgruening** [comment]
@lparsons if you like you can also try to enhance the bioperl conda package. I think most of the dependencies are also missing there.

**Comment by bgruening** [comment]
If you want to work on tool_dependencies ... look at the perl_bioperl package to get an idea how this is working.

**Comment by erasche** [comment]
@lparsons "what a cargo-port is" -- https://depot.galaxyproject.org/software/ :)
