### ISSUE TITLE
AMRFinder Plus incorrectly installed?

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/tools-iuc#6596]
Hi, 

I try to use the AMRFinder plus wrapper on a personnal galaxy instance.
I use the amrfinderplus database companion to installed last database without error.

When I try to run a job with the tools, I give this error that indicated :
`This tool was disabled before the job completed. Please contact your Galaxy admi`

All dependancy seems correctly installed on galaxy admin interface:
`ncbi-amrfinderplus @3.12.8 | conda | toolshed.g2.bx.psu.edu/repos/iuc/amrfinderplus/amrfinderplus/3.12.8+galaxy0`

But the conda env seems empty?

**Comment by mvdbeek** [comment]
> This tool was disabled before the job completed.

This means that the job handler processing the job did not have the tool loaded. I would restart the job handler (or the instance) and then your jobs should work. If that's not the case I would look at the logs and see why the tool was not loaded.

**Comment by bernt-matthias** [comment]
@bvalot feel free to reopen if this does not solve your problem

**Comment by bvalot** [comment]
I uninstall and reinstall tools and then dependency correctly install this time.
