### ISSUE TITLE
Small collection of GEM tools

### ISSUE THREAD

**Issue by emikar** [galaxyproject/tools-iuc#6597]
Hi!

As part of my work in [Elixir Norway](https://elixir.no/), I've developed a small collection of Galaxy modules for running and generating visualizations from genome-scale metabolic models (GEMs), which I plan to submit PRs for shortly. Would it be more sensible to submit these as separate PRs, or as some sort of collection?

The tools don't have explicit inter-dependencies (apart from the first module which generates an optional input, a csv, for several of the other tools), but provide functionality within the same domain, and might be interesting to use in the same set of analyses.

There are 7 modules overall:

1. **gem_extract_exchange**: Extracts the exchange reactions of the provided gem as a CSV, which can then be modified and used as an input to modify the environment for the other GEM modules
2. **gem_check_memote**: Runs memote on provided GEM, returning snapshot report
3. **gem_escher_visualization**: Runs Escher with specified parameters, giving a modifiable html file with an overview of the metabolic network
4. **gem_flux_distribution**: Performs FBA to solve the provided model with the provided parameters, returning a flux distribution in the form of a CSV
5. **gem_flux_variability_analysis**: Performs FVA to return the reachable flux ranges for the proivded model and parameters
6. **gem_phenotype_phase_plane**: Runs a phenotype phase plane analysis for the provided model and parameters, showing how the model objective scales with the specified reactions
7. **gem_knockout**: Performs single or double knockout analysis for the provided model and parameters, returning all flux values for WT and KO for every (combination of) gene knockout

**Comment by bgruening** [comment]
@emikar if they belong to the same set of tool we call this tool suite. You can submit all of them together if you like. Place them into one folder with a shared macro file.

Thanks for considering your tools for IUC.

**Comment by emikar** [comment]
Great! Thanks for the hasty response :)
