### ISSUE TITLE
HISAT2 wrapper requiring SAMtools package version 1.2 but not found during installation.

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/tools-iuc#661]
Hi All,

Trying to install HISAT2 today on a 16.01 based cloud image (pre-release testing for Enis), and it fails to install a dependency:

Error installing tool dependency samtools version 1.2: Unable to locate required tool shed repository named package_samtools_1_2 owned by iuc with revision f6ae3ba3f3c1.

The [wrapper](https://github.com/galaxyproject/tools-iuc/blob/master/tools/hisat2/hisat2.xml) specifies

  `<requirement type="package" version="1.2">samtools</requirement>`

but when I peruse the main tool shed, the closest I can find to that are `package_samtools_1_2` and `suite_samtools_1_2`.

**Comment by yhoogstrate** [comment]
Hey Dave,

The tool depencies seems to be correct (https://github.com/galaxyproject/tools-iuc/blob/master/tools/hisat2/tool_dependencies.xml). This week I believe I expecienced an error of the same kind, but not with samtools if I remember correctly.

Could you check whether `package_samtools_1_2` is already installed on the cloud image, and whether the corresponding revision number is different. Something like that occured on my instance. Re-installation of the package solved it for me.

**Comment by tnabtaf** [comment]
`package_samtools_1_2` is installed (and so are 4 earlier versions of package_samtools).  The revision ID is `6eea04363026`.

I've reinstalled `package_samtools_1_2'`, now revision `f6ae3ba3f3c1` and that worked.  I was then able to successfully reinstall HISAT2.

So, I think I'm working.

And, I'm obviously learning too.  :-/

**Comment by yhoogstrate** [comment]
Hey @tnabtaf, I don't think this is behaving as expected. This looks like a bug in Galaxy's tool shed installer. Maybe report it over there?
