### ISSUE TITLE
Make IRMA working in older (less than 23) versions of Galaxy as well

### ISSUE THREAD

**Issue by ajkarloss** [galaxyproject/tools-iuc#6612]
Hi, We want to use IRMA in our production galaxy (21.09). But it does not work for anything less than 23. Possible for a quick fix?

**Comment by bernt-matthias** [comment]
Not sure if it will work with older versions. Hence we probably won't lower the profile. My suggestion would be that you change the profile in the tool sources that are installed in your instance and try if it works.
