### ISSUE TITLE
AMRFinderPlus doen't recognize database

### ISSUE THREAD

**Issue by Truongphikt** [galaxyproject/tools-iuc#6619]
## The issue

Hi, galaxy team, **I encountered a trouble that could not use the database of AMRFinderPlus.**

I deployed Galaxy on my local server. I installed AMRFinderPlus v3.12.8+galaxy0. However, when I used AMRFinderPlus, the database didn't show up.

![image](https://github.com/user-attachments/assets/2e268e76-6c4b-457a-bad8-2b44461ea9e7)

## Attempt but failed

I tried to modify the database loc file of AMRFinderPlus which showed up in the  "Data Tables" of the Admin panel. I modified the loc file as follows:

```console
# this is a tab separated file describing the location of Amrfinderplus database
#
# the columns are:
# value, name, path
#
# for example
amrfinderplus_V3.12-2024-05-02.2   V3.12-2024-05-02.2      /mnt/databases/amrfinderplus
``` 
[amrfinderplus_versioned.loc.sample.txt](https://github.com/user-attachments/files/18091649/amrfinderplus_versioned.loc.sample.txt)

I am sure that the separator is a tab. But the error said:
```
Line 7 in tool data table 'amrfinderplus_versioned_database' is invalid (HINT: '<TAB>' characters must be used to separate fields): amrfinderplus_V3.12-2024-05-02.2 V3.12-2024-05-02.2 /mnt/databases/amrfinderplus"
```
![image](https://github.com/user-attachments/assets/caf3ec1b-84a3-427a-b81f-fe6469f99180)

Hope to receive replies soon. Thank you guys for the incredible platform.

**Comment by bernt-matthias** [comment]
Can you upload the loc file somewhere and share the link?

**Comment by Truongphikt** [comment]
I just found out that the loc file has 4 columns, not 3. [[ref][1]]

```
# this is a tab separated file describing the location of amrfinderplus database
#
# the columns are:
# value, name, path
#
# for example
amrfinderplus_V3.12-2024-05-02.2        V3.12-2024-05-02.2      3.12    /mnt/databases/amrfinderplus
```
The loc file above goes smoothly.

[1]: https://github.com/galaxyproject/tools-iuc/blob/d2208e858d6486dd2e832978aca30ca67837cfd6/tools/bakta/test-data/amrfinderplus_versioned_database.loc
