### ISSUE TITLE
Changes were made to volcano plot without changing the tool version, now workflows fail, please revert to version

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/tools-iuc#6620]
Hi there,

@paulzierep made some changes on the volcano plot tool recently, without changing the tool version by mistake. As a result, I have workflows failing now:

![image](https://github.com/user-attachments/assets/cafbb2fe-a940-46c7-af0e-c7766f5adb69)

Could we please revert version 0.0.6 of volcano plot to its previous state and then push the rest of Paul's changes under a newer version number?

I currently get this in pipelines that I have been running without issues for months:

```
bioblend.ConnectionError: Unexpected HTTP status code: 400: {"err_msg": {"shape_col": "No value found for 'Categories that can be used to plot different shapes or facet (useful if multivariable associations are investigated)'.", "shape_or_facet"
: "No value found for 'Display categories by:'."}, "err_code": 0, "err_data": {"39": {"shape_col": "No value found for 'Categories that can be used to plot different shapes or facet (useful if multivariable associations are investigated)'.", "sh
ape_or_facet": "No value found for 'Display categories by:'."}}}
```

I suspect it is the last change that broke things somehow.

I'm suprised that the CI let this go.

**Comment by pcm32** [comment]
I found the issue, while a macro for versions was changed, this macro wasn't being used in the version field of the XML.

**Comment by pcm32** [comment]
Could someone with admin rights please re-instate the volcano plot version 0.0.6 in the toolshed to git revision https://github.com/paulzierep/tools-iuc/commit/84949ce3d77433f035c14406fccc5bc6beaa7a0d ? Thanks.

**Comment by paulzierep** [comment]
hi @pcm32 sorry for that, I just saw I mixed two tools, and only bumped another tool, big fail ! Hope it can be reverted, not sure if the is possible in the toolshed. If not we could push the revert as a new PR, and then you only need to change the tool version of your workflow.

**Comment by pcm32** [comment]
Thanks @paulzierep, no problem. I would prefer if someone with privileges re-states the adequate revision under that version on the toolshed, and then a new version number is pushed with your changes. I have various workflows in various versions (and other people might as well have, there is even an IWC workflow broken because of this), so I would prefer not to have to change them. Any admin who has the IUC user password for the toolshed should be able to push that older revision with that version there (I have done it in the past with my own user for my tools).

**Comment by bgruening** [comment]
@pcm32 can you test the latest version please?

**Comment by bgruening** [comment]
This needs to be merged next: https://github.com/galaxyproject/tools-iuc/pull/6622

**Comment by pcm32** [comment]
Thanks for this @bgruening . I need to wait for the CI to reinstall on those machines, I don't admin them, so I cannot force it, but it should run overnight and I can check tomorrow.

**Comment by bgruening** [comment]
Thanks!

**Comment by pcm32** [comment]
This seems to have worked, I don't get the warning of the field anymore when opening the workflow.

**Comment by bgruening** [comment]
Thanks!
