### ISSUE TITLE
IUC member proposal - Greg Von Kuster

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#670]
Hi Commissioners,

I would like propose Greg Von Kuster (@gregvonkuster) as a new IUC member.
Greg already contributed a lot to the bgruening/galaxytools repository, the IUC tools and was for a long long time Galaxy developer! 
I'm sure he will be a great addition to our team and I'm confident he will help us to improve this service even more.

I will try to assist him in the first month if he has IUC related questions.

Please comment and vote!
Bjoern

**Comment by mvdbeek** [comment]
I think this is a great idea, strong :+1: from me!

**Comment by peterjc** [comment]
+1

**Comment by davebx** [comment]
+1

**Comment by nsoranzo** [comment]
:+1:

**Comment by erasche** [comment]
:+1:

**Comment by blankenberg** [comment]
+1

**Comment by yhoogstrate** [comment]
+1

**Comment by gregvonkuster** [comment]
Thanks everyone!  I’m back…

**Comment by martenson** [comment]
@bgruening I invited @gregvonkuster to the org and the IUC team. Welcome Greg.

**Comment by bgruening** [comment]
thanks @martenson!
