### ISSUE TITLE
stacks needs new archive_datatypes

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#676]
Stacks is indirectly dependent on a tool from @cmonjeau called archive_datatypes.
This package is old and some of the imports are not up to date with recent galaxy versions.
I have a updated version here;
https://github.com/tiagoantao/galaxy-stacks/tree/master/tools/archive_datatypes

**Comment by tiagoantao** [comment]
ping @yvanlebras and @bgruening FYI

**Comment by yvanlebras** [comment]
If I don't make a mistake, it's planned to stop using archive and use data collection instead or in complement...

**Comment by tiagoantao** [comment]
The problem is more serious: the python files of stacks need update.

**Comment by tiagoantao** [comment]
Because of user needs, I really need to get the tool working very very soon. I am currently developing in
https://github.com/tiagoantao/galaxy-stacks/tree/master/

These changes can be included whenever you see fit. I am find a few other minor problems (e.g. velvet dependencies, ...).

**Comment by bgruening** [comment]
Data collections are the way to go. @tiagoantao do you need help here? Can we close it?

**Comment by abretaud** [comment]
Stacks no longer uses archives
