### ISSUE TITLE
package_python_2_7_10 needs to compile against libcrypto

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/tools-iuc#679]
This is mostly an issue for people using Galaxy in a Docker container, but the hashlib package that comes with `package_python_2_7_10` needs to get linked against libcrypto from openssl. That's not listed as a requirement, so if one installs `package_python_2_7_10` inside a docker container and worker nodes on a cluster don't happen to either have that same version or don't export the version of openssl then a random variety of packages (most notably matplotlib) will be non-functional.

**Comment by erasche** [comment]
We are not linking against openssl any more. I believe the best thing will be for the docker containers to include the openssl libraries, which `package_python_2_7_10` should be able to take advantage of at build-time. This issue should probably be migrated to the galaxy docker repo http://github.com/bgruening/docker-galaxy-stable

**Comment by dpryan79** [comment]
openssl is included already in the docker container and everything runs fine there. If one then runs jobs on a cluster, however, the version of openssl on the nodes won't necessarily match or even be compatible with the version that's installed in the container (this will be true on any heterogeneous cluster).

**Comment by bgruening** [comment]
@dpryan79 this is a bigger issue and Galaxy has some problems with the classic tool_dependencies to work on heterogeneous clusters. I hope this is fixed with conda dependencies. Please feel free to reopen!
