### ISSUE TITLE
Some of my ChIP-exo tools are failing tests

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/tools-iuc#689]
I'd like to get these tools configured correctly to pass functional tests: cwpair, genetrack, repmatch_gff3.
Each of these tools has a dependency on anaconda python using this recipe:
```
    <package name="anaconda" version="2.3.0">
        <repository name="package_anaconda_2_3_0" owner="iuc" />
    </package>
```
The tests fail because attempts to import packages contained in anaconda python fail:

```
Traceback (most recent call last):
  File "/Users/gvk/work/git_workspace/tools-iuc/tools/cwpair2/cwpair2.py", line 17, in <module>
    import cwpair2_util
  File "/Users/gvk/work/git_workspace/tools-iuc/tools/cwpair2/cwpair2_util.py", line 6, in <module>
    import matplotlib
ImportError: No module named matplotlib
```
I'm hoping someone can let me know if there is something I need to correct to get these tests to pass.  Any insight is appreciated!

**Comment by bgruening** [comment]
@gregvonkuster with tests you mean the classical tests not the conda based tests in the repo, correct? So you package anaconda is installed and this is the error message you get?

**Comment by gregvonkuster** [comment]
@bgruening I'm running the planemo conda based tests similar to how the .travis.yml config in this repo demonstrates.  These tools work fine outside of testing, but planemo tests do not pass with the error I showed above.

**Comment by bgruening** [comment]
Can you look at the logs at the top. I don't think there is a package called anaconda in the channels, so this will not be installed.

**Comment by gregvonkuster** [comment]
Here are the logs up to the point that the galaxy.ini file is read - sorry for the length - I'm not quite sure what to look for.

$ planemo test --conda_dependency_resolution --conda_prefix $CONDA_PREFIX --galaxy_branch $GALAXY_RELEASE  --galaxy_source $GALAXY_REPO --skip_venv .
Testing using galaxy_root /Users/gvk/work/git_workspace/galaxy
Testing tools with command [cd /Users/gvk/work/git_workspace/galaxy; COMMON_STARTUP_ARGS=--skip-venv; export COMMON_STARTUP_ARGS; echo "Set COMMON_STARTUP_ARGS to ${COMMON_STARTUP_ARGS}"; sh run_tests.sh $COMMON_STARTUP_ARGS --report_file /Users/gvk/work/git_workspace/tools-iuc/tools/cwpair2/tool_test_output.html --xunit_report_file /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp_eZfgX/xunit.xml --structured_data_report_file /Users/gvk/work/git_workspace/tools-iuc/tools/cwpair2/tool_test_output.json functional.test_toolbox]
Set COMMON_STARTUP_ARGS to --skip-venv
Requirement already satisfied (use --upgrade to upgrade): bx-python==0.7.3 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy==1.0.8 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): mercurial==3.4.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): numpy==1.9.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Paste==2.0.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): PasteDeploy==1.5.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): docutils==0.12 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): wchartype==0.1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): repoze.lru==0.6 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): Routes==2.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): WebOb==1.4.1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): WebHelpers==1.3 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): Mako==1.0.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): pytz==2015.4 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): Babel==2.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): Beaker==1.7.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): Cheetah==2.4.4 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): Markdown==2.6.3 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): bioblend==0.7.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 34))
Requirement already satisfied (use --upgrade to upgrade): boto==2.38.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 35))
Requirement already satisfied (use --upgrade to upgrade): requests==2.8.1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 36))
Requirement already satisfied (use --upgrade to upgrade): requests-toolbelt==0.4.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 37))
Requirement already satisfied (use --upgrade to upgrade): kombu==3.0.30 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied (use --upgrade to upgrade): amqp==1.4.8 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied (use --upgrade to upgrade): anyjson==0.3.3 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 42))
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy-migrate==0.10.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 45))
Requirement already satisfied (use --upgrade to upgrade): decorator==4.0.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 46))
Requirement already satisfied (use --upgrade to upgrade): Tempita==0.5.3dev in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 47))
Requirement already satisfied (use --upgrade to upgrade): sqlparse==0.1.16 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied (use --upgrade to upgrade): pbr==1.8.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 49))
Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 51))
Requirement already satisfied (use --upgrade to upgrade): Parsley==1.3 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 52))
Requirement already satisfied (use --upgrade to upgrade): nose==1.3.7 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 53))
Requirement already satisfied (use --upgrade to upgrade): svgwrite==1.1.6 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 54))
Requirement already satisfied (use --upgrade to upgrade): Fabric==1.10.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 57))
Requirement already satisfied (use --upgrade to upgrade): paramiko==1.15.2 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 58))
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied (use --upgrade to upgrade): Whoosh==2.4.1+gx1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied (use --upgrade to upgrade): pysam==0.8.4+gx1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r requirements.txt (line 69))
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=2.0.1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from svgwrite==1.1.6->-r requirements.txt (line 54))
You are using pip version 8.0.3, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): nose in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r ./lib/galaxy/dependencies/dev-requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): NoseHTML in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r ./lib/galaxy/dependencies/dev-requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): twill==0.9.1 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r ./lib/galaxy/dependencies/dev-requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): mock in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from -r ./lib/galaxy/dependencies/dev-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from mock->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from mock->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): six>=1.7 in /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages (from mock->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 4))
You are using pip version 8.0.3, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[('app:main', 'new_file_path', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/tmpR2foOs/new_files_path_PjbIUJ'), ('app:main', 'database_connection', 'sqlite:////var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/tmpR2foOs/database/universe.sqlite'), ('app:main', 'data_manager_config_file', 'config/data_manager_conf.xml.sample,test/functional/tools/sample_data_manager_conf.xml'), ('app:main', 'job_queue_workers', 5), ('app:main', 'log_destination', 'stdout'), ('app:main', 'allow_user_deletion', True), ('app:main', 'master_api_key', 'test_key'), ('app:main', 'tool_config_file', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp_eZfgX/tool_conf.xml,/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp_eZfgX/shed_tool_conf.xml'), ('app:main', 'template_cache_path', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/tmpR2foOs/database/compiled_templates'), ('app:main', 'job_working_directory', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/tmpR2foOs/job_working_directory_AmY_3Q'), ('app:main', 'tool_dependency_dir', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp_eZfgX/deps'), ('app:main', 'check_migrate_tools', False), ('app:main', 'tool_path', 'tools'), ('app:main', 'enable_beta_tool_formats', True), ('app:main', 'user_library_import_dir', None), ('app:main', 'galaxy_data_manager_data_path', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/data_manager_test_tmpRmowmY/data_manager_tool-dataLdziFv'), ('app:main', 'tool_data_table_config_path', 'config/tool_data_table_conf.xml.sample,test/functional/tool-data/sample_tool_data_tables.xml'), ('app:main', 'file_path', '/var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/tmpR2foOs/database/files'), ('app:main', 'datatype_converters_config_file', 'datatype_converters_conf.xml.sample'), ('app:main', 'database_auto_migrate', True), ('app:main', 'use_tasked_jobs', True), ('app:main', 'auto_configure_logging', True), ('app:main', 'tool_parse_help', False), ('app:main', 'shed_tool_data_table_config', 'config/shed_tool_data_table_conf.xml'), ('app:main', 'update_integrated_tool_panel', False), ('app:main', 'admin_users', 'test@bx.psu.edu'), ('app:main', 'template_path', 'templates'), ('app:main', 'allow_user_creation', True), ('app:main', 'use_heartbeat', False), ('app:main', 'allow_library_path_paste', True), ('app:main', 'api_allow_run_as', 'test@bx.psu.edu'), ('app:main', 'test_conf', 'test.conf'), ('app:main', 'id_secret', 'changethisinproductiontoo'), ('app:main', 'library_import_dir', '/Users/gvk/work/git_workspace/tools-iuc/tools/cwpair2/test-data'), ('app:main', 'cleanup_job', 'onsuccess'), ('app:main', 'running_functional_tests', True)]
DEBUG:galaxy.app:python path is: /Users/gvk/work/git_workspace/galaxy/scripts, /Users/gvk/work/git_workspace/galaxy/lib, /Users/gvk/work/git_workspace/galaxy/lib, /Users/gvk/work/git_workspace/galaxy/test, /Users/gvk/conda/envs/iuc_conda/lib/python27.zip, /Users/gvk/conda/envs/iuc_conda/lib/python2.7, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/plat-darwin, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/plat-mac, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/plat-mac/lib-scriptpackages, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/lib-tk, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/lib-old, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/lib-dynload, /Users/gvk/.local/lib/python2.7/site-packages, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg, /Users/gvk/conda/envs/iuc_conda/lib/python2.7/site-packages
INFO:galaxy.config:Logging at '10' level to 'stdout'
galaxy.queue_worker INFO 2016-03-19 17:31:58,996 Initializing main Galaxy Queue Worker on sqlalchemy+sqlite://
tool_shed.tool_shed_registry DEBUG 2016-03-19 17:31:59,045 Loading references to tool sheds from /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp_eZfgX/tool_sheds_conf.xml
tool_shed.tool_shed_registry DEBUG 2016-03-19 17:31:59,045 Loaded reference to tool shed: Target Shed
galaxy.app DEBUG 2016-03-19 17:31:59,047 Using "galaxy.ini" config file: /var/folders/qm/p6jt97wj4239jx8gdv7jy75m0000gn/T/tmp6PdJOw/functional_tests_wsgi.ini
migrate.versioning.repository DEBUG 2016-03-19 17:31:59,143 Loading repository lib/galaxy/model/migrate...

**Comment by bgruening** [comment]
Have a look at the travis file: https://github.com/galaxyproject/tools-iuc/blob/master/.travis.yml#L23

Can you run the install command before you run plane test and see if there is anything installed.

**Comment by gregvonkuster** [comment]
@bgruening Thanks for this information.  I think the problem was that I was not keeping up with installing new conda packages?  Anyway, I did the install and now I can test these tools.  Tests are still failing, but failures are not due to import issues.  I'll submit fixes for these tool's tests shortly.  I'll close this now - thanks again for all of you help!
