### ISSUE TITLE
IUC talk proposal

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#693]
Dear @galaxyproject/iuc!

GCC is coming and the talk deadline is **this Friday**. 
Do we want to present the IUC and recent tool development features at the GCC. I guess we have enough to present and give a round-up of the last years. 

* members and especially new members
* statistics about the repo/work
* best practice guidelines
* community involvement (3 IUC codefests so far)
* driving new technologies (Tool syntax enhancements)
  *  macros
  * macro-inheritence
  * template-input
  * sections
  * tool profiles
  * new test capabilities
* dependencies - IUC is providing a lot of tool_dependencies for the entire community
  * conda dependency - TNG dependency management
* starforge/bioarchive/cargo-store/ ?
* automated testing of tools with github/planemo/travis
* we offer Galaxy Tool dev workshops like the one at GCC

Is this interesting enough to apply for a talk and tell the community more about our work? Anyone wants to give this talk or/and help to work on it?

**Comment by gregvonkuster** [comment]
Hi Bjorn,

Thanks for initiating this idea.  I think it is an excellent idea and could complement the information shared during the Training Days.  The IUC is a principle component in the success of Galaxy, and I think that exposure like this benefits both the IUC and the Galaxy community.  A component of the IUC charter should be a constant effort to acquire additional good-standing members to help oversee the addition of new Galaxy utilities and maintenance of existing utilities.

Unfortunately I won’t be attending the GCC again this year as my current organization does not support it.  Let me know if there is anything I can do to help though and I’ll try my best (my bandwidth is currently stretched thin).  ;)

Greg Von Kuster

**Comment by peterjc** [comment]
I also think this would be a worthwhile talk, and would support @bgruening presenting it. Like @gregvonkuster, I don't have access to funding to attend GCC this year. Maybe we can host a trail run presentation over an IUC Google Hangout, but I would at least try to give some feedback on any draft slides.

**Comment by bgruening** [comment]
Ok, thanks you all for your support. If we get accepted I will ask for a hangout session. I will sketch something up and post a google docs link here. Hopefully, I will find time tomorrow. Until then let me know if you have more ideas.

**Comment by bgruening** [comment]
Sorry to be late on this.
We started a draft here: https://docs.google.com/document/d/1agyWeehrGF1Joko7f7oGCCJT5Gtbw3VWl26W33tr3Mw/edit?usp=sharing

Please feel free to join and put your affiliations into it. I need to baby-sit for a few more hours but will be back in 3-4 hours and finish this up.

**Comment by gregvonkuster** [comment]
Bjoern and I are finished for now, so others feel free to edit as you see fit.  Thanks!  I’m not sure if there is a word limitation, if so we may have a boit too much text…

**Comment by bgruening** [comment]
So we need to submit soon. Anyone wants to present it? I need to provide names :)

**Comment by peterjc** [comment]
Looks like you @bgruening - perhaps with @gregvonkuster and @jmchilton etc if they'll be there too?

**Comment by bgruening** [comment]
@gregvonkuster will not be there ... I will try to get a video setup, maybe we can do this all together. Otherwise I'm fine with presenting us.
@galaxyproject/iuc any last minute comment?

**Comment by bgruening** [comment]
Done. Thanks everyone!
