### ISSUE TITLE
BUG: DESeq2 wrapper - all vs. all produces empty output collection

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#715]
DESeq2 Galaxy Version 2.1.8.3

When running an analysis and specifying "Output all levels vs all levels of primary factor (use when you have >2 levels for primary factor)", a dataset collection is output that should contain the various tables. However, we are seeing and empty collection when running it this way on our installation. I haven't yet confirmed if a specific set of data or options causes this.

**Comment by lparsons** [comment]
ping @bgruening, any ideas on this one? Workarounds? Thanks.

**Comment by lparsons** [comment]
Trying to track down this issue, and I found a couple of odd things that may be causing this...

1. The [`deseq_out`](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.xml#L148) output data element is filtered if `many_contrasts is False`. However, [the `deseq_out` string is passed using the -o parameter to `deseq2.R`](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.xml#L39). The string is used by [`deseq2.R` as the base name for the output files](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.R#L349). I'm not sure what the `deseq_out` string is set to when `many_contrasts` is False, but perhaps this is causing Galaxy to fail to find the datasets. Also, in the [`discover_datasets` action](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.xml#L156), perhaps using `_vs_` would be better.

2. From the [collections documentation (in the PR on Bitbucket)](https://bitbucket.org/galaxy/galaxy-central/pull-requests/634/allow-tools-to-explicitly-produce-dataset/) I don't see how Galaxy knows the format of each dataset when specifying `discover_datasets`. Perhaps something is missing from these docs?

**Comment by lparsons** [comment]
After a bit more digging, I'm now thinking that the [`discover_datasets` action](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.xml#L156) is just wrong. Looking at the [`discover_datasets` documentation](https://wiki.galaxyproject.org/Admin/Tools/Multiple%20Output%20Files#Number_of_Output_datasets_cannot_be_determined_until_tool_run) I believe that a `directory`must be supplied, and a regex that provides Galaxy with a `designation`. Simply putting `vs` as a filename match won't do (according to these docs).

**Comment by lparsons** [comment]
I'd like to propose two fixes, actually. one that can be applied to the existing toolshed version ASAP (that doesn't depend on changing `deseq2.R`) and a second that go in with the next version of deseq2 where the R script is included. I'll see about getting PR's in for both of those...

**Comment by lparsons** [comment]
OK, got the first fix in, but didn't quite get to the second. I'm not sure of the correct way to get [`deseq2.R` to output the files in an appropriate subdirectory](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.R#L349), which can then be specified in [`discover_datasets` in `deseq2.xml`](https://github.com/galaxyproject/tools-iuc/blob/deseq_new/tools/deseq2/deseq2.xml#L156). Thoughts or advice?

**Comment by bgruening** [comment]
@lparsons why do you need the subdir?

**Comment by lparsons** [comment]
@bgruening A subdirectory isn't required, but it's suggested in the [documentation for `discover_datasets`](https://wiki.galaxyproject.org/Admin/Tools/Multiple%20Output%20Files#Number_of_Output_datasets_cannot_be_determined_until_tool_run). My main concerns are ensuring the files get written to the appropriate tool output directory and that the correct set of files are put in the collection. A subdirectory for each collection makes that simple.

**Comment by bgruening** [comment]
@lparsons subdir would be great! But the underlying issue should be solved on the framework level as well. @jmchilton improved this already in 16.04 a lot. Feel free to patch the R script if you like.
I'm going to close this issue, please feel free to open a new one with the subdir idea.
