### ISSUE TITLE
ucsc tools

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-iuc#717]
Two of your packages [download and install some of the ucsc tools](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_ucsc_tools_312/tool_dependencies.xml). I was wondering why you made this repository, since you haven't implemented any of these tools (written the xml and put them on the tool shed, as far as I can tell). Has anyone implemented these tools, e.g. `bedClip`. I haven't been able to find an example of anyone doing so.

**Comment by yhoogstrate** [comment]
Hey @zfrenchee, if you're refering to *package_ucsc_tools_0_1* and *package_ucsc_tools_312*, I think I know the answer. If you dive into the history of version _0_1 you can see it was orignally mapping to the latest build. This is against the galaxy philosphy and probably that's the reason why 312 was created. That one should be the package definition for only version 312 of ucsc's tools and is in concordance with the galaxy philosophy and the ideal way of managing dependencies in a reproducible manner. I would suggest to use `_312`.
I am not aware of a wrapper for `bedClip`. If you think you are able to create a wrapper for `bedClip` that would be of big help to the whole community :wink:.

**Comment by martenson** [comment]
@zfrenchee in addition to @yhoogstrate I would like to point out that IUC does not necessarily wrap all the tools, but is trying to provide packages of common software to enable tool authors to wrap it.

**Comment by martenson** [comment]
also e.g. deeptools v 1.5.10 depend on ucsc package https://github.com/galaxyproject/tools-iuc/blob/3c4a2b13b0f3a280de4f98f4f5e0dc29e10fc7a0/packages/package_python_2_7_deeptools_1_5_10/tool_dependencies.xml

**Comment by zfrenchee** [comment]
Thanks guys!
