### ISSUE TITLE
package_python_2_7_biopython_1_66 in MTS?

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/tools-iuc#747]
Hello,

I need `package_python_2_7_biopython_1_66` as a dependency. I found it on TTS but not on MTS.
Is it normal?

Thanks

Bérénice

**Comment by peterjc** [comment]
Yes, it is here: https://github.com/biopython/galaxy_packages

Is the TTS version working fine? If so I can update the MTS, or @bgruening and @chapmanb can too.

**Comment by peterjc** [comment]
Actually its not on the MTS or TTS either...

https://toolshed.g2.bx.psu.edu/view/biopython/package_python_2_7_biopython_1_66
https://testtoolshed.g2.bx.psu.edu/view/biopython/package_python_2_7_biopython_1_66

I'm not sure where the IUC owned entry came from:

https://testtoolshed.g2.bx.psu.edu/view/iuc/package_python_2_7_biopython_1_66

CC @bgruening

**Comment by bgruening** [comment]
Very likely this was me during testing :(.
It uses a strict binding to python_2_7 and not the old way that are used by the biopython owner. 
Do you want me to add this new recipe to the biopython repository and we push it as biopython owner to both TS?

@bebatut is this package actually working ;)?

**Comment by peterjc** [comment]
Yes please @bgruening - Assuming its working, I would suggest updating https://github.com/biopython/galaxy_packages and posting it to the MTS and TTS under the Biopython username, and then deprecate the IUC entry on the TTS?

(Alternatively, if the IUC as a whole would prefer, we could just deprecate the Biopython owned tool shed entries and put them all under IUC ownership in future. Should we discuss this on the mailing list?)

**Comment by bebatut** [comment]
@bgruening It seems to work for the tool which needed it :)

**Comment by bgruening** [comment]
@peterjc I don't mind. For me it would be easier to handle one less TS user but I appreciate the biopython involvement in Galaxy. Do you plan to have some dedicated biopython tools for Galaxy? Or would this end up in tools-iuc or pico_galaxy?

@bebatut good to know!

**Comment by peterjc** [comment]
By analogy to Linux distribution packaging, I've come to think we (Biopython) might as well leave the Galaxy Packaging to the IUC. Like @bgruening, having to deal with my personal Galaxy Tool Shed account, the IUC account, *and* the Biopython account is a bit of extra overhead.

@chapmanb @tiagoantao: as other Biopython developers with a foot in the Galaxy ecosystem, what you you think about looking after the dependency definitions under the IUC account in future?

**Comment by tiagoantao** [comment]
I can help with this. Due to personal complications this week is very bad timing, but starting next week I expect to have plenty of time.

**Comment by tiagoantao** [comment]
What is the best way to advance this? Should I submit a PR for tools-uic for 1.66? @bgruening could tutor me for this first version and I would take care of this autonomously 1.67 and onwards?

**Comment by bgruening** [comment]
@tiagoantao a simple PR with 1.66 would be great. We will review it, merge it and get it into TTS as quickly as possible. From there we should test is properly, maybe with Galaxy Docker and get it into MTS.

**Comment by peterjc** [comment]
@tiagoantao does this mean you're OK with using https://github.com/galaxyproject/tools-iuc/ rather than https://github.com/biopython/galaxy_packages in future?

**Comment by tiagoantao** [comment]
@peterjc I am fine with both, I leave that decision to you

**Comment by tiagoantao** [comment]
This is currently pending on https://github.com/biopython/biopython/pull/822

This is needed to have a robust dependency test.

**Comment by peterjc** [comment]
@tiagoantao your Biopython test-framework enhancements in https://github.com/biopython/biopython/pull/822 could be in Biopython 1.67, but won't affect 1.66 which is already out.

@bgruening it sounds like we could move the Biopython Galaxy packages to the tools-iuc repository, and iuc ownership on the Tool Shed in future.

**Comment by tiagoantao** [comment]
Lets see if I am getting this right (probably not):

1. I would take the version here to start with: https://github.com/biopython/galaxy_packages/tree/master/package_biopython_1_66

2. This is mostly an exercise of getting dependencies in. I suspect that I will have to add a few new packages to achieve completeness, say simcoal for example

**Comment by peterjc** [comment]
The older packages named like ``package_biopython_1_66`` are using the default version of Python (and live on GitHub at https://github.com/biopython/galaxy_packages), while the Galaxy Python packaging ecosystem seems to have shifted towards separate packages for specific versions of python like ``package_python_2_7_biopython_1_66`` (as in this issue's title). This specific package was something @bgruening did for the Test Tool Shed, but which is not yet in the Main Tool Shed, and is not yet on GitHub anywhere.

Expanding the dependencies within the Galaxy Tool Shed ecosystem (e.g. simcoal etc) is a worthy but separate goal.

**Comment by peterjc** [comment]
@bgruening can you add your ``package_python_2_7_biopython_1_66`` with strict binding to Python 2.7 from the TTS to the ``iuc-tools`` repository and MTS please?

In future we'll drop the Biopython https://github.com/biopython/galaxy_packages packages in favour of the IUC owned ones.
