### ISSUE TITLE
IUC member proposal - Anthony Bretaudeau

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#756]
Hi,

I would like see Anthony Bretaudeau (@abretaud) becoming an IUC member.

Anthony already contributed a lot to the IUC repository and is very active in the metagenomic field.
He has contributed to the Galaxy codebase and is a very active member of the French Galaxy community.

As usual I will try to assist him in the first months if he has IUC related questions.

Please comment and vote!

**Comment by erasche** [comment]
:+1:

**Comment by mvdbeek** [comment]
👍

**Comment by nsoranzo** [comment]
:+1:

**Comment by yhoogstrate** [comment]
:+1:

**Comment by martenson** [comment]
👍

**Comment by abretaud** [comment]
Thank you all!
Very excited to be a part of it!
Anthony

**Comment by blankenberg** [comment]
+1

**Comment by bgruening** [comment]
@gregvonkuster I know you already agreed via mail, can we get an official one here as well :)

**Comment by nekrut** [comment]
👍

**Comment by martenson** [comment]
@abretaud I formally invited you to the galaxyproject GH org; please make sure you have strong password on this account 
and welcome!

**Comment by bgruening** [comment]
@abretaud welcome! You will get a mail from me with all TS credentials soon.
:tada:

**Comment by gregvonkuster** [comment]
Belated +1 - I must have sent it earlier by email, sorry!  Welcome aboard!
