### ISSUE TITLE
Are we ready for automatic TS push?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#765]
@galaxyproject/core are we ready to push conda-tested tools automatic to the MTS?
I think it worked well for TTS or was there any problems?

What about packages? Do we want to upload them as well?

**Comment by nsoranzo** [comment]
:+1: but at the same time we should document that on the README and mention that you can skip testing/uploading with this trick: https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by bgruening** [comment]
Oh yes, documentation should be updated :)

**Comment by mvdbeek** [comment]
For tools that are conda-tested a definite 👍 
For packages I would say yes as well, given that we have no formal checks in place anyway.
Ideally we would test the package installation from the testtoolshed first before merging. Could we perhaps let jenkins do that?

**Comment by martenson** [comment]
this is splendid, thank you fellas!
