### ISSUE TITLE
Trinity (e4a9e0798360) incorrect tool dependencies

### ISSUE THREAD

**Issue by JJAlmagro** [galaxyproject/tools-iuc#789]
Hello, 

When installing trinity (e4a9e0798360) there is a problem with the edger and express dependencies. In these lines https://github.com/galaxyproject/tools-iuc/blob/master/tools/trinity/tool_dependencies.xml#L15, https://github.com/galaxyproject/tools-iuc/blob/master/tools/trinity/tool_dependencies.xml#L21 these two packages appear as:
```
<package name="edger" version="3.12.0">
<package name="express" version="1.5.1">
```
However, in these packages https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_r_edger_3_12_0/tool_dependencies.xml#L6, 
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_express_1_5_1/tool_dependencies.xml#L3 they appear with a different name:
```
<package name="bioconductor-edger" version="3.12.0">
<package name="eXpress" version="1.5.1">
```

Therefore, I suppose that Galaxy does not recognize them and they are shown as Never Installed.

**Comment by lparsons** [comment]
BTW, just a general observation, there are many duplicate dependencies for this trinity install. I realize this can be tough to deal with, given the large dependency chain, but it would be nice to address this somehow.

Examples:

* cairo
    * `package_cairo_1_12_14` from `devteam`
    * `package_cairo_1_12_14` from `iuc`

* freetype
    * `package_freetype_2_5_2` from `devteam`
    * `package_freetype_2_5_2` from `iuc`

* libpng
    * `package_libpng_1_6_7` from `devteam`
    * `package_libpng_1_6_7` from `iuc`

* ncurses
    * `package_ncurses_5_9` from `iuc`
    * `package_ncurses_6_0` from `iuc`

* pixman
    * `package_pixman_0_32_4` from `devteam`
    * `package_pixman_0_32_4` from `iuc`
    * `package_pixman_0_32_6` from `iuc`

* R
    * `package_r_3_1_2` from `iuc`
    * `package_r_3_2_1` from `iuc`

* readline
    * `package_readline_6_2` from `iuc`
    * `package_readline_6_3` from `iuc`
