### ISSUE TITLE
jbrowse: option to automatically enable all tracks

### ISSUE THREAD

**Issue by tseemann** [galaxyproject/tools-iuc#794]
The default is to show NO tracks. This is confusing to users. Be good to have an option at creation to turn on all tracks or not.

**Comment by erasche** [comment]
This is standard for JBrowse. The option to have them visible by default is available in the upcoming version.

https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/macros.xml#L51

**Comment by tseemann** [comment]
My argument for this one would be that JBrowse is a base platform for which experts build on for users, which the Galaxy JBrowse should make as helpful to real users as possible. 

I look forward to that update.

**Comment by erasche** [comment]
It's a fair argument!

I believe the argument against "default on" is the amount of data that would be immediately downloaded. If you're visualizing N bam tracks, that may trigger a very large download even if you just wanted to view one of them.

I hope to have the update pushed before GCC this year.

**Comment by tseemann** [comment]
Cool - i'm sure i'll get to meet you at GCC - @Slugger70 encouraged me to attend.
