### ISSUE TITLE
IUC member proposal - Saskia Hiltemann

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#803]
Hi Commissioners,

I would like to see Saskia Hiltemann (@shiltemann) becoming an IUC member.
Saskia is doing an awesome job on a lot of wrappers but especially on
https://github.com/galaxyproject/tools-iuc/pull/429 (mothur). The latter one slows my browser down if I want to see this PR :)

She also contributed to the Galaxy codebase, worked on datatypes and maintains an Interactive Environment.

I will try to assist her in the first month if she has IUC related questions.

Please comment and vote!
Bjoern

**Comment by erasche** [comment]
:+1::exclamation:

**Comment by nsoranzo** [comment]
:+1:

**Comment by natefoo** [comment]
:+1:

**Comment by abretaud** [comment]
+1 !

**Comment by gregvonkuster** [comment]
👍

**Comment by blankenberg** [comment]
+1

**Comment by bgruening** [comment]
I think this is a string yes! 

@martenson can you do your magic please and add Saskia to this repo and to the ML. I will send her all other credentials this evening.

**Comment by shiltemann** [comment]
Thanks all! excited to be joining the team :)

**Comment by bgruening** [comment]
Welcome Saskia!

**Comment by martenson** [comment]
@shiltemann You should have received a subscription email from the iuc list. I have also added you to the IUC team at the galaxyproject github org. Please make sure you have a strong GitHub password. Thanks and welcome!
