### ISSUE TITLE
Bug: package_fontconfig_2_11_1 unable to locate ZLIB

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#813]
When I attempt to install the latest [trinity package](https://toolshed.g2.bx.psu.edu/view/iuc/trinity/f7564c3f9dc0) (revision 6:f7564c3f9dc0) from the main toolshed, I've run into an error with the fontconfig dependency. `package_fontconfig_2_11_1` installs, missing the `fontconfig` dependency due to an error during installation: 

```
/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtdl2QZ0K/fontconfig-2.11.1/test/test-migration.c:44: warning: the use of `mktemp' is dangerous, better use `mkstemp'
/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtdl2QZ0K/fontconfig-2.11.1/fc-cache/.libs/lt-fc-cache: /lib64/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /opt/galaxy/galaxy-app/tool-dependencies/libpng/1.6.7/iuc/package_libpng_1_6_7/588666932a32/lib/libpng16.so.16)
make[2]: *** [install-data-local] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
```

This is using `release_16.04` of Galaxy, on CentOS 6.

**Comment by bgruening** [comment]
@lparsons which version of zlib do you have installed?

**Comment by lparsons** [comment]
@bgruening The zlib package installed in the dependency tree for Trinity is [`package_zlib_1_2_8`](https://toolshed.g2.bx.psu.edu/view/iuc/package_zlib_1_2_8/63a4a902cda2). There is also [`package_bzlib_1_0`](https://toolshed.g2.bx.psu.edu/view/iuc/package_bzlib_1_0/af4887e1f595), but I think that's something different.

**Comment by lparsons** [comment]
Seems like this is most likely an issue with libpng. I think the problem is that libpng attempts to use `$ZLIB_ROOT_PATH`, but the zlip package sets `ZLIB_ROOT_DIR`. Working on a patch and test now...

**Comment by lparsons** [comment]
Hmmm... I see ZLIB_ROOT_DIR in the debug logs, but not seeing in the tool_dependencies.xml files... Still investigating.

**Comment by lparsons** [comment]
This seems very inelegant, but I added an explicit `set_environment_for_install` for zlib and all was happy. 

*rant on*
I feel rather strongly that the environments for dependencies should automatically be set both during install (if `prior_installation_required` is `True`) and during execution. Requiring package authors to work all the way down the dependency chain is asking too much. It's hard enough writing these packages (to the point I've nearly stopped doing it). 😞 
*rant off*

**Comment by gregvonkuster** [comment]
+1 - I feel your pain  :)

**Comment by lparsons** [comment]
@nsoranzo or @bgruening, any chance we can get this merged and push the changes for atlas and this package to the toolshed? Those are the last things standing in my way of getting the latest Trinity tools installed... 😄
