### ISSUE TITLE
Bug: package_atlas_3_10 precompiled linux_x64 tarball fails to install

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#831]
When attempting to install the precompiled tarball of the linux_x64 version of atlas, the following error occurs:

```
tool_shed.galaxy_install.tool_dependencies.recipe.step_handler DEBUG 2016-06-16 16:34:50,023 Attempting to download via url: https://depot.galaxyproject.org/software/atlas/atlas_3.10.2_linux_x64.tar.gz
tool_shed.galaxy_install.tool_dependencies.recipe.step_handler DEBUG 2016-06-16 16:35:11,984 Successfully downloaded from url: https://depot.galaxyproject.org/software/atlas/atlas_3.10.2_linux_x64.tar.gz
tool_shed.galaxy_install.tool_dependencies.recipe.install_environment:atlas DEBUG 2016-06-16 16:35:11,991 +
                        command -v gfortran || return 0
                        BUNDLED_LGF_CANON=/opt/galaxy/galaxy-app/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/f27d2f8761ae/lib/libgfortran.so.3.0.0 &&
                        BUNDLED_LGF_VERS=`objdump -p $BUNDLED_LGF_CANON | grep GFORTRAN_1 | sed -r 's/.*GFORTRAN_1\.([0-9])+/\1/' | sort -n | tail -1` &&
                        echo 'program test; end program test' > test.f90 &&
                        gfortran -o test test.f90 &&
                        LGF=`ldd test | grep libgfortran | awk '{print $3}'` &&
                        LGF_CANON=`readlink -f $LGF` &&
                        LGF_VERS=`objdump -p $LGF_CANON | grep GFORTRAN_1 | sed -r 's/.*GFORTRAN_1\.([0-9])+/\1/' | sort -n | tail -1` &&
                        if [ $LGF_VERS -gt $BUNDLED_LGF_VERS ]; then
                            cp -p $BUNDLED_LGF_CANON ${BUNDLED_LGF_CANON}.bundled &&
                            cp -p $LGF_CANON $BUNDLED_LGF_CANON
                        fi

tool_shed.galaxy_install.install_manager ERROR 2016-06-16 16:35:12,036 Error installing tool dependency atlas version 3.10.2.
Traceback (most recent call last):
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/install_manager.py", line 124, in install_and_build_package_via_fabric
    tool_dependency = self.install_and_build_package( install_environment, tool_dependency, actions_dict )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/install_manager.py", line 109, in install_and_build_package
    initial_download=False )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 31, in execute_step
    initial_download=initial_download )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 1869, in execute_step
    job_name=package_name )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 117, in handle_command
    output = self.handle_complex_command( command, job_name=job_name )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 169, in handle_complex_command
    cwd=state.env[ 'lcwd' ] )
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtd66Ymtq'
```

**Comment by lparsons** [comment]
I suspect that this error is due to setting `cwd` in the `Popen` call at [`install_environment.py` line 169](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py#L169). However, I'm not sure what it should be set to, or why the current value of `state.env[ 'lcwd' ]` doesn't work.

**Comment by lparsons** [comment]
Ping @gregvonkuster?

**Comment by gregvonkuster** [comment]
This code originally used Fabric, but was re-written to mimic Fabric, but not use it since a weakness of Fabric is that it is not thread-safe.  The use of the environment in this particular call is based on this: http://docs.fabfile.org/en/1.11/usage/env.html, and should work, so I'm not sure what could be causing the problem with the atlas recipe.  One of my priorities was to eliminate the use of Fabric in the Tool Shed installation processes, and I got pretty close, but was not able to completely eliminate it before I ran out of time working with the core team.

**Comment by lparsons** [comment]
Thanks @gregvonkuster. After more investigation, I think the issue actually had to do with the behavior of the the `move_directory_files` action and not the `execute_complex_command` function. The workaround in #832 seems to take care of it, but I'm not sure if there is a cleaner way to fix things.

**Comment by nsoranzo** [comment]
This is a Galaxy bug which is going to be fixed by https://github.com/galaxyproject/galaxy/pull/2522.

**Comment by lparsons** [comment]
@nsoranzo One _minor_ thing... the tarball get's copied over here, which is not necessary. Is there a standard method of avoiding this?

**Comment by nsoranzo** [comment]
@lparsons On OS X only, I suppose?

**Comment by nsoranzo** [comment]
Forget the previous comment.

**Comment by lparsons** [comment]
No, this is on CentOS. The issue is that the atlas tarball on galaxydepot is a [tarbomb](http://www.linfo.org/tarbomb.html) and thus, when it gets extracted, the current dir (`.`) contains the tarball as well as the contents. Issuing the `move_directory_files` on `.`, moves the tarball as well as the extracted contents... Hope this is clear... ;-)

**Comment by nsoranzo** [comment]
@lparsons Yes, thanks, you are right. I guess we should fix atlas_3.10.2_linux_x64.tar.gz , upstream is at https://depot.galaxyproject.org/package/linux/x86_64/atlas/atlas-3.10.2-Linux-x86_64.tar.gz .

Ping @natefoo

**Comment by lparsons** [comment]
If I'm reading the docs right, if we create a subdir with the same name as the tarball, there won't be any change necessary to the atlas `tool_dependencies.xml` since Galaxy will chdir into that directory after extracting the archive?
