### ISSUE TITLE
Deep Tools correctGCBias unrecognized arg --filterOut produces an error

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#835]
**Observed at** http://usegalaxy.org

**Version** 

> tool id: toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_compute_gc_bias/deeptools_compute_gc_bias/2.2.3.0
> tool version: 2.2.3.0
> job tool version: computeGCBias 2.2.3

**Error**

> job stderr:
> Fatal error: Exit code 2 ()
> usage:
>  computeGCBias -b file.bam --effectiveGenomeSize 2150570000 -g mm9.2bit -l 200 --GCbiasFrequenciesFile freq.txt [options]
> computeGCBias: error: unrecognized arguments: --filterOut /galaxy-repl/main/files/XXX/XXX/dataset_XX.dat

**Tool form display of option**

<img width="722" alt="screen shot 2016-06-22 at 12 56 39 pm" src="https://cloud.githubusercontent.com/assets/8999735/16281502/944fbe32-3879-11e6-8537-574c8566e843.png">

**Other recent changes to the tool captured here** 

https://github.com/galaxyproject/galaxy/issues/2331

Note: Not fully resolved as of this post date. Did not locate other changes that may have addressed this already. If an update on Main will correct, can close this out and make a ticket for that change.

ping @gregvonkuster @bgruening

**Comment by nsoranzo** [comment]
@jennaj DeepTools Galaxy wrappers are hosted at https://github.com/fidelram/deepTools  , not here. Please report the issue there.

**Comment by bgruening** [comment]
It's ok @jennaj it's on my todo list.

**Comment by jennaj** [comment]
@bgruening cool, thanks!

**Comment by jennaj** [comment]
@bgruening Super, thanks. I didn't find an issue ticket, so if you could link it here - or the pull - once made, would be great.

**Comment by jennaj** [comment]
Just sharing - The linked ticket above may be related.

**Comment by jennaj** [comment]
Moved to https://github.com/fidelram/deepTools/issues/434
