### ISSUE TITLE
Data collection and element_identifier

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/tools-iuc#857]
We (@yvanlebras and me) have a problem with [Stacks refmap tool:](https://github.com/galaxyproject/tools-iuc/blob/master/tools/stacks/stacks_refmap.xml)
-It takes as input a data collection of bam files produced by BWA (latest from devteam)
-Each dataset in this collection have an identifier corresponding to the fastq name
-Stacks needs to have access to these bam identifiers to use it as sample name

I have tried using $dataset.element_identifier instead of $dataset.name ([here for example)](https://github.com/galaxyproject/tools-iuc/blob/master/tools/stacks/stacks_refmap.xml#L15), but when launching the tool in galaxy 16.04, element_identifier still returns the same value as name attribute ("Map with BWA on data 47 and data 3 (mapped reads in BAM format)" instead of the expected "SRR034310_CAAC").

It does the same when launching it in a workflow.
I know the identifier is in the db as it is correctly written when looking at the data collection.

I am not sure if there is a problem in the wrapper, or maybe a bug in galaxy?
@jmchilton maybe you have a clue on this? (I saw the element_identifier keyword in your slides this morning)

**Comment by mvdbeek** [comment]
@abretaud can you try running this through the api? I believe in another form I already encountered this in https://github.com/galaxyproject/tools-devteam/pull/366/files, so just as for repeats we may need to do something with conditionals here

**Comment by abretaud** [comment]
Oh yes, it looks very similar!
Here is an example of content of param_dict[ "identifier_key" ]  on https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/evaluation.py#L259:
`{<galaxy.model.HistoryDatasetAssociation object at 0x16943e10>: u'individual_sample11|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x135d3450>: u'individual_sample7|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x16962590>: u'individual_sample3|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x135bb110>: u'individual_sample16|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x16962090>: u'individual_sample13|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x169438d0>: u'individual_sample12|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x135bd3d0>: u'individual_sample6|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x133709d0>: u'popmap|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x154a3910>: u'individual_sample15|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x154a3690>: u'individual_sample1|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x135bdf50>: u'individual_sample9|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x135bb690>: u'individual_sample8|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x154bd8d0>: u'individual_sample2|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x16952f90>: u'individual_sample10|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x16943310>: u'individual_sample5|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x154a3510>: u'individual_sample14|__identifier__', <galaxy.model.HistoryDatasetAssociation object at 0x1692d750>: u'individual_sample4|__identifier__'}`
I guess the trailing numbr should be removed?

**Comment by yhoogstrate** [comment]
Has this issue been resolved @abretaud ?

**Comment by abretaud** [comment]
Yes, resolved!
