### ISSUE TITLE
galaxydepot prebuilt R 3.2.1 is missing atlas: `package_r_3_2_1`

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#873]
The `tool_dependencies.xml` file for [`package_r_3_2_1` does not properly set the install environment for building R, missing the atlas package](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_r_3_2_1/tool_dependencies.xml#L60).

Using the prebuilt package, `package_deseq2_1_10_0` and `package_bioconductor_edger_3_14_0` both fail to install on CentOS 6 with the error: 

```
/usr/bin/ld: cannot find -lblas
```

However, if I add the following to the `tool_dependencies.xml` file, rebuild R, then deseq2 and edger install fine.

```
<package name="atlas" version="3.10.2">
    <repository changeset_revision="f27d2f8761ae" name="package_atlas_3_10" owner="iuc" prior_installation_required="True" toolshed="https://toolshed.g2.bx.psu.edu" />
</package>
```

Actually, I'm not positive that adding this step is necessary, but building R certainly is.

**Comment by lparsons** [comment]
@abretaud Thanks for helping with the other issues, and sorry to bug you, but I thought you might be able to shed some light on this...

One possible issue that I'm investigating that that [`package_r_3_2_1` does not actually setup atlas in the environment before building](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_r_3_2_1/tool_dependencies.xml#L60) (though atlas is required to be installed), so perhaps that's causing an issue? I'm going to test a few things now.

**Comment by abretaud** [comment]
Yes, looking at the error, adding atlas to the setup env should fix it, but I'm wondering if it should be added to R package or to the deseq2 and edger packages. I'd probably add it to deseq2 and edger if R itself compiled correctly, but not 100% sure...

**Comment by lparsons** [comment]
@abretaud I'm not sure either. I'm trying to test adding it to deseq2 now, but I haven't been able to generate a valid `set_environment_for_install` block yet (I suspect some issue with installed revision or something).

**Comment by lparsons** [comment]
I was able to set the ATLAS environment for deseq2 and edger, but the same error occurred. I also added it to R, but none of these things fixed the error. :-(

**Comment by lparsons** [comment]
Just noticed that R is actually not built on my system (64-bit Linux), but instead a pre-compiled binary is downloaded from galaxydepot. I'll see if compiling with the ATLAS libraries fixes anything...

**Comment by lparsons** [comment]
@abretaud Looks like this is indeed an issue with the R package. I was able to get things working by adding the atlas package to `set_environment_for_install` and actually building R, instead of using the one from galaxydepot. Who is a good person to ping on this?

**Comment by lparsons** [comment]
@davebx Is this something you can help with?

**Comment by lparsons** [comment]
From my testing, it looks like no changes are needed to the `tool_dependency.xml` file for any of the tools (`package_r_3_2_1`, `package_bioconductor_edger_3_14_0`, or `package_deseq2_1_10_0`. The only change that needs to be made is fixing the galaxydepot pre-built binary.

**Comment by abretaud** [comment]
It's strange, the libblas lib is included in the R 3.2.1 tarball: https://depot.galaxyproject.org/software/r/r_3.2.1_linux_x64.tar.gz
And LD_LIBRARY_PATH should be set there: https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_r_3_2_1/tool_dependencies.xml#L100

**Comment by lparsons** [comment]
@abretaud I just know that things fail if I use the tarball at https://depot.galaxyproject.org/software/r/r_3.2.1_linux_x64.tar.gz. If I build R using the recipe in `tool_dependencies.xml`, it works. Can you install R and edger on a fresh Galaxy install on some 64bit Linux?

**Comment by nsoranzo** [comment]
@lparsons @abretaud `r_3.2.1_linux_x64.tar.gz` from depot seems to be missing `libblas.a` , `libblas.so` and `libblas.so.3` , open an issue on StarForge?
