### ISSUE TITLE
Mothur on MTS

### ISSUE THREAD

**Issue by ericenns** [galaxyproject/tools-iuc#874]
Hi, We are looking at upgrading our Mothur install on Galaxy, but noticed it is only on the TTS. Is it ready for production use?

**Comment by bgruening** [comment]
ping @shiltemann 
@ericenns additional testing would still be nice if you have some time. It should be ready, at lest conda packages and travis are ready and happy :)

**Comment by shiltemann** [comment]
yep, it should be ready :) ..and please do let me know if you run into anything, they could indeed do with some more testing in a real-world setting, I'm sure there are plenty of things that could be improved, also just for better usability etc (e.g. would it be useful for certain tools to consume collections?) I'm afraid I have a very technical view of these tools and don't know all that much about the details of how people are using them in their analyses, so any feedback welcome!

the suite-install still runs into a maximum recursion depth error, so I'm afraid it will involve clicking install on a 125 tools for now still :/

**Comment by Takadonet** [comment]
@ericenns and I attempted to install mothur package and getting the following stacktrace
https://gist.github.com/Takadonet/6b1429af416d2303ec45bda6c59c62df

Any ideas? @shiltemann @bgruening

**Comment by shiltemann** [comment]
hmm, looks like a missing dependency on glibc maybe? try a `yum install glibc-devel` or `apt-get install libc6-dev build-essential` perhaps?

**Comment by Takadonet** [comment]
Its already installed.

**Comment by shiltemann** [comment]
hmm, this is using toolshed dependencies I suppose? would enabling conda be an option?

**Comment by Takadonet** [comment]
Not at the moment, we are planning to upgrade our infrastructure specifically so we can use conda. My current plan of attack is that https://nml@toolshed.g2.bx.psu.edu/repos/jjohnson/mothur_toolsuite/raw-file/tip/mothur/tool_dependencies.xml compiles correctly on our system so trying to figure out what are the differences between the two tool_dependencies.xml

**Comment by shiltemann** [comment]
maybe `yum install glibc-static` ? (I see the -static flag is set in the makefile for uchime)

**Comment by Takadonet** [comment]
that work!... to get farther down the line.

Got the following stacktrace

https://gist.github.com/Takadonet/d68bdfffdfa108e4f053eb650c4d6ea0

**Comment by shiltemann** [comment]
progress! ..could you try commenting out this line in `source/uchime_src/mk` file and try installing again?

`echo $CPPName >> /dev/tty`

if that works I will update it in the tool dependencies file

**Comment by Takadonet** [comment]
well sourceforge is down at the moment so I cannot test it out.Boost will not install. I added that new sed that comments out that echo. Hope to provide you an answer soon.

**Comment by martenson** [comment]
@Takadonet Boost packages should be backed up here: https://depot.galaxyproject.org/package/sourceforge/

**Comment by Takadonet** [comment]
package_boost_1_57 attempts to download http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz

**Comment by martenson** [comment]
@Takadonet I understand, I am merely pointing out our backups that can be used for manual testing of things when SF is down. In longer run we plan to proxy things to provide mirror in case primary source is unavailable.

**Comment by Takadonet** [comment]
@shiltemann Looksl ike commenting out that line did not help. Still missing

g++: /lib/libz.a: No such file or directory

Which is strange to me because zlib is installed correctly. Maybe not linked correctly?

**Comment by shiltemann** [comment]
ah, overlooked that in the previous error message, but I'm assuming the other error messages are gone now? ..could be it's just named differently on your system orso (only tested on ubuntu) ..hope to have some time to look into this tomorrow :)

**Comment by Takadonet** [comment]
The error message are gone. Thanks for all your help

**Comment by shiltemann** [comment]
sorry for the delay, I just tested this on CentOS6 and it worked for me without problems, what system are you on exactly? Looks like something may be going wrong on this line in tool dependencies file:  
`<action type="shell_command">sed -i 's/\${BOOST_LIBRARY_DIR}zlib.a/${ZLIB_ROOT_DIR}\/lib\/libz.a/' source/makefile</action>` 

..could you check in  `source/makefile` if it substituted the correct values?  (and if not you could just enter the correct values as a workaround) ..looks like maybe the ZLIB environment variable wasn't set properly?
