### ISSUE TITLE
pcre - /bin/sh: 1: ./configure: not found

### ISSUE THREAD

**Issue by mictadlo** [galaxyproject/tools-iuc#880]
Hello,
I tried to install `text_processing` 2016-03-18 (4) on Galaxy version 15.07 and I have got the following error:

      pcre 	8.34 	package 	Error 	/bin/sh: 1: ./configure: not found

How is it possible to fix it?

Thank you in advance.

Mic

**Comment by bgruening** [comment]
@mictadlo it can be that you need a newer Galaxy version. I remember that we fixed some bugs in Galaxy that should solve this, not entirely sure. But if you can upgrade your Galaxy.

**Comment by yhoogstrate** [comment]
I'm closing this issue because it's addressed at Bjoerns repo.
