### ISSUE TITLE
Installation of package_deseq2_1_2_10 fails due to non-available R package

### ISSUE THREAD

**Issue by diehlsa** [galaxyproject/tools-iuc#890]
Hi,

the installation of package_deseq2_1_2_10 fails on installing deseq2 with the following error:

> ERROR: dependency ‘XVector’ is not available for package ‘GenomicRanges’
> * removing ‘/export/galaxy-central/tool_deps/deseq2/1.2.10/iuc/package_deseq2_1_2_10/2d4a7ae561d6/GenomicRanges’

It's a dependency of the latest diffbind. I was able to reproduce the error on the galaxy-stable docker image.

**Comment by nsoranzo** [comment]
@diehlsa Thanks for reporting, I have opened #891 which should hopefully fix that.

**Comment by nsoranzo** [comment]
`package_deseq2_1_2_10` has been updated on the Main and Test ToolSheds.

**Comment by diehlsa** [comment]
Thanks for the quick fix, but now I get the following error:

`configure: error: "libxml not found"`

**Comment by nsoranzo** [comment]
@diehlsa Thanks for reporting again, the problem with `libxml` should now be fixed by #892, Main and Test ToolSheds are updated. Please let us know if you further issues!

**Comment by diehlsa** [comment]
Thanks a lot, @nsoranzo! It works now.
