### ISSUE TITLE
BWA-MEM:  Missing filter on bitwise flag:  0x800 (supplementary alignment)

### ISSUE THREAD

**Issue by odoland** [galaxyproject/tools-iuc#897]
Hello Galaxy Project!

Can you add a new bitwise flag filter, for the bitwise flag: 0x800 which is "supplementary alignment"? 
I would like to extract supplementary alignment. 

The current BWA-MEM has filters only up to the PCR Optical Duplicate (0x400)

*Samtools Filter, not BWA-MEM

**Comment by nsoranzo** [comment]
@odoland Are you sure you speaking of the right tool? I can't find bitwise filtering in BWA-MEM tool.

**Comment by odoland** [comment]
Oops! Meant to say the tool:

SAMTOOLS:
Filter SAM or BAM, output SAM or BAM files on FLAG MAPQ RG LN or by region (Galaxy Version 1.1.2)

I will edit the post!

**Comment by nsoranzo** [comment]
@odoland This is [tools/samtool_filter2/samtool_filter2.xml](https://github.com/galaxyproject/tools-devteam/blob/master/tools/samtool_filter2/samtool_filter2.xml) in repository https://github.com/galaxyproject/tools-devteam .

**Comment by odoland** [comment]
Thanks @nsoranzo ! I suggested the addition to the dev teams
