### ISSUE TITLE
package_mummer_3_23  missing on GitHub

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#9]
We have https://toolshed.g2.bx.psu.edu/view/iuc/package_mummer_3_23  and https://testtoolshed.g2.bx.psu.edu/view/iuc/package_mummer_3_23 on the Tool Sheds under the IUC account, but the package source is not yet here under https://github.com/galaxyproject/tools-iuc/tree/master/packages

I don't see it under https://github.com/bgruening/galaxytools/tree/master/packages with @bgruening's other packages. The tool shed commit notes the original was by @jj-umn 

We could just commit the current package to git as-is from the ToolShed?

[The reason I was looking at this is I want to declare gnuplot as a dependency, see PR #7]

**Comment by erasche** [comment]
@peterjc is this still an issue since you've added your own package? Do you want to merge your mummer package here or are you happy with it in pico_galaxy?

**Comment by peterjc** [comment]
The source for ``package_mummer_3_23`` is still not on GitHub under IUC, so yes, this is still an issue,

My user facing mummer wrapper under pico_galaxy simply depends on ``iuc/package_mummer_3_23`` in the TTS and MTS: https://github.com/peterjc/pico_galaxy/tree/master/tools/mummer 

To echo @bgruening's question, @jj-umn - as the original author do you have any objections to us downloading ``package_mummer_3_23`` from the Tool Shed into this git repository for any future development?

**Comment by jj-umn** [comment]
I'm happy to have anything I've done move new new ownership.   I obviously haven't had time to keep up to date with everything.   Thus, might interest in putting tools up for adoption.

**Comment by peterjc** [comment]
That's great @jj-umn - the mummer package is already under the IUC namespace on the Tool Shed, so it is effectively already under the IUC's care.

Let's go ahead and import it into this GitHub repository for future maintenance.

**Comment by bgruening** [comment]
Great, I will do this today.

**Comment by peterjc** [comment]
Thanks all :)
