### ISSUE TITLE
Trinity dependencies broken in the main toolshed

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#905]
```
The settings for name, version and type from a contained tool configuration file's requirement tag does not match the information for the following tool dependency definitions in the tool_dependencies.xml file, so these tool dependencies have no relationship with any tools within this repository.
* name: deseq2, type: package, version: 1.10.0
* name: rsem, type: package, version: 1.2.28
* name: bioconductor-edger, type: package, version: 3.14.0
* name: bowtie2, type: package, version: 2.2.6
* name: bioconductor-limma, type: package, version: 3.28.10
* name: eXpress, type: package, version: 1.5.1
```

**Comment by nsoranzo** [comment]
Where/when exactly are you seeing this? These are requirements of other tools in the new  [suite_trinity](https://toolshed.g2.bx.psu.edu/view/iuc/suite_trinity/).

**Comment by lparsons** [comment]
@nsoranzo: https://toolshed.g2.bx.psu.edu/view/iuc/trinity/831abd20e690

**Comment by nsoranzo** [comment]
Thanks @lparsons, I had trouble to see it because I was logged in as `iuc` and TS was showing me the "manage repository" interface, where this warning was not shown!
Is this creating you problems when installing/updating, apart from asking to install dependencies not needed for the `trinity` tool?

@jmchilton Is there a way to solve this for a suite defined in `.shed.yml` ? If not, I guess that there will be little incentive to fix it, since this is not an issue when using conda as dependency resolver.

**Comment by lparsons** [comment]
@nsoranzo I haven't actually tested out installing things yet. Is Conda "ready for primetime" as a dependency management system in Galaxy? I was under the impression I'd need to wait until at least release 16.07, esp since I've not seen any docs about how it works yet.

**Comment by nsoranzo** [comment]
@lparsons As IUC we have agreed that conda is ready, since it is available since 16.01, it is on by default since 16.04 and it will be possible to install conda deps through the admin UI in 16.07 thanks to https://github.com/galaxyproject/galaxy/pull/2554.
Therefore, for new tool submission/upgrades we switched from asking tool_dependencies.xml/TS packages to (bio)conda recipes.
@bgruening correct me if I'm wrong, please.

**Comment by bgruening** [comment]
This sounds correct to me :)
Also we probably need to add documentation somewhere. @lparsons can you help we with this and give me a list of questions you have in mind?

**Comment by lparsons** [comment]
@bgruening Sounds great. Here are a few quick things from the top of my head, we can perhaps find a better location for these at some point (an issue perhaps) and I'll clean them up.

1. For existing installs, I didn't see anything telling us that we should turn on conda dependency resolution.
2. How do conda dependencies work? I understand the old system with env.sh and dependencies in specific directories, but don't really know how conda is implemented in Galaxy. Where do things get installed?
3. What is required to make use of this? Any specific packages, Galaxy revision, OS version, etc.?
4. How do I know what system is being used by a given tool?
5. How do I go about specifying conda dependencies for a tool? All the docs still seem to recommend (or exclusively discuss) the `tool_dependencies.xml` method.
6. Where can I find a list of existing conda packages that I can point to, so I don't have to reinvent the wheel for common dependencies?
7. How can I create a new conda package for a dependency?
8. Is there a way to migrate old `tool_dependecies.xml` tools to conda? And/or is there a plan to do that for tools? And what is the recommendation for existing installations? Will I continue to maintain both systems or migrate to the new conda system eventually?

**Comment by bgruening** [comment]
@lparsons great thanks. I will try to address all this during my train ride in 2 days.

**Comment by lparsons** [comment]
@bgruening Thanks! I'm very much looking forward to a new dependency system... Conda seems like a great choice. Ping me when you get something up and I'll "test drive" the docs for you if you like. ;-)

**Comment by bgruening** [comment]
Awesome, will do!

**Comment by lparsons** [comment]
@nsoranzo @bgruening @abretaud I'm not sure if this is related, but it not, I can create a new ticket, just let me know.

When I attempt to update `trinity` to the latest revision (not a new version, but `258c64019e50` to `831abd20e690`, run get an internal server error. See: https://gist.github.com/lparsons/3937cce0ea8f942a1fe4bca391b027d6

Also, I'm a bit confused on the recommended upgrade path for Trinity. The update the existing Trinity seems to remove a number of tools, while the new suite adds them back as separate repos. Shouldn't this be a version change for Trinity? Any help or advice would be appreciated.

**Comment by nsoranzo** [comment]
831abd20e690 is a new version, as can be seen on the MTS under "View Changelog", but there is an intermediate revision to which you can upgrade your current version.

The error in your gist is a Galaxy bug, can you please open a ticket on the galaxy repository for that? Thanks a lot for reporting!

**Comment by bgruening** [comment]
@lparsons can we close this?

**Comment by lparsons** [comment]
@bgruening The warning is still being displayed on the main toolshed. Was a fix merged in yet and just isn't up on the toolshed?

**Comment by abretaud** [comment]
Closing this as we use conda now
