### ISSUE TITLE
Some packages depending on package_python_2_7_numpy_1_9 currently fail to install

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/tools-iuc#906]
It looks like a new revision of package_python_2_7_numpy_1_9 was posted to the toolshed in June (presumably due to an update of the atlas package). While that's all well and good, the previous revision is no longer available in the toolshed. There are a number of packages in the toolshed (e.g., package_python_2_7_deeptools_2_2_3, from the IUC) that depend on package_python_2_7_numpy_1_9. It looks like `planemo upload` or something else modifies the `tool_dependency.xml` file to set an explicit revision for dependencies when things are uploaded to the toolshed. Because of that, many packages uploaded before June 23 that depend on the numpy package will have a hard-coded revision that isn't available. The simplest solution would be to just make the previous revision (57b37f63cb84) or package_python_2_7_numpy_1_9 installable via the toolshed again.

I guess this will become a non-issue once everyone switches to using conda as a dependency resolver, but in the interim...

**Comment by mvdbeek** [comment]
Ah yes, the problem is complex, because galaxy simply installs the latest revision for packages, no matter what ... but there are situations where this doesn't work as expected. 
I'm testing this now to make sure I'm not saying nonsense, but I think on new, clean instances without any history of these packages it works.

**Comment by dpryan79** [comment]
Installing the latest version would be fine, the problem is that it seems to be honouring the revision numbers in the `tool_dependency.xml` :(

**Comment by mvdbeek** [comment]
Well, that depends ... I tried installing package_python_2_7_deeptools_2_2_3 from the MTS, and I got numpy in revision f24fc0b630fc (which is broken on OS X, once again, due to ATLAS), which is correct, right? And package_python_2_7_bx_python_0_7, which depends on numpy didn't complain about the revision (but because numpy is not installed I'm not 100% sure there is no problem).

I think the problem occurs when any of these packages has been previsouly installed in an older revision ... but that's tough to debug, and changing this part of the code is difficult, because the testing doesn't conver these complex cases ...

**Comment by dpryan79** [comment]
That could be the case then, or perhaps this is a random bug in the 16.01 release, which is what I'm using for the next couple weeks still. As long as this works on clean systems and/or current releases then this issue can get closed (I'll just tough it out until the next upgrade).

**Comment by mvdbeek** [comment]
Hmm, we may have fixed this, but the only thing that comes to mind is https://github.com/galaxyproject/galaxy/pull/1868 ... do you have any error in the logs that look like [this](https://github.com/galaxyproject/galaxy/issues/1865#issuecomment-192396467) ?
Do you have the commit 4dc40352de31babba69ca06618d6ac64add15c56 (`git cat-file -t 4dc40352de31babba69ca06618d6ac64add15c56`) ?

**Comment by dpryan79** [comment]
Yup, that's exactly the sort of error I get. I don't have any of the backported fixes since I pulled the docker container in January, but I'll implement that one and hopefully it'll do the trick. Thanks!

**Comment by dpryan79** [comment]
That seems to have done the trick (after first updating package_python_2_7_numpy_1_9 to the newest revision)!

**Comment by mvdbeek** [comment]
Cool, thanks for following up!

**Comment by dpryan79** [comment]
Oh, I found a bug. Lines 422-423 of `lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py` is:

    log.debug( "Tool dependency %s version %s cannot be installed (it was probably previously installed), " %
        ( str( tool_dependency.name, str( tool_dependency.version ) ) ) )

but it should be:

    log.debug( "Tool dependency %s version %s cannot be installed (it was probably previously installed), " %
        ( str( tool_dependency.name ), str( tool_dependency.version ) ) )

It's a misplaced ")".

**Comment by gregvonkuster** [comment]
FWIW, I'm seeing this issue on 16.04.  I have not investigated to confirm, but I'm fairly certain this is a somewhat recent regression, and is related to the installed_changeset_revision value stored in the database for tool dependencies.  The behavior used to be that the installed_changeset_revision would be automatically updated to the tip of the repository in the Tool Shed, but this process is not currently performed, so dependent installed tools show missing dependencies.

**Comment by nsoranzo** [comment]
> It's a misplaced ")".

@dpryan79 This bug will be fixed by https://github.com/galaxyproject/galaxy/pull/2767 , thanks for reporting!

**Comment by martenson** [comment]
The mentioned PR has been merged.
