### ISSUE TITLE
SRA to fastq error

### ISSUE THREAD

**Issue by njbowen** [galaxyproject/tools-iuc#918]
Fatal error: Exit code 127 (Could not locate fastq-dump binary)
/galaxy-repl/main/jobdir/013/745/13745479/tool_script.sh: line 9: vdb-config: command not found
/galaxy-repl/main/jobdir/013/745/13745479/tool_script.sh: line 9: prefetch: command not found

getting the above error in galaxy when trying to convert SRR accession to fastq

**Comment by yhoogstrate** [comment]
Any idea @mvdbeek ?

**Comment by mvdbeek** [comment]
The tool dependencies are not (successfully) installed.
@njbowen We'd need to know more to advise on anything.
What version of the sratools are you using and what galaxy version and how did you install the tool dependencies?

**Comment by njbowen** [comment]
I was using an account at the usegalaxy.org  web portal.  Not a local install.  Have since been able to get fastq groomer to work on imported fastq files.  Thanks.
