### ISSUE TITLE
Poster / GitHub badge for Galaxy tools

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#925]
I'm sitting here with @yhoogstrate and discussion some ideas ... one is to have some kind of poster badge or github badge, similar to: https://github.com/bioconda/bioconda-recipes/issues/1971

The idea is that a developer can put this SVG on a poster or a github account and link back to tools-iuc, Tool Shed.

**Comment by bgruening** [comment]
xref: https://bioconda.github.io/_static/badge-generator/

**Comment by yhoogstrate** [comment]
It would probably also be useful to have something like an icon [galaxy tool available][+ IUC approved] to use in README.MD's, linking to the galaxy repo in the main tool shed.

**Comment by gregvonkuster** [comment]
This was always the intent back when the IUC was formed. ;)

**Comment by martenson** [comment]
I will see what I can do.

**Comment by bgruening** [comment]
Thanks @martenson!

**Comment by bernt-matthias** [comment]
Covered by this: https://github.com/galaxyproject/tools-iuc/blob/master/iuc_logo.png and https://github.com/galaxyproject/tools-iuc/blob/master/iuc_logo.svg
