### ISSUE TITLE
http://multiqc.info as tool for creating reports?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#966]
@shiltemann what do you think about this?

**Comment by shiltemann** [comment]
ooo this looks very spiffy, I like it. Good documentation, already in conda, yes, definitely, let's go for it, would love to see this in Galaxy :)

**Comment by abretaud** [comment]
Hej,
I think @yvanlebras and @cmonjeau did some work on this: https://github.com/ewels/MultiQC/issues/15
(but I don't know if it's working :smile: )

**Comment by yvanlebras** [comment]
Hallo, 
Effectively, this was the first development and contribution to Galaxy with the EnginesOn start-up project hat ;) 
Apparently, there is some code update to apply now. @cmonjeau and or I have to check this....

-------- Message d'origine --------
De : Anthony Bretaudeau <notifications@github.com> 
Date : 27/09/2016  10:01  (GMT+01:00) 
À : galaxyproject/tools-iuc <tools-iuc@noreply.github.com> 
Cc : Yvan Le Bras <yvan.le_bras@irisa.fr>, Mention <mention@noreply.github.com> 
Objet : Re: [galaxyproject/tools-iuc] http://multiqc.info as tool for creating reports? (#966) 

Hej,
I think @yvanlebras and @cmonjeau did some work on this: https://github.com/ewels/MultiQC/issues/15
(but I don't know if it's working :smile: )

**Comment by yvanlebras** [comment]
For the code : https://github.com/EnginesOn/galaxy_tools/tree/master/tools/multiqc

-------- Message d'origine --------
De : Anthony Bretaudeau <notifications@github.com> 
Date : 27/09/2016  10:01  (GMT+01:00) 
À : galaxyproject/tools-iuc <tools-iuc@noreply.github.com> 
Cc : Yvan Le Bras <yvan.le_bras@irisa.fr>, Mention <mention@noreply.github.com> 
Objet : Re: [galaxyproject/tools-iuc] http://multiqc.info as tool for creating reports? (#966) 

Hej,
I think @yvanlebras and @cmonjeau did some work on this: https://github.com/ewels/MultiQC/issues/15
(but I don't know if it's working :smile: )

**Comment by yhoogstrate** [comment]
Is this still an open issue @yvanlebras ?

**Comment by dpryan79** [comment]
This can be closed

**Comment by bebatut** [comment]
Thanks @dpryan79!
