### ISSUE TITLE
Error 404 on installing package_bioconductor_limma_3_28_10

### ISSUE THREAD

**Issue by adefelicibus** [galaxyproject/tools-iuc#979]
Error downloading from URL
https://depot.galaxyproject.org/software/limma/limma_3.28.10_src_all.tar.gz:
HTTP Error 404: Not Found

**Comment by erasche** [comment]
Bioarchive only has 3.28.0 for some reason https://bioarchive.galaxyproject.org/limma_3.28.0.tar.gz

Old limma was lost during the cargo port fiasco.

**Comment by nsoranzo** [comment]
Ping @abretaud which created the package and may still have the sources.

**Comment by abretaud** [comment]
Hi,
Sorry, I don't have the sources on my disk...
So the only solution is to update limma?

**Comment by adefelicibus** [comment]
Any news about it?

**Comment by abretaud** [comment]
I think this was fixed in #1031 (forgot to update this issue, sorry)
Reopen if you still have problems with it
