### ISSUE TITLE
stacks 1.40 clone_filter does not work with uncompressed files

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#980]
As per the subject, clone_filter seems to have a problem with uncompressed fastq files (paired end).
I can offer to submit a PR to 1.42 (and also stacks packages) if @abretaud is fine with that.

**Comment by abretaud** [comment]
@tiagoantao is there still a problem with this tool? I'm of course always fine with PR :)

**Comment by tiagoantao** [comment]
This was actually a problem with the version of Galaxy. Newer versions of Galaxy do this automatically.
