### ISSUE TITLE
DESEQ2 failing at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#988]
Update2: Might be actual. Other tools show this symptom.

**Tool**

toolshed.g2.bx.psu.edu/repos/iuc/deseq2/deseq2/2.1.8.3

**Error**

> Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
> Creating a generic function for 'nchar' from package 'base' in package 'S4Vectors'
> Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
>   missing values in 'row.names' are not allowed
> Calls: rownames<- ... rownames<- -> row.names<- -> row.names<-.data.frame

All of the inputs look to be correct htseq_count files created within Galaxy (no spaces in gene names or in factor names). 

Usage issue that someone recognizes or is this a bug? I can't check the version versus the tool shed right now, so am not sure if the version at http://usegalaxy.org is the most current or not. Will update when MTS online again.

**Comment by jennaj** [comment]
@bgruening The multi-select does seem to be at the root of the problem, or it is a good guess anyway. Other tools had problems distinguishing between multiple inputs in this form field. I'll link in the other ticket. Tested at usegalaxy.org, this is what Deeptools errors:

<img width="632" alt="screen shot 2016-10-11 at 11 18 54 am" src="https://cloud.githubusercontent.com/assets/8999735/19282966/26eb379e-8fa5-11e6-9b77-486a3c182fac.png">

<img width="581" alt="screen shot 2016-10-11 at 11 18 18 am" src="https://cloud.githubusercontent.com/assets/8999735/19282981/2f7e65ca-8fa5-11e6-823e-9ae1170ab163.png">

<img width="631" alt="screen shot 2016-10-11 at 11 18 03 am" src="https://cloud.githubusercontent.com/assets/8999735/19282991/36c605cc-8fa5-11e6-8f35-27207d04831e.png">

**Comment by natefoo** [comment]
deseq2 has been updated to version 2.1.8.4 if someone on the @galaxyproject/bug-squad would like to test to see if the new version fixes it.

**Comment by jennaj** [comment]
testing, update once done

**Comment by jennaj** [comment]
Long error message, but perhaps there is a clue in here. The inputs seem fine from my checks.  @galaxyproject/guac could one of you help to decode what is going wrong? Dependency issue (R?)

> Dataset generation errors
> Dataset 131: DESeq2 result file on data 105, data 103, and others
> 
> Tool execution generated the following error message:
> Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
> Loading required package: S4Vectors
> Loading required package: stats4
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: 'BiocGenerics'
> 
> The following objects are masked from 'package:parallel':
> 
>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
>     clusterExport, clusterMap, parApply, parCapply, parLapply,
>     parLapplyLB, parRapply, parSapply, parSapplyLB
> 
> The following objects are masked from 'package:stats':
> 
>     IQR, mad, xtabs
> 
> The following objects are masked from 'package:base':
> 
>     Filter, Find, Map, Position, Reduce, anyDuplicated, append,
>     as.data.frame, as.vector, cbind, colnames, do.call, duplicated,
>     eval, evalq, get, grep, grepl, intersect, is.unsorted, lapply,
>     lengths, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
>     pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
>     tapply, union, unique, unlist, unsplit
> 
> Loading required package: IRanges
> Loading required package: GenomicRanges
> Loading required package: GenomeInfoDb
> Loading required package: SummarizedExperiment
> Loading required package: Biobase
> Welcome to Bioconductor
> 
>     Vignettes contain introductory material; view with
>     'browseVignettes()'. To cite Bioconductor, see
>     'citation("Biobase")', and for packages 'citation("pkgname")'.
> 
> Loading required package: Rcpp
> Loading required package: RcppArmadillo
> Warning messages:
> 1: replacing previous import by 'ggplot2::unit' when loading 'Hmisc' 
> 2: replacing previous import by 'ggplot2::arrow' when loading 'Hmisc' 
> 3: replacing previous import by 'scales::alpha' when loading 'Hmisc' 
> Warning message:
> package 'getopt' was built under R version 3.3.1 
> Warning messages:
> 1: replacing previous import by 'ggplot2::unit' when loading 'Hmisc' 
> 2: replacing previous import by 'ggplot2::arrow' when loading 'Hmisc' 
> 3: replacing previous import by 'scales::alpha' when loading 'Hmisc' 
> Warning message:
> package 'rjson' was built under R version 3.3.1 
> estimating size factors
> estimating dispersions
> gene-wise dispersion estimates
> mean-dispersion relationship
> final dispersion estimates
> fitting model and testing
> -- replacing outliers and refitting for 116 genes
> -- DESeq argument 'minReplicatesForReplace' = 7 
> -- original counts are preserved in counts(dds)
> estimating dispersions
> fitting model and testing
> Error in text(x = c(0, length(h1$counts)), y = 0, label = paste(c(0, 1)),  : 
>   object 'h1' not found
> Calls: generateSpecificPlots -> text
> The tool produced the following additional output:
> discarding /galaxy/main/deps/_conda/bin from PATH
> prepending /galaxy-repl/main/jobdir/014/161/14161924/conda-env/bin to PATH
> 
> R version 3.2.2 (2015-08-14) -- "Fire Safety"
> Copyright (C) 2015 The R Foundation for Statistical Computing
> Platform: x86_64-pc-linux-gnu (64-bit)
> 
> R is free software and comes with ABSOLUTELY NO WARRANTY.
> You are welcome to redistribute it under certain conditions.
> Type 'license()' or 'licence()' for distribution details.
> 
> R is a collaborative project with many contributors.
> Type 'contributors()' for more information and
> 'citation()' on how to cite R or R packages in publications.
> 
> Type 'demo()' for some demos, 'help()' for on-line help, or
> 'help.start()' for an HTML browser interface to help.
> Type 'q()' to quit R.
> 
> > library(DESeq2); sink("DESEQ2_ROOT_PATH"); cat(file.path(find.package("DESeq2"),"script","deseq2.R"))
> > 
> > DESeq2 run information
> 
> sample table:
>                      HDMvsAM145
> dataset_17589978.dat        HDM
> dataset_17589980.dat        HDM
> dataset_17589982.dat        HDM
> dataset_17589984.dat        HDM
> dataset_17589986.dat        HDM
> dataset_17589988.dat        HDM
> dataset_17589990.dat        HDM
> dataset_17589997.dat        HDM
> dataset_17590001.dat        HDM
> dataset_17590003.dat        HDM
> dataset_17590005.dat      AM145
> dataset_17590007.dat      AM145
> dataset_17590009.dat      AM145
> dataset_17590011.dat      AM145
> dataset_17590013.dat      AM145
> dataset_17590015.dat      AM145
> dataset_17590017.dat      AM145
> dataset_17590019.dat      AM145
> dataset_17590021.dat      AM145
> dataset_17590023.dat      AM145
> 
> design formula:
> ~HDMvsAM145
> 
> 
> primary factor: HDMvsAM145 
> 
> ---------------------
> 20 samples with counts over 24421 genes
> using disperion fit type: parametric 
> creating plots
> summary of results
> HDMvsAM145: AM145 vs HDM
> 
> out of 20330 with nonzero total read count
> adjusted p-value < 0.1
> LFC > 0 (up)     : 3642, 18% 
> LFC < 0 (down)   : 3441, 17% 
> outliers [1]     : 0, 0% 
> low counts [2]   : 2742, 13% 
> (mean count < 1)
> [1] see 'cooksCutoff' argument of ?results
> [2] see 'independentFiltering' argument of ?results
> 
> NULL

**Comment by jennaj** [comment]
Update: If "Visualising the analysis results" is set to "no", the tool runs. Could be the root issue or related. Shared history with @moheydarian in gitter

**Comment by devikaatgit** [comment]
Any updates/solutions for the issue? Its not just about multiple factors - the tools does not run even for just two basic factor levels. Tried running with the visualising the analysis results set to no but didnt get any results.

**Comment by jennaj** [comment]
@devikaatgit Hi Devika, thanks for the feedback and hope you are doing well! 

The correction is still in progress. Much of the admin team is involved in training activities right now, but this is a priority too! Look for more updates next week. And you are correct - the tool can fail with even single factors. The original error was different than the most current. 

If you are getting an error with visualization set to no, and are working at http://usegalaxy.org, could you send in a bug report? Would be helpful, thank you!

**Comment by bgruening** [comment]
@jennaj @natefoo there is a new DESeq2 update in the TS with conda package.

**Comment by jennaj** [comment]
ping @galaxyproject/guac FYI

**Comment by jennaj** [comment]
ping @natefoo the new version is ready. ETA for main update? https://toolshed.g2.bx.psu.edu/view/iuc/deseq2/4939397c4706

**Comment by natefoo** [comment]
@jennaj just updated it last night, restarted just now and the new version is available. Let me know if there are any problems.

**Comment by jennaj** [comment]
@natefoo Thanks, testing right now

**Comment by jennaj** [comment]
Still failing

**Comment by jennaj** [comment]
The tool is working now for several test use cases - closing out, thanks everyone!
