### ISSUE TITLE
Support testing of tools via Docker

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#990]
Since, yesterday we have implicit Docker support for all tools that already supported by conda. What do you think about testing all tools in conda _and_ in Docker automatically in Travis. At least for the first time until the dust settles, this should increase the quality of our tools and we could state that IUC tools are supported by both technologies.

Disadvantage is twice as much time spent in testing.

ping @galaxyproject/iuc

**Comment by mvdbeek** [comment]
yes, absolutely, I think we should do that. I wouldn't be surprised if the docker containers -- even if built locally -- turn out to be more mature. I think we could half the chunksize and instead add docker.

**Comment by abretaud** [comment]
+1 for this, it would make docker a first class citizen as conda

**Comment by bernt-matthias** [comment]
Seems possible nowadays.
