### ISSUE TITLE
JBROWSE_SOURCE_DIR is not defined when installing Jbrowse

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/tools-iuc#993]
The environment variable JBROWSE_SOURCE_DIR is not defined when installing Jbrowse. When executing jbrowse in Galaxy no directory is passed to the script leading to the following error:

```
Fatal error: Exit code 1 ()
usage: jbrowse.py [-h] [--jbrowse JBROWSE] [--outdir OUTDIR] [--standalone]
                  xml
jbrowse.py: error: argument --jbrowse: expected one argument
mv: cannot stat `/remote/RMS/users/galaxyd/job_working_directory/008/8727/dataset_50589_files/index.html': No such file or directory
```

**Comment by erasche** [comment]
Hi @dwightkuo 

Not sure how this is happening. It should be set for both versions of JBrowse

- https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_jbrowse_1_12_0/tool_dependencies.xml#L21
- https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_jbrowse_1_11_6/tool_dependencies.xml#L110

How did you install JBrowse? I assume from toolshed, but wanted to double check. Also, what versions of the jbrowse tool and jbrowse package do you have installed?

**Comment by dwightkuo** [comment]
Hi Eric,

Yes I installed from the toolshed. The jbrowse package is v0.4. Do I need
to install jbrowse separately outside of galaxy?

I just noticed that there's an installation failure for
package_jbrowse_1_12_0 which references python2.6. I'm running galaxy using
python2.7 via scl enable python27 so could this be the issue? I've included
the error below:


Tool shed repository 'package_jbrowse_1_12_0' tool dependencies:
> jbrowse 1.12.0 package Error  File
> "/opt/galaxy/lib/tool_shed/galaxy_install/install_manager.py", line 142, in
> install_and_build_package_via_fabric
>     tool_dependency = self.install_and_build_package(
> tool_shed_repository, tool_dependency, actions_dict )
>   File "/opt/galaxy/lib/tool_shed/galaxy_install/install_manager.py", line
> 136, in install_and_build_package
>     dir = tmp_dir
>   File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
>     self.gen.throw(type, value, traceback)
>   File
> "/opt/galaxy/eggs/Fabric-1.7.0-py2.6.egg/fabric/context_managers.py", line
> 142, in _setenv
>     yield
>   File "/opt/galaxy/lib/tool_shed/galaxy_install/install_manager.py", line
> 100, in install_and_build_package
>     initial_download=True )
>   File
> "/opt/galaxy/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py",
> line 32, in execute_step
>     initial_download=initial_download )
>   File
> "/opt/galaxy/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py",
> line 685, in execute_step
>     dir = self.url_download( work_dir, downloaded_filename, url,
> extract=True, checksums=checksums )
>   File
> "/opt/galaxy/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py",
> line 223, in url_download
>     extraction_path = archive.extract( install_dir )
>   File
> "/opt/galaxy/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py",
> line 89, in extract
>     os.chmod( absolute_filepath, unix_permissions )
> [Errno 2] No such file or directory:
> '/tmp/tmp-toolshed-mtdfjKGYa/JBrowse-1.12.0/JBrowse-1.12.0/'


Thanks,

Dwight

**Comment by erasche** [comment]
Ok, this looks like it might be a bug inthat package

**Comment by dwightkuo** [comment]
Hi Eric,

Looks like the error was caused because the python_2_7 module wasn't
correctly installed. I fixed that. (I get "Installed, missing tool
dependencies" for BioPython_1_66 and package_samtools_1_2 which I can't
seem to resolve).

However, the tool now runs but when I tried to use a BLAST XML file as
input the track looks to be empty. When I try a BED file instead I get the
following error:


> Fatal error: Matched on Error:
> INFO:jbrowse:Processing Default / Book1.txt
> Can't locate Bio/FeatureIO.pm in @INC (you may need to install the
> Bio::FeatureIO module) (@INC contains:
> /opt/shed_tools/jbrowse/1.12.0/iuc/package_jbrowse_1_12_0/22be3ae5599d/JBrowse-1.12.0/bin/../src/perl5
> /opt/shed_tools/perl/5.18.1/iuc/package_perl_5_18/8b3509930a44/lib/perl5
> /opt/shed_tools/bundle_jbrowse/1.12.0/iuc/package_perl_bundle_jbrowse_1_12_0/52153ec17769/lib/perl5/x86_64-linux
> /opt/shed_tools/bundle_jbrowse/1.12.0/iuc/package_perl_bundle_jbrowse_1_12_0/52153ec17769/lib/perl5
> /nfs/sw/perl5/sharedperlmodules /usr/local/share/perl5
> /opt/shed_tools/perl/5.18.1/iuc/package_perl_5_18/8b3509930a44/lib/site_perl/5.18.1/x86_64-linux
> /opt/shed_tools/perl/5.18.1/iuc/package_perl_5_18/8b3509930a44/lib/site_perl/5.18.1
> /opt/shed_tools/perl/5.18.1/iuc/package_perl_5_18/8b3509930a44/lib/5.18.1/x86_64-linux
> /opt/shed_tools/perl/5.18.1/iuc/package_perl_5_18/8b3509930a44/lib/5.18.1
> .) at
> /opt/shed_tools/jbrowse/1.12.0/iuc/package_jbrowse_1_12_0/22be3ae5599d/JBrowse-1.12.0/bin/../src/perl5/Bio/JBrowse/Cmd/FlatFileToJson.pm
> line 155.
> Traceback (most recent call last):


Any suggestions would be appreciated.

Thanks!

Dwight
