### ISSUE TITLE
IUC member proposal - Lance Parsons

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#999]
Hi Commissioners,

I would like to see see Lance Parsons (@lparsons) becoming an IUC member.
Lance is helping us a lot in tools-iuc and in Galaxy since years, contributed important tools and always triggers the important questions.

I will try to assist him in the first month with any IUC related questions!

Please comment and vote!
Ciao,
Bjoern

**Comment by nsoranzo** [comment]
:+1:

**Comment by martenson** [comment]
I believe Lance wil be a tremendous member. :+1:

**Comment by shiltemann** [comment]
:+1:

**Comment by mvdbeek** [comment]
:+1

**Comment by davebx** [comment]
> bgruening added the enhancement label

How appropriate.

**Comment by nekrut** [comment]
+1

**Comment by erasche** [comment]
:+1:

**Comment by lparsons** [comment]
Thanks for the thumbs up everyone.

**Comment by blankenberg** [comment]
+1

**Comment by bgruening** [comment]
Wonderful! Welcome @lparsons!
@martenson can you do your magic and add @lparsons to the TS and the github repos! Thanks!

**Comment by martenson** [comment]
@bgruening all should be done, welcome @lparsons

**Comment by bgruening** [comment]
@martenson thanks a lot!

**Comment by lparsons** [comment]
Thanks again all!
